/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco3_2020/donnees_coco3/sas_coco3/fr.cdsp.ddi.elipss.202005.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco3_2020/donnees_coco3/sas_coco3/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = fr_cdsp_ ;

proc format library = library ;
   value COCO3_CA
      1 = '18-24 ans'  
      2 = '25-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-79 ans' ;
   value COCO3__A
      1 = '18-22 ans'  
      2 = '23-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-75 ans'  
      7 = '76-79 ans' ;
   value COCO3__B
      1 = 'Aucun/CEP/BEPC'  
      2 = 'CAP/BEP'  
      3 = 'Bac/Bac+2'  
      4 = 'Bac+3 et plus' ;
   value COCO3__C
      1 = 'Homme'  
      2 = 'Femme' ;
   value COCO3__D
      1 = 'Région parisienne'  
      2 = 'Bassin parisien'  
      3 = 'Nord'  
      4 = 'Est'  
      5 = 'Ouest'  
      6 = 'Sud-ouest'  
      7 = 'Centre-est'  
      8 = 'Méditerranée' ;
   value COCO3_Q0F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
     .A = 'N''a pas répondu' ;
   value LABA
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu' ;
   value LABB
      1 = 'Choisi'  
      2 = 'Non Choisi' ;
   value COCO3__R
      1 = 'J’ai été testé(e) positif(ve)'  
      2 = 'J’ai de fortes suspicions d’avoir été atteint(e)'  
      3 = 'Je ne pense pas avoir été atteint(e)'  
     .A = 'N''a pas répondu' ;
   value COCO3_Q1F
      1 = 'Je suis guéri(e)'  
      2 = 'Je suis encore malade mais je vais plutôt bien'  
      3 = 'Je suis malade'  
     .A = 'Non concernée' ;
   value COCO3__S
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais' ;
   value LABC
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value COCO3__W
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
     .A = 'N''a pas répondu' ;
   value COCO3__X
      1 = 'Jamais'  
      2 = 'Rarement'  
      3 = 'Parfois'  
      4 = 'Souvent'  
      5 = 'Très souvent'  
      6 = 'Je vis actuellement seul(e)' ;
   value COCO3_Q3F
      0 = 'En retraite'  
      1 = 'En congés'  
      2 = 'En congé maladie'  
      3 = 'En congé parental en raison de la garde de mes enfants (auto'  
      4 = 'Au chômage partiel ou chômage technique'  
      5 = 'Au chômage'  
      6 = 'Au travail, que ce soit à la maison ou sur mon lieu habituel'  
     .B = 'N''a pas répondu' ;
   value COCO3__Y
      1 = 'Principalement travaillé sur votre lieu de travail habituel'  
      2 = 'Alterné télétravail et travail sur votre lieu de travail hab'  
      3 = 'Principalement été en télétravail'  
      4 = 'Aucune de ces situations'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value LABD
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'Non concernée' ;
   value COCO3_AI
      1 = 'Jamais'  
      2 = 'Une fois par semaine ou moins'  
      3 = 'Une fois tous les deux ou trois jours'  
      4 = 'Tous les jours ou presque'  
     .A = 'N''a pas répondu' ;
   value COCO3_Q5F
      1 = 'Tous les jours d’école ou presque'  
      2 = 'Au moins deux fois par semaine'  
      3 = 'Au moins une fois par semaine'  
      4 = 'Jamais'  
      5 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABE
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABF
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
      6 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABG
      1 = 'Je n’ai pas fait cette activité'  
      2 = 'Entre 0 et 1 heure'  
      3 = 'Entre 1 et 2 heures'  
      4 = 'Entre 2 et 3 heures'  
      5 = 'Entre 3 et 4 heures'  
      6 = 'Entre 4 et 6 heures'  
      7 = 'Entre 6 et 8 heures'  
      8 = 'Entre 8 et 10 heures'  
      9 = 'Plus de 10 heures'  
     .A = 'N''a pas répondu' ;
   value LABH
      1 = 'Très souvent'  
      2 = 'Souvent'  
      3 = 'Parfois'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value COCO3_BQ
      0 = '0 - Pas du tout'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Énormément'  
     .A = 'N''a pas répondu' ;
   value COCO3_BR
      1 = 'Tout à fait satisfait(e)'  
      2 = 'Plutôt satisfait(e)'  
      3 = 'Plutôt pas satisfait(e)'  
      4 = 'Pas du tout satisfait(e)'  
     .A = 'N''a pas répondu' ;
   value COCO3_Q7F
      0 = '0 - Conséquences sanitaires'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Conséquences économiques'  
     .A = 'N''a pas répondu' ;
   value COCO3_BS
      1 = 'Beaucoup plus'  
      2 = 'Un peu plus'  
      3 = 'Autant'  
      4 = 'Un peu moins'  
      5 = 'Beaucoup moins'  
      6 = 'Je ne sais pas'  
     .A = 'N''a pas répondu' ;
   value COCO3_BT
      1 = 'Souvent'  
      2 = 'Parfois'  
      3 = 'Rarement'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABI
      1 = 'Oui'  
      2 = 'Non'  
     .A = 'N''a pas répondu' ;
   value LABJ
      1 = 'C’est de la famille ou un parent'  
      2 = 'C’est un(e) ami(e) proche'  
      3 = 'C’est une connaissance'  
      4 = 'Je n’en connais pas'  
     .A = 'N''a pas répondu' ;
   value COCO3_DN
      1 = 'Très fréquentes'  
      2 = 'Plutôt fréquentes'  
      3 = 'Plutôt rares'  
      4 = 'Très rares'  
     .A = 'N''a pas répondu' ;
   value COCO3_DO
      1 = 'Toujours ou presque toujours'  
      2 = 'Parfois'  
      3 = 'Rarement'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABK
      1 = 'Très fréquemment'  
      2 = 'Plutôt fréquemment'  
      3 = 'Plutôt rarement'  
      4 = 'Très rarement'  
     .A = 'N''a pas répondu' ;
   value LABL
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value LABM
      1 = 'Fortement en désaccord'  
      2 = 'Plutôt en désaccord'  
      3 = 'Avis mitigé'  
      4 = 'Plutôt en accord'  
      5 = 'Fortement en accord'  
      6 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value COCO3_EI
      0 = '0 - Très insatisfait(e)'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Très satisfait(e)'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO3_EJ
      1 = 'Seulement du télétravail'  
      2 = 'Plus de télétravail que de travail sur place'  
      3 = 'Plus de travail sur place que de télétravail'  
      4 = 'Seulement du travail sur place'  
      5 = 'Je ne suis pas en activité'  
     .A = 'N''a pas répondu' ;
   value COCO3_ER
      0 = 'En retraite'  
      1 = 'En congés'  
      2 = 'En congé maladie'  
      3 = 'En congé parental en raison de la garde des enfants (autoris'  
      4 = 'Au chômage partiel ou chômage technique'  
      5 = 'Au chômage'  
      6 = 'Au travail, que ce soit à la maison ou sur son lieu habituel'  
      8 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value COCO3_ES
      1 = 'Principalement travaillé sur son lieu de travail habituel (y'  
      2 = 'Alterné télétravail et travail sur son lieu de travail habit'  
      3 = 'Principalement été en télétravail'  
      4 = 'Il ou elle n’occupe pas d’emploi actuellement'  
     .A = 'Non concernée' ;
   value LABN
      1 = 'Toujours'  
      2 = 'Souvent'  
      3 = 'Parfois'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABO
      1 = 'Toujours'  
      2 = 'Souvent'  
      3 = 'Parfois'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu'  
     .B = 'Non concerné' ;
   value LABP
      0 = 'Bien-être subjectif le plus élevé'  
      1 = 'Bien-être subjectif le plus faible' ;
   value EAYY_A1F
      1 = 'Un homme'  
      2 = 'Une femme' ;
   value EAYY_A2A
      4 = 'Moins de 24 ans'  
      5 = 'De 25 à 29 ans'  
      6 = 'De 30 à 34 ans'  
      7 = 'De 35 à 39 ans'  
      8 = 'De 40 à 44 ans'  
      9 = 'De 45 à 49 ans'  
      10 = 'De 50 à 54 ans'  
      11 = 'De 55 à 59 ans'  
      12 = 'De 60 à 64 ans'  
      13 = 'De 65 à 69 ans'  
      14 = '70 ans et plus' ;
   value EAYY_A3F
      1 = 'Oui, de naissance'  
      2 = '(Oui par réintégration, naturalisation, par mariage, par déc'  
      3 = 'Non'  
      4 = 'Apatride' ;
   value EAYY_A3B
      1 = 'France'  
      2 = 'Union européenne'  
      3 = 'Hors Union européenne'  
      9 = 'N''a pas répondu' ;
   value LABQ
      1 = 'Union européenne'  
      2 = 'Hors Union européenne'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_A3D
      1 = 'Oui'  
      2 = 'Non' ;
   value EAYY_A4F
      1 = 'Célibataire (jamais légalement marié(e))'  
      2 = 'Pacsé(e)'  
      3 = 'Union libre ou concubinage'  
      4 = 'Marié(e) (ou séparé(e) mais non divorcé(e))'  
      5 = 'Divorcé(e)'  
      6 = 'Pacs dissout'  
      7 = 'Veuf(ve)'  
      77 = 'Refuse de répondre' ;
   value EAYY_A5F
      1 = 'Oui, avec quelqu''un qui vit dans votre logement'  
      2 = 'Oui, avec quelqu''un qui ne vit pas dans votre logement'  
      3 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_A5A
      1 = 'Marié(e)'  
      2 = 'Pacsé(e)'  
      3 = 'En union libre, en concubinage'  
      4 = 'Autre (précisez)'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A5C
      1 = 'Depuis moins d’un an'  
      2 = 'Depuis un an ou plus'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A_A
      1 = 'Moins de 2 ans'  
      2 = 'De 2 à 4 ans'  
      3 = 'De 5 à 9 ans'  
      4 = 'De 10 à 14 ans'  
      5 = 'De 15 à 19 ans'  
      6 = 'De 20 à 24 ans'  
      7 = '25 ans et plus'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1F
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      77 = 'Refuse de répondre' ;
   value EAYY_B10F
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B_A
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B_B
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de réponse'  
      8 = 'Ne sait pas' ;
   value LABR
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B18F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,' ;
   value EAYY_B_D
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire (' ;
   value EAYY_B_E
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire ('  
      6 = 'Non concerné' ;
   value EAYY_B_F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,'  
      66 = 'Non concerné' ;
   value LABS
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1B
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      7 = 'Refuse de répondre' ;
   value EAYY_B_H
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EAYY_B1C
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre' ;
   value EAYY_B2F
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salarié(e) d''un particulier'  
      7 = 'Vous aidez un membre de votre famille dans son travail sans'  
      8 = 'Vous êtes chef d''entreprise salarié, PDG, gérant(e) minorita'  
      9 = 'Vous êtes indépendant(e) ou à votre compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B25F
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_B2C
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salairé(e) d''un particulier'  
      7 = 'Il(elle) aide un membre de sa famille dans son travail sans'  
      8 = 'Il(elle) est chef d''entreprise salarié, PDG, gérant(e) minor'  
      9 = 'Il(elle) est indépendant(e) ou à son compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value LABT
      1 = 'Aucun salarié'  
      2 = 'Au moins 1 salarié'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B5F
      1 = 'Contrat à durée indéterminée'  
      2 = '(Contrat à durée déterminée (dont contrat saisonnier))'  
      4 = 'Contrat d''interim ou de travail temporaire'  
      5 = 'Contrat d''apprentissage'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5A
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5B
      1 = '(80% et plus)'  
      3 = 'Entre 50 et 80%'  
      4 = 'Mi-temps (50%)'  
      5 = 'Moins d''un mi-temps (moins de 50%)'  
      6 = 'Non concerné' ;
   value EAYY_B5C
      1 = 'Pour exercer une autre activité professionnelle, ou suivre d'  
      2 = 'Pour raisons de santé'  
      3 = 'Vous n''avez pas trouvé d''emploi à temps plein'  
      4 = 'Cela vous a été imposé par votre employeur'  
      5 = 'Pour vous occuper de vos enfants, ou d''un autre membre de vo'  
      6 = 'Pour disposer de temps libre ou faire des travaux domestique'  
      7 = 'Pour une autre raison (précisez)'  
      66 = 'Non concerné' ;
   value EAYY_B6A
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvier(e) qualifié(e) ou hautement qualifié(e), technicien(n'  
      3 = 'Technicien(ne)'  
      4 = 'Agent de maîtrise, maîtrise administrative ou commerciale, V'  
      5 = 'Ingénieur, cadre (à l''exception des directeurs généraux ou d'  
      6 = 'Employé(e) de bureau, employé(e) de commerce, personnel de s'  
      7 = 'Directeur général, adjoint direct'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B6B
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvrier(e) qualifié(e) ou hautement qualifié(e), technicien('  
      3 = 'Technicien(ne)'  
      4 = 'Personnel de catégorie C ou assimilé'  
      5 = 'Personnel de catégorie B ou assimilé'  
      6 = 'Personnel de catégorie A ou assimilé'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B7B
      1 = 'Production, chantier, exploitation'  
      2 = 'Installation, réparation, maintenance'  
      3 = 'Gardiennage, nettoyage, entretien ménager'  
      4 = 'Manutention, magasinage, logistique'  
      5 = 'Secrétariat, saisie, accueil'  
      6 = 'Gestion, comptabilité'  
      7 = 'Commercial, technico-commercial'  
      8 = 'Études, recherche et développement, méthodes'  
      9 = 'Enseignement'  
      10 = 'Soin des personnes'  
      11 = 'Autre fonction (précisez)'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B8F
      1 = 'Moins de 10'  
      2 = '10 à 49'  
      3 = '50 à 499'  
      4 = '500 et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B9F
      1 = 'Moins de 20 hectares'  
      2 = 'De 20 à moins de 50 hectares'  
      3 = 'De 50 à moins de 100 hectares'  
      4 = 'De 100 à moins de 200 hectares'  
      5 = '200 hectares et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_C1F
      1 = '1 habitant'  
      2 = '2 habitants'  
      3 = '3 habitants'  
      4 = '4 habitants'  
      5 = '5 habitants'  
      6 = '6 habitants et plus' ;
   value EAYY_C1J
      1 = '0 jeune'  
      2 = '1 jeune'  
      3 = '2 jeunes'  
      4 = '3 jeunes ou plus' ;
   value EAYY_C8F
      1 = 'Oui'  
      2 = 'Non'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8A
      1 = '1 enfant'  
      2 = '2 enfants'  
      3 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8B
      1 = '0 enfant'  
      2 = '1 enfant'  
      3 = '2 enfants'  
      4 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D1F
      1 = 'Propriétaire (ou copropriétaire) : vous ne payez pas de créd'  
      2 = 'Accédant à la propriété : vous payez toujours un crédit immo'  
      3 = '(Locataire, sous-locataire)'  
      5 = 'Occupant à titre gratuit'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_D1A
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D2F
      1 = 'Votre conjoint(e)'  
      2 = 'Un autre membre du foyer'  
      3 = 'Une autre personne de votre famille'  
      4 = 'Un autre particulier'  
      5 = 'Un organisme HLM (ou assimilé, OPAC, offices, sociétés, fond'  
      6 = 'Une administration, organisme de Sécurité Sociale ou associa'  
      7 = 'Une banque, assurance ou autre société du secteur public ou'  
      8 = 'L''employeur d''un membre du ménage dans le cadre d''un logemen'  
      9 = 'Autre cas'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_D3F
      1 = 'Une maison individuelle'  
      2 = 'Un appartement'  
      3 = 'Autre (précisez)' ;
   value EAYY_D4F
      1 = '1 pièce'  
      2 = '2 pièces'  
      3 = '3 pièces'  
      4 = '4 pièces'  
      5 = '5 pièces'  
      6 = '6 pièces'  
      7 = '7 pièces'  
      8 = '8 pièces'  
      9 = '9 pièces et plus' ;
   value EAYY_D5F
      1 = 'Moins de 2 ans'  
      2 = 'Entre 2 à 5 ans'  
      3 = 'Entre 5 et 10 ans'  
      4 = 'Entre 10 et 15 ans'  
      5 = 'Il y a plus de 15 ans'  
      9 = 'N''a pas répondu' ;
   value EAYY_D6F
      1 = 'Maisons dispersées, hors agglomération'  
      2 = 'Maisons en lotissement, en quartier pavillonnaire ou en vill'  
      3 = 'Immeubles en ville (autre que cité ou grand ensemble)'  
      4 = 'Immeubles en cité ou grand ensemble'  
      5 = 'Habitat mixte : à la fois immeubles et maisons'  
      9 = 'N''a pas répondu' ;
   value LABU
      1 = 'Choisi'  
      2 = 'Non choisi'  
      9 = 'N''a pas répondu' ;
   value LABV
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas' ;
   value EAYY_E2A
      3 = '(Moins de 800 €)'  
      4 = 'De 800 à moins de 1000 €'  
      5 = 'De 1000 à moins de 1200 €'  
      6 = 'De 1200 à moins de 1500 €'  
      7 = 'De 1500 à moins de 1800 €'  
      8 = 'De 1800 à moins de 2000 €'  
      9 = 'De 2000 à moins de 2500 €'  
      10 = 'De 2500 à moins de 3000 €'  
      11 = 'De 3000 à moins de 4000 €'  
      12 = 'De 4000 à moins de 6000 €'  
      13 = '(6000 € et plus)'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_E_A
      1 = 'Moins de 650 €'  
      2 = 'De 650 à moins de 950 €'  
      3 = 'De 950 à moins de 1200 €'  
      4 = 'De 1200 à moins de 1400 €'  
      5 = 'De 1400 à moins de 1650 €'  
      6 = 'De 1650 à moins de 1900 €'  
      7 = 'De 1900 à moins de 2200 €'  
      8 = 'De 2200 à moins de 2500 €'  
      9 = 'De 2500 à moins de 3200 €'  
      10 = '3200 € et plus'  
      99 = 'N''a pas répondu' ;
   value EAYY_E_B
      1 = 'À partir du montant déclaré des ressources'  
      2 = 'À partir de la tranche déclarée des ressources'  
      3 = 'Non calculé' ;
   value LABW
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas'  
     .A = 'Non enquêté(e)' ;
   value EAYY_E4F
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
     .B = 'Non enquêté(e)' ;
   value EAYY_E5F
      1 = 'Vous ne pouvez pas y arriver sans faire de dettes'  
      2 = 'Vous y arrivez difficilement'  
      3 = 'C''''est juste, il faut faire attention'  
      4 = 'Ça va'  
      5 = 'Vous êtes plutôt à l''''aise'  
      6 = 'Vous êtes vraiment à l''''aise'  
      99 = 'N''a pas répondu' ;
   value EAYY_E5A
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABX
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABY
      1 = 'Au moins une fois par semaine'  
      2 = 'Une à trois fois par mois'  
      3 = 'Plusieurs fois dans l''année (mais moins d''une fois par mois)'  
      4 = 'Seulement pour des occasions exceptionnelles'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_F3F
      1 = 'Il n''y en a pas'  
      2 = '1 ou 2 personnes'  
      3 = 'Entre 3 et 5 personnes'  
      4 = '6 personnes ou plus'  
      8 = 'Ne sait pas' ;
   value EAYY_F4F
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_F5F
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n''est jamais assez prudent quand on a affaire aux autres'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value LABZ
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_G1F
      1 = 'Moins de 2 heures par jour'  
      2 = 'De 2 à 4 heures par jour'  
      3 = 'Plus de 4 heures par jour'  
      4 = 'Je ne regarde par la télévision'  
      8 = 'Ne sait pas' ;
   value EAYY_G2F
      1 = 'Aucun'  
      2 = 'Moins de 6'  
      3 = 'De 6 à moins de 12'  
      4 = 'De 12 à 24 (c''est-à-dire entre 1 et 2 livres par mois)'  
      5 = 'De 25 à 50 (c''est-à-dire plus de 2 livres par mois)'  
      6 = 'Plus de 50 (c''est-à-dire plus de 4 livres par mois)'  
      8 = 'Ne sait pas' ;
   value LABAA
      1 = 'Jamais'  
      2 = '1 à 3 fois'  
      3 = '4 à 6 fois'  
      4 = '7 à 12 fois'  
      5 = 'Plus de 12 fois'  
      9 = 'N''a pas répondu' ;
   value EAYY_G4F
      1 = 'Régulièrement tout au long de l''année'  
      2 = 'De temps en temps tout au long de l''année'  
      3 = 'Seulement pendant certaines périodes ou pendant les vacances'  
      4 = 'Occasionnellement ou rarement'  
      5 = 'Jamais'  
      8 = 'Ne sait pas' ;
   value EAYY_G5F
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu' ;
   value EAYY_H1A
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_H2F
      1 = 'Pas du tout d''importance'  
      2 = 'Un peu d''importance'  
      3 = 'Assez d''importance'  
      4 = 'Beaucoup d''importance'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_H4F
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_I1F
      1 = 'Beaucoup'  
      2 = 'Assez'  
      3 = 'Peu'  
      4 = 'Pas du tout'  
      8 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_I8F
      0 = 'Gauche'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = 'Droite'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas'  
      9996 = 'Non enquêté' ;
   value EAYY_J1F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_K3F
      1 = 'Tous les jours ou presque'  
      2 = 'Plusieurs fois par semaine'  
      3 = 'Une fois par semaine'  
      4 = 'Une à trois fois par mois'  
      5 = 'Moins souvent'  
      9 = 'N''a pas répondu' ;
   value EAYY_PCS
      10 = 'Agriculteurs exploitants'  
      20 = '(Artisans, commerçants et chefs d''entreprise)'  
      31 = 'Professions libérales et assimilés'  
      32 = 'Cadres de la fonction publique, professions intellectuelles'  
      36 = 'Cadres d''entreprise'  
      41 = 'Professions intermédiaires de l''enseignement, de la santé, d'  
      46 = 'Professions intermédiaires administratives et commerciales d'  
      47 = 'Techniciens'  
      48 = 'Contremaîtres, agents de maîtrise'  
      51 = 'Employés de la fonction publique'  
      54 = 'Employés administratifs d''entreprise'  
      55 = 'Employés de commerce'  
      56 = 'Personnels des services directs aux particuliers'  
      61 = 'Ouvriers qualifiés'  
      66 = '(Ouvriers non qualifiés et ouvriers agricoles)'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value LABAB
      1 = 'Agriculteurs exploitants'  
      2 = 'Artisans, commerçants et chefs d''entreprise'  
      3 = 'Cadres et professions intellectuelles supérieures'  
      4 = 'Professions intermédiaires'  
      5 = 'Employés'  
      6 = 'Ouvriers'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value EAYY_TYP
      1 = 'Ménages d''une seule personne'  
      2 = 'Familles monoparentales'  
      3 = 'Couples sans enfant'  
      4 = 'Couples avec enfant(s)'  
      5 = 'Ménages complexes de plus d''une personne' ;
   value INSEE_NU
      1 = 'FR1 : Région parisienne'  
      2 = 'FR2 : Bassin parisien'  
      3 = 'FR3 : Nord'  
      4 = 'FR4 : Est'  
      5 = 'FR5 : Ouest'  
      6 = 'FR6 : Sud-ouest'  
      7 = 'FR7 : Centre-est'  
      8 = 'FR8 : Méditerranée'  
      9 = 'FRA : Départements d''Outre-Mer' ;
   value INSEE_CA
      111 = 'Commune appartenant à un grand pôle (10 000 emplois ou plus)'  
      112 = 'Commune appartenant à la couronne d''un grand pôle'  
      120 = 'Commune multipolarisée des grandes aires urbaines'  
      211 = 'Commune appartenant à un moyen pôle (5 000 à moins de 10 000'  
      212 = 'Commune appartenant à la couronne d''un moyen pôle'  
      221 = 'Commune appartenant à un petit pôle (de 1 500 à moins de 5 0'  
      222 = 'Commune appartenant à la couronne d''un petit pôle'  
      300 = 'Autre commune multipolarisée'  
      400 = 'Commune isolée hors influence des pôles' ;
   value INSEE_TA
      0 = 'Commune hors aire urbaine'  
      1 = 'Commune appartenant à une aire urbaine de moins de 15 000 ha'  
      2 = 'Commune appartenant à une aire urbaine de 15 000 à 19 999 ha'  
      3 = 'Commune appartenant à une aire urbaine de 20 000 à 24 999 ha'  
      4 = 'Commune appartenant à une aire urbaine de 25 000 à 34 999 ha'  
      5 = 'Commune appartenant à une aire urbaine de 35 000 à 49 999 ha'  
      6 = 'Commune appartenant à une aire urbaine de 50 000 à 99 999 ha'  
      7 = 'Commune appartenant à une aire urbaine de 100 000 à 199 999'  
      8 = 'Commune appartenant à une aire urbaine de 200 000 à 499 999'  
      9 = 'Commune appartenant à une aire urbaine de 500 000 à 9 999 99'  
      10 = 'Commune appartenant à l''aire urbaine de Paris' ;
   value INSEE_TU
      0 = 'Commune rurale'  
      1 = 'Commune appartenant à une unité urbaine de 2 000 à 4 999 hab'  
      2 = 'Commune appartenant à une unité urbaine de 5 000 à 9 999 hab'  
      3 = 'Commune appartenant à une unité urbaine de 10 000 à 19 999 h'  
      4 = 'Commune appartenant à une unité urbaine de 20 000 à 49 999 h'  
      5 = 'Commune appartenant à une unité urbaine de 50 000 à 99 999 h'  
      6 = 'Commune appartenant à une unité urbaine de 100 000 à 199 999'  
      7 = 'Commune appartenant à une unité urbaine de 200 000 à 1 999 9'  
      8 = 'Commune appartenant à l''unité urbaine de Paris' ;
   value COCO3_FL
      1 = 'Français(e)'  
      2 = 'A acquis la nationalité française'  
      3 = 'Nationalité étrangère' ;

DATA library.&dataset ;
INFILE datafile LRECL=1043;
INPUT
   UID_ANONYM_COVID  1-4    coco3_cal_AGE1  5        coco3_cal_AGE2  6     
   coco3_cal_DIPL  7        coco3_cal_SEXE  8        coco3_cal_ZEAT  9     
   coco3_q04  10-13         coco3_q06_1  14-17       coco3_q06_10  18-21   
   coco3_q06_2  22-25       coco3_q06_3  26-29       coco3_q06_4  30-33    
   coco3_q06_5  34-37       coco3_q06_6  38-41       coco3_q06_7  42-45    
   coco3_q06_8  46-49       coco3_q06_9  50-53       coco3_q07_1  54       
   coco3_q07_2  55          coco3_q07_3  56          coco3_q09  57-60      
   coco3_q10  61-64         coco3_q16  65            coco3_q17  66-69      
   coco3_q18  70-73         coco3_q19  74-77         coco3_q20  78-81      
   coco3_q21  82-85         coco3_q25_a  86          coco3_q37  87-90      
   coco3_q38_modifie_bis  91-94   coco3_q41_1  95-98    
   coco3_q41_2  99-102      coco3_q41_3  103-106     coco3_q41_4  107-110  
   coco3_q41_5  111-114     coco3_q41_6  115-118  
   coco3_q46_modifie_1  119-122   coco3_q46_modifie_2  123-126
   coco3_q46_modifie_3  127-130   coco3_q46_modifie_4  131-134
   coco3_q47  135-138       coco3_q51  139-142       coco3_q52_1  143-146  
   coco3_q52_2  147-150     coco3_q52_3  151-154     coco3_q52_4  155-158  
   coco3_q53_1  159-162     coco3_q53_2  163-166     coco3_q53_3  167-170  
   coco3_q54_1  171-174     coco3_q54_2  175-178     coco3_q54_3  179-182  
   coco3_q54_4  183-186     coco3_q54_5  187-190     coco3_q54_6  191-194  
   coco3_q54_7  195-198     coco3_q54_8  199-202     coco3_q54_bis_1  203-206
   coco3_q54_bis_2  207-210   coco3_q54_bis_3  211-214
   coco3_q54_bis_4  215-218   coco3_q54_bis_5  219-222
   coco3_q54_bis_6  223-226   coco3_q54_bis_7  227-230   coco3_q59_1  231-234  
   coco3_q59_2  235-238     coco3_q59_3  239-242     coco3_q59_4  243-246  
   coco3_q59_5  247-250     coco3_q59_6  251-254     coco3_q59_7  255-258  
   coco3_q59_8  259-262     coco3_q59_9  263-266     coco3_q60_3  267-270  
   coco3_q60_5  271-274     coco3_q60_6  275-278     coco3_q64  279-280    
   coco3_q68  281-284       coco3_q79  285-288       coco3_q113  289-292   
   coco3_q114  293-296      coco3_q115  297-300      coco3_q116_1  301-304 
   coco3_q116_2  305-308    coco3_q116_3  309-312    coco3_q116_4  313-316 
   coco3_q116_5  317-320    coco3_q116_6  321-324    coco3_q117  325-328   
   coco3_q118_1  329-332    coco3_q118_2  333-336    coco3_q118_3  337-340 
   coco3_q118_4  341-344    coco3_q118_5  345-348    coco3_q118_6  349-352 
   coco3_q119  353-356      coco3_q120_1  357-360    coco3_q120_2  361-364 
   coco3_q120_3  365-368    coco3_q120_4  369-372    coco3_q120_5  373-376 
   coco3_q120_6  377-380    coco3_q120_7  381-384    coco3_q120_8  385-388 
   coco3_q121_1  389-392    coco3_q121_10  393-396   coco3_q121_2  397-400 
   coco3_q121_3  401-404    coco3_q121_4  405-408    coco3_q121_5  409-412 
   coco3_q121_6  413-416    coco3_q121_7  417-420    coco3_q121_8  421-424 
   coco3_q121_9  425-428    coco3_q122_1  429-432    coco3_q122_2  433-436 
   coco3_q122_3  437-440    coco3_q122_4  441-444    coco3_q122_5  445-448 
   coco3_q122_6  449-452    coco3_q122_7  453-456    coco3_q122_8  457-460 
   coco3_q122_9  461-464    coco3_q122_10  465-468   coco3_q122_11  469-472
   coco3_q123  473-476      coco3_q124  477-480      coco3_q125_1  481-484 
   coco3_q125_2  485-488    coco3_q125_3  489-492    coco3_q125_4  493-496 
   coco3_q125_5  497-500    coco3_q126_1  501-504    coco3_q126_2  505-508 
   coco3_q126_3  509-512    coco3_q126_4  513-516    coco3_q126_5  517-520 
   coco3_q126_6  521-524    coco3_q127_1  525-528    coco3_q127_2  529-532 
   coco3_q127_3  533-536    coco3_q127_4  537-540    coco3_q127_5  541-544 
   coco3_q127_6  545-548    coco3_q128  549-552      coco3_q129  553-556   
   coco3_q130  557-560      coco3_q131  561-564      coco3_q132_1  565-568 
   coco3_q132_2  569-572    coco3_q132_3  573-576    coco3_q132_4  577-580 
   coco3_q132_5  581-584    coco3_q132_6  585-588    coco3_q132_7  589-592 
   coco3_q133  593-596      coco3_q134  597-600      coco3_q135_1  601-604 
   coco3_q135_2  605-608    coco3_q135_3  609-612    coco3_q136_1  613-616 
   coco3_q136_2  617-620    coco3_q136_3  621-624    coco3_q137_1  625-628 
   coco3_q137_2  629-632    coco3_q137_3  633-636    coco3_q138_1  637-640 
   coco3_q138_2  641-644    coco3_q138_3  645-648    coco3_q139_1  649-652 
   coco3_q139_2  653-656    coco3_q139_3  657-660    coco3_q140_1  661-664 
   coco3_q140_2  665-668    coco3_q140_3  669-672    coco3_SWB  673-690    
   ea17_SWB  691-708        ea18_SWB  709-726        ea19_SWB  727-744     
   eayy_A1  745             eayy_A2A_rec  746-747    eayy_A3_rec  748      
   eayy_A3B_rec  749        eayy_A3C_rec  750        eayy_A3D  751         
   eayy_A3E_rec  752        eayy_A4  753-754         eayy_A5  755          
   eayy_A5A  756-759        eayy_A5C  760-763        eayy_A5C_rec  764-767 
   eayy_B1  768-769         eayy_B10A  770           eayy_B10AA  771-774   
   eayy_B10ACJT  775        eayy_B11  776            eayy_B11CJT  777      
   eayy_B18_rec  778-779    eayy_B18C  780           eayy_B18CCJT  781     
   eayy_B18CJT_rec  782-783   eayy_B1A  784-787        eayy_B1ACJT  788-791  
   eayy_B1B  792            eayy_B1BCJT  793         eayy_B1CJT  794-795   
   eayy_B2_rec  796-797     eayy_B25  798            eayy_B2CJT_rec  799-800
   eayy_B4_rec  801         eayy_B4CJT_rec  802      eayy_B5_rec  803      
   eayy_B5A  804            eayy_B5B_rec  805        eayy_B5C  806-807     
   eayy_B6A_rec  808-809    eayy_B6B_rec  810-811    eayy_B7B_rec  812-813 
   eayy_B8_rec  814         eayy_B9_rec  815         eayy_C1_rec  816      
   eayy_C1JEU  817          eayy_C8  818-821         eayy_C8A_rec  822-825 
   eayy_C8B_rec  826-829    eayy_D1_rec  830         eayy_D1A  831-834     
   eayy_D2  835-836         eayy_D3  837             eayy_D4_rec  838      
   eayy_D5_rec  839         eayy_D6  840             eayy_D7_1  841        
   eayy_D7_10  842          eayy_D7_2  843           eayy_D7_3  844        
   eayy_D7_4  845           eayy_D7_5  846           eayy_D7_6  847        
   eayy_D7_7  848           eayy_D7_8  849           eayy_D7_9  850        
   eayy_E1A  851            eayy_E1B  852            eayy_E1C  853         
   eayy_E1D  854            eayy_E1E  855            eayy_E1F  856         
   eayy_E1G  857            eayy_E1H  858            eayy_E1I  859         
   eayy_E1J  860            eayy_E2A_rec  861-862    eayy_E2AUC  863-864   
   eayy_E2AUC_SOURCE  865   eayy_E3A  866-869        eayy_E3B  870-873     
   eayy_E3C  874-877        eayy_E3D  878-881        eayy_E3E  882-885     
   eayy_E4  886-889         eayy_E5  890-891         eayy_E5A  892-895     
   eayy_E5B_1  896-899      eayy_E5B_2  900-903      eayy_E5B_3  904-907   
   eayy_E5B_4  908-911      eayy_E5B_5  912-915      eayy_E5B_6  916-919   
   eayy_E5B_7  920-923      eayy_E5B_8  924-927      eayy_E5B_9  928-931   
   eayy_F1_rec  932         eayy_F3  933             eayy_F4  934-937      
   eayy_F5  938-941         eayy_F6_rec  942         eayy_F7  943          
   eayy_F8  944             eayy_G1  945             eayy_G2  946          
   eayy_G3A  947            eayy_G3B  948            eayy_G3C  949         
   eayy_G4  950             eayy_G5  951             eayy_G6_1  952        
   eayy_G6_2  953           eayy_G6_3  954           eayy_G6_4  955        
   eayy_H1A  956            eayy_H2  957             eayy_H4  958          
   eayy_I1  959             eayy_I8  960-961         eayy_J1  962          
   eayy_K3  963             eayy_PCS18  964-966      eayy_PCS6  967-969    
   eayy_PCS6CJT  970-972    eayy_TYPMEN5  973        VAGUE  974-977        
   insee_NUTS1  978         insee_CATAEU2010  979-981   insee_TAU2014  982-983
   insee_TUU2014  984       coco3_POIDS  985-1002    coco3_PDSPLT $ 1003-1020
   coco3_cal_NAT  1021      coco3_POIDS_INIT  1022-1032
   coco3_PDSPLT_INIT $ 1033-1043 ;                       

LABEL
   UID_ANONYM_COVID = "Identifiant interviewé"
   coco3_cal_AGE1 = "Age décennal (calage panel pilote)"
   coco3_cal_AGE2 = "Age décennal (calage)"
   coco3_cal_DIPL = "Diplôme (calage)"
   coco3_cal_SEXE = "Sexe"
   coco3_cal_ZEAT = "Zone d'études et d'aménagement du territoire"
   coco3_q04 = "Auto-évaluation de la santé"
   coco3_q06_1 = "Symptômes pendant les deux dernières semaines : Toux"
   coco3_q06_10 = "Symptômes pendant les deux dernières semaines : Aucun de ces symptômes"
   coco3_q06_2 = "Symptômes pendant les deux dernières semaines : Maux de tête"
   coco3_q06_3 = "Symptômes pendant les deux dernières semaines : Fatigue"
   coco3_q06_4 = "Symptômes pendant les deux dernières semaines : Rhume"
   coco3_q06_5 = "Symptômes pendant les deux dernières semaines : Maux de gorge"
   coco3_q06_6 = "Symptômes pendant les deux dernières semaines : Gêne respiratoire"
   coco3_q06_7 = "Symptômes pendant les deux dernières semaines : Courbatures"
   coco3_q06_8 = "Symptômes pendant les deux dernières semaines : Fièvre"
   coco3_q06_9 = "Symptômes pendant les deux dernières semaines : Troubles digestifs"
   coco3_q07_1 = "Consultation médicale : Aucune"
   coco3_q07_2 = "Consultation médicale : Pour un ou plusieurs symptômes"
   coco3_q07_3 = "Consultation médicale : Autres raisons"
   coco3_q09 = "Infection par le virus covid-19"
   coco3_q10 = "État de santé actuel après une probable infection par le virus covid-19"
   coco3_q16 = "Les 2 dernières semaines, s'est senti : Nerveux"
   coco3_q17 = "Les 2 dernières semaines, s'est senti : Découragé"
   coco3_q18 = "Les 2 dernières semaines, s'est senti : Calme"
   coco3_q19 = "Les 2 dernières semaines, s'est senti : Triste et abattu"
   coco3_q20 = "Les 2 dernières semaines, s'est senti : Heureux"
   coco3_q21 = "Sentiment de solitude"
   coco3_q25_a = "Tensions au sein du ménage au cours des 2 dernières semaines"
   coco3_q37 = "Situation professionnelle actuelle pendant le confinement"
   coco3_q38_modifie_bis = "Situation actuelle vis-à-vis du télétravail"
   coco3_q41_1 = "Conditions de travail : Des risques pour la santé"
   coco3_q41_2 = "Conditions de travail : Des conflits avec employeur"
   coco3_q41_3 = "Conditions de travail : Des conflits avec collègues"
   coco3_q41_4 = "Conditions de travail : Un risque de chômage"
   coco3_q41_5 = "Conditions de travail : Une perte de salaire"
   coco3_q41_6 = "Conditions de travail : Aucune de ces situations"
   coco3_q46_modifie_1 = "Dépense 1 000€ : Avec économies"
   coco3_q46_modifie_2 = "Dépense 1 000€ : Avec emprunt auprès des proches"
   coco3_q46_modifie_3 = "Dépense 1 000€ : Avec emprunt auprès d'une banque"
   coco3_q46_modifie_4 = "Dépense 1 000€ : Impossible"
   coco3_q47 = "Fréquence des sorties au cours des deux dernières semaines"
   coco3_q51 = "Fréquence de la surveillance des travaux scolaires des enfants"
   coco3_q52_1 = "Fréquence des rencontres avec des amis dans la vie réelle"
   coco3_q52_2 = "Fréquence des rencontres avec des amis dans la vie virtuelle"
   coco3_q52_3 = "Fréquence des rencontres avec la famille dans la vie réelle"
   coco3_q52_4 = "Fréquence des rencontres avec  la famille par rencontre virtuelle"
   coco3_q53_1 = "Fréquence des contacts avec la famille à l'étranger"
   coco3_q53_2 = "Fréquence des contacts avec des amis à l'étranger"
   coco3_q53_3 = "Fréquence des contacts avec des collègues à l'étranger"
   coco3_q54_1 = "Reçu un coup de main ou l’aide : De la famille"
   coco3_q54_2 = "Reçu un coup de main ou l’aide : D'amis proches"
   coco3_q54_3 = "Reçu un coup de main ou l'aide : De collègues"
   coco3_q54_4 = "Reçu un coup de main ou l'aide : De voisins"
   coco3_q54_5 = "Reçu un coup de main ou l'aide : D'agents des services publics"
   coco3_q54_6 = "Reçu un coup de main ou l'aide : De bénévoles d’une association"
   coco3_q54_7 = "Reçu un coup de main ou l'aide : De personnes que vous ne connaissiez pas auparavant"
   coco3_q54_8 = "Reçu un coup de main ou l'aide : De personne"
   coco3_q54_bis_1 = "Donné un coup de main ou de l’aide à : La famille"
   coco3_q54_bis_2 = "Donné un coup de main ou de l’aide à : Des amis proches"
   coco3_q54_bis_3 = "Donné un coup de main ou l'aide à : Des collègues"
   coco3_q54_bis_4 = "Donné un coup de main ou l'aide à : Des voisins"
   coco3_q54_bis_5 = "Donné un coup de main ou l'aide à : Une association"
   coco3_q54_bis_6 = "Donné un coup de main ou l'aide à : Des personnes que vous ne connaissiez pas auparavant"
   coco3_q54_bis_7 = "Donné un coup de main ou l'aide à : Personne"
   coco3_q59_1 = "Temps consacré à : Faire du ménage"
   coco3_q59_2 = "Temps consacré à : S’occuper de ses enfants"
   coco3_q59_3 = "Temps consacré à : Prendre soin de personnes fragiles ou vulnérables"
   coco3_q59_4 = "Temps consacré à : Exercer son activité professionnelle"
   coco3_q59_5 = "Temps consacré à : Faire des exercices physiques / du sport"
   coco3_q59_6 = "Temps consacré à : Dormir"
   coco3_q59_7 = "Temps consacré à : Parler au téléphone"
   coco3_q59_8 = "Temps consacré à : Utiliser des réseaux sociaux"
   coco3_q59_9 = "Temps consacré à : Regarder la télévision"
   coco3_q60_3 = "Fréquence de : Lire"
   coco3_q60_5 = "Fréquence de : Prier"
   coco3_q60_6 = "Fréquence de : Méditer"
   coco3_q64 = "Stress lié au confinement"
   coco3_q68 = "Satisfaction quant à la manière dont le Gouvernement français gère l'épidémie du Covid-19"
   coco3_q79 = "Préoccupation par les conséquences sanitaires ou économiques de l’épidémie du Covid-19"
   coco3_q113 = "Sentiment d'avoir plus de temps libre qu’avant le confinement"
   coco3_q114 = "Fréquence de sortie du logement pendant plus d’une heure"
   coco3_q115 = "Avoir noué de nouvelles relations depuis le début du confinement"
   coco3_q116_1 = "Nouvelles relations : Voisins"
   coco3_q116_2 = "Nouvelles relations : Collègues"
   coco3_q116_3 = "Nouvelles relations : Personnes participant aux même activités collectives"
   coco3_q116_4 = "Nouvelles relations : Personnes rencontrées en ligne"
   coco3_q116_5 = "Nouvelles relations : Commerçants"
   coco3_q116_6 = "Nouvelles relations : Autre"
   coco3_q117 = "Suivre des groupes sur des supports électroniques"
   coco3_q118_1 = "Suivi via supports électroniques : Groupes familiaux"
   coco3_q118_2 = "Suivi via supports électroniques : Groupes amicaux"
   coco3_q118_3 = "Suivi via supports électroniques : Groupes professionnels"
   coco3_q118_4 = "Suivi via supports électroniques : Groupes associatifs"
   coco3_q118_5 = "Suivi via supports électroniques : Groupes thématiques"
   coco3_q118_6 = "Suivi via supports électroniques : Autres"
   coco3_q119 = "Avoir moins ou plus du tout de contact avec quelques personnes depuis le début du confinement"
   coco3_q120_1 = "Moins de contact avec : Membres de la famille"
   coco3_q120_2 = "Moins de contact avec : Voisins"
   coco3_q120_3 = "Moins de contact avec : Collègues"
   coco3_q120_4 = "Moins de contact avec : Amis"
   coco3_q120_5 = "Moins de contact avec : Personnes participant aux même activités collectives"
   coco3_q120_6 = "Moins de contact avec : Personnes rencontrées en ligne"
   coco3_q120_7 = "Moins de contact avec : Commerçants"
   coco3_q120_8 = "Moins de contact avec : Autre"
   coco3_q121_1 = "Connait : Chauffeur de bus ou de camion"
   coco3_q121_10 = "Connait : Enseignant"
   coco3_q121_2 = "Connait : Cadre supérieur de grande entreprise"
   coco3_q121_3 = "Connait : Agent d’entretien de bureaux ou de domiciles"
   coco3_q121_4 = "Connait : Coiffeur"
   coco3_q121_5 = "Connait : Responsable des ressources humaines"
   coco3_q121_6 = "Connait : Avocat"
   coco3_q121_7 = "Connait : Mécanicien automobile"
   coco3_q121_8 = "Connait : Infirmier"
   coco3_q121_9 = "Connait : Policier"
   coco3_q122_1 = "Depuis confinement, contact avec : Chauffeur de bus ou de camion"
   coco3_q122_2 = "Depuis confinement, contact avec : Cadre supérieur de grande entreprise"
   coco3_q122_3 = "Depuis confinement, contact avec : Agent d’entretien de bureaux ou de domiciles"
   coco3_q122_4 = "Depuis confinement, contact avec : Coiffeur"
   coco3_q122_5 = "Depuis confinement, contact avec : Responsable des ressources humaines"
   coco3_q122_6 = "Depuis confinement, contact avec : Avocat"
   coco3_q122_7 = "Depuis confinement, contact avec : Mécanicien automobile"
   coco3_q122_8 = "Depuis confinement, contact avec : Infirmier"
   coco3_q122_9 = "Depuis confinement, contacts avec : Policier"
   coco3_q122_10 = "Depuis confinement, contact avec : Enseignant"
   coco3_q122_11 = "Depuis confinement, contact avec : Aucune de ces professions"
   coco3_q123 = "Fréquence des relations sociales avant le confinement"
   coco3_q124 = "Fréquence de se serrer la main ou de faire la bise lors des rencontres avant le confinement"
   coco3_q125_1 = "Fréquence des contacts directs avec (avant confinement) : Des personnes beaucoup plus jeunes"
   coco3_q125_2 = "Fréquence des contacts directs avec (avant confinement) : Des personnes un peu plus jeunes"
   coco3_q125_3 = "Fréquence des contacts directs avec (avant confinement) : Des personnes d’environ le même âge"
   coco3_q125_4 = "Fréquence des contacts directs avec (avant confinement) : Des personnes un peu plus âgées"
   coco3_q125_5 = "Fréquence des contacts directs avec (avant confinement) : Des personnes beaucoup plus âgées"
   coco3_q126_1 = "Depuis le début du confinement : Changé d’emploi principal"
   coco3_q126_2 = "Depuis le début du confinement : Pris un petit boulot supplémentaire"
   coco3_q126_3 = "Depuis le début du confinement : Commencé de nouvelles activités comme auto-entrepreneur"
   coco3_q126_4 = "Depuis le début du confinement : Changé le contenu de vos tâches professionnelles"
   coco3_q126_5 = "Depuis le début du confinement : Été volontaire pour de nouvelles tâches"
   coco3_q126_6 = "Depuis le début du confinement : Aucune de ces modifications dans le cadre du travail"
   coco3_q127_1 = "Depuis le début du confinement : Une reprise du travail"
   coco3_q127_2 = "Depuis le début du confinement : Diminution du temps de travail ou de l’activité"
   coco3_q127_3 = "Depuis le début du confinement : Augmentation du temps de travail obligatoire"
   coco3_q127_4 = "Depuis le début du confinement : Obligation de travailler en horaires inhabituels"
   coco3_q127_5 = "Depuis le début du confinement : Dégradation des conditions de travail"
   coco3_q127_6 = "Depuis le début du confinement : Aucune de ces modifications des conditions de travail"
   coco3_q128 = "Comportement actuel au travail : Se soucie peu de l'établissement employeur tant qu'il reçoit son salaire"
   coco3_q129 = "Comportement actuel au travail : Les responsables de l'établissement employeur savent ce qu'ils font"
   coco3_q130 = "Satisfaction à l'égard du travail actuel"
   coco3_q131 = "Préférence pour le télétravail à l'avenir"
   coco3_q132_1 = "Avis sur le télétravail : Permet d’optimiser la journée de travail"
   coco3_q132_2 = "Avis sur le télétravail : Permet de se concentrer davantage"
   coco3_q132_3 = "Avis sur le télétravail : Mélange trop vie privée et vie professionnelle"
   coco3_q132_4 = "Avis sur le télétravail : Diminue le contrôle du travail et son efficacité"
   coco3_q132_5 = "Avis sur le télétravail : Pousse les gens à travailler plus"
   coco3_q132_6 = "Avis sur le télétravail : Augmente l’autonomie des travailleurs"
   coco3_q132_7 = "Avis sur le télétravail : N'apporte aucun de ces changements"
   coco3_q133 = "Situation professionnelle actuelle (conjoint(e)) (recodage)"
   coco3_q134 = "Situation actuelle vis-à-vis du télétravail (conjoint(e))"
   coco3_q135_1 = "Fréquence de faire la cuisine depuis le début du confinement : L'interviewé"
   coco3_q135_2 = "Fréquence de faire la cuisine depuis le début du confinement : Conjoint(e)"
   coco3_q135_3 = "Fréquence de faire la cuisine depuis le début du confinement : Autre personne"
   coco3_q136_1 = "Fréquence de faire les courses depuis le début du confinement : L'interviewé"
   coco3_q136_2 = "Fréquence de faire les courses depuis le début du confinement : Conjoint(e)"
   coco3_q136_3 = "Fréquence de faire les courses depuis le début du confinement : Autre personne"
   coco3_q137_1 = "Fréquence de faire la lessive depuis le début du confinement : L'interviewé"
   coco3_q137_2 = "Fréquence de faire la lessive depuis le début du confinement : Conjoint(e)"
   coco3_q137_3 = "Fréquence de faire la lessive depuis le début du confinement : Autre personne"
   coco3_q138_1 = "Fréquence de faire le repassage depuis le début du confinement : L'interviewé"
   coco3_q138_2 = "Fréquence de faire le repassage depuis le début du confinement : Conjoint(e)"
   coco3_q138_3 = "Fréquence de faire le repassage depuis le début du confinement : Autre personne"
   coco3_q139_1 = "Fréquence de faire le ménage depuis le début du confinement : L'interviewé"
   coco3_q139_2 = "Fréquence de faire le ménage depuis le début du confinement : Conjoint(e)"
   coco3_q139_3 = "Fréquence de faire le ménage depuis le début du confinement : Autre personne"
   coco3_q140_1 = "Fréquence de faire du bricolage, jardinage, etc. depuis le début du confinement : L'interviewé"
   coco3_q140_2 = "Fréquence de faire du bricolage, jardinage, etc. depuis le début du confinement : Conjoint(e)"
   coco3_q140_3 = "Fréquence de faire du bricolage, jardinage, etc. depuis le début du confinement : Autre personne"
   coco3_SWB = "Niveau de bien-être subjectif"
   ea17_SWB = "Index de bien-être subjectif (calcul EA17)"
   ea18_SWB = "Index de bien-être subjectif (calcul EA18)"
   ea19_SWB = "Index de bien-être subjectif (calcul EA19)"
   eayy_A1 = "Sexe (enquête annuelle)"
   eayy_A2A_rec = "Age quinquennal (recodage)"
   eayy_A3_rec = "A la nationalité francaise (recodage)"
   eayy_A3B_rec = "Pays de naissance (recodage)"
   eayy_A3C_rec = "Nationalité (recodage)"
   eayy_A3D = "A une seconde nationalité"
   eayy_A3E_rec = "Seconde nationalité (recodage)"
   eayy_A4 = "Statut matrimonial légal"
   eayy_A5 = "Vit en couple"
   eayy_A5A = "Situation familiale"
   eayy_A5C = "Ancienneté du couple"
   eayy_A5C_rec = "Ancienneté du couple (recodage)"
   eayy_B1 = "Situation principale vis-à-vis du travail"
   eayy_B10A = "Recherche d'emploi"
   eayy_B10AA = "Rercherche un autre emploi"
   eayy_B10ACJT = "Recherche d'emploi (conjoint)"
   eayy_B11 = "Ne travaille pas mais a déjà travaillé"
   eayy_B11CJT = "Ne travaille pas mais a déjà travaillé (conjoint)"
   eayy_B18_rec = "Diplôme le plus élevé (recodage)"
   eayy_B18C = "Niveau de formation (recodage)"
   eayy_B18CCJT = "Niveau de formation (conjoint) (calcul)"
   eayy_B18CJT_rec = "Diplôme le plus élevé (conjoint) (recodage)"
   eayy_B1A = "Emploi (étudiant, chômeur, retraité, autre inactif)"
   eayy_B1ACJT = "Emploi (étudiant, chômeur, retraité, autre inactif) (conjoint)"
   eayy_B1B = "Exercice d'une activité professionnelle (recodage)"
   eayy_B1BCJT = "Exercice d'une activité professionnelle (conjoint) (calcul)"
   eayy_B1CJT = "Situation principale vis-à-vis du travail (conjoint)"
   eayy_B2_rec = "Statut de l'activité actuelle ou antérieure (recodage)"
   eayy_B25 = "Supervision d'autres salariés"
   eayy_B2CJT_rec = "Statut de l'activité actuelle ou antérieure (conjoint) (calcul)"
   eayy_B4_rec = "Nombre de salariés employés actuellement ou par le passé (recodage)"
   eayy_B4CJT_rec = "Nombre de salariés employés actuellement ou par le passé (conjoint) (calcul)"
   eayy_B5_rec = "Type de contrat de travail (recodage)"
   eayy_B5A = "Temps de travail"
   eayy_B5B_rec = "Type de temps partiel (recodage)"
   eayy_B5C = "Raison principale du travail à temps partiel"
   eayy_B6A_rec = "Catégorie de l'emploi actuel ou antérieur secteur privé (recodage)"
   eayy_B6B_rec = "Catégorie de l'emploi actuel ou antérieur secteur public (recodage)"
   eayy_B7B_rec = "Fonction principale de l'emploi actuel ou antérieur (recodage)"
   eayy_B8_rec = "Nombre de salariés dans l'entreprise de l'emploi actuel ou antérieur (recodage)"
   eayy_B9_rec = "Superficie de l'exploitation actuelle ou antérieure (recodage)"
   eayy_C1_rec = "Nombre de personnes dans le foyer (recodage)"
   eayy_C1JEU = "Nombre de jeunes (calcul)"
   eayy_C8 = "A des enfants"
   eayy_C8A_rec = "Nombre d'enfants (recodage)"
   eayy_C8B_rec = "Nombre d'enfants cohabitants (recodage)"
   eayy_D1_rec = "Statut d'occupation du logement (recodage)"
   eayy_D1A = "Appartenance du logement à un organisme HLM"
   eayy_D2 = "Propriétaire du logement"
   eayy_D3 = "Type d'habitation"
   eayy_D4_rec = "Nombre pièces d'habitation du logement (recodage)"
   eayy_D5_rec = "Année d'emménagement dans le logement (calcul)"
   eayy_D6 = "Type d'habitat au voisinage du logement"
   eayy_D7_1 = "Problèmes concernant le quartier : Terrains-vagues, locaux désaffectés, friches industrielles, logements insalubres"
   eayy_D7_10 = "Problèmes concernant le quartier : Aucun de ces problèmes"
   eayy_D7_2 = "Problèmes concernant le quartier : Bruits ou pollution"
   eayy_D7_3 = "Problèmes concernant le quartier : Voirie insuffisante"
   eayy_D7_4 = "Problèmes concernant le quartier : Saleté"
   eayy_D7_5 = "Problèmes concernant le quartier : Manque d'espaces verts"
   eayy_D7_6 = "Problèmes concernant le quartier : Manque de commerces"
   eayy_D7_7 = "Problèmes concernant le quartier : Manque de lieux de rencontre, d'équipements"
   eayy_D7_8 = "Problèmes concernant le quartier : Isolement du quartier"
   eayy_D7_9 = "Problèmes concernant le quartier : Manque de sécurité"
   eayy_E1A = "Personnes dans le ménage percevant : Salaires, traitements et primes"
   eayy_E1B = "Personnes dans le ménage percevant : Revenus d'une activité professionnelle non salariée"
   eayy_E1C = "Personnes dans le ménage percevant : Allocations de chômage"
   eayy_E1D = "Personnes dans le ménage percevant : Préretraites, retraites"
   eayy_E1E = "Personnes dans le ménage percevant : Prestations liées à la maladie ou l'invalidité"
   eayy_E1F = "Personnes dans le ménage percevant : Prestations familiales et bourses"
   eayy_E1G = "Personnes dans le ménage percevant : Allocation logement, aide au logement"
   eayy_E1H = "Personnes dans le ménage percevant : RSA"
   eayy_E1I = "Personnes dans le ménage percevant : Loyers et fermages"
   eayy_E1J = "Personnes dans le ménage percevant : Pensions, aides"
   eayy_E2A_rec = "Tranche de montant des ressources (calcul)"
   eayy_E2AUC = "Tranche de revenu mensuel du ménage par unité de consommation (calcul)"
   eayy_E2AUC_SOURCE = "Source d'information du montant des ressources par unité de consommation"
   eayy_E3A = "Détention placements financiers : Livrets d'épargne"
   eayy_E3B = "Détention placements financiers : Epargne-logement"
   eayy_E3C = "Détention placements financiers : Assurances-vies"
   eayy_E3D = "Détention placements financiers : Epargne retraite"
   eayy_E3E = "Détention placements financiers : Valeurs immobilières"
   eayy_E4 = "Résidence secondaire"
   eayy_E5 = "Situation financière actuelle du mènage"
   eayy_E5A = "Baisse de revenu importante les 12 derniers mois"
   eayy_E5B_1 = "Baisse de revenu importante les 12 derniers mois : Licenciement/perte d'emploi"
   eayy_E5B_2 = "Baisse de revenu importante les 12 derniers mois : Modification du salaire/heures"
   eayy_E5B_3 = "Baisse de revenu importante les 12 derniers mois : Invalidité/incapacité"
   eayy_E5B_4 = "Baisse de revenu importante les 12 derniers mois : Maternité/congé parental/garde des enfants"
   eayy_E5B_5 = "Baisse de revenu importante les 12 derniers mois : Départ à la retraite"
   eayy_E5B_6 = "Baisse de revenu importante les 12 derniers mois : Mariage/rupture"
   eayy_E5B_7 = "Baisse de revenu importante les 12 derniers mois : Décès"
   eayy_E5B_8 = "Baisse de revenu importante les 12 derniers mois : Autre changement dans le ménage"
   eayy_E5B_9 = "Baisse de revenu importante les 12 derniers mois : Autre raison"
   eayy_F1_rec = "Fréquence de rencontre des amis (recodage)"
   eayy_F3 = "A quelqu'un pour discuter de questions intimes et personnelles"
   eayy_F4 = "Sentiment de solitude"
   eayy_F5 = "Opinion confiance ou prudence en général"
   eayy_F6_rec = "Fréquence de rencontre de la famille (recodage)"
   eayy_F7 = "Membre association humanitaire ou sociale"
   eayy_F8 = "Membre amicale ou association sportive ou culturelle"
   eayy_G1 = "Télévision les 12 derniers mois"
   eayy_G2 = "Nombre de livres lus les 12 derniers mois"
   eayy_G3A = "Sortie culturelle les 12 derniers mois : Au cinéma"
   eayy_G3B = "Sortie culturelle les 12 derniers mois : Au théâtre ou au concert"
   eayy_G3C = "Sortie culturelle les 12 derniers mois : Au musée ou une exposition"
   eayy_G4 = "Bricolage les 12 derniers mois"
   eayy_G5 = "Maîtrise d'une langue étrangère"
   eayy_G6_1 = "Partir en vacances les 12 derniers mois : Non"
   eayy_G6_2 = "Partir en vacances les 12 derniers mois : Dans la région"
   eayy_G6_3 = "Partir en vacances les 12 derniers mois : Dans une autre région"
   eayy_G6_4 = "Partir en vacances les 12 derniers mois : A l'étranger"
   eayy_H1A = "A une religion (recodage)"
   eayy_H2 = "Importance de la religion"
   eayy_H4 = "Éducation religieuse"
   eayy_I1 = "Intérêt pour la politique"
   eayy_I8 = "Auto-positionnement sur l'échelle gauche/droite"
   eayy_J1 = "État de santé"
   eayy_K3 = "Fréquence activité sportive 30 minutes d'affilée"
   eayy_PCS18 = "Catégorie socioprofessionnelle en 18 postes (profession actuelle ou dernière profession)"
   eayy_PCS6 = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession)"
   eayy_PCS6CJT = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession) (conjoint)"
   eayy_TYPMEN5 = "Type de ménage (calcul)"
   VAGUE = "VAGUE"
   insee_NUTS1 = "Nomenclature des unités territoriales statistiques niv. 1"
   insee_CATAEU2010 = "Catégorie de la commune dans le zonage en aires urbaines 2010"
   insee_TAU2014 = "Tranche d'aire urbaine 2014"
   insee_TUU2014 = "Tranche d'unité urbaine 2014"
   coco3_POIDS = "Poids individu"
   coco3_PDSPLT = "Poids individu (pilote)"
   coco3_cal_NAT = "Nationalité (calage)"
   coco3_POIDS_INIT = "Poids initial"
   coco3_PDSPLT_INIT = "Poids initial (pilote)" ;

 /* User Missing Value Specifications */
  IF coco3_q04 = 9999 THEN coco3_q04 =. ;
  IF coco3_q06_1 = 9999 THEN coco3_q06_1 =. ;
  IF coco3_q06_10 = 9999 THEN coco3_q06_10 =. ;
  IF coco3_q06_2 = 9999 THEN coco3_q06_2 =. ;
  IF coco3_q06_3 = 9999 THEN coco3_q06_3 =. ;
  IF coco3_q06_4 = 9999 THEN coco3_q06_4 =. ;
  IF coco3_q06_5 = 9999 THEN coco3_q06_5 =. ;
  IF coco3_q06_6 = 9999 THEN coco3_q06_6 =. ;
  IF coco3_q06_7 = 9999 THEN coco3_q06_7 =. ;
  IF coco3_q06_8 = 9999 THEN coco3_q06_8 =. ;
  IF coco3_q06_9 = 9999 THEN coco3_q06_9 =. ;
  IF coco3_q09 = 9999 THEN coco3_q09 =. ;
  IF coco3_q10 = 6666 THEN coco3_q10 =. ;
  IF coco3_q17 = 9999 THEN coco3_q17 =. ;
  IF coco3_q18 = 9999 THEN coco3_q18 =. ;
  IF coco3_q19 = 9999 THEN coco3_q19 =. ;
  IF coco3_q20 = 9999 THEN coco3_q20 =. ;
  IF coco3_q21 = 9999 THEN coco3_q21 =. ;
  IF coco3_q37 = 6666 OR coco3_q37 = 9999 THEN coco3_q37 =. ;
  IF coco3_q38_modifie_bis = 6666 OR coco3_q38_modifie_bis = 9999 THEN coco3_q38_modifie_bis =. ;
  IF coco3_q41_1 = 6666 THEN coco3_q41_1 =. ;
  IF coco3_q41_2 = 6666 THEN coco3_q41_2 =. ;
  IF coco3_q41_3 = 6666 THEN coco3_q41_3 =. ;
  IF coco3_q41_4 = 6666 THEN coco3_q41_4 =. ;
  IF coco3_q41_5 = 6666 THEN coco3_q41_5 =. ;
  IF coco3_q41_6 = 6666 THEN coco3_q41_6 =. ;
  IF coco3_q46_modifie_1 = 9999 THEN coco3_q46_modifie_1 =. ;
  IF coco3_q46_modifie_2 = 9999 THEN coco3_q46_modifie_2 =. ;
  IF coco3_q46_modifie_3 = 9999 THEN coco3_q46_modifie_3 =. ;
  IF coco3_q46_modifie_4 = 9999 THEN coco3_q46_modifie_4 =. ;
  IF coco3_q47 = 9999 THEN coco3_q47 =. ;
  IF coco3_q51 = 9999 THEN coco3_q51 =. ;
  IF coco3_q52_1 = 9999 THEN coco3_q52_1 =. ;
  IF coco3_q52_2 = 9999 THEN coco3_q52_2 =. ;
  IF coco3_q52_3 = 9999 THEN coco3_q52_3 =. ;
  IF coco3_q52_4 = 9999 THEN coco3_q52_4 =. ;
  IF coco3_q53_1 = 9999 THEN coco3_q53_1 =. ;
  IF coco3_q53_2 = 9999 THEN coco3_q53_2 =. ;
  IF coco3_q53_3 = 9999 THEN coco3_q53_3 =. ;
  IF coco3_q54_1 = 9999 THEN coco3_q54_1 =. ;
  IF coco3_q54_2 = 9999 THEN coco3_q54_2 =. ;
  IF coco3_q54_3 = 9999 THEN coco3_q54_3 =. ;
  IF coco3_q54_4 = 9999 THEN coco3_q54_4 =. ;
  IF coco3_q54_5 = 9999 THEN coco3_q54_5 =. ;
  IF coco3_q54_6 = 9999 THEN coco3_q54_6 =. ;
  IF coco3_q54_7 = 9999 THEN coco3_q54_7 =. ;
  IF coco3_q54_8 = 9999 THEN coco3_q54_8 =. ;
  IF coco3_q54_bis_1 = 9999 THEN coco3_q54_bis_1 =. ;
  IF coco3_q54_bis_2 = 9999 THEN coco3_q54_bis_2 =. ;
  IF coco3_q54_bis_3 = 9999 THEN coco3_q54_bis_3 =. ;
  IF coco3_q54_bis_4 = 9999 THEN coco3_q54_bis_4 =. ;
  IF coco3_q54_bis_5 = 9999 THEN coco3_q54_bis_5 =. ;
  IF coco3_q54_bis_6 = 9999 THEN coco3_q54_bis_6 =. ;
  IF coco3_q54_bis_7 = 9999 THEN coco3_q54_bis_7 =. ;
  IF coco3_q59_1 = 9999 THEN coco3_q59_1 =. ;
  IF coco3_q59_2 = 9999 THEN coco3_q59_2 =. ;
  IF coco3_q59_3 = 9999 THEN coco3_q59_3 =. ;
  IF coco3_q59_4 = 9999 THEN coco3_q59_4 =. ;
  IF coco3_q59_5 = 9999 THEN coco3_q59_5 =. ;
  IF coco3_q59_6 = 9999 THEN coco3_q59_6 =. ;
  IF coco3_q59_7 = 9999 THEN coco3_q59_7 =. ;
  IF coco3_q59_8 = 9999 THEN coco3_q59_8 =. ;
  IF coco3_q59_9 = 9999 THEN coco3_q59_9 =. ;
  IF coco3_q60_3 = 9999 THEN coco3_q60_3 =. ;
  IF coco3_q60_5 = 9999 THEN coco3_q60_5 =. ;
  IF coco3_q60_6 = 9999 THEN coco3_q60_6 =. ;
  IF coco3_q64 = 9999 THEN coco3_q64 =. ;
  IF coco3_q68 = 9999 THEN coco3_q68 =. ;
  IF coco3_q79 = 9999 THEN coco3_q79 =. ;
  IF coco3_q113 = 9999 THEN coco3_q113 =. ;
  IF coco3_q114 = 9999 THEN coco3_q114 =. ;
  IF coco3_q115 = 9999 THEN coco3_q115 =. ;
  IF coco3_q116_1 = 6666 THEN coco3_q116_1 =. ;
  IF coco3_q116_2 = 6666 THEN coco3_q116_2 =. ;
  IF coco3_q116_3 = 6666 THEN coco3_q116_3 =. ;
  IF coco3_q116_4 = 6666 THEN coco3_q116_4 =. ;
  IF coco3_q116_5 = 6666 THEN coco3_q116_5 =. ;
  IF coco3_q116_6 = 6666 THEN coco3_q116_6 =. ;
  IF coco3_q117 = 9999 THEN coco3_q117 =. ;
  IF coco3_q118_1 = 6666 THEN coco3_q118_1 =. ;
  IF coco3_q118_2 = 6666 THEN coco3_q118_2 =. ;
  IF coco3_q118_3 = 6666 THEN coco3_q118_3 =. ;
  IF coco3_q118_4 = 6666 THEN coco3_q118_4 =. ;
  IF coco3_q118_5 = 6666 THEN coco3_q118_5 =. ;
  IF coco3_q118_6 = 6666 THEN coco3_q118_6 =. ;
  IF coco3_q119 = 9999 THEN coco3_q119 =. ;
  IF coco3_q120_1 = 6666 THEN coco3_q120_1 =. ;
  IF coco3_q120_2 = 6666 THEN coco3_q120_2 =. ;
  IF coco3_q120_3 = 6666 THEN coco3_q120_3 =. ;
  IF coco3_q120_4 = 6666 THEN coco3_q120_4 =. ;
  IF coco3_q120_5 = 6666 THEN coco3_q120_5 =. ;
  IF coco3_q120_6 = 6666 THEN coco3_q120_6 =. ;
  IF coco3_q120_7 = 6666 THEN coco3_q120_7 =. ;
  IF coco3_q120_8 = 6666 THEN coco3_q120_8 =. ;
  IF coco3_q121_1 = 9999 THEN coco3_q121_1 =. ;
  IF coco3_q121_10 = 9999 THEN coco3_q121_10 =. ;
  IF coco3_q121_2 = 9999 THEN coco3_q121_2 =. ;
  IF coco3_q121_3 = 9999 THEN coco3_q121_3 =. ;
  IF coco3_q121_4 = 9999 THEN coco3_q121_4 =. ;
  IF coco3_q121_5 = 9999 THEN coco3_q121_5 =. ;
  IF coco3_q121_6 = 9999 THEN coco3_q121_6 =. ;
  IF coco3_q121_7 = 9999 THEN coco3_q121_7 =. ;
  IF coco3_q121_8 = 9999 THEN coco3_q121_8 =. ;
  IF coco3_q121_9 = 9999 THEN coco3_q121_9 =. ;
  IF coco3_q122_1 = 6666 THEN coco3_q122_1 =. ;
  IF coco3_q122_2 = 6666 THEN coco3_q122_2 =. ;
  IF coco3_q122_3 = 6666 THEN coco3_q122_3 =. ;
  IF coco3_q122_4 = 6666 THEN coco3_q122_4 =. ;
  IF coco3_q122_5 = 6666 THEN coco3_q122_5 =. ;
  IF coco3_q122_6 = 6666 THEN coco3_q122_6 =. ;
  IF coco3_q122_7 = 6666 THEN coco3_q122_7 =. ;
  IF coco3_q122_8 = 6666 THEN coco3_q122_8 =. ;
  IF coco3_q122_9 = 6666 THEN coco3_q122_9 =. ;
  IF coco3_q122_10 = 6666 THEN coco3_q122_10 =. ;
  IF coco3_q122_11 = 6666 THEN coco3_q122_11 =. ;
  IF coco3_q123 = 9999 THEN coco3_q123 =. ;
  IF coco3_q124 = 9999 THEN coco3_q124 =. ;
  IF coco3_q125_1 = 9999 THEN coco3_q125_1 =. ;
  IF coco3_q125_2 = 9999 THEN coco3_q125_2 =. ;
  IF coco3_q125_3 = 9999 THEN coco3_q125_3 =. ;
  IF coco3_q125_4 = 9999 THEN coco3_q125_4 =. ;
  IF coco3_q125_5 = 9999 THEN coco3_q125_5 =. ;
  IF coco3_q126_1 = 9999 THEN coco3_q126_1 =. ;
  IF coco3_q126_2 = 9999 THEN coco3_q126_2 =. ;
  IF coco3_q126_3 = 9999 THEN coco3_q126_3 =. ;
  IF coco3_q126_4 = 9999 THEN coco3_q126_4 =. ;
  IF coco3_q126_5 = 9999 THEN coco3_q126_5 =. ;
  IF coco3_q126_6 = 9999 THEN coco3_q126_6 =. ;
  IF coco3_q127_1 = 6666 OR coco3_q127_1 = 9999 THEN coco3_q127_1 =. ;
  IF coco3_q127_2 = 6666 OR coco3_q127_2 = 9999 THEN coco3_q127_2 =. ;
  IF coco3_q127_3 = 6666 OR coco3_q127_3 = 9999 THEN coco3_q127_3 =. ;
  IF coco3_q127_4 = 6666 OR coco3_q127_4 = 9999 THEN coco3_q127_4 =. ;
  IF coco3_q127_5 = 6666 OR coco3_q127_5 = 9999 THEN coco3_q127_5 =. ;
  IF coco3_q127_6 = 6666 OR coco3_q127_6 = 9999 THEN coco3_q127_6 =. ;
  IF coco3_q128 = 9999 THEN coco3_q128 =. ;
  IF coco3_q129 = 9999 THEN coco3_q129 =. ;
  IF coco3_q130 = 6666 OR coco3_q130 = 9999 THEN coco3_q130 =. ;
  IF coco3_q131 = 9999 THEN coco3_q131 =. ;
  IF coco3_q132_1 = 9999 THEN coco3_q132_1 =. ;
  IF coco3_q132_2 = 9999 THEN coco3_q132_2 =. ;
  IF coco3_q132_3 = 9999 THEN coco3_q132_3 =. ;
  IF coco3_q132_4 = 9999 THEN coco3_q132_4 =. ;
  IF coco3_q132_5 = 9999 THEN coco3_q132_5 =. ;
  IF coco3_q132_6 = 9999 THEN coco3_q132_6 =. ;
  IF coco3_q132_7 = 9999 THEN coco3_q132_7 =. ;
  IF coco3_q133 = 9999 THEN coco3_q133 =. ;
  IF coco3_q134 = 6666 THEN coco3_q134 =. ;
  IF coco3_q135_1 = 9999 THEN coco3_q135_1 =. ;
  IF coco3_q135_2 = 9999 OR coco3_q135_2 = 6666 THEN coco3_q135_2 =. ;
  IF coco3_q135_3 = 9999 THEN coco3_q135_3 =. ;
  IF coco3_q136_1 = 9999 THEN coco3_q136_1 =. ;
  IF coco3_q136_2 = 9999 THEN coco3_q136_2 =. ;
  IF coco3_q136_3 = 9999 THEN coco3_q136_3 =. ;
  IF coco3_q137_1 = 9999 THEN coco3_q137_1 =. ;
  IF coco3_q137_2 = 9999 OR coco3_q137_2 = 6666 THEN coco3_q137_2 =. ;
  IF coco3_q137_3 = 9999 THEN coco3_q137_3 =. ;
  IF coco3_q138_1 = 9999 THEN coco3_q138_1 =. ;
  IF coco3_q138_2 = 9999 OR coco3_q138_2 = 6666 THEN coco3_q138_2 =. ;
  IF coco3_q138_3 = 9999 THEN coco3_q138_3 =. ;
  IF coco3_q139_1 = 9999 THEN coco3_q139_1 =. ;
  IF coco3_q139_2 = 9999 OR coco3_q139_2 = 6666 THEN coco3_q139_2 =. ;
  IF coco3_q139_3 = 9999 THEN coco3_q139_3 =. ;
  IF coco3_q140_1 = 9999 THEN coco3_q140_1 =. ;
  IF coco3_q140_2 = 9999 OR coco3_q140_2 = 6666 THEN coco3_q140_2 =. ;
  IF coco3_q140_3 = 9999 THEN coco3_q140_3 =. ;
  IF coco3_SWB = 9999 THEN coco3_SWB =. ;
  IF eayy_A3_rec >= 7 THEN eayy_A3_rec =. ;
  IF eayy_A3B_rec >= 9 THEN eayy_A3B_rec =. ;
  IF eayy_A3C_rec >= 6 THEN eayy_A3C_rec =. ;
  IF eayy_A3D >= 6 THEN eayy_A3D =. ;
  IF eayy_A3E_rec >= 6 THEN eayy_A3E_rec =. ;
  IF eayy_A4 >= 77 THEN eayy_A4 =. ;
  IF eayy_A5 >= 7 THEN eayy_A5 =. ;
  IF eayy_A5A >= 6 OR eayy_A5A = 9996 THEN eayy_A5A =. ;
  IF eayy_A5C >= 6 OR eayy_A5C = 9996 THEN eayy_A5C =. ;
  IF eayy_A5C_rec >= 66 OR eayy_A5C_rec = 9996 THEN eayy_A5C_rec =. ;
  IF eayy_B1 >= 77 THEN eayy_B1 =. ;
  IF eayy_B10A >= 6 THEN eayy_B10A =. ;
  IF eayy_B10AA >= 6 OR eayy_B10AA = 9996 THEN eayy_B10AA =. ;
  IF eayy_B10ACJT >= 6 THEN eayy_B10ACJT =. ;
  IF eayy_B11 >= 6 THEN eayy_B11 =. ;
  IF eayy_B11CJT >= 6 THEN eayy_B11CJT =. ;
  IF eayy_B18_rec >= 77 THEN eayy_B18_rec =. ;
  IF eayy_B18C >= 7 THEN eayy_B18C =. ;
  IF eayy_B18CCJT >= 6 THEN eayy_B18CCJT =. ;
  IF eayy_B18CJT_rec >= 66 THEN eayy_B18CJT_rec =. ;
  IF eayy_B1A >= 6 OR eayy_B1A = 9996 THEN eayy_B1A =. ;
  IF eayy_B1ACJT >= 6 OR eayy_B1ACJT = 9996 THEN eayy_B1ACJT =. ;
  IF eayy_B1B >= 7 THEN eayy_B1B =. ;
  IF eayy_B1BCJT >= 6 THEN eayy_B1BCJT =. ;
  IF eayy_B1CJT >= 66 THEN eayy_B1CJT =. ;
  IF eayy_B2_rec >= 66 THEN eayy_B2_rec =. ;
  IF eayy_B25 >= 6 THEN eayy_B25 =. ;
  IF eayy_B2CJT_rec >= 66 THEN eayy_B2CJT_rec =. ;
  IF eayy_B4_rec >= 6 THEN eayy_B4_rec =. ;
  IF eayy_B4CJT_rec >= 6 THEN eayy_B4CJT_rec =. ;
  IF eayy_B5_rec >= 6 THEN eayy_B5_rec =. ;
  IF eayy_B5A >= 6 THEN eayy_B5A =. ;
  IF eayy_B5B_rec >= 6 THEN eayy_B5B_rec =. ;
  IF eayy_B5C >= 66 THEN eayy_B5C =. ;
  IF eayy_B6A_rec >= 66 THEN eayy_B6A_rec =. ;
  IF eayy_B6B_rec >= 66 THEN eayy_B6B_rec =. ;
  IF eayy_B7B_rec >= 66 THEN eayy_B7B_rec =. ;
  IF eayy_B8_rec >= 6 THEN eayy_B8_rec =. ;
  IF eayy_B9_rec >= 6 THEN eayy_B9_rec =. ;
  IF eayy_C1JEU >= 9 THEN eayy_C1JEU =. ;
  IF eayy_C8 >= 7 OR eayy_C8 = 9996 THEN eayy_C8 =. ;
  IF eayy_C8A_rec >= 6 OR eayy_C8A_rec = 9996 THEN eayy_C8A_rec =. ;
  IF eayy_C8B_rec >= 6 OR eayy_C8B_rec = 9996 THEN eayy_C8B_rec =. ;
  IF eayy_D1_rec >= 7 THEN eayy_D1_rec =. ;
  IF eayy_D1A >= 6 OR eayy_D1A = 9996 THEN eayy_D1A =. ;
  IF eayy_D2 >= 66 THEN eayy_D2 =. ;
  IF eayy_D4_rec >= 99 THEN eayy_D4_rec =. ;
  IF eayy_D5_rec >= 9 THEN eayy_D5_rec =. ;
  IF eayy_D6 >= 9 THEN eayy_D6 =. ;
  IF eayy_D7_1 >= 9 THEN eayy_D7_1 =. ;
  IF eayy_D7_10 >= 9 THEN eayy_D7_10 =. ;
  IF eayy_D7_2 >= 9 THEN eayy_D7_2 =. ;
  IF eayy_D7_3 >= 9 THEN eayy_D7_3 =. ;
  IF eayy_D7_4 >= 9 THEN eayy_D7_4 =. ;
  IF eayy_D7_5 >= 9 THEN eayy_D7_5 =. ;
  IF eayy_D7_6 >= 9 THEN eayy_D7_6 =. ;
  IF eayy_D7_7 >= 9 THEN eayy_D7_7 =. ;
  IF eayy_D7_8 >= 9 THEN eayy_D7_8 =. ;
  IF eayy_D7_9 >= 9 THEN eayy_D7_9 =. ;
  IF eayy_E2A_rec >= 77 THEN eayy_E2A_rec =. ;
  IF eayy_E2AUC >= 66 THEN eayy_E2AUC =. ;
  IF eayy_E3A = 9996 THEN eayy_E3A =. ;
  IF eayy_E3B = 9996 THEN eayy_E3B =. ;
  IF eayy_E3C = 9996 THEN eayy_E3C =. ;
  IF eayy_E3D = 9996 THEN eayy_E3D =. ;
  IF eayy_E3E = 9996 THEN eayy_E3E =. ;
  IF eayy_E4 >= 7 OR eayy_E4 = 9996 THEN eayy_E4 =. ;
  IF eayy_E5 >= 99 THEN eayy_E5 =. ;
  IF eayy_E5A >= 9 OR eayy_E5A = 9996 THEN eayy_E5A =. ;
  IF eayy_E5B_1 >= 6 THEN eayy_E5B_1 =. ;
  IF eayy_E5B_2 >= 6 THEN eayy_E5B_2 =. ;
  IF eayy_E5B_3 >= 6 THEN eayy_E5B_3 =. ;
  IF eayy_E5B_4 >= 6 THEN eayy_E5B_4 =. ;
  IF eayy_E5B_5 >= 6 THEN eayy_E5B_5 =. ;
  IF eayy_E5B_6 >= 6 THEN eayy_E5B_6 =. ;
  IF eayy_E5B_7 >= 6 THEN eayy_E5B_7 =. ;
  IF eayy_E5B_8 >= 6 THEN eayy_E5B_8 =. ;
  IF eayy_E5B_9 >= 6 OR eayy_E5B_9 = 9996 THEN eayy_E5B_9 =. ;
  IF eayy_F1_rec >= 7 THEN eayy_F1_rec =. ;
  IF eayy_F3 >= 8 THEN eayy_F3 =. ;
  IF eayy_F4 >= 7 OR eayy_F4 = 9996 THEN eayy_F4 =. ;
  IF eayy_F5 >= 7 OR eayy_F5 = 9996 THEN eayy_F5 =. ;
  IF eayy_F6_rec >= 7 THEN eayy_F6_rec =. ;
  IF eayy_F7 >= 7 THEN eayy_F7 =. ;
  IF eayy_F8 >= 7 THEN eayy_F8 =. ;
  IF eayy_G1 >= 8 THEN eayy_G1 =. ;
  IF eayy_G2 >= 8 THEN eayy_G2 =. ;
  IF eayy_G3A >= 9 THEN eayy_G3A =. ;
  IF eayy_G3B >= 9 THEN eayy_G3B =. ;
  IF eayy_G3C >= 9 THEN eayy_G3C =. ;
  IF eayy_G4 >= 8 THEN eayy_G4 =. ;
  IF eayy_G5 >= 9 THEN eayy_G5 =. ;
  IF eayy_G6_1 >= 9 THEN eayy_G6_1 =. ;
  IF eayy_G6_2 >= 9 THEN eayy_G6_2 =. ;
  IF eayy_G6_3 >= 9 THEN eayy_G6_3 =. ;
  IF eayy_G6_4 >= 9 THEN eayy_G6_4 =. ;
  IF eayy_H1A >= 7 THEN eayy_H1A =. ;
  IF eayy_H2 >= 7 THEN eayy_H2 =. ;
  IF eayy_H4 >= 7 THEN eayy_H4 =. ;
  IF eayy_I1 >= 8 THEN eayy_I1 =. ;
  IF eayy_I8 >= 77 THEN eayy_I8 =. ;
  IF eayy_J1 >= 7 THEN eayy_J1 =. ;
  IF eayy_K3 >= 9 THEN eayy_K3 =. ;
  IF eayy_PCS18 >= 666 THEN eayy_PCS18 =. ;
  IF eayy_PCS6 >= 66 THEN eayy_PCS6 =. ;
  IF eayy_PCS6CJT >= 66 THEN eayy_PCS6CJT =. ;
  IF eayy_TYPMEN5 >= 6 THEN eayy_TYPMEN5 =. ;
  IF insee_NUTS1 >= 99 THEN insee_NUTS1 =. ;
  IF insee_CATAEU2010 >= 999 THEN insee_CATAEU2010 =. ;
  IF insee_TAU2014 >= 99 THEN insee_TAU2014 =. ;
  IF insee_TUU2014 >= 9 THEN insee_TUU2014 =. ;

FORMAT
   coco3_cal_AGE1 COCO3_CA.   coco3_cal_AGE2 COCO3__A.   coco3_cal_DIPL COCO3__B.
   coco3_cal_SEXE COCO3__C.   coco3_cal_ZEAT COCO3__D.   coco3_q04 COCO3_Q0F.  
   coco3_q06_1 LABA.        coco3_q06_10 LABA.       coco3_q06_2 LABA.     
   coco3_q06_3 LABA.        coco3_q06_4 LABA.        coco3_q06_5 LABA.     
   coco3_q06_6 LABA.        coco3_q06_7 LABA.        coco3_q06_8 LABA.     
   coco3_q06_9 LABA.        coco3_q07_1 LABB.        coco3_q07_2 LABB.     
   coco3_q07_3 LABB.        coco3_q09 COCO3__R.      coco3_q10 COCO3_Q1F.  
   coco3_q16 COCO3__S.      coco3_q17 LABC.          coco3_q18 LABC.       
   coco3_q19 LABC.          coco3_q20 LABC.          coco3_q21 COCO3__W.   
   coco3_q25_a COCO3__X.    coco3_q37 COCO3_Q3F.     coco3_q38_modifie_bis COCO3__Y.
   coco3_q41_1 LABD.        coco3_q41_2 LABD.        coco3_q41_3 LABD.     
   coco3_q41_4 LABD.        coco3_q41_5 LABD.        coco3_q41_6 LABD.     
   coco3_q46_modifie_1 LABA.   coco3_q46_modifie_2 LABA.   coco3_q46_modifie_3 LABA.
   coco3_q46_modifie_4 LABA.   coco3_q47 COCO3_AI.      coco3_q51 COCO3_Q5F.  
   coco3_q52_1 LABE.        coco3_q52_2 LABE.        coco3_q52_3 LABE.     
   coco3_q52_4 LABE.        coco3_q53_1 LABF.        coco3_q53_2 LABF.     
   coco3_q53_3 LABF.        coco3_q54_1 LABA.        coco3_q54_2 LABA.     
   coco3_q54_3 LABA.        coco3_q54_4 LABA.        coco3_q54_5 LABA.     
   coco3_q54_6 LABA.        coco3_q54_7 LABA.        coco3_q54_8 LABA.     
   coco3_q54_bis_1 LABA.    coco3_q54_bis_2 LABA.    coco3_q54_bis_3 LABA. 
   coco3_q54_bis_4 LABA.    coco3_q54_bis_5 LABA.    coco3_q54_bis_6 LABA. 
   coco3_q54_bis_7 LABA.    coco3_q59_1 LABG.        coco3_q59_2 LABG.     
   coco3_q59_3 LABG.        coco3_q59_4 LABG.        coco3_q59_5 LABG.     
   coco3_q59_6 LABG.        coco3_q59_7 LABG.        coco3_q59_8 LABG.     
   coco3_q59_9 LABG.        coco3_q60_3 LABH.        coco3_q60_5 LABH.     
   coco3_q60_6 LABH.        coco3_q64 COCO3_BQ.      coco3_q68 COCO3_BR.   
   coco3_q79 COCO3_Q7F.     coco3_q113 COCO3_BS.     coco3_q114 COCO3_BT.  
   coco3_q115 LABI.         coco3_q116_1 LABD.       coco3_q116_2 LABD.    
   coco3_q116_3 LABD.       coco3_q116_4 LABD.       coco3_q116_5 LABD.    
   coco3_q116_6 LABD.       coco3_q117 LABI.         coco3_q118_1 LABD.    
   coco3_q118_2 LABD.       coco3_q118_3 LABD.       coco3_q118_4 LABD.    
   coco3_q118_5 LABD.       coco3_q118_6 LABD.       coco3_q119 LABI.      
   coco3_q120_1 LABD.       coco3_q120_2 LABD.       coco3_q120_3 LABD.    
   coco3_q120_4 LABD.       coco3_q120_5 LABD.       coco3_q120_6 LABD.    
   coco3_q120_7 LABD.       coco3_q120_8 LABD.       coco3_q121_1 LABJ.    
   coco3_q121_10 LABJ.      coco3_q121_2 LABJ.       coco3_q121_3 LABJ.    
   coco3_q121_4 LABJ.       coco3_q121_5 LABJ.       coco3_q121_6 LABJ.    
   coco3_q121_7 LABJ.       coco3_q121_8 LABJ.       coco3_q121_9 LABJ.    
   coco3_q122_1 LABD.       coco3_q122_2 LABD.       coco3_q122_3 LABD.    
   coco3_q122_4 LABD.       coco3_q122_5 LABD.       coco3_q122_6 LABD.    
   coco3_q122_7 LABD.       coco3_q122_8 LABD.       coco3_q122_9 LABD.    
   coco3_q122_10 LABD.      coco3_q122_11 LABD.      coco3_q123 COCO3_DN.  
   coco3_q124 COCO3_DO.     coco3_q125_1 LABK.       coco3_q125_2 LABK.    
   coco3_q125_3 LABK.       coco3_q125_4 LABK.       coco3_q125_5 LABK.    
   coco3_q126_1 LABA.       coco3_q126_2 LABA.       coco3_q126_3 LABA.    
   coco3_q126_4 LABA.       coco3_q126_5 LABA.       coco3_q126_6 LABA.    
   coco3_q127_1 LABL.       coco3_q127_2 LABL.       coco3_q127_3 LABL.    
   coco3_q127_4 LABL.       coco3_q127_5 LABL.       coco3_q127_6 LABL.    
   coco3_q128 LABM.         coco3_q129 LABM.         coco3_q130 COCO3_EI.  
   coco3_q131 COCO3_EJ.     coco3_q132_1 LABA.       coco3_q132_2 LABA.    
   coco3_q132_3 LABA.       coco3_q132_4 LABA.       coco3_q132_5 LABA.    
   coco3_q132_6 LABA.       coco3_q132_7 LABA.       coco3_q133 COCO3_ER.  
   coco3_q134 COCO3_ES.     coco3_q135_1 LABN.       coco3_q135_2 LABO.    
   coco3_q135_3 LABN.       coco3_q136_1 LABN.       coco3_q136_2 LABO.    
   coco3_q136_3 LABN.       coco3_q137_1 LABN.       coco3_q137_2 LABO.    
   coco3_q137_3 LABN.       coco3_q138_1 LABN.       coco3_q138_2 LABO.    
   coco3_q138_3 LABN.       coco3_q139_1 LABN.       coco3_q139_2 LABO.    
   coco3_q139_3 LABN.       coco3_q140_1 LABN.       coco3_q140_2 LABO.    
   coco3_q140_3 LABN.       ea17_SWB LABP.           ea18_SWB LABP.        
   ea19_SWB LABP.           eayy_A1 EAYY_A1F.        eayy_A2A_rec EAYY_A2A.
   eayy_A3_rec EAYY_A3F.    eayy_A3B_rec EAYY_A3B.   eayy_A3C_rec LABQ.    
   eayy_A3D EAYY_A3D.       eayy_A3E_rec LABQ.       eayy_A4 EAYY_A4F.     
   eayy_A5 EAYY_A5F.        eayy_A5A EAYY_A5A.       eayy_A5C EAYY_A5C.    
   eayy_A5C_rec EAYY_A_A.   eayy_B1 EAYY_B1F.        eayy_B10A EAYY_B10F.  
   eayy_B10AA EAYY_B_A.     eayy_B10ACJT EAYY_B_B.   eayy_B11 LABR.        
   eayy_B11CJT LABR.        eayy_B18_rec EAYY_B18F.   eayy_B18C EAYY_B_D.   
   eayy_B18CCJT EAYY_B_E.   eayy_B18CJT_rec EAYY_B_F.   eayy_B1A LABS.        
   eayy_B1ACJT LABS.        eayy_B1B EAYY_B1B.       eayy_B1BCJT EAYY_B_H. 
   eayy_B1CJT EAYY_B1C.     eayy_B2_rec EAYY_B2F.    eayy_B25 EAYY_B25F.   
   eayy_B2CJT_rec EAYY_B2C.   eayy_B4_rec LABT.        eayy_B4CJT_rec LABT.  
   eayy_B5_rec EAYY_B5F.    eayy_B5A EAYY_B5A.       eayy_B5B_rec EAYY_B5B.
   eayy_B5C EAYY_B5C.       eayy_B6A_rec EAYY_B6A.   eayy_B6B_rec EAYY_B6B.
   eayy_B7B_rec EAYY_B7B.   eayy_B8_rec EAYY_B8F.    eayy_B9_rec EAYY_B9F. 
   eayy_C1_rec EAYY_C1F.    eayy_C1JEU EAYY_C1J.     eayy_C8 EAYY_C8F.     
   eayy_C8A_rec EAYY_C8A.   eayy_C8B_rec EAYY_C8B.   eayy_D1_rec EAYY_D1F. 
   eayy_D1A EAYY_D1A.       eayy_D2 EAYY_D2F.        eayy_D3 EAYY_D3F.     
   eayy_D4_rec EAYY_D4F.    eayy_D5_rec EAYY_D5F.    eayy_D6 EAYY_D6F.     
   eayy_D7_1 LABU.          eayy_D7_10 LABU.         eayy_D7_2 LABU.       
   eayy_D7_3 LABU.          eayy_D7_4 LABU.          eayy_D7_5 LABU.       
   eayy_D7_6 LABU.          eayy_D7_7 LABU.          eayy_D7_8 LABU.       
   eayy_D7_9 LABU.          eayy_E1A LABV.           eayy_E1B LABV.        
   eayy_E1C LABV.           eayy_E1D LABV.           eayy_E1E LABV.        
   eayy_E1F LABV.           eayy_E1G LABV.           eayy_E1H LABV.        
   eayy_E1I LABV.           eayy_E1J LABV.           eayy_E2A_rec EAYY_E2A.
   eayy_E2AUC EAYY_E_A.     eayy_E2AUC_SOURCE EAYY_E_B.   eayy_E3A LABW.        
   eayy_E3B LABW.           eayy_E3C LABW.           eayy_E3D LABW.        
   eayy_E3E LABW.           eayy_E4 EAYY_E4F.        eayy_E5 EAYY_E5F.     
   eayy_E5A EAYY_E5A.       eayy_E5B_1 LABX.         eayy_E5B_2 LABX.      
   eayy_E5B_3 LABX.         eayy_E5B_4 LABX.         eayy_E5B_5 LABX.      
   eayy_E5B_6 LABX.         eayy_E5B_7 LABX.         eayy_E5B_8 LABX.      
   eayy_E5B_9 LABX.         eayy_F1_rec LABY.        eayy_F3 EAYY_F3F.     
   eayy_F4 EAYY_F4F.        eayy_F5 EAYY_F5F.        eayy_F6_rec LABY.     
   eayy_F7 LABZ.            eayy_F8 LABZ.            eayy_G1 EAYY_G1F.     
   eayy_G2 EAYY_G2F.        eayy_G3A LABAA.          eayy_G3B LABAA.       
   eayy_G3C LABAA.          eayy_G4 EAYY_G4F.        eayy_G5 EAYY_G5F.     
   eayy_G6_1 LABU.          eayy_G6_2 LABU.          eayy_G6_3 LABU.       
   eayy_G6_4 LABU.          eayy_H1A EAYY_H1A.       eayy_H2 EAYY_H2F.     
   eayy_H4 EAYY_H4F.        eayy_I1 EAYY_I1F.        eayy_I8 EAYY_I8F.     
   eayy_J1 EAYY_J1F.        eayy_K3 EAYY_K3F.        eayy_PCS18 EAYY_PCS.  
   eayy_PCS6 LABAB.         eayy_PCS6CJT LABAB.      eayy_TYPMEN5 EAYY_TYP.
   insee_NUTS1 INSEE_NU.    insee_CATAEU2010 INSEE_CA.   insee_TAU2014 INSEE_TA.
   insee_TUU2014 INSEE_TU.   coco3_cal_NAT COCO3_FL. ;
                      

LENGTH
   UID_ANONYM_COVID 4       coco3_cal_AGE1 3         coco3_cal_AGE2 3      
   coco3_cal_DIPL 3         coco3_cal_SEXE 3         coco3_cal_ZEAT 3      
   coco3_q04 4              coco3_q06_1 4            coco3_q06_10 4        
   coco3_q06_2 4            coco3_q06_3 4            coco3_q06_4 4         
   coco3_q06_5 4            coco3_q06_6 4            coco3_q06_7 4         
   coco3_q06_8 4            coco3_q06_9 4            coco3_q07_1 3         
   coco3_q07_2 3            coco3_q07_3 3            coco3_q09 4           
   coco3_q10 4              coco3_q16 3              coco3_q17 4           
   coco3_q18 4              coco3_q19 4              coco3_q20 4           
   coco3_q21 4              coco3_q25_a 3            coco3_q37 4           
   coco3_q38_modifie_bis 4   coco3_q41_1 4            coco3_q41_2 4         
   coco3_q41_3 4            coco3_q41_4 4            coco3_q41_5 4         
   coco3_q41_6 4            coco3_q46_modifie_1 4    coco3_q46_modifie_2 4 
   coco3_q46_modifie_3 4    coco3_q46_modifie_4 4    coco3_q47 4           
   coco3_q51 4              coco3_q52_1 4            coco3_q52_2 4         
   coco3_q52_3 4            coco3_q52_4 4            coco3_q53_1 4         
   coco3_q53_2 4            coco3_q53_3 4            coco3_q54_1 4         
   coco3_q54_2 4            coco3_q54_3 4            coco3_q54_4 4         
   coco3_q54_5 4            coco3_q54_6 4            coco3_q54_7 4         
   coco3_q54_8 4            coco3_q54_bis_1 4        coco3_q54_bis_2 4     
   coco3_q54_bis_3 4        coco3_q54_bis_4 4        coco3_q54_bis_5 4     
   coco3_q54_bis_6 4        coco3_q54_bis_7 4        coco3_q59_1 4         
   coco3_q59_2 4            coco3_q59_3 4            coco3_q59_4 4         
   coco3_q59_5 4            coco3_q59_6 4            coco3_q59_7 4         
   coco3_q59_8 4            coco3_q59_9 4            coco3_q60_3 4         
   coco3_q60_5 4            coco3_q60_6 4            coco3_q64 3           
   coco3_q68 4              coco3_q79 4              coco3_q113 4          
   coco3_q114 4             coco3_q115 4             coco3_q116_1 4        
   coco3_q116_2 4           coco3_q116_3 4           coco3_q116_4 4        
   coco3_q116_5 4           coco3_q116_6 4           coco3_q117 4          
   coco3_q118_1 4           coco3_q118_2 4           coco3_q118_3 4        
   coco3_q118_4 4           coco3_q118_5 4           coco3_q118_6 4        
   coco3_q119 4             coco3_q120_1 4           coco3_q120_2 4        
   coco3_q120_3 4           coco3_q120_4 4           coco3_q120_5 4        
   coco3_q120_6 4           coco3_q120_7 4           coco3_q120_8 4        
   coco3_q121_1 4           coco3_q121_10 4          coco3_q121_2 4        
   coco3_q121_3 4           coco3_q121_4 4           coco3_q121_5 4        
   coco3_q121_6 4           coco3_q121_7 4           coco3_q121_8 4        
   coco3_q121_9 4           coco3_q122_1 4           coco3_q122_2 4        
   coco3_q122_3 4           coco3_q122_4 4           coco3_q122_5 4        
   coco3_q122_6 4           coco3_q122_7 4           coco3_q122_8 4        
   coco3_q122_9 4           coco3_q122_10 4          coco3_q122_11 4       
   coco3_q123 4             coco3_q124 4             coco3_q125_1 4        
   coco3_q125_2 4           coco3_q125_3 4           coco3_q125_4 4        
   coco3_q125_5 4           coco3_q126_1 4           coco3_q126_2 4        
   coco3_q126_3 4           coco3_q126_4 4           coco3_q126_5 4        
   coco3_q126_6 4           coco3_q127_1 4           coco3_q127_2 4        
   coco3_q127_3 4           coco3_q127_4 4           coco3_q127_5 4        
   coco3_q127_6 4           coco3_q128 4             coco3_q129 4          
   coco3_q130 4             coco3_q131 4             coco3_q132_1 4        
   coco3_q132_2 4           coco3_q132_3 4           coco3_q132_4 4        
   coco3_q132_5 4           coco3_q132_6 4           coco3_q132_7 4        
   coco3_q133 4             coco3_q134 4             coco3_q135_1 4        
   coco3_q135_2 4           coco3_q135_3 4           coco3_q136_1 4        
   coco3_q136_2 4           coco3_q136_3 4           coco3_q137_1 4        
   coco3_q137_2 4           coco3_q137_3 4           coco3_q138_1 4        
   coco3_q138_2 4           coco3_q138_3 4           coco3_q139_1 4        
   coco3_q139_2 4           coco3_q139_3 4           coco3_q140_1 4        
   coco3_q140_2 4           coco3_q140_3 4           eayy_A1 3             
   eayy_A2A_rec 3           eayy_A3_rec 3            eayy_A3B_rec 3        
   eayy_A3C_rec 3           eayy_A3D 3               eayy_A3E_rec 3        
   eayy_A4 3                eayy_A5 3                eayy_A5A 4            
   eayy_A5C 4               eayy_A5C_rec 4           eayy_B1 3             
   eayy_B10A 3              eayy_B10AA 4             eayy_B10ACJT 3        
   eayy_B11 3               eayy_B11CJT 3            eayy_B18_rec 3        
   eayy_B18C 3              eayy_B18CCJT 3           eayy_B18CJT_rec 3     
   eayy_B1A 4               eayy_B1ACJT 4            eayy_B1B 3            
   eayy_B1BCJT 3            eayy_B1CJT 3             eayy_B2_rec 3         
   eayy_B25 3               eayy_B2CJT_rec 3         eayy_B4_rec 3         
   eayy_B4CJT_rec 3         eayy_B5_rec 3            eayy_B5A 3            
   eayy_B5B_rec 3           eayy_B5C 3               eayy_B6A_rec 3        
   eayy_B6B_rec 3           eayy_B7B_rec 3           eayy_B8_rec 3         
   eayy_B9_rec 3            eayy_C1_rec 3            eayy_C1JEU 3          
   eayy_C8 4                eayy_C8A_rec 4           eayy_C8B_rec 4        
   eayy_D1_rec 3            eayy_D1A 4               eayy_D2 3             
   eayy_D3 3                eayy_D4_rec 3            eayy_D5_rec 3         
   eayy_D6 3                eayy_D7_1 3              eayy_D7_10 3          
   eayy_D7_2 3              eayy_D7_3 3              eayy_D7_4 3           
   eayy_D7_5 3              eayy_D7_6 3              eayy_D7_7 3           
   eayy_D7_8 3              eayy_D7_9 3              eayy_E1A 3            
   eayy_E1B 3               eayy_E1C 3               eayy_E1D 3            
   eayy_E1E 3               eayy_E1F 3               eayy_E1G 3            
   eayy_E1H 3               eayy_E1I 3               eayy_E1J 3            
   eayy_E2A_rec 3           eayy_E2AUC 3             eayy_E2AUC_SOURCE 3   
   eayy_E3A 4               eayy_E3B 4               eayy_E3C 4            
   eayy_E3D 4               eayy_E3E 4               eayy_E4 4             
   eayy_E5 3                eayy_E5A 4               eayy_E5B_1 4          
   eayy_E5B_2 4             eayy_E5B_3 4             eayy_E5B_4 4          
   eayy_E5B_5 4             eayy_E5B_6 4             eayy_E5B_7 4          
   eayy_E5B_8 4             eayy_E5B_9 4             eayy_F1_rec 3         
   eayy_F3 3                eayy_F4 4                eayy_F5 4             
   eayy_F6_rec 3            eayy_F7 3                eayy_F8 3             
   eayy_G1 3                eayy_G2 3                eayy_G3A 3            
   eayy_G3B 3               eayy_G3C 3               eayy_G4 3             
   eayy_G5 3                eayy_G6_1 3              eayy_G6_2 3           
   eayy_G6_3 3              eayy_G6_4 3              eayy_H1A 3            
   eayy_H2 3                eayy_H4 3                eayy_I1 3             
   eayy_I8 3                eayy_J1 3                eayy_K3 3             
   eayy_PCS18 4             eayy_PCS6 4              eayy_PCS6CJT 4        
   eayy_TYPMEN5 3           VAGUE 4                  insee_NUTS1 3         
   insee_CATAEU2010 4       insee_TAU2014 3          insee_TUU2014 3       
   coco3_cal_NAT 3 ;

   

RUN ;
