/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/21027/Desktop/MAD/ELIPSS/EA19/diffusion/cdsp_ea2019/donnees_EA2019/sas_ea201903/fr.cdsp.ddi.elipss.201903.ea.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/21027/Desktop/MAD/ELIPSS/EA19/diffusion/cdsp_ea2019/donnees_EA2019/sas_ea201903/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = fr_cdsp_ ;

proc format library = library ;
   value EA19_A1F
      1 = 'Un homme'  
      2 = 'Une femme' ;
   value EA19_A2A
      4 = 'Moins de 24 ans'  
      5 = 'De 25 à 29 ans'  
      6 = 'De 30 à 34 ans'  
      7 = 'De 35 à 39 ans'  
      8 = 'De 40 à 44 ans'  
      9 = 'De 45 à 49 ans'  
      10 = 'De 50 à 54 ans'  
      11 = 'De 55 à 59 ans'  
      12 = 'De 60 à 64 ans'  
      13 = 'De 65 à 69 ans'  
      14 = '70 ans et plus' ;
   value EA19_A3F
      1 = 'Oui, de naissance'  
      2 = '(Oui par réintégration, naturalisation, par mariage, par déc'  
      3 = 'Non'  
      4 = 'Apatride' ;
   value EA19_A3B
      1 = 'France'  
      2 = 'Union européenne'  
      3 = 'Hors Union européenne'  
      9 = 'N''a pas répondu' ;
   value LABA
      1 = 'Union européenne'  
      2 = 'Hors Union européenne'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value LABB
      1 = 'Oui'  
      2 = 'Non' ;
   value EA19_A4F
      1 = 'Célibataire (jamais légalement marié(e))'  
      2 = 'Pacsé(e)'  
      3 = 'Union libre ou concubinage'  
      4 = 'Marié(e) (ou séparé(e) mais non divorcé(e))'  
      5 = 'Divorcé(e)'  
      6 = 'Pacs dissout'  
      7 = 'Veuf(ve)'  
      77 = 'Refuse de répondre' ;
   value EA19_A5F
      1 = 'Oui, avec quelqu''un qui vit dans votre logement'  
      2 = 'Oui, avec quelqu''un qui ne vit pas dans votre logement'  
      3 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EA19_A5A
      1 = 'Marié(e)'  
      2 = 'Pacsé(e)'  
      3 = 'En union libre, en concubinage'  
      4 = 'Autre (précisez)'  
      6 = 'Non concerné' ;
   value EA19_A5C
      1 = 'Depuis moins d’un an'  
      2 = 'Depuis un an ou plus'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EA19_A_A
      1 = 'Moins de 2 ans'  
      2 = 'De 2 à 4 ans'  
      3 = 'De 5 à 9 ans'  
      4 = 'De 10 à 14 ans'  
      5 = 'De 15 à 19 ans'  
      6 = 'De 20 à 24 ans'  
      7 = '25 ans et plus'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu' ;
   value EA19_B1F
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      77 = 'Refuse de répondre' ;
   value LABC
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné' ;
   value EA19_B1B
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      7 = 'Refuse de répondre' ;
   value EA19_B5A
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EA19_B5C
      1 = 'Pour exercer une autre activité professionnelle, ou suivre d'  
      2 = 'Pour raisons de santé'  
      3 = 'Vous n''avez pas trouvé d''emploi à temps plein'  
      4 = 'Cela vous a été imposé par votre employeur'  
      5 = 'Pour vous occuper de vos enfants, ou d''un autre membre de vo'  
      6 = 'Pour disposer de temps libre ou faire des travaux domestique'  
      7 = 'Pour une autre raison (précisez)'  
      66 = 'Non concerné' ;
   value EA19_B25F
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value LABD
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné' ;
   value EA19_B18F
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire (' ;
   value EA19_B_B
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,' ;
   value EA19_B2F
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salarié(e) d''un particulier'  
      7 = 'Vous aidez un membre de votre famille dans son travail sans'  
      8 = 'Vous êtes chef d''entreprise salarié, PDG, gérant(e) minorita'  
      9 = 'Vous êtes indépendant(e) ou à votre compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value LABE
      1 = 'Aucun salarié'  
      2 = 'Au moins 1 salarié'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EA19_B5F
      1 = 'Contrat à durée indéterminée'  
      2 = '(Contrat à durée déterminée (dont contrat saisonnier))'  
      4 = 'Contrat d''interim ou de travail temporaire'  
      5 = 'Contrat d''apprentissage'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EA19_B5B
      1 = '(80% et plus)'  
      3 = 'Entre 50 et 80%'  
      4 = 'Mi-temps (50%)'  
      5 = 'Moins d''un mi-temps (moins de 50%)'  
      6 = 'Non concerné' ;
   value EA19_B6A
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvier(e) qualifié(e) ou hautement qualifié(e), technicien(n'  
      3 = 'Technicien(ne)'  
      4 = 'Agent de maîtrise, maîtrise administrative ou commerciale, V'  
      5 = 'Ingénieur, cadre (à l''exception des directeurs généraux ou d'  
      6 = 'Employé(e) de bureau, employé(e) de commerce, personnel de s'  
      7 = 'Directeur général, adjoint direct'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EA19_B6B
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvrier(e) qualifié(e) ou hautement qualifié(e), technicien('  
      3 = 'Technicien(ne)'  
      4 = 'Personnel de catégorie C ou assimilé'  
      5 = 'Personnel de catégorie B ou assimilé'  
      6 = 'Personnel de catégorie A ou assimilé'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EA19_B7B
      1 = 'Production, chantier, exploitation'  
      2 = 'Installation, réparation, maintenance'  
      3 = 'Gardiennage, nettoyage, entretien ménager'  
      4 = 'Manutention, magasinage, logistique'  
      5 = 'Secrétariat, saisie, accueil'  
      6 = 'Gestion, comptabilité'  
      7 = 'Commercial, technico-commercial'  
      8 = 'Études, recherche et développement, méthodes'  
      9 = 'Enseignement'  
      10 = 'Soin des personnes'  
      11 = 'Autre fonction (précisez)'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EA19_B8F
      1 = 'Moins de 10'  
      2 = '10 à 49'  
      3 = '50 à 499'  
      4 = '500 et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EA19_B9F
      1 = 'Moins de 20 hectares'  
      2 = 'De 20 à moins de 50 hectares'  
      3 = 'De 50 à moins de 100 hectares'  
      4 = 'De 100 à moins de 200 hectares'  
      5 = '200 hectares et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EA19_PCS
      10 = 'Agriculteurs exploitants'  
      20 = '(Artisans, commerçants et chefs d''entreprise)'  
      31 = 'Professions libérales et assimilés'  
      32 = 'Cadres de la fonction publique, professions intellectuelles'  
      36 = 'Cadres d''entreprise'  
      41 = 'Professions intermédiaires de l''enseignement, de la santé, d'  
      46 = 'Professions intermédiaires administratives et commerciales d'  
      47 = 'Techniciens'  
      48 = 'Contremaîtres, agents de maîtrise'  
      51 = 'Employés de la fonction publique'  
      54 = 'Employés administratifs d''entreprise'  
      55 = 'Employés de commerce'  
      56 = 'Personnels des services directs aux particuliers'  
      61 = 'Ouvriers qualifiés'  
      66 = '(Ouvriers non qualifiés et ouvriers agricoles)'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value LABF
      1 = 'Agriculteurs exploitants'  
      2 = 'Artisans, commerçants et chefs d''entreprise'  
      3 = 'Cadres et professions intellectuelles supérieures'  
      4 = 'Professions intermédiaires'  
      5 = 'Employés'  
      6 = 'Ouvriers'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value EA19_B1C
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre' ;
   value EA19_B_D
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EA19_B_E
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de réponse'  
      8 = 'Ne sait pas' ;
   value EA19_B2C
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salairé(e) d''un particulier'  
      7 = 'Il(elle) aide un membre de sa famille dans son travail sans'  
      8 = 'Il(elle) est chef d''entreprise salarié, PDG, gérant(e) minor'  
      9 = 'Il(elle) est indépendant(e) ou à son compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EA19_B_G
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,'  
      66 = 'Non concerné' ;
   value EA19_B_H
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire ('  
      6 = 'Non concerné' ;
   value EA19_TYP
      1 = 'Ménages d''une seule personne'  
      2 = 'Familles monoparentales'  
      3 = 'Couples sans enfant'  
      4 = 'Couples avec enfant(s)'  
      5 = 'Ménages complexes de plus d''une personne' ;
   value EA19_C1F
      1 = '1 habitant'  
      2 = '2 habitants'  
      3 = '3 habitants'  
      4 = '4 habitants'  
      5 = '5 habitants'  
      6 = '6 habitants et plus' ;
   value EA19_C1J
      1 = '0 jeune'  
      2 = '1 jeune'  
      3 = '2 jeunes'  
      4 = '3 jeunes ou plus' ;
   value EA19_C8A
      1 = '1 enfant'  
      2 = '2 enfants'  
      3 = '3 enfants ou plus'  
      6 = 'Non concerné' ;
   value EA19_C8B
      1 = '0 enfant'  
      2 = '1 enfant'  
      3 = '2 enfants'  
      4 = '3 enfants ou plus'  
      6 = 'Non concerné' ;
   value EA19_D1F
      1 = 'Propriétaire (ou copropriétaire) : vous ne payez pas de créd'  
      2 = 'Accédant à la propriété : vous payez toujours un crédit immo'  
      3 = '(Locataire, sous-locataire)'  
      5 = 'Occupant à titre gratuit'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value LABG
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EA19_D2F
      1 = 'Votre conjoint(e)'  
      2 = 'Un autre membre du foyer'  
      3 = 'Une autre personne de votre famille'  
      4 = 'Un autre particulier'  
      5 = 'Un organisme HLM (ou assimilé, OPAC, offices, sociétés, fond'  
      6 = 'Une administration, organisme de Sécurité Sociale ou associa'  
      7 = 'Une banque, assurance ou autre société du secteur public ou'  
      8 = 'L''employeur d''un membre du ménage dans le cadre d''un logemen'  
      9 = 'Autre cas'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_D3F
      1 = 'Une maison individuelle'  
      2 = 'Un appartement'  
      3 = 'Autre (précisez)' ;
   value EA19_D4F
      1 = '1 pièce'  
      2 = '2 pièces'  
      3 = '3 pièces'  
      4 = '4 pièces'  
      5 = '5 pièces'  
      6 = '6 pièces'  
      7 = '7 pièces'  
      8 = '8 pièces'  
      9 = '9 pièces et plus' ;
   value EA19_D5F
      1 = 'Moins de 2 ans'  
      2 = 'Entre 2 à 5 ans'  
      3 = 'Entre 5 et 10 ans'  
      4 = 'Entre 10 et 15 ans'  
      5 = 'Il y a plus de 15 ans'  
      9 = 'N''a pas répondu' ;
   value EA19_D6F
      1 = 'Maisons dispersées, hors agglomération'  
      2 = 'Maisons en lotissement, en quartier pavillonnaire ou en vill'  
      3 = 'Immeubles en ville (autre que cité ou grand ensemble)'  
      4 = 'Immeubles en cité ou grand ensemble'  
      5 = 'Habitat mixte : à la fois immeubles et maisons'  
      9 = 'N''a pas répondu' ;
   value LABH
      1 = 'Choisi'  
      2 = 'Non choisi'  
      9 = 'N''a pas répondu' ;
   value LABI
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas' ;
   value EA19_E2A
      1 = 'Moins de 650 €'  
      2 = 'De 650 à moins de 950 €'  
      3 = 'De 950 à moins de 1200 €'  
      4 = 'De 1200 à moins de 1400 €'  
      5 = 'De 1400 à moins de 1650 €'  
      6 = 'De 1650 à moins de 1900 €'  
      7 = 'De 1900 à moins de 2200 €'  
      8 = 'De 2200 à moins de 2500 €'  
      9 = 'De 2500 à moins de 3200 €'  
      10 = '3200 € et plus'  
      99 = 'N''a pas répondu' ;
   value EA19_E_A
      1 = 'À partir du montant déclaré des ressources'  
      2 = 'À partir de la tranche déclarée des ressources'  
      3 = 'Non calculé' ;
   value EA19_E_B
      3 = '(Moins de 800 €)'  
      4 = 'De 800 à moins de 1000 €'  
      5 = 'De 1000 à moins de 1200 €'  
      6 = 'De 1200 à moins de 1500 €'  
      7 = 'De 1500 à moins de 1800 €'  
      8 = 'De 1800 à moins de 2000 €'  
      9 = 'De 2000 à moins de 2500 €'  
      10 = 'De 2500 à moins de 3000 €'  
      11 = 'De 3000 à moins de 4000 €'  
      12 = 'De 4000 à moins de 6000 €'  
      13 = '(6000 € et plus)'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value LABJ
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre' ;
   value LABK
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu' ;
   value LABL
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EA19_E5F
      1 = 'Vous ne pouvez pas y arriver sans faire de dettes'  
      2 = 'Vous y arrivez difficilement'  
      3 = 'C''''est juste, il faut faire attention'  
      4 = 'Ça va'  
      5 = 'Vous êtes plutôt à l''''aise'  
      6 = 'Vous êtes vraiment à l''''aise'  
      99 = 'N''a pas répondu' ;
   value LABM
      1 = 'Au moins une fois par semaine'  
      2 = 'Une à trois fois par mois'  
      3 = 'Plusieurs fois dans l''année (mais moins d''une fois par mois)'  
      4 = 'Seulement pour des occasions exceptionnelles'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_F3F
      1 = 'Il n''y en a pas'  
      2 = '1 ou 2 personnes'  
      3 = 'Entre 3 et 5 personnes'  
      4 = '6 personnes ou plus'  
      8 = 'Ne sait pas' ;
   value EA19_F4F
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_F5F
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n''est jamais assez prudent quand on a affaire aux autres'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value LABN
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_G1F
      1 = 'Moins de 2 heures par jour'  
      2 = 'De 2 à 4 heures par jour'  
      3 = 'Plus de 4 heures par jour'  
      4 = 'Je ne regarde par la télévision'  
      8 = 'Ne sait pas' ;
   value EA19_G2F
      1 = 'Aucun'  
      2 = 'Moins de 6'  
      3 = 'De 6 à moins de 12'  
      4 = 'De 12 à 24 (c''est-à-dire entre 1 et 2 livres par mois)'  
      5 = 'De 25 à 50 (c''est-à-dire plus de 2 livres par mois)'  
      6 = 'Plus de 50 (c''est-à-dire plus de 4 livres par mois)'  
      8 = 'Ne sait pas' ;
   value LABO
      1 = 'Jamais'  
      2 = '1 à 3 fois'  
      3 = '4 à 6 fois'  
      4 = '7 à 12 fois'  
      5 = 'Plus de 12 fois'  
      9 = 'N''a pas répondu' ;
   value EA19_G4F
      1 = 'Régulièrement tout au long de l''année'  
      2 = 'De temps en temps tout au long de l''année'  
      3 = 'Seulement pendant certaines périodes ou pendant les vacances'  
      4 = 'Occasionnellement ou rarement'  
      5 = 'Jamais'  
      8 = 'Ne sait pas' ;
   value EA19_G5A
      1 = 'Allemand'  
      2 = 'Anglais'  
      3 = 'Arabe'  
      4 = 'Espagnol'  
      5 = 'Italien'  
      6 = 'Portugais'  
      7 = '(Langues régionales)'  
      8 = '(Autres langues)'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu' ;
   value EA19_H2F
      1 = 'Pas du tout d''importance'  
      2 = 'Un peu d''importance'  
      3 = 'Assez d''importance'  
      4 = 'Beaucoup d''importance'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_I1F
      1 = 'Beaucoup'  
      2 = 'Assez'  
      3 = 'Peu'  
      4 = 'Pas du tout'  
      8 = 'Ne sait pas' ;
   value EA19_I8F
      0 = 'Gauche'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = 'Droite'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_J1F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_K3F
      1 = 'Tous les jours ou presque'  
      2 = 'Plusieurs fois par semaine'  
      3 = 'Une fois par semaine'  
      4 = 'Une à trois fois par mois'  
      5 = 'Moins souvent'  
      9 = 'N''a pas répondu' ;
   value EA19_H1F
      1 = 'Aucune'  
      2 = 'Catholique'  
      3 = 'Protestante'  
      4 = 'Musulmane'  
      5 = '(Autre religion)'  
      7 = 'Refuse de répondre' ;
   value EA19_H3F
      1 = 'Plusieurs fois par semaine'  
      2 = 'Une fois par semaine'  
      3 = 'Une ou deux fois par mois'  
      4 = 'De temps en temps, aux grandes fêtes'  
      5 = 'Uniquement pour les cérémonies, mariages'  
      6 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_H4A
      1 = 'Catholique'  
      2 = 'Protestante'  
      3 = 'Musulmane'  
      4 = '(Autre religion)'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EA19_H5F
      1 = 'Plusieurs fois par jour'  
      2 = 'Une fois par jour'  
      3 = 'Souvent'  
      4 = 'Rarement'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_I9A
      1 = 'Lutte Ouvrière'  
      2 = 'Le NPA'  
      3 = 'Le Parti Communiste'  
      4 = 'La France Insoumise'  
      5 = 'Le Parti de Gauche'  
      6 = 'Le Parti Socialiste'  
      7 = 'Le Parti Radical de Gauche'  
      8 = 'Europe Écologie/Les Verts'  
      9 = 'La République en marche !'  
      10 = 'Le MoDem'  
      11 = 'L''UDI'  
      12 = 'Les Républicains'  
      13 = 'Debout la France'  
      14 = 'Le Front National'  
      15 = 'Un autre parti'  
      16 = 'Aucun parti'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_J3F
      1 = 'Oui, fortement limité(e)'  
      2 = 'Oui, limité(e), mais pas fortement'  
      3 = 'Non, pas limité(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value LABP
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais'  
      9 = 'N''a pas répondu' ;
   value LABQ
      1 = 'Oui'  
      2 = 'Non'  
      8 = 'Ne sait pas' ;
   value EA19_K1F
      1 = 'Moins de 155 cm'  
      2 = 'Entre 155 et 159 cm'  
      3 = 'Entre 160 et 164 cm'  
      4 = 'Entre 165 et 169 cm'  
      5 = 'Entre 170 et 174 cm'  
      6 = 'Entre 175 et 179 cm'  
      7 = 'Entre 180 et 184 cm'  
      8 = '185 cm et plus'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_K2F
      1 = 'Moins de 55 kg'  
      2 = 'Entre 55 et 59 kg'  
      3 = 'Entre 60 et 64 kg'  
      4 = 'Entre 65 et 69 kg'  
      5 = 'Entre 70 et 74 kg'  
      6 = 'Entre 75 et 79 kg'  
      7 = 'Entre 80 et 84 kg'  
      8 = 'Entre 85 et et 94 kg'  
      9 = '95 kg et plus'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_K4F
      1 = 'Tous les jours'  
      2 = 'Quatre fois par semaine ou plus'  
      3 = 'Deux ou trois fois par semaine'  
      4 = 'Une fois par semaine'  
      5 = 'Deux à quatre fois par mois'  
      6 = 'Une fois par mois ou moins souvent'  
      7 = 'Jamais'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EA19_K5A
      1 = '1 ou 2 verres'  
      2 = '3 ou 4 verres'  
      3 = '5 ou 6 verres'  
      4 = '7 à 9 verres'  
      5 = '10 verres ou plus'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EA19_K5B
      1 = 'Jamais'  
      2 = 'Moins d''''une fois par mois'  
      3 = 'Une fois par mois'  
      4 = 'Une fois par semaine'  
      5 = 'Tous les jours ou presque'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value LABR
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EA19_K6B
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EA19_PAN
      1 = 'Issu du panel recruté en 2012'  
      2 = 'Issu du panel recruté en 2016' ;
   value CAL_SEXE
      1 = 'Homme'  
      2 = 'Femme' ;
   value CAL_AGE1F
      1 = '18-24 ans'  
      2 = '25-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-79 ans' ;
   value CAL_AGE2F
      1 = '18-22 ans'  
      2 = '23-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-75 ans'  
      7 = '76-79 ans' ;
   value CAL_DIPL
      1 = 'Aucun/CEP/BEPC'  
      2 = 'CAP/BEP'  
      3 = 'Bac/Bac+2'  
      4 = 'Bac+3 et plus' ;
   value CAL_ZEAT
      1 = 'Région parisienne'  
      2 = 'Bassin parisien'  
      3 = 'Nord'  
      4 = 'Est'  
      5 = 'Ouest'  
      6 = 'Sud-ouest'  
      7 = 'Centre-est'  
      8 = 'Méditerranée' ;
   value INSEE_NU
      1 = 'FR1 : Région parisienne'  
      2 = 'FR2 : Bassin parisien'  
      3 = 'FR3 : Nord'  
      4 = 'FR4 : Est'  
      5 = 'FR5 : Ouest'  
      6 = 'FR6 : Sud-ouest'  
      7 = 'FR7 : Centre-est'  
      8 = 'FR8 : Méditerranée'  
      9 = 'FRA : Départements d''Outre-Mer' ;
   value INSEE_CA
      111 = 'Commune appartenant à un grand pôle (10 000 emplois ou plus)'  
      112 = 'Commune appartenant à la couronne d''un grand pôle'  
      120 = 'Commune multipolarisée des grandes aires urbaines'  
      211 = 'Commune appartenant à un moyen pôle (5 000 à moins de 10 000'  
      212 = 'Commune appartenant à la couronne d''un moyen pôle'  
      221 = 'Commune appartenant à un petit pôle (de 1 500 à moins de 5 0'  
      222 = 'Commune appartenant à la couronne d''un petit pôle'  
      300 = 'Autre commune multipolarisée'  
      400 = 'Commune isolée hors influence des pôles' ;
   value INSEE_TA
      0 = 'Commune hors aire urbaine'  
      1 = 'Commune appartenant à une aire urbaine de moins de 15 000 ha'  
      2 = 'Commune appartenant à une aire urbaine de 15 000 à 19 999 ha'  
      3 = 'Commune appartenant à une aire urbaine de 20 000 à 24 999 ha'  
      4 = 'Commune appartenant à une aire urbaine de 25 000 à 34 999 ha'  
      5 = 'Commune appartenant à une aire urbaine de 35 000 à 49 999 ha'  
      6 = 'Commune appartenant à une aire urbaine de 50 000 à 99 999 ha'  
      7 = 'Commune appartenant à une aire urbaine de 100 000 à 199 999'  
      8 = 'Commune appartenant à une aire urbaine de 200 000 à 499 999'  
      9 = 'Commune appartenant à une aire urbaine de 500 000 à 9 999 99'  
      10 = 'Commune appartenant à l''aire urbaine de Paris' ;
   value INSEE_TU
      0 = 'Commune rurale'  
      1 = 'Commune appartenant à une unité urbaine de 2 000 à 4 999 hab'  
      2 = 'Commune appartenant à une unité urbaine de 5 000 à 9 999 hab'  
      3 = 'Commune appartenant à une unité urbaine de 10 000 à 19 999 h'  
      4 = 'Commune appartenant à une unité urbaine de 20 000 à 49 999 h'  
      5 = 'Commune appartenant à une unité urbaine de 50 000 à 99 999 h'  
      6 = 'Commune appartenant à une unité urbaine de 100 000 à 199 999'  
      7 = 'Commune appartenant à une unité urbaine de 200 000 à 1 999 9'  
      8 = 'Commune appartenant à l''unité urbaine de Paris' ;

DATA library.&dataset ;
INFILE datafile LRECL=244;
INPUT
   UID_ea  1-4              ea19_A1  5               ea19_A2A_rec  6-7     
   ea19_A3_rec  8           ea19_A3B_rec  9          ea19_A3C_rec  10      
   ea19_A3D  11             ea19_A3E_rec  12         ea19_A4  13-14        
   ea19_A5  15              ea19_A5A  16             ea19_A5C  17          
   ea19_A5C_rec  18-19      ea19_B1  20-21           ea19_B1A  22          
   ea19_B1B  23             ea19_B5A  24             ea19_B5C  25-26       
   ea19_B25  27             ea19_B10A  28            ea19_B10AA  29        
   ea19_B11  30             ea19_B18C  31            ea19_B18_rec  32-33   
   ea19_B2_rec  34-35       ea19_B4_rec  36          ea19_B5_rec  37       
   ea19_B5B_rec  38         ea19_B6A_rec  39-40      ea19_B6B_rec  41-42   
   ea19_B7B_rec  43-44      ea19_B8_rec  45          ea19_B9_rec  46       
   ea19_PCS18  47-49        ea19_PCS6  50-52         ea19_B1CJT  53-54     
   ea19_B1ACJT  55          ea19_B1BCJT  56          ea19_B10ACJT  57      
   ea19_B2CJT_rec  58-59    ea19_B4CJT_rec  60       ea19_B11CJT  61       
   ea19_B18CJT_rec  62-63   ea19_B18CCJT  64         ea19_PCS6CJT  65-67   
   ea19_TYPMEN5  68         ea19_C1_rec  69          ea19_C1JEU  70        
   ea19_C8  71              ea19_C8A_rec  72         ea19_C8B_rec  73      
   ea19_D1_rec  74          ea19_D1A  75             ea19_D2  76-77        
   ea19_D3  78              ea19_D4_rec  79          ea19_D5_rec  80       
   ea19_D6  81              ea19_D7_1  82            ea19_D7_2  83         
   ea19_D7_3  84            ea19_D7_4  85            ea19_D7_5  86         
   ea19_D7_6  87            ea19_D7_7  88            ea19_D7_8  89         
   ea19_D7_9  90            ea19_D7_10  91           ea19_E1A  92          
   ea19_E1B  93             ea19_E1C  94             ea19_E1D  95          
   ea19_E1E  96             ea19_E1F  97             ea19_E1G  98          
   ea19_E1H  99             ea19_E1I  100            ea19_E1J  101         
   ea19_E2AUC  102-103      ea19_E2AUC_SOURCE  104   ea19_E2A_rec  105-106 
   ea19_E3A  107            ea19_E3B  108            ea19_E3C  109         
   ea19_E3D  110            ea19_E3E  111            ea19_E4  112          
   ea19_E5A  113            ea19_E5B_1  114          ea19_E5B_2  115       
   ea19_E5B_3  116          ea19_E5B_4  117          ea19_E5B_5  118       
   ea19_E5B_6  119          ea19_E5B_7  120          ea19_E5B_8  121       
   ea19_E5B_9  122          ea19_E5  123-124         ea19_F1_rec  125      
   ea19_F3  126             ea19_F4  127             ea19_F5  128          
   ea19_F6_rec  129         ea19_F7  130             ea19_F8  131          
   ea19_G1  132             ea19_G2  133             ea19_G3A  134         
   ea19_G3B  135            ea19_G3C  136            ea19_G4  137          
   ea19_G5A_rec  138-139    ea19_G6_1  140           ea19_G6_2  141        
   ea19_G6_3  142           ea19_G6_4  143           ea19_G5  144          
   ea19_H2  145             ea19_H4  146             ea19_I1  147          
   ea19_I8  148-149         ea19_J1  150             ea19_K3  151          
   ea19_H1_rec  152         ea19_H1A  153            ea19_H3  154          
   ea19_H4A_rec  155        ea19_H5  156             ea19_I9A  157-158     
   ea19_J2  159             ea19_J3  160             ea19_J7A  161         
   ea19_J7B  162            ea19_J7C  163            ea19_J7D  164         
   ea19_J7E  165            ea19_J11  166            ea19_J9  167          
   ea19_J10  168            ea19_J12  169            ea19_J13_rec  170     
   ea19_K1_rec  171-172     ea19_K2_rec  173-174     ea19_K4  175-176      
   ea19_K5A  177            ea19_K5B  178            ea19_K6  179          
   ea19_K6A_1  180          ea19_K6A_2  181          ea19_K6A_3  182       
   ea19_K6A_4  183          ea19_K6A_5  184          ea19_K6A_6  185       
   ea19_K6A_7  186          ea19_K6B  187            ea19_PANEL  188       
   POIDS_INIT  189-199      PDSPLT_INIT  200-210     cal_SEXE  211         
   cal_AGE1  212            cal_AGE2  213            cal_DIPL  214         
   cal_ZEAT  215            POIDS_ea19  216-226      PDSPLT_ea19  227-237  
   insee_NUTS1  238         insee_CATAEU2010  239-241   insee_TAU2014  242-243
   insee_TUU2014  244     ;                       

LABEL
   UID_ea = "Identifiant interviewé"
   ea19_A1 = "Sexe (enquête annuelle)"
   ea19_A2A_rec = "Age quinquennal (recodage)"
   ea19_A3_rec = "A la nationalité francaise (recodage)"
   ea19_A3B_rec = "Pays de naissance (recodage)"
   ea19_A3C_rec = "Nationalité (recodage)"
   ea19_A3D = "A une seconde nationalité"
   ea19_A3E_rec = "Seconde nationalité (recodage)"
   ea19_A4 = "Statut matrimonial légal"
   ea19_A5 = "Vit en couple"
   ea19_A5A = "Situation familiale"
   ea19_A5C = "Ancienneté du couple"
   ea19_A5C_rec = "Ancienneté du couple (recodage)"
   ea19_B1 = "Situation principale vis-à-vis du travail"
   ea19_B1A = "Emploi (étudiant, chômeur, retraité, autre inactif)"
   ea19_B1B = "Exercice d'une activité professionnelle (recodage)"
   ea19_B5A = "Temps de travail"
   ea19_B5C = "Raison principale du travail à temps partiel"
   ea19_B25 = "Supervision d'autres salariés"
   ea19_B10A = "Recherche d'emploi"
   ea19_B10AA = "Rercherche un autre emploi"
   ea19_B11 = "Ne travaille pas mais a déjà travaillé"
   ea19_B18C = "Niveau de formation (recodage)"
   ea19_B18_rec = "Diplôme le plus élevé (recodage)"
   ea19_B2_rec = "Statut de l'activité actuelle ou antérieure (recodage)"
   ea19_B4_rec = "Nombre de salariés employés actuellement ou par le passé (recodage)"
   ea19_B5_rec = "Type de contrat de travail (recodage)"
   ea19_B5B_rec = "Type de temps partiel (recodage)"
   ea19_B6A_rec = "Catégorie de l'emploi actuel ou antérieur secteur privé (recodage)"
   ea19_B6B_rec = "Catégorie de l'emploi actuel ou antérieur secteur public (recodage)"
   ea19_B7B_rec = "Fonction principale de l'emploi actuel ou antérieur (recodage)"
   ea19_B8_rec = "Nombre de salariés dans l'entreprise de l'emploi actuel ou antérieur (recodage)"
   ea19_B9_rec = "Superficie de l'exploitation actuelle ou antérieure (recodage)"
   ea19_PCS18 = "Catégorie socioprofessionnelle en 18 postes (profession actuelle ou dernière profession)"
   ea19_PCS6 = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession)"
   ea19_B1CJT = "Situation principale vis-à-vis du travail (conjoint)"
   ea19_B1ACJT = "Emploi (étudiant, chômeur, retraité, autre inactif) (conjoint)"
   ea19_B1BCJT = "Exercice d'une activité professionnelle (conjoint) (calcul)"
   ea19_B10ACJT = "Recherche d'emploi (conjoint)"
   ea19_B2CJT_rec = "Statut de l'activité actuelle ou antérieure (conjoint) (calcul)"
   ea19_B4CJT_rec = "Nombre de salariés employés actuellement ou par le passé (conjoint) (calcul)"
   ea19_B11CJT = "Ne travaille pas mais a déjà travaillé (conjoint)"
   ea19_B18CJT_rec = "Diplôme le plus élevé (conjoint) (recodage)"
   ea19_B18CCJT = "Niveau de formation (conjoint) (calcul)"
   ea19_PCS6CJT = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession) (conjoint)"
   ea19_TYPMEN5 = "Type de ménage (calcul)"
   ea19_C1_rec = "Nombre de personnes dans le foyer (recodage)"
   ea19_C1JEU = "Nombre de jeunes (calcul)"
   ea19_C8 = "A des enfants"
   ea19_C8A_rec = "Nombre d'enfants (recodage)"
   ea19_C8B_rec = "Nombre d'enfants cohabitants (recodage)"
   ea19_D1_rec = "Statut d'occupation du logement (recodage)"
   ea19_D1A = "Appartenance du logement à un organisme HLM"
   ea19_D2 = "Propriétaire du logement"
   ea19_D3 = "Type d'habitation"
   ea19_D4_rec = "Nombre pièces d'habitation du logement (recodage)"
   ea19_D5_rec = "Année d'emménagement dans le logement (calcul)"
   ea19_D6 = "Type d'habitat au voisinage du logement"
   ea19_D7_1 = "Problèmes concernant le quartier : terrains-vagues, locaux désaffectés, friches industrielles, logements insalubres"
   ea19_D7_2 = "Problèmes concernant le quartier : bruits ou pollution"
   ea19_D7_3 = "Problèmes concernant le quartier : voirie insuffisante"
   ea19_D7_4 = "Problèmes concernant le quartier : saleté"
   ea19_D7_5 = "Problèmes concernant le quartier : manque d'espaces verts"
   ea19_D7_6 = "Problèmes concernant le quartier : manque de commerces"
   ea19_D7_7 = "Problèmes concernant le quartier : manque de lieux de rencontre, d'équipements"
   ea19_D7_8 = "Problèmes concernant le quartier : isolement du quartier"
   ea19_D7_9 = "Problèmes concernant le quartier : manque de sécurité"
   ea19_D7_10 = "Problèmes concernant le quartier : aucun de ces problèmes"
   ea19_E1A = "Personnes dans le ménage percevant : salaires, traitements et primes"
   ea19_E1B = "Personnes dans le ménage percevant : revenus d'une activité professionnelle non salariée"
   ea19_E1C = "Personnes dans le ménage percevant : allocations de chômage"
   ea19_E1D = "Personnes dans le ménage percevant : préretraites, retraites"
   ea19_E1E = "Personnes dans le ménage percevant : prestations liées à la maladie ou l'invalidité"
   ea19_E1F = "Personnes dans le ménage percevant : prestations familiales et bourses"
   ea19_E1G = "Personnes dans le ménage percevant : allocation logement, aide au logement"
   ea19_E1H = "Personnes dans le ménage percevant : RSA"
   ea19_E1I = "Personnes dans le ménage percevant : loyers et fermages"
   ea19_E1J = "Personnes dans le ménage percevant : pensions, aides"
   ea19_E2AUC = "Tranche de revenu mensuel du ménage par unité de consommation (calcul)"
   ea19_E2AUC_SOURCE = "Source d'information du montant des ressources par unité de consommation"
   ea19_E2A_rec = "Tranche de montant des ressources (calcul)"
   ea19_E3A = "Détention placements financiers : livrets d'épargne"
   ea19_E3B = "Détention placements financiers : épargne-logement"
   ea19_E3C = "Détention placements financiers : assurances-vies"
   ea19_E3D = "Détention placements financiers : épargne retraite"
   ea19_E3E = "Détention placements financiers : valeurs immobilières"
   ea19_E4 = "Résidence secondaire"
   ea19_E5A = "Baisse de revenu importante les 12 derniers mois"
   ea19_E5B_1 = "Baisse de revenu importante les 12 derniers mois : licenciement/perte d'emploi"
   ea19_E5B_2 = "Baisse de revenu importante les 12 derniers mois : modification du salaire/heures"
   ea19_E5B_3 = "Baisse de revenu importante les 12 derniers mois : invalidité/incapacité"
   ea19_E5B_4 = "Baisse de revenu importante les 12 derniers mois : maternité/congé parental/garde des enfants"
   ea19_E5B_5 = "Baisse de revenu importante les 12 derniers mois : départ à la retraite"
   ea19_E5B_6 = "Baisse de revenu importante les 12 derniers mois : mariage/rupture"
   ea19_E5B_7 = "Baisse de revenu importante les 12 derniers mois : décès"
   ea19_E5B_8 = "Baisse de revenu importante les 12 derniers mois : autre changement dans le ménage"
   ea19_E5B_9 = "Baisse de revenu importante les 12 derniers mois: autre raison"
   ea19_E5 = "Situation financière actuelle du mènage"
   ea19_F1_rec = "Fréquence de rencontre des amis (recodage)"
   ea19_F3 = "A quelqu'un pour discuter de questions intimes et personnelles"
   ea19_F4 = "Sentiment de solitude"
   ea19_F5 = "Opinion confiance ou prudence en général"
   ea19_F6_rec = "Fréquence de rencontre de la famille (recodage)"
   ea19_F7 = "Membre association humanitaire ou sociale"
   ea19_F8 = "Membre amicale ou association sportive ou culturelle"
   ea19_G1 = "Télévision les 12 derniers mois"
   ea19_G2 = "Nombre de livres lus les 12 derniers mois"
   ea19_G3A = "Sortie culturelle les 12 derniers mois : au cinéma"
   ea19_G3B = "Sortie culturelle les 12 derniers mois : au théâtre ou au concert"
   ea19_G3C = "Sortie culturelle les 12 derniers mois : au musée ou une exposition"
   ea19_G4 = "Bricolage les 12 derniers mois"
   ea19_G5A_rec = "Langue étrangère maitrisée (recodage)"
   ea19_G6_1 = "Partir en vacances les 12 derniers mois : non"
   ea19_G6_2 = "Partir en vacances les 12 derniers mois : dans la région"
   ea19_G6_3 = "Partir en vacances les 12 derniers mois : dans une autre région"
   ea19_G6_4 = "Partir en vacances les 12 derniers mois : à l'étranger"
   ea19_G5 = "Maîtrise d'une langue étrangère"
   ea19_H2 = "Importance de la religion"
   ea19_H4 = "Éducation religieuse"
   ea19_I1 = "Intérêt pour la politique"
   ea19_I8 = "Auto-positionnement sur l'échelle gauche/droite"
   ea19_J1 = "État de santé"
   ea19_K3 = "Fréquence activité sportive 30 minutes d'affilée"
   ea19_H1_rec = "Religion (recodage)"
   ea19_H1A = "A une religion (recodage)"
   ea19_H3 = "Fréquence de l'assistance à un office religieux"
   ea19_H4A_rec = "Éducation religieuse : religion (recodage)"
   ea19_H5 = "Fréquence de la prière"
   ea19_I9A = "Proximité partisane précise"
   ea19_J2 = "Existence d'une maladie chronique"
   ea19_J3 = "Limité depuis au moins 6 mois à cause d'un problème de santé"
   ea19_J7A = "Les 4 dernières semaines, s'est senti : nerveux"
   ea19_J7B = "Les 4 dernières semaines, s'est senti : découragé"
   ea19_J7C = "Les 4 dernières semaines, s'est senti : calme et détendu"
   ea19_J7D = "Les 4 dernières semaines, s'est senti : triste et abattu"
   ea19_J7E = "Les 4 dernières semaines, s'est senti : heureux"
   ea19_J11 = "Bénéficaire de la Couverture médicale universelle complémentaire"
   ea19_J9 = "A une complémentaire santé"
   ea19_J10 = "A renoncé à certains soins pour des raisons financières les 12 derniers mois"
   ea19_J12 = "Prise en charge à 100% Sécurité sociale : une ALD"
   ea19_J13_rec = "Prise en charge à 100% Sécurité sociale : autre motif (recodage)"
   ea19_K1_rec = "Taille de l'interviewé (recodage)"
   ea19_K2_rec = "Poids de l'interviewé (recodage)"
   ea19_K4 = "Consommation d'alcool au cours des douze derniers mois"
   ea19_K5A = "Quantité d'alcool bu les jours de consommation"
   ea19_K5B = "Fréquence de consommation d'au moins 6 verres standards"
   ea19_K6 = "Fumeur"
   ea19_K6A_1 = "Fume : du tabac à rouler"
   ea19_K6A_2 = "Fume : des cigarettes"
   ea19_K6A_3 = "Fume : des cigarillos"
   ea19_K6A_4 = "Fume : des cigares"
   ea19_K6A_5 = "Fume : la pipe"
   ea19_K6A_6 = "Fume : la chicha ou le narguilé"
   ea19_K6A_7 = "Fume : la cigarette électronique"
   ea19_K6B = "Fumeur quotidien"
   ea19_PANEL = "Appartenance panel"
   POIDS_INIT = "Poids initial"
   PDSPLT_INIT = "Poids initial (panel pilote)"
   cal_SEXE = "Sexe panéliste (calage)"
   cal_AGE1 = "Age décennal (calage panel pilote)"
   cal_AGE2 = "Age décennal (calage)"
   cal_DIPL = "Diplôme (calage)"
   cal_ZEAT = "Zone d'études et d'aménagement du territoire (ZEAT)"
   POIDS_ea19 = "Poids individu"
   PDSPLT_ea19 = "Poids individu (panel pilote)"
   insee_NUTS1 = "Nomenclature des unités territoriales statistiques niv. 1"
   insee_CATAEU2010 = "Catégorie de la commune dans le zonage en aires urbaines 2010"
   insee_TAU2014 = "Tranche d'aire urbaine 2014"
   insee_TUU2014 = "Tranche d'unité urbaine 2014" ;

 /* User Missing Value Specifications */
  IF ea19_A3_rec >= 7 THEN ea19_A3_rec =. ;
  IF ea19_A3B_rec >= 9 THEN ea19_A3B_rec =. ;
  IF ea19_A3C_rec >= 6 THEN ea19_A3C_rec =. ;
  IF ea19_A3D >= 6 THEN ea19_A3D =. ;
  IF ea19_A3E_rec >= 6 THEN ea19_A3E_rec =. ;
  IF ea19_A4 >= 77 THEN ea19_A4 =. ;
  IF ea19_A5 >= 7 THEN ea19_A5 =. ;
  IF ea19_A5A >= 6 THEN ea19_A5A =. ;
  IF ea19_A5C >= 6 THEN ea19_A5C =. ;
  IF ea19_A5C_rec >= 66 THEN ea19_A5C_rec =. ;
  IF ea19_B1 >= 77 THEN ea19_B1 =. ;
  IF ea19_B1A >= 6 THEN ea19_B1A =. ;
  IF ea19_B1B >= 7 THEN ea19_B1B =. ;
  IF ea19_B5A >= 6 THEN ea19_B5A =. ;
  IF ea19_B5C >= 66 THEN ea19_B5C =. ;
  IF ea19_B25 >= 6 THEN ea19_B25 =. ;
  IF ea19_B10A >= 6 THEN ea19_B10A =. ;
  IF ea19_B10AA >= 6 THEN ea19_B10AA =. ;
  IF ea19_B11 >= 6 THEN ea19_B11 =. ;
  IF ea19_B18C >= 7 THEN ea19_B18C =. ;
  IF ea19_B18_rec >= 77 THEN ea19_B18_rec =. ;
  IF ea19_B2_rec >= 66 THEN ea19_B2_rec =. ;
  IF ea19_B4_rec >= 6 THEN ea19_B4_rec =. ;
  IF ea19_B5_rec >= 6 THEN ea19_B5_rec =. ;
  IF ea19_B5B_rec >= 6 THEN ea19_B5B_rec =. ;
  IF ea19_B6A_rec >= 66 THEN ea19_B6A_rec =. ;
  IF ea19_B6B_rec >= 66 THEN ea19_B6B_rec =. ;
  IF ea19_B7B_rec >= 66 THEN ea19_B7B_rec =. ;
  IF ea19_B8_rec >= 6 THEN ea19_B8_rec =. ;
  IF ea19_B9_rec >= 6 THEN ea19_B9_rec =. ;
  IF ea19_PCS18 >= 666 THEN ea19_PCS18 =. ;
  IF ea19_PCS6 >= 66 THEN ea19_PCS6 =. ;
  IF ea19_B1CJT >= 66 THEN ea19_B1CJT =. ;
  IF ea19_B1ACJT >= 6 THEN ea19_B1ACJT =. ;
  IF ea19_B1BCJT >= 6 THEN ea19_B1BCJT =. ;
  IF ea19_B10ACJT >= 6 THEN ea19_B10ACJT =. ;
  IF ea19_B2CJT_rec >= 66 THEN ea19_B2CJT_rec =. ;
  IF ea19_B4CJT_rec >= 6 THEN ea19_B4CJT_rec =. ;
  IF ea19_B11CJT >= 6 THEN ea19_B11CJT =. ;
  IF ea19_B18CJT_rec >= 66 THEN ea19_B18CJT_rec =. ;
  IF ea19_B18CCJT >= 6 THEN ea19_B18CCJT =. ;
  IF ea19_PCS6CJT >= 66 THEN ea19_PCS6CJT =. ;
  IF ea19_TYPMEN5 >= 6 THEN ea19_TYPMEN5 =. ;
  IF ea19_C1JEU >= 9 THEN ea19_C1JEU =. ;
  IF ea19_C8 >= 7 THEN ea19_C8 =. ;
  IF ea19_C8A_rec >= 6 THEN ea19_C8A_rec =. ;
  IF ea19_C8B_rec >= 6 THEN ea19_C8B_rec =. ;
  IF ea19_D1_rec >= 7 THEN ea19_D1_rec =. ;
  IF ea19_D1A >= 6 THEN ea19_D1A =. ;
  IF ea19_D2 >= 66 THEN ea19_D2 =. ;
  IF ea19_D4_rec >= 99 THEN ea19_D4_rec =. ;
  IF ea19_D5_rec >= 9 THEN ea19_D5_rec =. ;
  IF ea19_D6 >= 9 THEN ea19_D6 =. ;
  IF ea19_D7_1 >= 9 THEN ea19_D7_1 =. ;
  IF ea19_D7_2 >= 9 THEN ea19_D7_2 =. ;
  IF ea19_D7_3 >= 9 THEN ea19_D7_3 =. ;
  IF ea19_D7_4 >= 9 THEN ea19_D7_4 =. ;
  IF ea19_D7_5 >= 9 THEN ea19_D7_5 =. ;
  IF ea19_D7_6 >= 9 THEN ea19_D7_6 =. ;
  IF ea19_D7_7 >= 9 THEN ea19_D7_7 =. ;
  IF ea19_D7_8 >= 9 THEN ea19_D7_8 =. ;
  IF ea19_D7_9 >= 9 THEN ea19_D7_9 =. ;
  IF ea19_D7_10 >= 9 THEN ea19_D7_10 =. ;
  IF ea19_E2AUC >= 66 THEN ea19_E2AUC =. ;
  IF ea19_E2A_rec >= 77 THEN ea19_E2A_rec =. ;
  IF ea19_E4 >= 7 THEN ea19_E4 =. ;
  IF ea19_E5A >= 9 THEN ea19_E5A =. ;
  IF ea19_E5B_1 >= 6 THEN ea19_E5B_1 =. ;
  IF ea19_E5B_2 >= 6 THEN ea19_E5B_2 =. ;
  IF ea19_E5B_3 >= 6 THEN ea19_E5B_3 =. ;
  IF ea19_E5B_4 >= 6 THEN ea19_E5B_4 =. ;
  IF ea19_E5B_5 >= 6 THEN ea19_E5B_5 =. ;
  IF ea19_E5B_6 >= 6 THEN ea19_E5B_6 =. ;
  IF ea19_E5B_7 >= 6 THEN ea19_E5B_7 =. ;
  IF ea19_E5B_8 >= 6 THEN ea19_E5B_8 =. ;
  IF ea19_E5B_9 >= 6 THEN ea19_E5B_9 =. ;
  IF ea19_E5 >= 99 THEN ea19_E5 =. ;
  IF ea19_F1_rec >= 7 THEN ea19_F1_rec =. ;
  IF ea19_F3 >= 8 THEN ea19_F3 =. ;
  IF ea19_F4 >= 7 THEN ea19_F4 =. ;
  IF ea19_F5 >= 7 THEN ea19_F5 =. ;
  IF ea19_F6_rec >= 7 THEN ea19_F6_rec =. ;
  IF ea19_F7 >= 7 THEN ea19_F7 =. ;
  IF ea19_F8 >= 7 THEN ea19_F8 =. ;
  IF ea19_G1 >= 8 THEN ea19_G1 =. ;
  IF ea19_G2 >= 8 THEN ea19_G2 =. ;
  IF ea19_G3A >= 9 THEN ea19_G3A =. ;
  IF ea19_G3B >= 9 THEN ea19_G3B =. ;
  IF ea19_G3C >= 9 THEN ea19_G3C =. ;
  IF ea19_G4 >= 8 THEN ea19_G4 =. ;
  IF ea19_G5A_rec >= 66 THEN ea19_G5A_rec =. ;
  IF ea19_G6_1 >= 9 THEN ea19_G6_1 =. ;
  IF ea19_G6_2 >= 9 THEN ea19_G6_2 =. ;
  IF ea19_G6_3 >= 9 THEN ea19_G6_3 =. ;
  IF ea19_G6_4 >= 9 THEN ea19_G6_4 =. ;
  IF ea19_G5 >= 9 THEN ea19_G5 =. ;
  IF ea19_H2 >= 7 THEN ea19_H2 =. ;
  IF ea19_H4 >= 7 THEN ea19_H4 =. ;
  IF ea19_I1 >= 8 THEN ea19_I1 =. ;
  IF ea19_I8 >= 77 THEN ea19_I8 =. ;
  IF ea19_J1 >= 7 THEN ea19_J1 =. ;
  IF ea19_K3 >= 9 THEN ea19_K3 =. ;
  IF ea19_H1_rec >= 7 THEN ea19_H1_rec =. ;
  IF ea19_H1A >= 7 THEN ea19_H1A =. ;
  IF ea19_H3 >= 7 THEN ea19_H3 =. ;
  IF ea19_H4A_rec >= 6 THEN ea19_H4A_rec =. ;
  IF ea19_H5 >= 7 THEN ea19_H5 =. ;
  IF ea19_I9A >= 77 THEN ea19_I9A =. ;
  IF ea19_J2 >= 7 THEN ea19_J2 =. ;
  IF ea19_J3 >= 7 THEN ea19_J3 =. ;
  IF ea19_J7A >= 9 THEN ea19_J7A =. ;
  IF ea19_J7B >= 9 THEN ea19_J7B =. ;
  IF ea19_J7C >= 9 THEN ea19_J7C =. ;
  IF ea19_J7D >= 9 THEN ea19_J7D =. ;
  IF ea19_J7E >= 9 THEN ea19_J7E =. ;
  IF ea19_J11 >= 8 THEN ea19_J11 =. ;
  IF ea19_J9 >= 6 THEN ea19_J9 =. ;
  IF ea19_J10 >= 7 THEN ea19_J10 =. ;
  IF ea19_J12 >= 7 THEN ea19_J12 =. ;
  IF ea19_J13_rec >= 8 THEN ea19_J13_rec =. ;
  IF ea19_K1_rec >= 77 THEN ea19_K1_rec =. ;
  IF ea19_K2_rec >= 77 THEN ea19_K2_rec =. ;
  IF ea19_K4 >= 77 THEN ea19_K4 =. ;
  IF ea19_K5A >= 6 THEN ea19_K5A =. ;
  IF ea19_K5B >= 6 THEN ea19_K5B =. ;
  IF ea19_K6 >= 7 THEN ea19_K6 =. ;
  IF ea19_K6A_1 >= 6 THEN ea19_K6A_1 =. ;
  IF ea19_K6A_2 >= 6 THEN ea19_K6A_2 =. ;
  IF ea19_K6A_3 >= 6 THEN ea19_K6A_3 =. ;
  IF ea19_K6A_4 >= 6 THEN ea19_K6A_4 =. ;
  IF ea19_K6A_5 >= 6 THEN ea19_K6A_5 =. ;
  IF ea19_K6A_6 >= 6 THEN ea19_K6A_6 =. ;
  IF ea19_K6A_7 >= 6 THEN ea19_K6A_7 =. ;
  IF ea19_K6B >= 6 THEN ea19_K6B =. ;
  IF cal_AGE1 >= 9 THEN cal_AGE1 =. ;
  IF cal_AGE2 >= 9 THEN cal_AGE2 =. ;
  IF cal_DIPL >= 9 THEN cal_DIPL =. ;
  IF cal_ZEAT >= 9 THEN cal_ZEAT =. ;
  IF insee_NUTS1 >= 99 THEN insee_NUTS1 =. ;
  IF insee_CATAEU2010 >= 999 THEN insee_CATAEU2010 =. ;
  IF insee_TAU2014 >= 99 THEN insee_TAU2014 =. ;
  IF insee_TUU2014 >= 9 THEN insee_TUU2014 =. ;

FORMAT
   ea19_A1 EA19_A1F.        ea19_A2A_rec EA19_A2A.   ea19_A3_rec EA19_A3F. 
   ea19_A3B_rec EA19_A3B.   ea19_A3C_rec LABA.       ea19_A3D LABB.        
   ea19_A3E_rec LABA.       ea19_A4 EA19_A4F.        ea19_A5 EA19_A5F.     
   ea19_A5A EA19_A5A.       ea19_A5C EA19_A5C.       ea19_A5C_rec EA19_A_A.
   ea19_B1 EA19_B1F.        ea19_B1A LABC.           ea19_B1B EA19_B1B.    
   ea19_B5A EA19_B5A.       ea19_B5C EA19_B5C.       ea19_B25 EA19_B25F.   
   ea19_B10A LABD.          ea19_B10AA LABD.         ea19_B11 LABC.        
   ea19_B18C EA19_B18F.     ea19_B18_rec EA19_B_B.   ea19_B2_rec EA19_B2F. 
   ea19_B4_rec LABE.        ea19_B5_rec EA19_B5F.    ea19_B5B_rec EA19_B5B.
   ea19_B6A_rec EA19_B6A.   ea19_B6B_rec EA19_B6B.   ea19_B7B_rec EA19_B7B.
   ea19_B8_rec EA19_B8F.    ea19_B9_rec EA19_B9F.    ea19_PCS18 EA19_PCS.  
   ea19_PCS6 LABF.          ea19_B1CJT EA19_B1C.     ea19_B1ACJT LABC.     
   ea19_B1BCJT EA19_B_D.    ea19_B10ACJT EA19_B_E.   ea19_B2CJT_rec EA19_B2C.
   ea19_B4CJT_rec LABE.     ea19_B11CJT LABC.        ea19_B18CJT_rec EA19_B_G.
   ea19_B18CCJT EA19_B_H.   ea19_PCS6CJT LABF.       ea19_TYPMEN5 EA19_TYP.
   ea19_C1_rec EA19_C1F.    ea19_C1JEU EA19_C1J.     ea19_C8 LABB.         
   ea19_C8A_rec EA19_C8A.   ea19_C8B_rec EA19_C8B.   ea19_D1_rec EA19_D1F. 
   ea19_D1A LABG.           ea19_D2 EA19_D2F.        ea19_D3 EA19_D3F.     
   ea19_D4_rec EA19_D4F.    ea19_D5_rec EA19_D5F.    ea19_D6 EA19_D6F.     
   ea19_D7_1 LABH.          ea19_D7_2 LABH.          ea19_D7_3 LABH.       
   ea19_D7_4 LABH.          ea19_D7_5 LABH.          ea19_D7_6 LABH.       
   ea19_D7_7 LABH.          ea19_D7_8 LABH.          ea19_D7_9 LABH.       
   ea19_D7_10 LABH.         ea19_E1A LABI.           ea19_E1B LABI.        
   ea19_E1C LABI.           ea19_E1D LABI.           ea19_E1E LABI.        
   ea19_E1F LABI.           ea19_E1G LABI.           ea19_E1H LABI.        
   ea19_E1I LABI.           ea19_E1J LABI.           ea19_E2AUC EA19_E2A.  
   ea19_E2AUC_SOURCE EA19_E_A.   ea19_E2A_rec EA19_E_B.   ea19_E3A LABI.        
   ea19_E3B LABI.           ea19_E3C LABI.           ea19_E3D LABI.        
   ea19_E3E LABI.           ea19_E4 LABJ.            ea19_E5A LABK.        
   ea19_E5B_1 LABL.         ea19_E5B_2 LABL.         ea19_E5B_3 LABL.      
   ea19_E5B_4 LABL.         ea19_E5B_5 LABL.         ea19_E5B_6 LABL.      
   ea19_E5B_7 LABL.         ea19_E5B_8 LABL.         ea19_E5B_9 LABL.      
   ea19_E5 EA19_E5F.        ea19_F1_rec LABM.        ea19_F3 EA19_F3F.     
   ea19_F4 EA19_F4F.        ea19_F5 EA19_F5F.        ea19_F6_rec LABM.     
   ea19_F7 LABN.            ea19_F8 LABN.            ea19_G1 EA19_G1F.     
   ea19_G2 EA19_G2F.        ea19_G3A LABO.           ea19_G3B LABO.        
   ea19_G3C LABO.           ea19_G4 EA19_G4F.        ea19_G5A_rec EA19_G5A.
   ea19_G6_1 LABH.          ea19_G6_2 LABH.          ea19_G6_3 LABH.       
   ea19_G6_4 LABH.          ea19_G5 LABK.            ea19_H2 EA19_H2F.     
   ea19_H4 LABN.            ea19_I1 EA19_I1F.        ea19_I8 EA19_I8F.     
   ea19_J1 EA19_J1F.        ea19_K3 EA19_K3F.        ea19_H1_rec EA19_H1F. 
   ea19_H1A LABJ.           ea19_H3 EA19_H3F.        ea19_H4A_rec EA19_H4A.
   ea19_H5 EA19_H5F.        ea19_I9A EA19_I9A.       ea19_J2 LABN.         
   ea19_J3 EA19_J3F.        ea19_J7A LABP.           ea19_J7B LABP.        
   ea19_J7C LABP.           ea19_J7D LABP.           ea19_J7E LABP.        
   ea19_J11 LABQ.           ea19_J9 LABG.            ea19_J10 LABJ.        
   ea19_J12 LABN.           ea19_J13_rec LABQ.       ea19_K1_rec EA19_K1F. 
   ea19_K2_rec EA19_K2F.    ea19_K4 EA19_K4F.        ea19_K5A EA19_K5A.    
   ea19_K5B EA19_K5B.       ea19_K6 LABJ.            ea19_K6A_1 LABR.      
   ea19_K6A_2 LABR.         ea19_K6A_3 LABR.         ea19_K6A_4 LABR.      
   ea19_K6A_5 LABR.         ea19_K6A_6 LABR.         ea19_K6A_7 LABR.      
   ea19_K6B EA19_K6B.       ea19_PANEL EA19_PAN.     cal_SEXE CAL_SEXE.    
   cal_AGE1 CAL_AGE1F.      cal_AGE2 CAL_AGE2F.      cal_DIPL CAL_DIPL.    
   cal_ZEAT CAL_ZEAT.       insee_NUTS1 INSEE_NU.    insee_CATAEU2010 INSEE_CA.
   insee_TAU2014 INSEE_TA.   insee_TUU2014 INSEE_TU. ;


LENGTH
   UID_ea 4                 ea19_A1 3                ea19_A2A_rec 3        
   ea19_A3_rec 3            ea19_A3B_rec 3           ea19_A3C_rec 3        
   ea19_A3D 3               ea19_A3E_rec 3           ea19_A4 3             
   ea19_A5 3                ea19_A5A 3               ea19_A5C 3            
   ea19_A5C_rec 3           ea19_B1 3                ea19_B1A 3            
   ea19_B1B 3               ea19_B5A 3               ea19_B5C 3            
   ea19_B25 3               ea19_B10A 3              ea19_B10AA 3          
   ea19_B11 3               ea19_B18C 3              ea19_B18_rec 3        
   ea19_B2_rec 3            ea19_B4_rec 3            ea19_B5_rec 3         
   ea19_B5B_rec 3           ea19_B6A_rec 3           ea19_B6B_rec 3        
   ea19_B7B_rec 3           ea19_B8_rec 3            ea19_B9_rec 3         
   ea19_PCS18 4             ea19_PCS6 4              ea19_B1CJT 3          
   ea19_B1ACJT 3            ea19_B1BCJT 3            ea19_B10ACJT 3        
   ea19_B2CJT_rec 3         ea19_B4CJT_rec 3         ea19_B11CJT 3         
   ea19_B18CJT_rec 3        ea19_B18CCJT 3           ea19_PCS6CJT 4        
   ea19_TYPMEN5 3           ea19_C1_rec 3            ea19_C1JEU 3          
   ea19_C8 3                ea19_C8A_rec 3           ea19_C8B_rec 3        
   ea19_D1_rec 3            ea19_D1A 3               ea19_D2 3             
   ea19_D3 3                ea19_D4_rec 3            ea19_D5_rec 3         
   ea19_D6 3                ea19_D7_1 3              ea19_D7_2 3           
   ea19_D7_3 3              ea19_D7_4 3              ea19_D7_5 3           
   ea19_D7_6 3              ea19_D7_7 3              ea19_D7_8 3           
   ea19_D7_9 3              ea19_D7_10 3             ea19_E1A 3            
   ea19_E1B 3               ea19_E1C 3               ea19_E1D 3            
   ea19_E1E 3               ea19_E1F 3               ea19_E1G 3            
   ea19_E1H 3               ea19_E1I 3               ea19_E1J 3            
   ea19_E2AUC 3             ea19_E2AUC_SOURCE 3      ea19_E2A_rec 3        
   ea19_E3A 3               ea19_E3B 3               ea19_E3C 3            
   ea19_E3D 3               ea19_E3E 3               ea19_E4 3             
   ea19_E5A 3               ea19_E5B_1 3             ea19_E5B_2 3          
   ea19_E5B_3 3             ea19_E5B_4 3             ea19_E5B_5 3          
   ea19_E5B_6 3             ea19_E5B_7 3             ea19_E5B_8 3          
   ea19_E5B_9 3             ea19_E5 3                ea19_F1_rec 3         
   ea19_F3 3                ea19_F4 3                ea19_F5 3             
   ea19_F6_rec 3            ea19_F7 3                ea19_F8 3             
   ea19_G1 3                ea19_G2 3                ea19_G3A 3            
   ea19_G3B 3               ea19_G3C 3               ea19_G4 3             
   ea19_G5A_rec 3           ea19_G6_1 3              ea19_G6_2 3           
   ea19_G6_3 3              ea19_G6_4 3              ea19_G5 3             
   ea19_H2 3                ea19_H4 3                ea19_I1 3             
   ea19_I8 3                ea19_J1 3                ea19_K3 3             
   ea19_H1_rec 3            ea19_H1A 3               ea19_H3 3             
   ea19_H4A_rec 3           ea19_H5 3                ea19_I9A 3            
   ea19_J2 3                ea19_J3 3                ea19_J7A 3            
   ea19_J7B 3               ea19_J7C 3               ea19_J7D 3            
   ea19_J7E 3               ea19_J11 3               ea19_J9 3             
   ea19_J10 3               ea19_J12 3               ea19_J13_rec 3        
   ea19_K1_rec 3            ea19_K2_rec 3            ea19_K4 3             
   ea19_K5A 3               ea19_K5B 3               ea19_K6 3             
   ea19_K6A_1 3             ea19_K6A_2 3             ea19_K6A_3 3          
   ea19_K6A_4 3             ea19_K6A_5 3             ea19_K6A_6 3          
   ea19_K6A_7 3             ea19_K6B 3               ea19_PANEL 3          
   cal_SEXE 3               cal_AGE1 3               cal_AGE2 3            
   cal_DIPL 3               cal_ZEAT 3               insee_NUTS1 3         
   insee_CATAEU2010 4       insee_TAU2014 3          insee_TUU2014 3 ;

   

RUN ;
