/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco2_2020/donnees_coco2/sas_coco2/fr.cdsp.ddi.elipss.202004.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco2_2020/donnees_coco2/sas_coco2/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = fr_cdsp_ ;

proc format library = library ;
   value COCO2_CA
      1 = 'Homme'  
      2 = 'Femme' ;
   value COCO2__A
      1 = '18-24 ans'  
      2 = '25-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-79 ans' ;
   value COCO2__B
      1 = '18-22 ans'  
      2 = '23-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-75 ans'  
      7 = '76-79 ans' ;
   value COCO2__C
      1 = 'Aucun/CEP/BEPC'  
      2 = 'CAP/BEP'  
      3 = 'Bac/Bac+2'  
      4 = 'Bac+3 et plus' ;
   value COCO2__D
      1 = 'Région parisienne'  
      2 = 'Bassin parisien'  
      3 = 'Nord'  
      4 = 'Est'  
      5 = 'Ouest'  
      6 = 'Sud-ouest'  
      7 = 'Centre-est'  
      8 = 'Méditerranée' ;
   value COCO2_Q0F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
     .A = 'N''a pas répondu' ;
   value LABA
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu' ;
   value LABB
      1 = 'Choisi'  
      2 = 'Non Choisi' ;
   value COCO2__R
      1 = 'J’ai été testé(e) positif(ve)'  
      2 = 'J’ai de fortes suspicions d’avoir été atteint(e)'  
      3 = 'Je ne pense pas avoir été atteint(e)'  
     .A = 'N''a pas répondu' ;
   value COCO2_Q1F
      1 = 'Je suis guéri(e)'  
      2 = 'Je suis encore malade mais je vais plutôt bien'  
      3 = 'Je suis malade'  
     .A = 'Non concernée' ;
   value COCO2__S
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais' ;
   value LABC
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value COCO2__W
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
     .A = 'N''a pas répondu' ;
   value COCO2__X
      1 = 'Jamais'  
      2 = 'Rarement'  
      3 = 'Parfois'  
      4 = 'Souvent'  
      5 = 'Très souvent'  
      6 = 'Je vis actuellement seul(e)' ;
   value COCO2_Q3F
      1 = 'Principalement travaillé sur votre lieu de travail habituel'  
      2 = 'Alterné télétravail et travail sur votre lieu de travail hab'  
      3 = 'Principalement été en télétravail'  
      4 = 'Aucune de ces situations'  
     .A = 'N''a pas répondu' ;
   value COCO2_Q4F
      1 = 'Jamais'  
      2 = 'Une fois par semaine ou moins'  
      3 = 'Une fois tous les deux ou trois jours'  
      4 = 'Tous les jours ou presque'  
     .A = 'N''a pas répondu' ;
   value LABD
      1 = 'Tous les jours d’école ou presque'  
      2 = 'Au moins deux fois par semaine'  
      3 = 'Au moins une fois par semaine'  
      4 = 'Jamais'  
      5 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABE
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABF
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
      6 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABG
      1 = 'Je n’ai pas fait cette activité'  
      2 = 'Entre 0 et 1 heure'  
      3 = 'Entre 1 et 2 heures'  
      4 = 'Entre 2 et 3 heures'  
      5 = 'Entre 3 et 4 heures'  
      6 = 'Entre 4 et 6 heures'  
      7 = 'Entre 6 et 8 heures'  
      8 = 'Entre 8 et 10 heures'  
      9 = 'Plus de 10 heures'  
     .A = 'N''a pas répondu' ;
   value COCO2_Q6F
      0 = '0 - Pas du tout'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Énormément'  
     .A = 'N''a pas répondu' ;
   value COCO2_BD
      1 = 'Tout à fait satisfait(e)'  
      2 = 'Plutôt satisfait(e)'  
      3 = 'Plutôt pas satisfait(e)'  
      4 = 'Pas du tout satisfait(e)'  
     .A = 'N''a pas répondu' ;
   value COCO2_Q7F
      0 = '0 - Conséquences sanitaires'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Conséquences économiques'  
     .A = 'N''a pas répondu' ;
   value COCO2_Q9F
      1 = 'Oui, autant que je veux'  
      2 = 'Oui, mais pas autant que je veux'  
      3 = 'Non'  
     .A = 'N''a pas répondu'  
     .B = 'Non concerné' ;
   value COCO2_BJ
     .A = 'N''a pas répondu'  
     .B = 'Non concerné' ;
   value COCO2_CB
      1 = 'Inacceptable'  
      2 = 'Acceptable pour une période transitoire'  
      3 = 'Acceptable pour une mise en place définitive'  
     .A = 'N''a pas répondu' ;
   value COCO2_CC
      1 = 'Tout à fait favorable'  
      2 = 'Plutôt favorable'  
      3 = 'Plutôt pas favorable'  
      4 = 'Pas du tout favorable'  
     .A = 'N''a pas répondu' ;
   value LABH
      1 = 'Oui'  
      2 = 'Non'  
     .A = 'N''a pas répondu' ;
   value COCO2_BL
      1 = 'Groupe expérimental A'  
      2 = 'Groupe expérimental B' ;
   value LABI
      1 = 'Mettre en place ce confinement partiel'  
      2 = 'Continuer avec le confinement le plus strict'  
     .A = 'Non concerné'  
     .B = 'N''a pas répondu' ;
   value COCO2_CH
      0 = '0 - Limiter mes relations sociales'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Intensifier mes relations sociales'  
     .A = 'N''a pas répondu' ;
   value COCO2_CI
      0 = '0 - Travailler moins qu''avant'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Travailler plus qu''avant'  
     .A = 'N''a pas répondu' ;
   value COCO2_CJ
      0 = '0 - Consommer moins'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Consommer plus'  
     .A = 'N''a pas répondu' ;
   value LABJ
      1 = '1'  
      2 = '2'  
      3 = '3'  
      4 = '4 ou plus'  
      5 = 'Je n’ai pas fait un voyage de ce type'  
     .A = 'N''a pas répondu' ;
   value LABK
      1 = 'Aucun'  
      2 = '1'  
      3 = '2'  
      4 = '3'  
      5 = '4 ou plus'  
     .A = 'Non concerné'  
     .B = 'N''a pas répondu' ;
   value LABL
     .A = 'Non concerné' ;
   value LABM
      1 = 'Beaucoup moins que d’habitude'  
      2 = 'Un peu moins que d’habitude'  
      3 = 'Autant que d’habitude'  
      4 = 'Un peu plus que d’habitude'  
      5 = 'Beaucoup plus que d’habitude'  
      6 = 'Non concerné(e) ou ne pratique jamais cette activité'  
     .A = 'N''a pas répondu'  
     .B = 'Non concerné' ;
   value LABN
      1 = 'Tous les jours d’école ou presque'  
      2 = 'Au moins deux fois par semaine'  
      3 = 'Au moins une fois par semaine'  
      4 = 'Jamais'  
      5 = 'Non concerné(e)'  
      6666 = 'Non concerné'  
      9999 = 'N''a pas répondu' ;
   value LABO
      1 = 'Tout à fait d’accord'  
      2 = 'Plutôt d’accord'  
      3 = 'Plutôt pas d’accord'  
      4 = 'Pas d’accord du tout'  
      6666 = 'Non concerné'  
      9999 = 'N''a pas répondu' ;
   value LABP
      0 = 'Bien-être subjectif le plus élevé'  
      1 = 'Bien-être subjectif le plus faible' ;
   value EAYY_A1F
      1 = 'Un homme'  
      2 = 'Une femme' ;
   value EAYY_A2A
      4 = 'Moins de 24 ans'  
      5 = 'De 25 à 29 ans'  
      6 = 'De 30 à 34 ans'  
      7 = 'De 35 à 39 ans'  
      8 = 'De 40 à 44 ans'  
      9 = 'De 45 à 49 ans'  
      10 = 'De 50 à 54 ans'  
      11 = 'De 55 à 59 ans'  
      12 = 'De 60 à 64 ans'  
      13 = 'De 65 à 69 ans'  
      14 = '70 ans et plus' ;
   value EAYY_A3F
      1 = 'Oui, de naissance'  
      2 = '(Oui par réintégration, naturalisation, par mariage, par déc'  
      3 = 'Non'  
      4 = 'Apatride' ;
   value EAYY_A3B
      1 = 'France'  
      2 = 'Union européenne'  
      3 = 'Hors Union européenne'  
      9 = 'N''a pas répondu' ;
   value LABQ
      1 = 'Union européenne'  
      2 = 'Hors Union européenne'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_A3D
      1 = 'Oui'  
      2 = 'Non' ;
   value EAYY_A4F
      1 = 'Célibataire (jamais légalement marié(e))'  
      2 = 'Pacsé(e)'  
      3 = 'Union libre ou concubinage'  
      4 = 'Marié(e) (ou séparé(e) mais non divorcé(e))'  
      5 = 'Divorcé(e)'  
      6 = 'Pacs dissout'  
      7 = 'Veuf(ve)'  
      77 = 'Refuse de répondre' ;
   value EAYY_A5F
      1 = 'Oui, avec quelqu''un qui vit dans votre logement'  
      2 = 'Oui, avec quelqu''un qui ne vit pas dans votre logement'  
      3 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_A5A
      1 = 'Marié(e)'  
      2 = 'Pacsé(e)'  
      3 = 'En union libre, en concubinage'  
      4 = 'Autre (précisez)'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A5C
      1 = 'Depuis moins d’un an'  
      2 = 'Depuis un an ou plus'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A_A
      1 = 'Moins de 2 ans'  
      2 = 'De 2 à 4 ans'  
      3 = 'De 5 à 9 ans'  
      4 = 'De 10 à 14 ans'  
      5 = 'De 15 à 19 ans'  
      6 = 'De 20 à 24 ans'  
      7 = '25 ans et plus'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1F
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      77 = 'Refuse de répondre' ;
   value EAYY_B10F
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B_A
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B_B
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de réponse'  
      8 = 'Ne sait pas' ;
   value LABR
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B18F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,' ;
   value EAYY_B_D
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire (' ;
   value EAYY_B_E
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire ('  
      6 = 'Non concerné' ;
   value EAYY_B_F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,'  
      66 = 'Non concerné' ;
   value LABS
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1B
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      7 = 'Refuse de répondre' ;
   value EAYY_B_H
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EAYY_B1C
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre' ;
   value EAYY_B2F
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salarié(e) d''un particulier'  
      7 = 'Vous aidez un membre de votre famille dans son travail sans'  
      8 = 'Vous êtes chef d''entreprise salarié, PDG, gérant(e) minorita'  
      9 = 'Vous êtes indépendant(e) ou à votre compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B25F
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_B2C
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salairé(e) d''un particulier'  
      7 = 'Il(elle) aide un membre de sa famille dans son travail sans'  
      8 = 'Il(elle) est chef d''entreprise salarié, PDG, gérant(e) minor'  
      9 = 'Il(elle) est indépendant(e) ou à son compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value LABT
      1 = 'Aucun salarié'  
      2 = 'Au moins 1 salarié'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B5F
      1 = 'Contrat à durée indéterminée'  
      2 = '(Contrat à durée déterminée (dont contrat saisonnier))'  
      4 = 'Contrat d''interim ou de travail temporaire'  
      5 = 'Contrat d''apprentissage'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5A
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5B
      1 = '(80% et plus)'  
      3 = 'Entre 50 et 80%'  
      4 = 'Mi-temps (50%)'  
      5 = 'Moins d''un mi-temps (moins de 50%)'  
      6 = 'Non concerné' ;
   value EAYY_B5C
      1 = 'Pour exercer une autre activité professionnelle, ou suivre d'  
      2 = 'Pour raisons de santé'  
      3 = 'Vous n''avez pas trouvé d''emploi à temps plein'  
      4 = 'Cela vous a été imposé par votre employeur'  
      5 = 'Pour vous occuper de vos enfants, ou d''un autre membre de vo'  
      6 = 'Pour disposer de temps libre ou faire des travaux domestique'  
      7 = 'Pour une autre raison (précisez)'  
      66 = 'Non concerné' ;
   value EAYY_B6A
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvier(e) qualifié(e) ou hautement qualifié(e), technicien(n'  
      3 = 'Technicien(ne)'  
      4 = 'Agent de maîtrise, maîtrise administrative ou commerciale, V'  
      5 = 'Ingénieur, cadre (à l''exception des directeurs généraux ou d'  
      6 = 'Employé(e) de bureau, employé(e) de commerce, personnel de s'  
      7 = 'Directeur général, adjoint direct'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B6B
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvrier(e) qualifié(e) ou hautement qualifié(e), technicien('  
      3 = 'Technicien(ne)'  
      4 = 'Personnel de catégorie C ou assimilé'  
      5 = 'Personnel de catégorie B ou assimilé'  
      6 = 'Personnel de catégorie A ou assimilé'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B7B
      1 = 'Production, chantier, exploitation'  
      2 = 'Installation, réparation, maintenance'  
      3 = 'Gardiennage, nettoyage, entretien ménager'  
      4 = 'Manutention, magasinage, logistique'  
      5 = 'Secrétariat, saisie, accueil'  
      6 = 'Gestion, comptabilité'  
      7 = 'Commercial, technico-commercial'  
      8 = 'Études, recherche et développement, méthodes'  
      9 = 'Enseignement'  
      10 = 'Soin des personnes'  
      11 = 'Autre fonction (précisez)'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B8F
      1 = 'Moins de 10'  
      2 = '10 à 49'  
      3 = '50 à 499'  
      4 = '500 et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B9F
      1 = 'Moins de 20 hectares'  
      2 = 'De 20 à moins de 50 hectares'  
      3 = 'De 50 à moins de 100 hectares'  
      4 = 'De 100 à moins de 200 hectares'  
      5 = '200 hectares et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_C1F
      1 = '1 habitant'  
      2 = '2 habitants'  
      3 = '3 habitants'  
      4 = '4 habitants'  
      5 = '5 habitants'  
      6 = '6 habitants et plus' ;
   value EAYY_C1J
      1 = '0 jeune'  
      2 = '1 jeune'  
      3 = '2 jeunes'  
      4 = '3 jeunes ou plus' ;
   value EAYY_C8F
      1 = 'Oui'  
      2 = 'Non'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8A
      1 = '1 enfant'  
      2 = '2 enfants'  
      3 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8B
      1 = '0 enfant'  
      2 = '1 enfant'  
      3 = '2 enfants'  
      4 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D1F
      1 = 'Propriétaire (ou copropriétaire) : vous ne payez pas de créd'  
      2 = 'Accédant à la propriété : vous payez toujours un crédit immo'  
      3 = '(Locataire, sous-locataire)'  
      5 = 'Occupant à titre gratuit'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_D1A
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D2F
      1 = 'Votre conjoint(e)'  
      2 = 'Un autre membre du foyer'  
      3 = 'Une autre personne de votre famille'  
      4 = 'Un autre particulier'  
      5 = 'Un organisme HLM (ou assimilé, OPAC, offices, sociétés, fond'  
      6 = 'Une administration, organisme de Sécurité Sociale ou associa'  
      7 = 'Une banque, assurance ou autre société du secteur public ou'  
      8 = 'L''employeur d''un membre du ménage dans le cadre d''un logemen'  
      9 = 'Autre cas'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_D3F
      1 = 'Une maison individuelle'  
      2 = 'Un appartement'  
      3 = 'Autre (précisez)' ;
   value EAYY_D4F
      1 = '1 pièce'  
      2 = '2 pièces'  
      3 = '3 pièces'  
      4 = '4 pièces'  
      5 = '5 pièces'  
      6 = '6 pièces'  
      7 = '7 pièces'  
      8 = '8 pièces'  
      9 = '9 pièces et plus' ;
   value EAYY_D5F
      1 = 'Moins de 2 ans'  
      2 = 'Entre 2 à 5 ans'  
      3 = 'Entre 5 et 10 ans'  
      4 = 'Entre 10 et 15 ans'  
      5 = 'Il y a plus de 15 ans'  
      9 = 'N''a pas répondu' ;
   value EAYY_D6F
      1 = 'Maisons dispersées, hors agglomération'  
      2 = 'Maisons en lotissement, en quartier pavillonnaire ou en vill'  
      3 = 'Immeubles en ville (autre que cité ou grand ensemble)'  
      4 = 'Immeubles en cité ou grand ensemble'  
      5 = 'Habitat mixte : à la fois immeubles et maisons'  
      9 = 'N''a pas répondu' ;
   value LABU
      1 = 'Choisi'  
      2 = 'Non choisi'  
      9 = 'N''a pas répondu' ;
   value LABV
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas' ;
   value EAYY_E2A
      3 = '(Moins de 800 €)'  
      4 = 'De 800 à moins de 1000 €'  
      5 = 'De 1000 à moins de 1200 €'  
      6 = 'De 1200 à moins de 1500 €'  
      7 = 'De 1500 à moins de 1800 €'  
      8 = 'De 1800 à moins de 2000 €'  
      9 = 'De 2000 à moins de 2500 €'  
      10 = 'De 2500 à moins de 3000 €'  
      11 = 'De 3000 à moins de 4000 €'  
      12 = 'De 4000 à moins de 6000 €'  
      13 = '(6000 € et plus)'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_E_A
      1 = 'Moins de 650 €'  
      2 = 'De 650 à moins de 950 €'  
      3 = 'De 950 à moins de 1200 €'  
      4 = 'De 1200 à moins de 1400 €'  
      5 = 'De 1400 à moins de 1650 €'  
      6 = 'De 1650 à moins de 1900 €'  
      7 = 'De 1900 à moins de 2200 €'  
      8 = 'De 2200 à moins de 2500 €'  
      9 = 'De 2500 à moins de 3200 €'  
      10 = '3200 € et plus'  
      99 = 'N''a pas répondu' ;
   value EAYY_E_B
      1 = 'À partir du montant déclaré des ressources'  
      2 = 'À partir de la tranche déclarée des ressources'  
      3 = 'Non calculé' ;
   value LABW
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas'  
     .A = 'Non enquêté(e)' ;
   value EAYY_E4F
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
     .B = 'Non enquêté(e)' ;
   value EAYY_E5F
      1 = 'Vous ne pouvez pas y arriver sans faire de dettes'  
      2 = 'Vous y arrivez difficilement'  
      3 = 'C''''est juste, il faut faire attention'  
      4 = 'Ça va'  
      5 = 'Vous êtes plutôt à l''''aise'  
      6 = 'Vous êtes vraiment à l''''aise'  
      99 = 'N''a pas répondu' ;
   value EAYY_E5A
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABX
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABY
      1 = 'Au moins une fois par semaine'  
      2 = 'Une à trois fois par mois'  
      3 = 'Plusieurs fois dans l''année (mais moins d''une fois par mois)'  
      4 = 'Seulement pour des occasions exceptionnelles'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_F3F
      1 = 'Il n''y en a pas'  
      2 = '1 ou 2 personnes'  
      3 = 'Entre 3 et 5 personnes'  
      4 = '6 personnes ou plus'  
      8 = 'Ne sait pas' ;
   value EAYY_F4F
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_F5F
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n''est jamais assez prudent quand on a affaire aux autres'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value LABZ
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_G1F
      1 = 'Moins de 2 heures par jour'  
      2 = 'De 2 à 4 heures par jour'  
      3 = 'Plus de 4 heures par jour'  
      4 = 'Je ne regarde par la télévision'  
      8 = 'Ne sait pas' ;
   value EAYY_G2F
      1 = 'Aucun'  
      2 = 'Moins de 6'  
      3 = 'De 6 à moins de 12'  
      4 = 'De 12 à 24 (c''est-à-dire entre 1 et 2 livres par mois)'  
      5 = 'De 25 à 50 (c''est-à-dire plus de 2 livres par mois)'  
      6 = 'Plus de 50 (c''est-à-dire plus de 4 livres par mois)'  
      8 = 'Ne sait pas' ;
   value LABAA
      1 = 'Jamais'  
      2 = '1 à 3 fois'  
      3 = '4 à 6 fois'  
      4 = '7 à 12 fois'  
      5 = 'Plus de 12 fois'  
      9 = 'N''a pas répondu' ;
   value EAYY_G4F
      1 = 'Régulièrement tout au long de l''année'  
      2 = 'De temps en temps tout au long de l''année'  
      3 = 'Seulement pendant certaines périodes ou pendant les vacances'  
      4 = 'Occasionnellement ou rarement'  
      5 = 'Jamais'  
      8 = 'Ne sait pas' ;
   value EAYY_G5F
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu' ;
   value EAYY_H1A
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_H2F
      1 = 'Pas du tout d''importance'  
      2 = 'Un peu d''importance'  
      3 = 'Assez d''importance'  
      4 = 'Beaucoup d''importance'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_I1F
      1 = 'Beaucoup'  
      2 = 'Assez'  
      3 = 'Peu'  
      4 = 'Pas du tout'  
      8 = 'Ne sait pas' ;
   value EAYY_I8F
      0 = 'Gauche'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = 'Droite'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_J1F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_K3F
      1 = 'Tous les jours ou presque'  
      2 = 'Plusieurs fois par semaine'  
      3 = 'Une fois par semaine'  
      4 = 'Une à trois fois par mois'  
      5 = 'Moins souvent'  
      9 = 'N''a pas répondu' ;
   value EAYY_PCS
      10 = 'Agriculteurs exploitants'  
      20 = '(Artisans, commerçants et chefs d''entreprise)'  
      31 = 'Professions libérales et assimilés'  
      32 = 'Cadres de la fonction publique, professions intellectuelles'  
      36 = 'Cadres d''entreprise'  
      41 = 'Professions intermédiaires de l''enseignement, de la santé, d'  
      46 = 'Professions intermédiaires administratives et commerciales d'  
      47 = 'Techniciens'  
      48 = 'Contremaîtres, agents de maîtrise'  
      51 = 'Employés de la fonction publique'  
      54 = 'Employés administratifs d''entreprise'  
      55 = 'Employés de commerce'  
      56 = 'Personnels des services directs aux particuliers'  
      61 = 'Ouvriers qualifiés'  
      66 = '(Ouvriers non qualifiés et ouvriers agricoles)'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value LABAB
      1 = 'Agriculteurs exploitants'  
      2 = 'Artisans, commerçants et chefs d''entreprise'  
      3 = 'Cadres et professions intellectuelles supérieures'  
      4 = 'Professions intermédiaires'  
      5 = 'Employés'  
      6 = 'Ouvriers'  
      99 = 'N''a pas répondu'  
      666 = 'Non concerné'  
      999 = 'Valeur manquante' ;
   value EAYY_TYP
      1 = 'Ménages d''une seule personne'  
      2 = 'Familles monoparentales'  
      3 = 'Couples sans enfant'  
      4 = 'Couples avec enfant(s)'  
      5 = 'Ménages complexes de plus d''une personne' ;
   value INSEE_NU
      1 = 'FR1 : Région parisienne'  
      2 = 'FR2 : Bassin parisien'  
      3 = 'FR3 : Nord'  
      4 = 'FR4 : Est'  
      5 = 'FR5 : Ouest'  
      6 = 'FR6 : Sud-ouest'  
      7 = 'FR7 : Centre-est'  
      8 = 'FR8 : Méditerranée'  
      9 = 'FRA : Départements d''Outre-Mer' ;
   value INSEE_CA
      111 = 'Commune appartenant à un grand pôle (10 000 emplois ou plus)'  
      112 = 'Commune appartenant à la couronne d''un grand pôle'  
      120 = 'Commune multipolarisée des grandes aires urbaines'  
      211 = 'Commune appartenant à un moyen pôle (5 000 à moins de 10 000'  
      212 = 'Commune appartenant à la couronne d''un moyen pôle'  
      221 = 'Commune appartenant à un petit pôle (de 1 500 à moins de 5 0'  
      222 = 'Commune appartenant à la couronne d''un petit pôle'  
      300 = 'Autre commune multipolarisée'  
      400 = 'Commune isolée hors influence des pôles' ;
   value INSEE_TA
      0 = 'Commune hors aire urbaine'  
      1 = 'Commune appartenant à une aire urbaine de moins de 15 000 ha'  
      2 = 'Commune appartenant à une aire urbaine de 15 000 à 19 999 ha'  
      3 = 'Commune appartenant à une aire urbaine de 20 000 à 24 999 ha'  
      4 = 'Commune appartenant à une aire urbaine de 25 000 à 34 999 ha'  
      5 = 'Commune appartenant à une aire urbaine de 35 000 à 49 999 ha'  
      6 = 'Commune appartenant à une aire urbaine de 50 000 à 99 999 ha'  
      7 = 'Commune appartenant à une aire urbaine de 100 000 à 199 999'  
      8 = 'Commune appartenant à une aire urbaine de 200 000 à 499 999'  
      9 = 'Commune appartenant à une aire urbaine de 500 000 à 9 999 99'  
      10 = 'Commune appartenant à l''aire urbaine de Paris' ;
   value INSEE_TU
      0 = 'Commune rurale'  
      1 = 'Commune appartenant à une unité urbaine de 2 000 à 4 999 hab'  
      2 = 'Commune appartenant à une unité urbaine de 5 000 à 9 999 hab'  
      3 = 'Commune appartenant à une unité urbaine de 10 000 à 19 999 h'  
      4 = 'Commune appartenant à une unité urbaine de 20 000 à 49 999 h'  
      5 = 'Commune appartenant à une unité urbaine de 50 000 à 99 999 h'  
      6 = 'Commune appartenant à une unité urbaine de 100 000 à 199 999'  
      7 = 'Commune appartenant à une unité urbaine de 200 000 à 1 999 9'  
      8 = 'Commune appartenant à l''unité urbaine de Paris' ;

DATA library.&dataset ;
INFILE datafile LRECL=924;
INPUT
   UID_ANONYM_COVID  1-4    coco2_cal_SEXE  5        coco2_cal_AGE1  6     
   coco2_cal_AGE2  7        coco2_cal_DIPL  8        coco2_cal_ZEAT  9     
   coco2_q04  10-13         coco2_q06_1  14-17       coco2_q06_2  18-21    
   coco2_q06_3  22-25       coco2_q06_4  26-29       coco2_q06_5  30-33    
   coco2_q06_6  34-37       coco2_q06_7  38-41       coco2_q06_8  42-45    
   coco2_q06_9  46-49       coco2_q06_10  50-53      coco2_q07_1  54       
   coco2_q07_2  55          coco2_q07_3  56          coco2_q09  57-60      
   coco2_q10  61-64         coco2_q16  65            coco2_q17  66-69      
   coco2_q18  70-73         coco2_q19  74-77         coco2_q20  78-81      
   coco2_q21  82-85         coco2_q25_a  86          coco2_q38_modifie  87-90
   coco2_q47  91-94         coco2_q51  95-98         coco2_q52_1  99-102   
   coco2_q52_2  103-106     coco2_q52_3  107-110     coco2_q52_4  111-114  
   coco2_q53_1  115-118     coco2_q53_2  119-122     coco2_q53_3  123-126  
   coco2_q54_1  127-130     coco2_q54_2  131-134     coco2_q54_3  135-138  
   coco2_q54_4  139-142     coco2_q54_5  143-146     coco2_q54_6  147-150  
   coco2_q54_7  151-154     coco2_q54_8  155-158     coco2_q54_bis_1  159-162
   coco2_q54_bis_2  163-166   coco2_q54_bis_3  167-170
   coco2_q54_bis_4  171-174   coco2_q54_bis_5  175-178
   coco2_q54_bis_6  179-182   coco2_q54_bis_7  183-186   coco2_q59_1  187-190  
   coco2_q59_2  191-194     coco2_q59_3  195-198     coco2_q59_4  199-202  
   coco2_q59_5  203-206     coco2_q59_6  207-210     coco2_q59_7  211-214  
   coco2_q59_8  215-218     coco2_q59_9  219-222     coco2_q64  223-226    
   coco2_q68  227-230       coco2_q79  231-234       coco2_q92  235-238    
   coco2_q93_1  239-242     coco2_q93_2  243-246     coco2_q93_3  247-250  
   coco2_q93_4  251-254     coco2_q93_5  255-258     coco2_q94  259-262    
   coco2_q95_1  263-266     coco2_q95_2  267-270     coco2_q95_3  271-274  
   coco2_q95_4  275-278     coco2_q95_5  279-282     coco2_q95_6  283-286  
   coco2_q96_1  287-290     coco2_q96_2  291-294     coco2_q96_3  295-298  
   coco2_q96_4  299-302     coco2_q96_5  303-306     coco2_q96_6  307-310  
   coco2_q96_7  311-314     coco2_q96_8  315-318     coco2_q96_9  319-322  
   coco2_q97  323-326       coco2_q98  327-330       coco2_q99_1  331-334  
   coco2_q99_2  335-338     coco2_q99_3  339-342  
   coco2_Bloc2_DO_exp1_gpe  343   coco2_exp1_gpe_a  344-347
   coco2_exp1_gpe_b  348-351   coco2_q100  352-355      coco2_q101  356-359   
   coco2_q102  360-363      coco2_q103_1  364-367    coco2_q103_2  368-371 
   coco2_q103_3  372-375    coco2_q104_1  376-379    coco2_q104_2  380-383 
   coco2_q104_3  384-387    coco2_q105_1  388-391    coco2_q105_2  392-395 
   coco2_q105_3  396-399    coco2_q106_1  400-403    coco2_q106_2  404-407 
   coco2_q106_3  408-411    coco2_q107_1  412-415    coco2_q107_2  416-419 
   coco2_q107_3  420-423    coco2_q107_4  424-427    coco2_q107_5  428-431 
   coco2_q107_6  432-435    coco2_q107_7  436-439    coco2_q107_8  440-443 
   coco2_q108_1_1  444-447   coco2_q108_2_1  448-451   coco2_q108_3_1  452-455
   coco2_q108_4_1  456-459   coco2_q108_5_1  460-463   coco2_q108_6_1  464-467
   coco2_q108_7_1  468-471   coco2_q109_1  472-475    coco2_q109_2  476-479 
   coco2_q109_3  480-483    coco2_q109_4  484-487    coco2_q109_5  488-491 
   coco2_q109_6  492-495    coco2_q109_7  496-499    coco2_q109_8  500-503 
   coco2_q110_1  504-507    coco2_q110_2  508-511    coco2_q110_3  512-515 
   coco2_q111_1  516-519    coco2_q111_2  520-523    coco2_q111_3  524-527 
   coco2_q111_4  528-531    coco2_q111_5  532-535    coco2_q111_6  536-539 
   coco2_q112_1  540-543    coco2_q112_2  544-547    coco2_q112_3  548-551 
   coco2_SWB  552-571       ea17_SWB  572-589        ea18_SWB  590-607     
   ea19_SWB  608-625        eayy_A1  626             eayy_A2A_rec  627-628 
   eayy_A3_rec  629         eayy_A3B_rec  630        eayy_A3C_rec  631     
   eayy_A3D  632            eayy_A3E_rec  633        eayy_A4  634-635      
   eayy_A5  636             eayy_A5A  637-640        eayy_A5C  641-644     
   eayy_A5C_rec  645-648    eayy_B1  649-650         eayy_B10A  651        
   eayy_B10AA  652-655      eayy_B10ACJT  656        eayy_B11  657         
   eayy_B11CJT  658         eayy_B18_rec  659-660    eayy_B18C  661        
   eayy_B18CCJT  662        eayy_B18CJT_rec  663-664   eayy_B1A  665-668     
   eayy_B1ACJT  669-672     eayy_B1B  673            eayy_B1BCJT  674      
   eayy_B1CJT  675-676      eayy_B2_rec  677-678     eayy_B25  679         
   eayy_B2CJT_rec  680-681   eayy_B4_rec  682         eayy_B4CJT_rec  683   
   eayy_B5_rec  684         eayy_B5A  685            eayy_B5B_rec  686     
   eayy_B5C  687-688        eayy_B6A_rec  689-690    eayy_B6B_rec  691-692 
   eayy_B7B_rec  693-694    eayy_B8_rec  695         eayy_B9_rec  696      
   eayy_C1_rec  697         eayy_C1JEU  698          eayy_C8  699-702      
   eayy_C8A_rec  703-706    eayy_C8B_rec  707-710    eayy_D1_rec  711      
   eayy_D1A  712-715        eayy_D2  716-717         eayy_D3  718          
   eayy_D4_rec  719         eayy_D5_rec  720         eayy_D6  721          
   eayy_D7_1  722           eayy_D7_10  723          eayy_D7_2  724        
   eayy_D7_3  725           eayy_D7_4  726           eayy_D7_5  727        
   eayy_D7_6  728           eayy_D7_7  729           eayy_D7_8  730        
   eayy_D7_9  731           eayy_E1A  732            eayy_E1B  733         
   eayy_E1C  734            eayy_E1D  735            eayy_E1E  736         
   eayy_E1F  737            eayy_E1G  738            eayy_E1H  739         
   eayy_E1I  740            eayy_E1J  741            eayy_E2A_rec  742-743 
   eayy_E2AUC  744-745      eayy_E2AUC_SOURCE  746   eayy_E3A  747-750     
   eayy_E3B  751-754        eayy_E3C  755-758        eayy_E3D  759-762     
   eayy_E3E  763-766        eayy_E4  767-770         eayy_E5  771-772      
   eayy_E5A  773-776        eayy_E5B_1  777-780      eayy_E5B_2  781-784   
   eayy_E5B_3  785-788      eayy_E5B_4  789-792      eayy_E5B_5  793-796   
   eayy_E5B_6  797-800      eayy_E5B_7  801-804      eayy_E5B_8  805-808   
   eayy_E5B_9  809-812      eayy_F1_rec  813         eayy_F3  814          
   eayy_F4  815-818         eayy_F5  819-822         eayy_F6_rec  823      
   eayy_F7  824             eayy_F8  825             eayy_G1  826          
   eayy_G2  827             eayy_G3A  828            eayy_G3B  829         
   eayy_G3C  830            eayy_G4  831             eayy_G5  832          
   eayy_G6_1  833           eayy_G6_2  834           eayy_G6_3  835        
   eayy_G6_4  836           eayy_H1A  837            eayy_H2  838          
   eayy_H4  839             eayy_I1  840             eayy_I8  841-842      
   eayy_J1  843             eayy_K3  844             eayy_PCS18  845-847   
   eayy_PCS6  848-850       eayy_PCS6CJT  851-853    eayy_TYPMEN5  854     
   VAGUE  855-858           insee_NUTS1  859         insee_CATAEU2010  860-862
   insee_TAU2014  863-864   insee_TUU2014  865       coco2_POIDS  866-883  
   coco2_PDSPLT $ 884-901   coco2_cal_NAT  902       coco2_POIDS_INIT  903-913
   coco2_PDSPLT_INIT $ 914-924 ;                       

LABEL
   UID_ANONYM_COVID = "Identifiant interviewé"
   coco2_cal_SEXE = "Sexe"
   coco2_cal_AGE1 = "Age décennal (calage panel pilote)"
   coco2_cal_AGE2 = "Age décennal (calage)"
   coco2_cal_DIPL = "Diplôme (calage)"
   coco2_cal_ZEAT = "Zone d'études et d'aménagement du territoire"
   coco2_q04 = "Auto-évaluation de la santé"
   coco2_q06_1 = "Symptômes pendant les deux dernières semaines : Toux"
   coco2_q06_2 = "Symptômes pendant les deux dernières semaines : Maux de tête"
   coco2_q06_3 = "Symptômes pendant les deux dernières semaines : Fatigue"
   coco2_q06_4 = "Symptômes pendant les deux dernières semaines : Rhume"
   coco2_q06_5 = "Symptômes pendant les deux dernières semaines : Maux de gorge"
   coco2_q06_6 = "Symptômes pendant les deux dernières semaines : Gêne respiratoire"
   coco2_q06_7 = "Symptômes pendant les deux dernières semaines : Courbatures"
   coco2_q06_8 = "Symptômes pendant les deux dernières semaines : Fièvre"
   coco2_q06_9 = "Symptômes pendant les deux dernières semaines : Troubles digestifs"
   coco2_q06_10 = "Symptômes pendant les deux dernières semaines : Aucun de ces symptômes"
   coco2_q07_1 = "Consultation médicale : Aucune"
   coco2_q07_2 = "Consultation médicale : Pour un ou plusieurs symptômes"
   coco2_q07_3 = "Consultation médicale : Autres raisons"
   coco2_q09 = "Infection par le virus covid-19"
   coco2_q10 = "État de santé actuel après une probable infection par le virus covid-19"
   coco2_q16 = "Les 2 dernières semaines, s'est senti : nerveux"
   coco2_q17 = "Les 2 dernières semaines, s'est senti : découragé"
   coco2_q18 = "Les 2 dernières semaines, s'est senti : calme"
   coco2_q19 = "Les 2 dernières semaines, s'est senti : triste et abattu"
   coco2_q20 = "Les 2 dernières semaines, s'est senti : heureux"
   coco2_q21 = "Sentiment de solitude"
   coco2_q25_a = "Tensions au sein du ménage au cours des 2 dernières semaines"
   coco2_q38_modifie = "Situation actuelle vis-à-vis du télétravail au cours des 2 dernières semaines"
   coco2_q47 = "Fréquence des sorties au cours des deux dernières semaines"
   coco2_q51 = "Fréquence de la surveillance des travaux scolaires des enfants"
   coco2_q52_1 = "Fréquence des rencontres avec des amis dans la vie réelle"
   coco2_q52_2 = "Fréquence des rencontres virtuelles avec des amis"
   coco2_q52_3 = "Fréquence des rencontres avec la famille dans la vie réelle"
   coco2_q52_4 = "Fréquence des rencontres virtuelles avec  la famille"
   coco2_q53_1 = "Fréquence des contacts avec la famille à l'étranger"
   coco2_q53_2 = "Fréquence des contacts avec des amis à l'étranger"
   coco2_q53_3 = "Fréquence des contacts avec des collègues à l'étranger"
   coco2_q54_1 = "Reçu un coup de main ou l’aide : de la famille"
   coco2_q54_2 = "Reçu un coup de main ou l’aide : d'amis proches"
   coco2_q54_3 = "Reçu un coup de main ou l'aide : de collègues"
   coco2_q54_4 = "Reçu un coup de main ou l'aide : de voisins"
   coco2_q54_5 = "Reçu un coup de main ou l'aide : d'agents des services publics"
   coco2_q54_6 = "Reçu un coup de main ou l'aide : de bénévoles d’une association"
   coco2_q54_7 = "Reçu un coup de main ou l'aide : de personnes que vous ne connaissiez pas auparavant"
   coco2_q54_8 = "Reçu un coup de main ou l'aide : de personne"
   coco2_q54_bis_1 = "Donné un coup de main ou de l’aide à : la famille"
   coco2_q54_bis_2 = "Donné un coup de main ou de l’aide à : des amis proches"
   coco2_q54_bis_3 = "Donné un coup de main ou l'aide à : des collègues"
   coco2_q54_bis_4 = "Donné un coup de main ou l'aide à : des voisins"
   coco2_q54_bis_5 = "Donné un coup de main ou l'aide à : une association"
   coco2_q54_bis_6 = "Donné un coup de main ou l'aide à : des personnes que vous ne connaissiez pas auparavant"
   coco2_q54_bis_7 = "Donné un coup de main ou l'aide à : personne"
   coco2_q59_1 = "Temps consacré à : faire du ménage"
   coco2_q59_2 = "Temps consacré à : s’occuper de ses enfants"
   coco2_q59_3 = "Temps consacré à : prendre soin de personnes fragiles ou vulnérables"
   coco2_q59_4 = "Temps consacré à : exercer son activité professionnelle"
   coco2_q59_5 = "Temps consacré à : faire des exercices physiques / du sport"
   coco2_q59_6 = "Temps consacré à : dormir"
   coco2_q59_7 = "Temps consacré à : parler au téléphone"
   coco2_q59_8 = "Temps consacré à : utiliser des réseaux sociaux"
   coco2_q59_9 = "Temps consacré à : regarder la télévision"
   coco2_q64 = "Stress lié au confinement"
   coco2_q68 = "Satisfaction quant à la manière dont le Gouvernement français gère l'épidémie du virus Covid-19"
   coco2_q79 = "Préoccupation par les conséquences sanitaires ou les conséquences économiques de l’épidémie du virus Covid-19"
   coco2_q92 = "Disposer d’un endroit calme"
   coco2_q93_1 = "Opinion: Confiner plus longtemps : les personnes âgées"
   coco2_q93_2 = "Opinion: Confiner plus longtemps les personnes souffrant d'une maladie chronique"
   coco2_q93_3 = "Opinion: Confiner plus longtemps les personnes vivant dans les régions les plus à risque"
   coco2_q93_4 = "Opinion: Confiner plus longtemps les personnes pas encore atteintes"
   coco2_q93_5 = "Opinion: Ne confiner plus longtemps personne"
   coco2_q94 = "Âge à partir duquel les personnes devraient continuer à être confinées"
   coco2_q95_1 = "Opinion : Fermer jusqu'à cet été au moins les écoles, collèges et lycées"
   coco2_q95_2 = "Opinion : Fermer jusqu'à cet été au moins les restaurants, bars, hôtels"
   coco2_q95_3 = "Opinion : Fermer jusqu'à cet été au moins les musées, théâtres, salles de spectacle"
   coco2_q95_4 = "Opinion : Fermer jusqu'à cet été au moins les entreprises des secteurs du bâtiment et des travaux publics"
   coco2_q95_5 = "Opinion : Fermer jusqu'à cet été au moins les aéroports"
   coco2_q95_6 = "Opinion : Ne fermer jusqu'à cet été au moins aucun de ces établissements"
   coco2_q96_1 = "Opinion : Maintenir pour une période transitoire la distanciation sociale"
   coco2_q96_2 = "Opinion : Maintenir pour une période transitoire des tests généralisés"
   coco2_q96_3 = "Opinion : Maintenir pour une période transitoire la fermeture des écoles"
   coco2_q96_4 = "Opinion : Maintenir pour une période transitoire la fermeture des frontières nationales"
   coco2_q96_5 = "Opinion : Maintenir pour une période transitoire l’interdiction des déplacements en France"
   coco2_q96_6 = "Opinion : Maintenir pour une période transitoire l’interdiction des rassemblements"
   coco2_q96_7 = "Opinion : Maintenir pour une période transitoire le port d’un masque dans l’espace public"
   coco2_q96_8 = "Opinion : Maintenir pour une période transitoire le télétravail"
   coco2_q96_9 = "Opinion : Ne maintenir pour une période transitoire aucune de ces mesures"
   coco2_q97 = "Opinion : Autoriser les voyages sous condition d’avoir un certificat médical"
   coco2_q98 = "Avis sur une production d'une application pour lutter contre l’épidémie"
   coco2_q99_1 = "Avis sur une application pour lutter contre la diffusion de l’épidémie : L'installer volontairement"
   coco2_q99_2 = "Avis sur une application pour lutter contre la diffusion de l’épidémie : Encourager les autres à l'installer"
   coco2_q99_3 = "Avis sur une application pour lutter contre la diffusion de l’épidémie : Devrait être rendue obligatoire pour tout le monde"
   coco2_Bloc2_DO_exp1_gpe = "Appartenance au groupe expérimental (exp1_gpe)"
   coco2_exp1_gpe_a = "Avis sur une suspension partielle du confinement (pas d'autres informations - exp. A)"
   coco2_exp1_gpe_b = "Avis sur une suspension partielle du confinement (informations sur l'impact économique négatif - exp. B)"
   coco2_q100 = "Intentions pour les 3 mois après la sortie de déconfinement : concernant les relations sociales"
   coco2_q101 = "Intentions pour les 3 mois après la sortie de déconfinement : concernant le travail"
   coco2_q102 = "Intentions pour les 6 mois après la sortie de déconfinement : concernant la consommation"
   coco2_q103_1 = "Nombre de voyages en 2019 : dans un autre département en France"
   coco2_q103_2 = "Nombre de voyages en 2019 : dans un autre pays de l'UE"
   coco2_q103_3 = "Nombre de voyages en 2019 : dans un autre pays hors UE"
   coco2_q104_1 = "Nombre de voyages de plus d'une semaine en 2019 : dans un autre département en France"
   coco2_q104_2 = "Nombre de voyages de plus d'une semaine en 2019 : dans un autre pays de l'UE"
   coco2_q104_3 = "Nombre de voyages de plus d'une semaine en 2019 : dans un autre pays hors UE"
   coco2_q105_1 = "Annulation des voyages en France à cause de Covid-19 : non, aucun voyage programmé en France"
   coco2_q105_2 = "Annulation des voyages en France à cause du virus Covid-19 : oui"
   coco2_q105_3 = "Annulation des voyages en France à cause du virus Covid-19 : non, voyage(s) en France confirmé(s)"
   coco2_q106_1 = "Annulation des voyages à l'international à cause du virus Covid-19 : non, aucun voyage programmé à l'international"
   coco2_q106_2 = "Annulation des voyages à l'international à cause du virus Covid-19 : oui"
   coco2_q106_3 = "Annulation des voyages à l'international à cause du virus Covid-19 : non, voyage(s) à l'international confirmé(s)"
   coco2_q107_1 = "Enfants dans le logement : non-scolarisés et de moins de 3 ans"
   coco2_q107_2 = "Enfants dans le logement : scolarisés à l’école maternelle"
   coco2_q107_3 = "Enfants dans le logement : scolarisés à l’école élémentaire"
   coco2_q107_4 = "Enfants dans le logement : scolarisés au collège"
   coco2_q107_5 = "Enfants dans le logement : scolarisés au lycée"
   coco2_q107_6 = "Enfants dans le logement : en enseignement supérieur"
   coco2_q107_7 = "Enfants dans le logement : non scolarisés, quelle que soit leur activité"
   coco2_q107_8 = "Enfants dans le logement : Aucun"
   coco2_q108_1_1 = "Nombre d'enfants dans le logement : non-scolarisés et de moins de 3 ans"
   coco2_q108_2_1 = "Nombre d'enfants dans le logement : scolarisés à l’école maternelle"
   coco2_q108_3_1 = "Nombre d'enfants dans le logement : scolarisés à l’école élémentaire"
   coco2_q108_4_1 = "Nombre d'enfants dans le logement : scolarisés au collège"
   coco2_q108_5_1 = "Nombre d'enfants dans le logement : scolarisés au lycée"
   coco2_q108_6_1 = "Nombre d'enfants dans le logement : en enseignement supérieur"
   coco2_q108_7_1 = "Nombre d'enfants dans le logement : non scolarisés, quel que soit leur activité,"
   coco2_q109_1 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à consulter des sites éducatifs ou utiliser des logiciels éducatifs"
   coco2_q109_2 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à faire du tchat ou des rencontres par visio avec ses amis"
   coco2_q109_3 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à faire du dessin ou du bricolage"
   coco2_q109_4 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à faire les devoirs"
   coco2_q109_5 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à faire de la musique ou du chant"
   coco2_q109_6 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à faire du sport"
   coco2_q109_7 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à jouer"
   coco2_q109_8 = "Temps consacré par l’enfant le plus jeune, par rapport à d’habitude : à regarder la télévision"
   coco2_q110_1 = "Fréquence d'enseignement aux enfants : le(la) conjoint(e)"
   coco2_q110_2 = "Fréquence d'enseignement aux enfants : une autre personne"
   coco2_q110_3 = "Fréquence d'enseigner les enfants : les enfants travaillent de manière autonome"
   coco2_q111_1 = "Avis sur la classe à la maison : C’est une expérience qui m’a rapproché des enfants"
   coco2_q111_2 = "Avis sur la classe à la maison : A permis de se faire une meilleure idée des besoins scolaires"
   coco2_q111_3 = "Avis sur la classe à la maison : M'a stressé"
   coco2_q111_4 = "Avis sur la classe à la maison : A stressé les enfants"
   coco2_q111_5 = "Avis sur la classe à la maison : A détérioré son rapport avec les enfants à la maison"
   coco2_q111_6 = "Avis sur la classe à la maison : A permis de mieux gérer les enfants à la maison"
   coco2_q112_1 = "S’est occupé des enfants (hors classe à la maison) : interviewé"
   coco2_q112_2 = "S’est occupé des enfants (hors classe à la maison) : le(la) conjoint(e)"
   coco2_q112_3 = "S’est occupé des enfants (hors classe à la maison) : Une autre personne"
   coco2_SWB = "Niveau de bien-être subjectif"
   ea17_SWB = "Index de bien-être subjectif (calcul EA17)"
   ea18_SWB = "Index de bien-être subjectif (calcul EA18)"
   ea19_SWB = "Index de bien-être subjectif (calcul EA19)"
   eayy_A1 = "Sexe (enquête annuelle)"
   eayy_A2A_rec = "Age quinquennal (recodage)"
   eayy_A3_rec = "A la nationalité francaise (recodage)"
   eayy_A3B_rec = "Pays de naissance (recodage)"
   eayy_A3C_rec = "Nationalité (recodage)"
   eayy_A3D = "A une seconde nationalité"
   eayy_A3E_rec = "Seconde nationalité (recodage)"
   eayy_A4 = "Statut matrimonial légal"
   eayy_A5 = "Vit en couple"
   eayy_A5A = "Situation familiale"
   eayy_A5C = "Ancienneté du couple"
   eayy_A5C_rec = "Ancienneté du couple (recodage)"
   eayy_B1 = "Situation principale vis-à-vis du travail"
   eayy_B10A = "Recherche d'emploi"
   eayy_B10AA = "Rercherche un autre emploi"
   eayy_B10ACJT = "Recherche d'emploi (conjoint)"
   eayy_B11 = "Ne travaille pas mais a déjà travaillé"
   eayy_B11CJT = "Ne travaille pas mais a déjà travaillé (conjoint)"
   eayy_B18_rec = "Diplôme le plus élevé (recodage)"
   eayy_B18C = "Niveau de formation (recodage)"
   eayy_B18CCJT = "Niveau de formation (conjoint) (calcul)"
   eayy_B18CJT_rec = "Diplôme le plus élevé (conjoint) (recodage)"
   eayy_B1A = "Emploi (étudiant, chômeur, retraité, autre inactif)"
   eayy_B1ACJT = "Emploi (étudiant, chômeur, retraité, autre inactif) (conjoint)"
   eayy_B1B = "Exercice d'une activité professionnelle (recodage)"
   eayy_B1BCJT = "Exercice d'une activité professionnelle (conjoint) (calcul)"
   eayy_B1CJT = "Situation principale vis-à-vis du travail (conjoint)"
   eayy_B2_rec = "Statut de l'activité actuelle ou antérieure (recodage)"
   eayy_B25 = "Supervision d'autres salariés"
   eayy_B2CJT_rec = "Statut de l'activité actuelle ou antérieure (conjoint) (calcul)"
   eayy_B4_rec = "Nombre de salariés employés actuellement ou par le passé (recodage)"
   eayy_B4CJT_rec = "Nombre de salariés employés actuellement ou par le passé (conjoint) (calcul)"
   eayy_B5_rec = "Type de contrat de travail (recodage)"
   eayy_B5A = "Temps de travail"
   eayy_B5B_rec = "Type de temps partiel (recodage)"
   eayy_B5C = "Raison principale du travail à temps partiel"
   eayy_B6A_rec = "Catégorie de l'emploi actuel ou antérieur secteur privé (recodage)"
   eayy_B6B_rec = "Catégorie de l'emploi actuel ou antérieur secteur public (recodage)"
   eayy_B7B_rec = "Fonction principale de l'emploi actuel ou antérieur (recodage)"
   eayy_B8_rec = "Nombre de salariés dans l'entreprise de l'emploi actuel ou antérieur (recodage)"
   eayy_B9_rec = "Superficie de l'exploitation actuelle ou antérieure (recodage)"
   eayy_C1_rec = "Nombre de personnes dans le foyer (recodage)"
   eayy_C1JEU = "Nombre de jeunes (calcul)"
   eayy_C8 = "A des enfants"
   eayy_C8A_rec = "Nombre d'enfants (recodage)"
   eayy_C8B_rec = "Nombre d'enfants cohabitants (recodage)"
   eayy_D1_rec = "Statut d'occupation du logement (recodage)"
   eayy_D1A = "Appartenance du logement à un organisme HLM"
   eayy_D2 = "Propriétaire du logement"
   eayy_D3 = "Type d'habitation"
   eayy_D4_rec = "Nombre pièces d'habitation du logement (recodage)"
   eayy_D5_rec = "Année d'emménagement dans le logement (calcul)"
   eayy_D6 = "Type d'habitat au voisinage du logement"
   eayy_D7_1 = "Problèmes concernant le quartier : terrains-vagues, locaux désaffectés, friches industrielles, logements insalubres"
   eayy_D7_10 = "Problèmes concernant le quartier : aucun de ces problèmes"
   eayy_D7_2 = "Problèmes concernant le quartier : bruits ou pollution"
   eayy_D7_3 = "Problèmes concernant le quartier : voirie insuffisante"
   eayy_D7_4 = "Problèmes concernant le quartier : saleté"
   eayy_D7_5 = "Problèmes concernant le quartier : manque d'espaces verts"
   eayy_D7_6 = "Problèmes concernant le quartier : manque de commerces"
   eayy_D7_7 = "Problèmes concernant le quartier : manque de lieux de rencontre, d'équipements"
   eayy_D7_8 = "Problèmes concernant le quartier : isolement du quartier"
   eayy_D7_9 = "Problèmes concernant le quartier : manque de sécurité"
   eayy_E1A = "Personnes dans le ménage percevant : salaires, traitements et primes"
   eayy_E1B = "Personnes dans le ménage percevant : revenus d'une activité professionnelle non salariée"
   eayy_E1C = "Personnes dans le ménage percevant : allocations de chômage"
   eayy_E1D = "Personnes dans le ménage percevant : préretraites, retraites"
   eayy_E1E = "Personnes dans le ménage percevant : prestations liées à la maladie ou l'invalidité"
   eayy_E1F = "Personnes dans le ménage percevant : prestations familiales et bourses"
   eayy_E1G = "Personnes dans le ménage percevant : allocation logement, aide au logement"
   eayy_E1H = "Personnes dans le ménage percevant : RSA"
   eayy_E1I = "Personnes dans le ménage percevant : loyers et fermages"
   eayy_E1J = "Personnes dans le ménage percevant : pensions, aides"
   eayy_E2A_rec = "Tranche de montant des ressources (calcul)"
   eayy_E2AUC = "Tranche de revenu mensuel du ménage par unité de consommation (calcul)"
   eayy_E2AUC_SOURCE = "Source d'information du montant des ressources par unité de consommation"
   eayy_E3A = "Détention placements financiers : livrets d'épargne"
   eayy_E3B = "Détention placements financiers : épargne-logement"
   eayy_E3C = "Détention placements financiers : assurances-vies"
   eayy_E3D = "Détention placements financiers : épargne retraite"
   eayy_E3E = "Détention placements financiers : valeurs immobilières"
   eayy_E4 = "Résidence secondaire"
   eayy_E5 = "Situation financière actuelle du ménage"
   eayy_E5A = "Baisse de revenu importante les 12 derniers mois"
   eayy_E5B_1 = "Baisse de revenu importante les 12 derniers mois : licenciement/perte d'emploi"
   eayy_E5B_2 = "Baisse de revenu importante les 12 derniers mois : modification du salaire/ des heures"
   eayy_E5B_3 = "Baisse de revenu importante les 12 derniers mois : invalidité/incapacité"
   eayy_E5B_4 = "Baisse de revenu importante les 12 derniers mois : maternité/congé parental/garde des enfants"
   eayy_E5B_5 = "Baisse de revenu importante les 12 derniers mois : départ à la retraite"
   eayy_E5B_6 = "Baisse de revenu importante les 12 derniers mois : mariage/rupture"
   eayy_E5B_7 = "Baisse de revenu importante les 12 derniers mois : décès"
   eayy_E5B_8 = "Baisse de revenu importante les 12 derniers mois : autre changement dans le ménage"
   eayy_E5B_9 = "Baisse de revenu importante les 12 derniers mois: autre raison"
   eayy_F1_rec = "Fréquence de rencontre des amis (recodage)"
   eayy_F3 = "A quelqu'un pour discuter de questions intimes et personnelles"
   eayy_F4 = "Sentiment de solitude"
   eayy_F5 = "Opinion confiance ou prudence en général"
   eayy_F6_rec = "Fréquence de rencontre de la famille (recodage)"
   eayy_F7 = "Membre association humanitaire ou sociale"
   eayy_F8 = "Membre amicale ou association sportive ou culturelle"
   eayy_G1 = "Télévision les 12 derniers mois"
   eayy_G2 = "Nombre de livres lus les 12 derniers mois"
   eayy_G3A = "Sortie culturelle les 12 derniers mois : au cinéma"
   eayy_G3B = "Sortie culturelle les 12 derniers mois : au théâtre ou au concert"
   eayy_G3C = "Sortie culturelle les 12 derniers mois : au musée ou une exposition"
   eayy_G4 = "Bricolage les 12 derniers mois"
   eayy_G5 = "Maîtrise d'une langue étrangère"
   eayy_G6_1 = "Partir en vacances les 12 derniers mois : non"
   eayy_G6_2 = "Partir en vacances les 12 derniers mois : dans la région"
   eayy_G6_3 = "Partir en vacances les 12 derniers mois : dans une autre région"
   eayy_G6_4 = "Partir en vacances les 12 derniers mois : à l'étranger"
   eayy_H1A = "A une religion (recodage)"
   eayy_H2 = "Importance de la religion"
   eayy_H4 = "Éducation religieuse"
   eayy_I1 = "Intérêt pour la politique"
   eayy_I8 = "Auto-positionnement sur l'échelle gauche/droite"
   eayy_J1 = "État de santé"
   eayy_K3 = "Fréquence activité sportive 30 minutes d'affilée"
   eayy_PCS18 = "Catégorie socioprofessionnelle en 18 postes (profession actuelle ou dernière profession)"
   eayy_PCS6 = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession)"
   eayy_PCS6CJT = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession) (conjoint)"
   eayy_TYPMEN5 = "Type de ménage (calcul)"
   VAGUE = "VAGUE"
   insee_NUTS1 = "Nomenclature des unités territoriales statistiques niv. 1"
   insee_CATAEU2010 = "Catégorie de la commune dans le zonage en aires urbaines 2010"
   insee_TAU2014 = "Tranche d'aire urbaine 2014"
   insee_TUU2014 = "Tranche d'unité urbaine 2014"
   coco2_POIDS = "Poids individu"
   coco2_PDSPLT = "Poids individu (pilote)"
   coco2_cal_NAT = "Nationalité (calage)"
   coco2_POIDS_INIT = "Poids initial"
   coco2_PDSPLT_INIT = "Poids initial (pilote)" ;

 /* User Missing Value Specifications */
  IF coco2_q04 = 9999 THEN coco2_q04 =. ;
  IF coco2_q06_1 = 9999 THEN coco2_q06_1 =. ;
  IF coco2_q06_2 = 9999 THEN coco2_q06_2 =. ;
  IF coco2_q06_3 = 9999 THEN coco2_q06_3 =. ;
  IF coco2_q06_4 = 9999 THEN coco2_q06_4 =. ;
  IF coco2_q06_5 = 9999 THEN coco2_q06_5 =. ;
  IF coco2_q06_6 = 9999 THEN coco2_q06_6 =. ;
  IF coco2_q06_7 = 9999 THEN coco2_q06_7 =. ;
  IF coco2_q06_8 = 9999 THEN coco2_q06_8 =. ;
  IF coco2_q06_9 = 9999 THEN coco2_q06_9 =. ;
  IF coco2_q06_10 = 9999 THEN coco2_q06_10 =. ;
  IF coco2_q09 = 9999 THEN coco2_q09 =. ;
  IF coco2_q10 = 6666 THEN coco2_q10 =. ;
  IF coco2_q17 = 9999 THEN coco2_q17 =. ;
  IF coco2_q18 = 9999 THEN coco2_q18 =. ;
  IF coco2_q19 = 9999 THEN coco2_q19 =. ;
  IF coco2_q20 = 9999 THEN coco2_q20 =. ;
  IF coco2_q21 = 9999 THEN coco2_q21 =. ;
  IF coco2_q38_modifie = 9999 THEN coco2_q38_modifie =. ;
  IF coco2_q47 = 9999 THEN coco2_q47 =. ;
  IF coco2_q51 = 9999 THEN coco2_q51 =. ;
  IF coco2_q52_1 = 9999 THEN coco2_q52_1 =. ;
  IF coco2_q52_2 = 9999 THEN coco2_q52_2 =. ;
  IF coco2_q52_3 = 9999 THEN coco2_q52_3 =. ;
  IF coco2_q52_4 = 9999 THEN coco2_q52_4 =. ;
  IF coco2_q53_1 = 9999 THEN coco2_q53_1 =. ;
  IF coco2_q53_2 = 9999 THEN coco2_q53_2 =. ;
  IF coco2_q53_3 = 9999 THEN coco2_q53_3 =. ;
  IF coco2_q54_1 = 9999 THEN coco2_q54_1 =. ;
  IF coco2_q54_2 = 9999 THEN coco2_q54_2 =. ;
  IF coco2_q54_3 = 9999 THEN coco2_q54_3 =. ;
  IF coco2_q54_4 = 9999 THEN coco2_q54_4 =. ;
  IF coco2_q54_5 = 9999 THEN coco2_q54_5 =. ;
  IF coco2_q54_6 = 9999 THEN coco2_q54_6 =. ;
  IF coco2_q54_7 = 9999 THEN coco2_q54_7 =. ;
  IF coco2_q54_8 = 9999 THEN coco2_q54_8 =. ;
  IF coco2_q54_bis_1 = 9999 THEN coco2_q54_bis_1 =. ;
  IF coco2_q54_bis_2 = 9999 THEN coco2_q54_bis_2 =. ;
  IF coco2_q54_bis_3 = 9999 THEN coco2_q54_bis_3 =. ;
  IF coco2_q54_bis_4 = 9999 THEN coco2_q54_bis_4 =. ;
  IF coco2_q54_bis_5 = 9999 THEN coco2_q54_bis_5 =. ;
  IF coco2_q54_bis_6 = 9999 THEN coco2_q54_bis_6 =. ;
  IF coco2_q54_bis_7 = 9999 THEN coco2_q54_bis_7 =. ;
  IF coco2_q59_1 = 9999 THEN coco2_q59_1 =. ;
  IF coco2_q59_2 = 9999 THEN coco2_q59_2 =. ;
  IF coco2_q59_3 = 9999 THEN coco2_q59_3 =. ;
  IF coco2_q59_4 = 9999 THEN coco2_q59_4 =. ;
  IF coco2_q59_5 = 9999 THEN coco2_q59_5 =. ;
  IF coco2_q59_6 = 9999 THEN coco2_q59_6 =. ;
  IF coco2_q59_7 = 9999 THEN coco2_q59_7 =. ;
  IF coco2_q59_8 = 9999 THEN coco2_q59_8 =. ;
  IF coco2_q59_9 = 9999 THEN coco2_q59_9 =. ;
  IF coco2_q64 = 9999 THEN coco2_q64 =. ;
  IF coco2_q68 = 9999 THEN coco2_q68 =. ;
  IF coco2_q79 = 9999 THEN coco2_q79 =. ;
  IF coco2_q92 = 9999 OR coco2_q92 = 6666 THEN coco2_q92 =. ;
  IF coco2_q93_1 = 9999 THEN coco2_q93_1 =. ;
  IF coco2_q93_2 = 9999 THEN coco2_q93_2 =. ;
  IF coco2_q93_3 = 9999 THEN coco2_q93_3 =. ;
  IF coco2_q93_4 = 9999 THEN coco2_q93_4 =. ;
  IF coco2_q93_5 = 9999 THEN coco2_q93_5 =. ;
  IF coco2_q94 = 9999 OR coco2_q94 = 6666 THEN coco2_q94 =. ;
  IF coco2_q95_1 = 9999 THEN coco2_q95_1 =. ;
  IF coco2_q95_2 = 9999 THEN coco2_q95_2 =. ;
  IF coco2_q95_3 = 9999 THEN coco2_q95_3 =. ;
  IF coco2_q95_4 = 9999 THEN coco2_q95_4 =. ;
  IF coco2_q95_5 = 9999 THEN coco2_q95_5 =. ;
  IF coco2_q95_6 = 9999 THEN coco2_q95_6 =. ;
  IF coco2_q96_1 = 9999 THEN coco2_q96_1 =. ;
  IF coco2_q96_2 = 9999 THEN coco2_q96_2 =. ;
  IF coco2_q96_3 = 9999 THEN coco2_q96_3 =. ;
  IF coco2_q96_4 = 9999 THEN coco2_q96_4 =. ;
  IF coco2_q96_5 = 9999 THEN coco2_q96_5 =. ;
  IF coco2_q96_6 = 9999 THEN coco2_q96_6 =. ;
  IF coco2_q96_7 = 9999 THEN coco2_q96_7 =. ;
  IF coco2_q96_8 = 9999 THEN coco2_q96_8 =. ;
  IF coco2_q96_9 = 9999 THEN coco2_q96_9 =. ;
  IF coco2_q97 = 9999 THEN coco2_q97 =. ;
  IF coco2_q98 = 9999 THEN coco2_q98 =. ;
  IF coco2_q99_1 = 9999 THEN coco2_q99_1 =. ;
  IF coco2_q99_2 = 9999 THEN coco2_q99_2 =. ;
  IF coco2_q99_3 = 9999 THEN coco2_q99_3 =. ;
  IF coco2_exp1_gpe_a = 6666 OR coco2_exp1_gpe_a = 9999 THEN coco2_exp1_gpe_a =. ;
  IF coco2_exp1_gpe_b = 6666 OR coco2_exp1_gpe_b = 9999 THEN coco2_exp1_gpe_b =. ;
  IF coco2_q100 = 9999 THEN coco2_q100 =. ;
  IF coco2_q101 = 9999 THEN coco2_q101 =. ;
  IF coco2_q102 = 9999 THEN coco2_q102 =. ;
  IF coco2_q103_1 = 9999 THEN coco2_q103_1 =. ;
  IF coco2_q103_2 = 9999 THEN coco2_q103_2 =. ;
  IF coco2_q103_3 = 9999 THEN coco2_q103_3 =. ;
  IF coco2_q104_1 = 6666 OR coco2_q104_1 = 9999 THEN coco2_q104_1 =. ;
  IF coco2_q104_2 = 6666 OR coco2_q104_2 = 9999 THEN coco2_q104_2 =. ;
  IF coco2_q104_3 = 6666 OR coco2_q104_3 = 9999 THEN coco2_q104_3 =. ;
  IF coco2_q105_1 = 9999 THEN coco2_q105_1 =. ;
  IF coco2_q105_2 = 9999 THEN coco2_q105_2 =. ;
  IF coco2_q105_3 = 9999 THEN coco2_q105_3 =. ;
  IF coco2_q106_1 = 9999 THEN coco2_q106_1 =. ;
  IF coco2_q106_2 = 9999 THEN coco2_q106_2 =. ;
  IF coco2_q106_3 = 9999 THEN coco2_q106_3 =. ;
  IF coco2_q107_1 = 9999 THEN coco2_q107_1 =. ;
  IF coco2_q107_2 = 9999 THEN coco2_q107_2 =. ;
  IF coco2_q107_3 = 9999 THEN coco2_q107_3 =. ;
  IF coco2_q107_4 = 9999 THEN coco2_q107_4 =. ;
  IF coco2_q107_5 = 9999 THEN coco2_q107_5 =. ;
  IF coco2_q107_6 = 9999 THEN coco2_q107_6 =. ;
  IF coco2_q107_7 = 9999 THEN coco2_q107_7 =. ;
  IF coco2_q107_8 = 9999 THEN coco2_q107_8 =. ;
  IF coco2_q108_1_1 = 6666 THEN coco2_q108_1_1 =. ;
  IF coco2_q108_2_1 = 6666 THEN coco2_q108_2_1 =. ;
  IF coco2_q108_3_1 = 6666 THEN coco2_q108_3_1 =. ;
  IF coco2_q108_4_1 = 6666 THEN coco2_q108_4_1 =. ;
  IF coco2_q108_5_1 = 6666 THEN coco2_q108_5_1 =. ;
  IF coco2_q108_6_1 = 6666 THEN coco2_q108_6_1 =. ;
  IF coco2_q108_7_1 = 6666 THEN coco2_q108_7_1 =. ;
  IF coco2_q109_1 = 9999 OR coco2_q109_1 = 6666 THEN coco2_q109_1 =. ;
  IF coco2_q109_2 >= 6666 THEN coco2_q109_2 =. ;
  IF coco2_q109_3 >= 6666 THEN coco2_q109_3 =. ;
  IF coco2_q109_4 >= 6666 THEN coco2_q109_4 =. ;
  IF coco2_q109_5 >= 6666 THEN coco2_q109_5 =. ;
  IF coco2_q109_6 >= 6666 THEN coco2_q109_6 =. ;
  IF coco2_q109_7 >= 6666 THEN coco2_q109_7 =. ;
  IF coco2_q109_8 >= 6666 THEN coco2_q109_8 =. ;
  IF coco2_q110_1 >= 6666 THEN coco2_q110_1 =. ;
  IF coco2_q110_2 >= 6666 THEN coco2_q110_2 =. ;
  IF coco2_q110_3 >= 6666 THEN coco2_q110_3 =. ;
  IF coco2_q111_1 >= 6666 THEN coco2_q111_1 =. ;
  IF coco2_q111_2 >= 6666 THEN coco2_q111_2 =. ;
  IF coco2_q111_3 >= 6666 THEN coco2_q111_3 =. ;
  IF coco2_q111_4 >= 6666 THEN coco2_q111_4 =. ;
  IF coco2_q111_5 >= 6666 THEN coco2_q111_5 =. ;
  IF coco2_q111_6 >= 6666 THEN coco2_q111_6 =. ;
  IF coco2_q112_1 >= 6666 THEN coco2_q112_1 =. ;
  IF coco2_q112_2 >= 6666 THEN coco2_q112_2 =. ;
  IF coco2_q112_3 >= 6666 THEN coco2_q112_3 =. ;
  IF eayy_A3_rec >= 7 THEN eayy_A3_rec =. ;
  IF eayy_A3B_rec >= 9 THEN eayy_A3B_rec =. ;
  IF eayy_A3C_rec >= 6 THEN eayy_A3C_rec =. ;
  IF eayy_A3D >= 6 THEN eayy_A3D =. ;
  IF eayy_A3E_rec >= 6 THEN eayy_A3E_rec =. ;
  IF eayy_A4 >= 77 THEN eayy_A4 =. ;
  IF eayy_A5 >= 7 THEN eayy_A5 =. ;
  IF eayy_A5A >= 6 OR eayy_A5A = 9996 THEN eayy_A5A =. ;
  IF eayy_A5C >= 6 OR eayy_A5C = 9996 THEN eayy_A5C =. ;
  IF eayy_A5C_rec >= 66 OR eayy_A5C_rec = 9996 THEN eayy_A5C_rec =. ;
  IF eayy_B1 >= 77 THEN eayy_B1 =. ;
  IF eayy_B10A >= 6 THEN eayy_B10A =. ;
  IF eayy_B10AA >= 6 OR eayy_B10AA = 9996 THEN eayy_B10AA =. ;
  IF eayy_B10ACJT >= 6 THEN eayy_B10ACJT =. ;
  IF eayy_B11 >= 6 THEN eayy_B11 =. ;
  IF eayy_B11CJT >= 6 THEN eayy_B11CJT =. ;
  IF eayy_B18_rec >= 77 THEN eayy_B18_rec =. ;
  IF eayy_B18C >= 7 THEN eayy_B18C =. ;
  IF eayy_B18CCJT >= 6 THEN eayy_B18CCJT =. ;
  IF eayy_B18CJT_rec >= 66 THEN eayy_B18CJT_rec =. ;
  IF eayy_B1A >= 6 OR eayy_B1A = 9996 THEN eayy_B1A =. ;
  IF eayy_B1ACJT >= 6 OR eayy_B1ACJT = 9996 THEN eayy_B1ACJT =. ;
  IF eayy_B1B >= 7 THEN eayy_B1B =. ;
  IF eayy_B1BCJT >= 6 THEN eayy_B1BCJT =. ;
  IF eayy_B1CJT >= 66 THEN eayy_B1CJT =. ;
  IF eayy_B2_rec >= 66 THEN eayy_B2_rec =. ;
  IF eayy_B25 >= 6 THEN eayy_B25 =. ;
  IF eayy_B2CJT_rec >= 66 THEN eayy_B2CJT_rec =. ;
  IF eayy_B4_rec >= 6 THEN eayy_B4_rec =. ;
  IF eayy_B4CJT_rec >= 6 THEN eayy_B4CJT_rec =. ;
  IF eayy_B5_rec >= 6 THEN eayy_B5_rec =. ;
  IF eayy_B5A >= 6 THEN eayy_B5A =. ;
  IF eayy_B5B_rec >= 6 THEN eayy_B5B_rec =. ;
  IF eayy_B5C >= 66 THEN eayy_B5C =. ;
  IF eayy_B6A_rec >= 66 THEN eayy_B6A_rec =. ;
  IF eayy_B6B_rec >= 66 THEN eayy_B6B_rec =. ;
  IF eayy_B7B_rec >= 66 THEN eayy_B7B_rec =. ;
  IF eayy_B8_rec >= 6 THEN eayy_B8_rec =. ;
  IF eayy_B9_rec >= 6 THEN eayy_B9_rec =. ;
  IF eayy_C1JEU >= 9 THEN eayy_C1JEU =. ;
  IF eayy_C8 >= 7 OR eayy_C8 = 9996 THEN eayy_C8 =. ;
  IF eayy_C8A_rec >= 6 OR eayy_C8A_rec = 9996 THEN eayy_C8A_rec =. ;
  IF eayy_C8B_rec >= 6 OR eayy_C8B_rec = 9996 THEN eayy_C8B_rec =. ;
  IF eayy_D1_rec >= 7 THEN eayy_D1_rec =. ;
  IF eayy_D1A >= 6 OR eayy_D1A = 9996 THEN eayy_D1A =. ;
  IF eayy_D2 >= 66 THEN eayy_D2 =. ;
  IF eayy_D4_rec >= 99 THEN eayy_D4_rec =. ;
  IF eayy_D5_rec >= 9 THEN eayy_D5_rec =. ;
  IF eayy_D6 >= 9 THEN eayy_D6 =. ;
  IF eayy_D7_1 >= 9 THEN eayy_D7_1 =. ;
  IF eayy_D7_10 >= 9 THEN eayy_D7_10 =. ;
  IF eayy_D7_2 >= 9 THEN eayy_D7_2 =. ;
  IF eayy_D7_3 >= 9 THEN eayy_D7_3 =. ;
  IF eayy_D7_4 >= 9 THEN eayy_D7_4 =. ;
  IF eayy_D7_5 >= 9 THEN eayy_D7_5 =. ;
  IF eayy_D7_6 >= 9 THEN eayy_D7_6 =. ;
  IF eayy_D7_7 >= 9 THEN eayy_D7_7 =. ;
  IF eayy_D7_8 >= 9 THEN eayy_D7_8 =. ;
  IF eayy_D7_9 >= 9 THEN eayy_D7_9 =. ;
  IF eayy_E2A_rec >= 77 THEN eayy_E2A_rec =. ;
  IF eayy_E2AUC >= 66 THEN eayy_E2AUC =. ;
  IF eayy_E3A = 9996 THEN eayy_E3A =. ;
  IF eayy_E3B = 9996 THEN eayy_E3B =. ;
  IF eayy_E3C = 9996 THEN eayy_E3C =. ;
  IF eayy_E3D = 9996 THEN eayy_E3D =. ;
  IF eayy_E3E = 9996 THEN eayy_E3E =. ;
  IF eayy_E4 >= 7 OR eayy_E4 = 9996 THEN eayy_E4 =. ;
  IF eayy_E5 >= 99 THEN eayy_E5 =. ;
  IF eayy_E5A >= 9 OR eayy_E5A = 9996 THEN eayy_E5A =. ;
  IF eayy_E5B_1 >= 6 THEN eayy_E5B_1 =. ;
  IF eayy_E5B_2 >= 6 THEN eayy_E5B_2 =. ;
  IF eayy_E5B_3 >= 6 THEN eayy_E5B_3 =. ;
  IF eayy_E5B_4 >= 6 THEN eayy_E5B_4 =. ;
  IF eayy_E5B_5 >= 6 THEN eayy_E5B_5 =. ;
  IF eayy_E5B_6 >= 6 THEN eayy_E5B_6 =. ;
  IF eayy_E5B_7 >= 6 THEN eayy_E5B_7 =. ;
  IF eayy_E5B_8 >= 6 THEN eayy_E5B_8 =. ;
  IF eayy_E5B_9 >= 6 OR eayy_E5B_9 = 9996 THEN eayy_E5B_9 =. ;
  IF eayy_F1_rec >= 7 THEN eayy_F1_rec =. ;
  IF eayy_F3 >= 8 THEN eayy_F3 =. ;
  IF eayy_F4 >= 7 OR eayy_F4 = 9996 THEN eayy_F4 =. ;
  IF eayy_F5 >= 7 OR eayy_F5 = 9996 THEN eayy_F5 =. ;
  IF eayy_F6_rec >= 7 THEN eayy_F6_rec =. ;
  IF eayy_F7 >= 7 THEN eayy_F7 =. ;
  IF eayy_F8 >= 7 THEN eayy_F8 =. ;
  IF eayy_G1 >= 8 THEN eayy_G1 =. ;
  IF eayy_G2 >= 8 THEN eayy_G2 =. ;
  IF eayy_G3A >= 9 THEN eayy_G3A =. ;
  IF eayy_G3B >= 9 THEN eayy_G3B =. ;
  IF eayy_G3C >= 9 THEN eayy_G3C =. ;
  IF eayy_G4 >= 8 THEN eayy_G4 =. ;
  IF eayy_G5 >= 9 THEN eayy_G5 =. ;
  IF eayy_G6_1 >= 9 THEN eayy_G6_1 =. ;
  IF eayy_G6_2 >= 9 THEN eayy_G6_2 =. ;
  IF eayy_G6_3 >= 9 THEN eayy_G6_3 =. ;
  IF eayy_G6_4 >= 9 THEN eayy_G6_4 =. ;
  IF eayy_H1A >= 7 THEN eayy_H1A =. ;
  IF eayy_H2 >= 7 THEN eayy_H2 =. ;
  IF eayy_H4 >= 7 THEN eayy_H4 =. ;
  IF eayy_I1 >= 8 THEN eayy_I1 =. ;
  IF eayy_I8 >= 77 THEN eayy_I8 =. ;
  IF eayy_J1 >= 7 THEN eayy_J1 =. ;
  IF eayy_K3 >= 9 THEN eayy_K3 =. ;
  IF eayy_PCS18 >= 666 THEN eayy_PCS18 =. ;
  IF eayy_PCS6 >= 66 THEN eayy_PCS6 =. ;
  IF eayy_PCS6CJT >= 66 THEN eayy_PCS6CJT =. ;
  IF eayy_TYPMEN5 >= 6 THEN eayy_TYPMEN5 =. ;
  IF insee_NUTS1 >= 99 THEN insee_NUTS1 =. ;
  IF insee_CATAEU2010 >= 999 THEN insee_CATAEU2010 =. ;
  IF insee_TAU2014 >= 99 THEN insee_TAU2014 =. ;
  IF insee_TUU2014 >= 9 THEN insee_TUU2014 =. ;

FORMAT
   coco2_cal_SEXE COCO2_CA.   coco2_cal_AGE1 COCO2__A.   coco2_cal_AGE2 COCO2__B.
   coco2_cal_DIPL COCO2__C.   coco2_cal_ZEAT COCO2__D.   coco2_q04 COCO2_Q0F.  
   coco2_q06_1 LABA.        coco2_q06_2 LABA.        coco2_q06_3 LABA.     
   coco2_q06_4 LABA.        coco2_q06_5 LABA.        coco2_q06_6 LABA.     
   coco2_q06_7 LABA.        coco2_q06_8 LABA.        coco2_q06_9 LABA.     
   coco2_q06_10 LABA.       coco2_q07_1 LABB.        coco2_q07_2 LABB.     
   coco2_q07_3 LABB.        coco2_q09 COCO2__R.      coco2_q10 COCO2_Q1F.  
   coco2_q16 COCO2__S.      coco2_q17 LABC.          coco2_q18 LABC.       
   coco2_q19 LABC.          coco2_q20 LABC.          coco2_q21 COCO2__W.   
   coco2_q25_a COCO2__X.    coco2_q38_modifie COCO2_Q3F.   coco2_q47 COCO2_Q4F.  
   coco2_q51 LABD.          coco2_q52_1 LABE.        coco2_q52_2 LABE.     
   coco2_q52_3 LABE.        coco2_q52_4 LABE.        coco2_q53_1 LABF.     
   coco2_q53_2 LABF.        coco2_q53_3 LABF.        coco2_q54_1 LABA.     
   coco2_q54_2 LABA.        coco2_q54_3 LABA.        coco2_q54_4 LABA.     
   coco2_q54_5 LABA.        coco2_q54_6 LABA.        coco2_q54_7 LABA.     
   coco2_q54_8 LABA.        coco2_q54_bis_1 LABA.    coco2_q54_bis_2 LABA. 
   coco2_q54_bis_3 LABA.    coco2_q54_bis_4 LABA.    coco2_q54_bis_5 LABA. 
   coco2_q54_bis_6 LABA.    coco2_q54_bis_7 LABA.    coco2_q59_1 LABG.     
   coco2_q59_2 LABG.        coco2_q59_3 LABG.        coco2_q59_4 LABG.     
   coco2_q59_5 LABG.        coco2_q59_6 LABG.        coco2_q59_7 LABG.     
   coco2_q59_8 LABG.        coco2_q59_9 LABG.        coco2_q64 COCO2_Q6F.  
   coco2_q68 COCO2_BD.      coco2_q79 COCO2_Q7F.     coco2_q92 COCO2_Q9F.  
   coco2_q93_1 LABA.        coco2_q93_2 LABA.        coco2_q93_3 LABA.     
   coco2_q93_4 LABA.        coco2_q93_5 LABA.        coco2_q95_1 LABA.     
   coco2_q95_2 LABA.        coco2_q95_3 LABA.        coco2_q95_4 LABA.     
   coco2_q95_5 LABA.        coco2_q95_6 LABA.        coco2_q96_1 LABA.     
   coco2_q96_2 LABA.        coco2_q96_3 LABA.        coco2_q96_4 LABA.     
   coco2_q96_5 LABA.        coco2_q96_6 LABA.        coco2_q96_7 LABA.     
   coco2_q96_8 LABA.        coco2_q96_9 LABA.        coco2_q97 COCO2_CB.   
   coco2_q98 COCO2_CC.      coco2_q99_1 LABH.        coco2_q99_2 LABH.     
   coco2_q99_3 LABH.        coco2_Bloc2_DO_exp1_gpe COCO2_BL.   coco2_exp1_gpe_a LABI.
   coco2_exp1_gpe_b LABI.   coco2_q100 COCO2_CH.     coco2_q101 COCO2_CI.  
   coco2_q102 COCO2_CJ.     coco2_q103_1 LABJ.       coco2_q103_2 LABJ.    
   coco2_q103_3 LABJ.       coco2_q104_1 LABK.       coco2_q104_2 LABK.    
   coco2_q104_3 LABK.       coco2_q105_1 LABA.       coco2_q105_2 LABA.    
   coco2_q105_3 LABA.       coco2_q106_1 LABA.       coco2_q106_2 LABA.    
   coco2_q106_3 LABA.       coco2_q107_1 LABA.       coco2_q107_2 LABA.    
   coco2_q107_3 LABA.       coco2_q107_4 LABA.       coco2_q107_5 LABA.    
   coco2_q107_6 LABA.       coco2_q107_7 LABA.       coco2_q107_8 LABA.    
   coco2_q109_1 LABM.       coco2_q109_2 LABM.       coco2_q109_3 LABM.    
   coco2_q109_4 LABM.       coco2_q109_5 LABM.       coco2_q109_6 LABM.    
   coco2_q109_7 LABM.       coco2_q109_8 LABM.       coco2_q110_1 LABN.    
   coco2_q110_2 LABN.       coco2_q110_3 LABN.       coco2_q111_1 LABO.    
   coco2_q111_2 LABO.       coco2_q111_3 LABO.       coco2_q111_4 LABO.    
   coco2_q111_5 LABO.       coco2_q111_6 LABO.       coco2_q112_1 LABD.    
   coco2_q112_2 LABD.       coco2_q112_3 LABD.       coco2_SWB LABP.       
   ea17_SWB LABP.           ea18_SWB LABP.           ea19_SWB LABP.        
   eayy_A1 EAYY_A1F.        eayy_A2A_rec EAYY_A2A.   eayy_A3_rec EAYY_A3F. 
   eayy_A3B_rec EAYY_A3B.   eayy_A3C_rec LABQ.       eayy_A3D EAYY_A3D.    
   eayy_A3E_rec LABQ.       eayy_A4 EAYY_A4F.        eayy_A5 EAYY_A5F.     
   eayy_A5A EAYY_A5A.       eayy_A5C EAYY_A5C.       eayy_A5C_rec EAYY_A_A.
   eayy_B1 EAYY_B1F.        eayy_B10A EAYY_B10F.     eayy_B10AA EAYY_B_A.  
   eayy_B10ACJT EAYY_B_B.   eayy_B11 LABR.           eayy_B11CJT LABR.     
   eayy_B18_rec EAYY_B18F.   eayy_B18C EAYY_B_D.      eayy_B18CCJT EAYY_B_E.
   eayy_B18CJT_rec EAYY_B_F.   eayy_B1A LABS.           eayy_B1ACJT LABS.     
   eayy_B1B EAYY_B1B.       eayy_B1BCJT EAYY_B_H.    eayy_B1CJT EAYY_B1C.  
   eayy_B2_rec EAYY_B2F.    eayy_B25 EAYY_B25F.      eayy_B2CJT_rec EAYY_B2C.
   eayy_B4_rec LABT.        eayy_B4CJT_rec LABT.     eayy_B5_rec EAYY_B5F. 
   eayy_B5A EAYY_B5A.       eayy_B5B_rec EAYY_B5B.   eayy_B5C EAYY_B5C.    
   eayy_B6A_rec EAYY_B6A.   eayy_B6B_rec EAYY_B6B.   eayy_B7B_rec EAYY_B7B.
   eayy_B8_rec EAYY_B8F.    eayy_B9_rec EAYY_B9F.    eayy_C1_rec EAYY_C1F. 
   eayy_C1JEU EAYY_C1J.     eayy_C8 EAYY_C8F.        eayy_C8A_rec EAYY_C8A.
   eayy_C8B_rec EAYY_C8B.   eayy_D1_rec EAYY_D1F.    eayy_D1A EAYY_D1A.    
   eayy_D2 EAYY_D2F.        eayy_D3 EAYY_D3F.        eayy_D4_rec EAYY_D4F. 
   eayy_D5_rec EAYY_D5F.    eayy_D6 EAYY_D6F.        eayy_D7_1 LABU.       
   eayy_D7_10 LABU.         eayy_D7_2 LABU.          eayy_D7_3 LABU.       
   eayy_D7_4 LABU.          eayy_D7_5 LABU.          eayy_D7_6 LABU.       
   eayy_D7_7 LABU.          eayy_D7_8 LABU.          eayy_D7_9 LABU.       
   eayy_E1A LABV.           eayy_E1B LABV.           eayy_E1C LABV.        
   eayy_E1D LABV.           eayy_E1E LABV.           eayy_E1F LABV.        
   eayy_E1G LABV.           eayy_E1H LABV.           eayy_E1I LABV.        
   eayy_E1J LABV.           eayy_E2A_rec EAYY_E2A.   eayy_E2AUC EAYY_E_A.  
   eayy_E2AUC_SOURCE EAYY_E_B.   eayy_E3A LABW.           eayy_E3B LABW.        
   eayy_E3C LABW.           eayy_E3D LABW.           eayy_E3E LABW.        
   eayy_E4 EAYY_E4F.        eayy_E5 EAYY_E5F.        eayy_E5A EAYY_E5A.    
   eayy_E5B_1 LABX.         eayy_E5B_2 LABX.         eayy_E5B_3 LABX.      
   eayy_E5B_4 LABX.         eayy_E5B_5 LABX.         eayy_E5B_6 LABX.      
   eayy_E5B_7 LABX.         eayy_E5B_8 LABX.         eayy_E5B_9 LABX.      
   eayy_F1_rec LABY.        eayy_F3 EAYY_F3F.        eayy_F4 EAYY_F4F.     
   eayy_F5 EAYY_F5F.        eayy_F6_rec LABY.        eayy_F7 LABZ.         
   eayy_F8 LABZ.            eayy_G1 EAYY_G1F.        eayy_G2 EAYY_G2F.     
   eayy_G3A LABAA.          eayy_G3B LABAA.          eayy_G3C LABAA.       
   eayy_G4 EAYY_G4F.        eayy_G5 EAYY_G5F.        eayy_G6_1 LABU.       
   eayy_G6_2 LABU.          eayy_G6_3 LABU.          eayy_G6_4 LABU.       
   eayy_H1A EAYY_H1A.       eayy_H2 EAYY_H2F.        eayy_H4 LABZ.         
   eayy_I1 EAYY_I1F.        eayy_I8 EAYY_I8F.        eayy_J1 EAYY_J1F.     
   eayy_K3 EAYY_K3F.        eayy_PCS18 EAYY_PCS.     eayy_PCS6 LABAB.      
   eayy_PCS6CJT LABAB.      eayy_TYPMEN5 EAYY_TYP.   insee_NUTS1 INSEE_NU. 
   insee_CATAEU2010 INSEE_CA.   insee_TAU2014 INSEE_TA.   insee_TUU2014 INSEE_TU.
 ;
                      

LENGTH
   UID_ANONYM_COVID 4       coco2_cal_SEXE 3         coco2_cal_AGE1 3      
   coco2_cal_AGE2 3         coco2_cal_DIPL 3         coco2_cal_ZEAT 3      
   coco2_q04 4              coco2_q06_1 4            coco2_q06_2 4         
   coco2_q06_3 4            coco2_q06_4 4            coco2_q06_5 4         
   coco2_q06_6 4            coco2_q06_7 4            coco2_q06_8 4         
   coco2_q06_9 4            coco2_q06_10 4           coco2_q07_1 3         
   coco2_q07_2 3            coco2_q07_3 3            coco2_q09 4           
   coco2_q10 4              coco2_q16 3              coco2_q17 4           
   coco2_q18 4              coco2_q19 4              coco2_q20 4           
   coco2_q21 4              coco2_q25_a 3            coco2_q38_modifie 4   
   coco2_q47 4              coco2_q51 4              coco2_q52_1 4         
   coco2_q52_2 4            coco2_q52_3 4            coco2_q52_4 4         
   coco2_q53_1 4            coco2_q53_2 4            coco2_q53_3 4         
   coco2_q54_1 4            coco2_q54_2 4            coco2_q54_3 4         
   coco2_q54_4 4            coco2_q54_5 4            coco2_q54_6 4         
   coco2_q54_7 4            coco2_q54_8 4            coco2_q54_bis_1 4     
   coco2_q54_bis_2 4        coco2_q54_bis_3 4        coco2_q54_bis_4 4     
   coco2_q54_bis_5 4        coco2_q54_bis_6 4        coco2_q54_bis_7 4     
   coco2_q59_1 4            coco2_q59_2 4            coco2_q59_3 4         
   coco2_q59_4 4            coco2_q59_5 4            coco2_q59_6 4         
   coco2_q59_7 4            coco2_q59_8 4            coco2_q59_9 4         
   coco2_q64 4              coco2_q68 4              coco2_q79 4           
   coco2_q92 4              coco2_q93_1 4            coco2_q93_2 4         
   coco2_q93_3 4            coco2_q93_4 4            coco2_q93_5 4         
   coco2_q94 4              coco2_q95_1 4            coco2_q95_2 4         
   coco2_q95_3 4            coco2_q95_4 4            coco2_q95_5 4         
   coco2_q95_6 4            coco2_q96_1 4            coco2_q96_2 4         
   coco2_q96_3 4            coco2_q96_4 4            coco2_q96_5 4         
   coco2_q96_6 4            coco2_q96_7 4            coco2_q96_8 4         
   coco2_q96_9 4            coco2_q97 4              coco2_q98 4           
   coco2_q99_1 4            coco2_q99_2 4            coco2_q99_3 4         
   coco2_Bloc2_DO_exp1_gpe 3   coco2_exp1_gpe_a 4       coco2_exp1_gpe_b 4    
   coco2_q100 4             coco2_q101 4             coco2_q102 4          
   coco2_q103_1 4           coco2_q103_2 4           coco2_q103_3 4        
   coco2_q104_1 4           coco2_q104_2 4           coco2_q104_3 4        
   coco2_q105_1 4           coco2_q105_2 4           coco2_q105_3 4        
   coco2_q106_1 4           coco2_q106_2 4           coco2_q106_3 4        
   coco2_q107_1 4           coco2_q107_2 4           coco2_q107_3 4        
   coco2_q107_4 4           coco2_q107_5 4           coco2_q107_6 4        
   coco2_q107_7 4           coco2_q107_8 4           coco2_q108_1_1 4      
   coco2_q108_2_1 4         coco2_q108_3_1 4         coco2_q108_4_1 4      
   coco2_q108_5_1 4         coco2_q108_6_1 4         coco2_q108_7_1 4      
   coco2_q109_1 4           coco2_q109_2 4           coco2_q109_3 4        
   coco2_q109_4 4           coco2_q109_5 4           coco2_q109_6 4        
   coco2_q109_7 4           coco2_q109_8 4           coco2_q110_1 4        
   coco2_q110_2 4           coco2_q110_3 4           coco2_q111_1 4        
   coco2_q111_2 4           coco2_q111_3 4           coco2_q111_4 4        
   coco2_q111_5 4           coco2_q111_6 4           coco2_q112_1 4        
   coco2_q112_2 4           coco2_q112_3 4           eayy_A1 3             
   eayy_A2A_rec 3           eayy_A3_rec 3            eayy_A3B_rec 3        
   eayy_A3C_rec 3           eayy_A3D 3               eayy_A3E_rec 3        
   eayy_A4 3                eayy_A5 3                eayy_A5A 4            
   eayy_A5C 4               eayy_A5C_rec 4           eayy_B1 3             
   eayy_B10A 3              eayy_B10AA 4             eayy_B10ACJT 3        
   eayy_B11 3               eayy_B11CJT 3            eayy_B18_rec 3        
   eayy_B18C 3              eayy_B18CCJT 3           eayy_B18CJT_rec 3     
   eayy_B1A 4               eayy_B1ACJT 4            eayy_B1B 3            
   eayy_B1BCJT 3            eayy_B1CJT 3             eayy_B2_rec 3         
   eayy_B25 3               eayy_B2CJT_rec 3         eayy_B4_rec 3         
   eayy_B4CJT_rec 3         eayy_B5_rec 3            eayy_B5A 3            
   eayy_B5B_rec 3           eayy_B5C 3               eayy_B6A_rec 3        
   eayy_B6B_rec 3           eayy_B7B_rec 3           eayy_B8_rec 3         
   eayy_B9_rec 3            eayy_C1_rec 3            eayy_C1JEU 3          
   eayy_C8 4                eayy_C8A_rec 4           eayy_C8B_rec 4        
   eayy_D1_rec 3            eayy_D1A 4               eayy_D2 3             
   eayy_D3 3                eayy_D4_rec 3            eayy_D5_rec 3         
   eayy_D6 3                eayy_D7_1 3              eayy_D7_10 3          
   eayy_D7_2 3              eayy_D7_3 3              eayy_D7_4 3           
   eayy_D7_5 3              eayy_D7_6 3              eayy_D7_7 3           
   eayy_D7_8 3              eayy_D7_9 3              eayy_E1A 3            
   eayy_E1B 3               eayy_E1C 3               eayy_E1D 3            
   eayy_E1E 3               eayy_E1F 3               eayy_E1G 3            
   eayy_E1H 3               eayy_E1I 3               eayy_E1J 3            
   eayy_E2A_rec 3           eayy_E2AUC 3             eayy_E2AUC_SOURCE 3   
   eayy_E3A 4               eayy_E3B 4               eayy_E3C 4            
   eayy_E3D 4               eayy_E3E 4               eayy_E4 4             
   eayy_E5 3                eayy_E5A 4               eayy_E5B_1 4          
   eayy_E5B_2 4             eayy_E5B_3 4             eayy_E5B_4 4          
   eayy_E5B_5 4             eayy_E5B_6 4             eayy_E5B_7 4          
   eayy_E5B_8 4             eayy_E5B_9 4             eayy_F1_rec 3         
   eayy_F3 3                eayy_F4 4                eayy_F5 4             
   eayy_F6_rec 3            eayy_F7 3                eayy_F8 3             
   eayy_G1 3                eayy_G2 3                eayy_G3A 3            
   eayy_G3B 3               eayy_G3C 3               eayy_G4 3             
   eayy_G5 3                eayy_G6_1 3              eayy_G6_2 3           
   eayy_G6_3 3              eayy_G6_4 3              eayy_H1A 3            
   eayy_H2 3                eayy_H4 3                eayy_I1 3             
   eayy_I8 3                eayy_J1 3                eayy_K3 3             
   eayy_PCS18 4             eayy_PCS6 4              eayy_PCS6CJT 4        
   eayy_TYPMEN5 3           VAGUE 4                  insee_NUTS1 3         
   insee_CATAEU2010 4       insee_TAU2014 3          insee_TUU2014 3       
   coco2_cal_NAT 3 ;

   

RUN ;
