/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco4_2020/donnees_coco4/sas_coco4/fr.cdsp.elipss.20205coco4.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco4_2020/donnees_coco4/sas_coco4/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = fr_cdsp_ ;

proc format library = library ;
   value COCO4_CA
      1 = '18-24 ans'  
      2 = '25-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-79 ans' ;
   value COCO4__A
      1 = '18-22 ans'  
      2 = '23-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-75 ans'  
      7 = '76-79 ans' ;
   value COCO4__B
      1 = 'Aucun/CEP/BEPC'  
      2 = 'CAP/BEP'  
      3 = 'Bac/Bac+2'  
      4 = 'Bac+3 et plus' ;
   value COCO4__C
      1 = 'Homme'  
      2 = 'Femme' ;
   value COCO4__D
      1 = 'Région parisienne'  
      2 = 'Bassin parisien'  
      3 = 'Nord'  
      4 = 'Est'  
      5 = 'Ouest'  
      6 = 'Sud-ouest'  
      7 = 'Centre-est'  
      8 = 'Méditerranée' ;
   value COCO4_Q0F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
     .A = 'N''a pas répondu' ;
   value COCO4__E
      1 = 'Moins de 55 kg'  
      2 = 'Entre 55 et 59 kg'  
      3 = 'Entre 60 et 64 kg'  
      4 = 'Entre 65 et 69 kg'  
      5 = 'Entre 70 et 74 kg'  
      6 = 'Entre 75 et 79 kg'  
      7 = 'Entre 80 et 84 kg'  
      8 = 'Entre 85 et et 94 kg'  
      9 = '95 kg et plus'  
     .A = 'Refuse de répondre'  
     .B = 'Ne sait pas'  
     .C = 'Non réponse' ;
   value LABA
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu' ;
   value LABB
      1 = 'Choisi'  
      2 = 'Non Choisi' ;
   value COCO4__S
      1 = 'J’ai été testé(e) positif(ve)'  
      2 = 'J’ai de fortes suspicions d’avoir été atteint(e)'  
      3 = 'Je ne pense pas avoir été atteint(e)'  
     .A = 'N''a pas répondu' ;
   value COCO4_Q1F
      1 = 'Je suis guéri(e)'  
      2 = 'Je suis encore malade mais je vais plutôt bien'  
      3 = 'Je suis malade'  
     .A = 'Non concernée' ;
   value COCO4__T
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais' ;
   value LABC
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value COCO4__X
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
     .A = 'N''a pas répondu' ;
   value COCO4__Y
      1 = 'Jamais'  
      2 = 'Rarement'  
      3 = 'Parfois'  
      4 = 'Souvent'  
      5 = 'Très souvent'  
      6 = 'Je vis actuellement seul(e)'  
     .A = 'N''a pas répondu' ;
   value COCO4_Q3F
      1 = 'Principalement travaillé sur votre lieu de travail habituel'  
      2 = 'Alterné télétravail et travail sur votre lieu de travail hab'  
      3 = 'Principalement été en télétravail'  
      4 = 'Aucune de ces situations'  
     .A = 'N''a pas répondu' ;
   value COCO4_Q6F
      1 = 'C''était une expérience qui nous a fait perdre beaucoup de te'  
      2 = 'C''était une expérience qui a permis de prendre du recul et r'  
      3 = 'C''était une expérience qui a permis de consacrer du temps à'  
      4 = 'C’était une expérience qui a fatigué les nerfs'  
     .A = 'N''a pas répondu' ;
   value COCO4__Z
      1 = 'Plus difficiles que celles de la plupart des Français'  
      2 = 'Proches de celles de la plupart des Français'  
      3 = 'Meilleures que celles de la plupart des Français'  
     .A = 'N''a pas répondu' ;
   value COCO4_AA
      0 = '0 - Pas du tout'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Énormément'  
     .A = 'N''a pas répondu' ;
   value COCO4_AB
      1 = 'Tout à fait satisfait(e)'  
      2 = 'Plutôt satisfait(e)'  
      3 = 'Plutôt pas satisfait(e)'  
      4 = 'Pas du tout satisfait(e)'  
     .A = 'N''a pas répondu' ;
   value COCO4_Q7F
      0 = '0 - Conséquences sanitaires'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Conséquences économiques'  
     .A = 'N''a pas répondu' ;
   value LABD
      1 = 'Très fréquemment'  
      2 = 'Plutôt fréquemment'  
      3 = 'Plutôt rarement'  
      4 = 'Très rarement'  
     .A = 'N''a pas répondu' ;
   value COCO4_AH
      1 = 'Oui'  
      2 = 'Non'  
     .A = 'N''a pas répondu' ;
   value LABE
      1 = 'Tout à fait d’accord'  
      2 = 'Plutôt d’accord'  
      3 = 'Plutôt pas d’accord'  
      4 = 'Pas du tout d’accord'  
     .A = 'N''a pas répondu' ;
   value COCO4_AV
      1 = 'Que l''État fasse confiance aux entreprises et leur donne plu'  
      2 = 'Ou que l''État les contrôle et les réglemente plus étroitemen'  
     .A = 'N''a pas répondu' ;
   value COCO4_AW
      1 = 'L''école devrait donner avant tout le sens de la discipline e'  
      2 = 'L''école devrait former avant tout les gens à l''esprit éveill'  
     .A = 'N''a pas répondu' ;
   value COCO4_EX
      1 = 'Groupe expérimental q146'  
      2 = 'Groupe expérimental q147'  
      3 = 'Groupe expérimental q148' ;
   value COCO4_AX
      1 = 'Tout faire pour réduire la pollution, même si cela signifie'  
      2 = 'Avant tout assurer la liberté de déplacement de chacun, même'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO4_AY
      1 = 'Tout faire pour réduire la pollution, même si cela signifie'  
      2 = 'Avant tout assurer la liberté d’entreprendre, même si cela s'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO4_AZ
      1 = 'Tout faire pour réduire la pollution, même si cela signifie'  
      2 = 'Avant tout assurer la liberté de chacun dans ses choix de co'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO4_BA
      1 = 'Très bien'  
      2 = 'Assez bien'  
      3 = 'Pas très bien'  
      4 = 'Pas bien du tout'  
     .A = 'N''a pas répondu' ;
   value LABF
      1 = 'Beaucoup moins de dépenses'  
      2 = 'Un peu moins de dépenses'  
      3 = 'Le même niveau de dépenses'  
      4 = 'Un peu plus de dépenses'  
      5 = 'Beaucoup plus de dépenses'  
      6 = 'Je ne sais pas'  
     .A = 'N''a pas répondu' ;
   value LABG
     .A = 'N''a pas répondu' ;
   value COCO4_BO
      1 = 'Oui, d''ici début juin'  
      2 = 'Oui, d''ici la rentrée scolaire'  
      3 = 'Oui, d''ici la fin de l''année 2020'  
      4 = 'Oui, d''ici un an'  
      5 = 'Non, il n''y aura pas de deuxième pic'  
     .A = 'N''a pas répondu' ;
   value LABH
      1 = 'Trop payé'  
      2 = 'Payé juste comme il faut'  
      3 = 'Pas assez payé'  
     .A = 'N''a pas répondu' ;
   value LABI
      1 = '1 - Ne s''applique pas du tout à moi'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '5 - S''applique tout à fait à moi'  
     .A = 'N''a pas répondu' ;
   value LABJ
      1 = 'Très mal'  
      2 = 'Mal'  
      3 = 'Plutôt mal'  
      4 = 'Ni bien ni mal'  
      5 = 'Plutôt bien'  
      6 = 'Bien'  
      7 = 'Très bien'  
     .A = 'N''a pas répondu' ;
   value COCO4_SW
      0 = 'Bien-être subjectif le plus faible'  
      1 = 'Bien-être subjectif le plus élevé'  
     .A = 'N''a pas répondu' ;
   value LABK
      0 = 'Bien-être subjectif le plus élevé'  
      1 = 'Bien-être subjectif le plus faible'  
     .A = 'N''a pas répondu' ;
   value EAYY_A1F
      1 = 'Un homme'  
      2 = 'Une femme' ;
   value EAYY_A2A
      4 = 'Moins de 24 ans'  
      5 = 'De 25 à 29 ans'  
      6 = 'De 30 à 34 ans'  
      7 = 'De 35 à 39 ans'  
      8 = 'De 40 à 44 ans'  
      9 = 'De 45 à 49 ans'  
      10 = 'De 50 à 54 ans'  
      11 = 'De 55 à 59 ans'  
      12 = 'De 60 à 64 ans'  
      13 = 'De 65 à 69 ans'  
      14 = '70 ans et plus' ;
   value EAYY_A3F
      1 = 'Oui, de naissance'  
      2 = '(Oui par réintégration, naturalisation, par mariage, par déc'  
      3 = 'Non'  
      4 = 'Apatride' ;
   value EAYY_A3B
      1 = 'France'  
      2 = 'Union européenne'  
      3 = 'Hors Union européenne'  
      9 = 'N''a pas répondu' ;
   value LABL
      1 = 'Union européenne'  
      2 = 'Hors Union européenne'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_A3D
      1 = 'Oui'  
      2 = 'Non' ;
   value EAYY_A4F
      1 = 'Célibataire (jamais légalement marié(e))'  
      2 = 'Pacsé(e)'  
      3 = 'Union libre ou concubinage'  
      4 = 'Marié(e) (ou séparé(e) mais non divorcé(e))'  
      5 = 'Divorcé(e)'  
      6 = 'Pacs dissout'  
      7 = 'Veuf(ve)'  
      77 = 'Refuse de répondre' ;
   value EAYY_A5F
      1 = 'Oui, avec quelqu''un qui vit dans votre logement'  
      2 = 'Oui, avec quelqu''un qui ne vit pas dans votre logement'  
      3 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_A5A
      1 = 'Marié(e)'  
      2 = 'Pacsé(e)'  
      3 = 'En union libre, en concubinage'  
      4 = 'Autre (précisez)'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A5C
      1 = 'Depuis moins d’un an'  
      2 = 'Depuis un an ou plus'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A_A
      1 = 'Moins de 2 ans'  
      2 = 'De 2 à 4 ans'  
      3 = 'De 5 à 9 ans'  
      4 = 'De 10 à 14 ans'  
      5 = 'De 15 à 19 ans'  
      6 = 'De 20 à 24 ans'  
      7 = '25 ans et plus'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1F
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      77 = 'Refuse de répondre' ;
   value EAYY_B10F
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B_A
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B_B
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de réponse'  
      8 = 'Ne sait pas' ;
   value LABM
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B18F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,' ;
   value EAYY_B_D
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire (' ;
   value EAYY_B_E
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire ('  
      6 = 'Non concerné' ;
   value EAYY_B_F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,'  
      66 = 'Non concerné' ;
   value LABN
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1B
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      7 = 'Refuse de répondre' ;
   value EAYY_B_H
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EAYY_B1C
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre' ;
   value EAYY_B2F
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salarié(e) d''un particulier'  
      7 = 'Vous aidez un membre de votre famille dans son travail sans'  
      8 = 'Vous êtes chef d''entreprise salarié, PDG, gérant(e) minorita'  
      9 = 'Vous êtes indépendant(e) ou à votre compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B25F
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_B2C
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salairé(e) d''un particulier'  
      7 = 'Il(elle) aide un membre de sa famille dans son travail sans'  
      8 = 'Il(elle) est chef d''entreprise salarié, PDG, gérant(e) minor'  
      9 = 'Il(elle) est indépendant(e) ou à son compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value LABO
      1 = 'Aucun salarié'  
      2 = 'Au moins 1 salarié'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B5F
      1 = 'Contrat à durée indéterminée'  
      2 = '(Contrat à durée déterminée (dont contrat saisonnier))'  
      4 = 'Contrat d''interim ou de travail temporaire'  
      5 = 'Contrat d''apprentissage'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5A
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5B
      1 = '(80% et plus)'  
      3 = 'Entre 50 et 80%'  
      4 = 'Mi-temps (50%)'  
      5 = 'Moins d''un mi-temps (moins de 50%)'  
      6 = 'Non concerné' ;
   value EAYY_B5C
      1 = 'Pour exercer une autre activité professionnelle, ou suivre d'  
      2 = 'Pour raisons de santé'  
      3 = 'Vous n''avez pas trouvé d''emploi à temps plein'  
      4 = 'Cela vous a été imposé par votre employeur'  
      5 = 'Pour vous occuper de vos enfants, ou d''un autre membre de vo'  
      6 = 'Pour disposer de temps libre ou faire des travaux domestique'  
      7 = 'Pour une autre raison (précisez)'  
      66 = 'Non concerné' ;
   value EAYY_B6A
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvier(e) qualifié(e) ou hautement qualifié(e), technicien(n'  
      3 = 'Technicien(ne)'  
      4 = 'Agent de maîtrise, maîtrise administrative ou commerciale, V'  
      5 = 'Ingénieur, cadre (à l''exception des directeurs généraux ou d'  
      6 = 'Employé(e) de bureau, employé(e) de commerce, personnel de s'  
      7 = 'Directeur général, adjoint direct'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B6B
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvrier(e) qualifié(e) ou hautement qualifié(e), technicien('  
      3 = 'Technicien(ne)'  
      4 = 'Personnel de catégorie C ou assimilé'  
      5 = 'Personnel de catégorie B ou assimilé'  
      6 = 'Personnel de catégorie A ou assimilé'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B7B
      1 = 'Production, chantier, exploitation'  
      2 = 'Installation, réparation, maintenance'  
      3 = 'Gardiennage, nettoyage, entretien ménager'  
      4 = 'Manutention, magasinage, logistique'  
      5 = 'Secrétariat, saisie, accueil'  
      6 = 'Gestion, comptabilité'  
      7 = 'Commercial, technico-commercial'  
      8 = 'Études, recherche et développement, méthodes'  
      9 = 'Enseignement'  
      10 = 'Soin des personnes'  
      11 = 'Autre fonction (précisez)'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B8F
      1 = 'Moins de 10'  
      2 = '10 à 49'  
      3 = '50 à 499'  
      4 = '500 et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B9F
      1 = 'Moins de 20 hectares'  
      2 = 'De 20 à moins de 50 hectares'  
      3 = 'De 50 à moins de 100 hectares'  
      4 = 'De 100 à moins de 200 hectares'  
      5 = '200 hectares et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_C1F
      1 = '1 habitant'  
      2 = '2 habitants'  
      3 = '3 habitants'  
      4 = '4 habitants'  
      5 = '5 habitants'  
      6 = '6 habitants et plus' ;
   value EAYY_C1J
      1 = '0 jeune'  
      2 = '1 jeune'  
      3 = '2 jeunes'  
      4 = '3 jeunes ou plus' ;
   value EAYY_C8F
      1 = 'Oui'  
      2 = 'Non'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8A
      1 = '1 enfant'  
      2 = '2 enfants'  
      3 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8B
      1 = '0 enfant'  
      2 = '1 enfant'  
      3 = '2 enfants'  
      4 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D1F
      1 = 'Propriétaire (ou copropriétaire) : vous ne payez pas de créd'  
      2 = 'Accédant à la propriété : vous payez toujours un crédit immo'  
      3 = '(Locataire, sous-locataire)'  
      5 = 'Occupant à titre gratuit'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_D1A
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D2F
      1 = 'Votre conjoint(e)'  
      2 = 'Un autre membre du foyer'  
      3 = 'Une autre personne de votre famille'  
      4 = 'Un autre particulier'  
      5 = 'Un organisme HLM (ou assimilé, OPAC, offices, sociétés, fond'  
      6 = 'Une administration, organisme de Sécurité Sociale ou associa'  
      7 = 'Une banque, assurance ou autre société du secteur public ou'  
      8 = 'L''employeur d''un membre du ménage dans le cadre d''un logemen'  
      9 = 'Autre cas'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_D3F
      1 = 'Une maison individuelle'  
      2 = 'Un appartement'  
      3 = 'Autre (précisez)' ;
   value EAYY_D4F
      1 = '1 pièce'  
      2 = '2 pièces'  
      3 = '3 pièces'  
      4 = '4 pièces'  
      5 = '5 pièces'  
      6 = '6 pièces'  
      7 = '7 pièces'  
      8 = '8 pièces'  
      9 = '9 pièces et plus' ;
   value EAYY_D5F
      1 = 'Moins de 2 ans'  
      2 = 'Entre 2 à 5 ans'  
      3 = 'Entre 5 et 10 ans'  
      4 = 'Entre 10 et 15 ans'  
      5 = 'Il y a plus de 15 ans'  
      9 = 'N''a pas répondu' ;
   value EAYY_D6F
      1 = 'Maisons dispersées, hors agglomération'  
      2 = 'Maisons en lotissement, en quartier pavillonnaire ou en vill'  
      3 = 'Immeubles en ville (autre que cité ou grand ensemble)'  
      4 = 'Immeubles en cité ou grand ensemble'  
      5 = 'Habitat mixte : à la fois immeubles et maisons'  
      9 = 'N''a pas répondu' ;
   value LABP
      1 = 'Choisi'  
      2 = 'Non choisi'  
      9 = 'N''a pas répondu' ;
   value LABQ
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas' ;
   value EAYY_E2A
      3 = '(Moins de 800 €)'  
      4 = 'De 800 à moins de 1000 €'  
      5 = 'De 1000 à moins de 1200 €'  
      6 = 'De 1200 à moins de 1500 €'  
      7 = 'De 1500 à moins de 1800 €'  
      8 = 'De 1800 à moins de 2000 €'  
      9 = 'De 2000 à moins de 2500 €'  
      10 = 'De 2500 à moins de 3000 €'  
      11 = 'De 3000 à moins de 4000 €'  
      12 = 'De 4000 à moins de 6000 €'  
      13 = '(6000 € et plus)'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_E_A
      1 = 'Moins de 650 €'  
      2 = 'De 650 à moins de 950 €'  
      3 = 'De 950 à moins de 1200 €'  
      4 = 'De 1200 à moins de 1400 €'  
      5 = 'De 1400 à moins de 1650 €'  
      6 = 'De 1650 à moins de 1900 €'  
      7 = 'De 1900 à moins de 2200 €'  
      8 = 'De 2200 à moins de 2500 €'  
      9 = 'De 2500 à moins de 3200 €'  
      10 = '3200 € et plus'  
      99 = 'N''a pas répondu' ;
   value EAYY_E_B
      1 = 'À partir du montant déclaré des ressources'  
      2 = 'À partir de la tranche déclarée des ressources'  
      3 = 'Non calculé' ;
   value LABR
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas'  
     .A = 'Non enquêté(e)' ;
   value EAYY_E4F
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
     .B = 'Non enquêté(e)' ;
   value EAYY_E5F
      1 = 'Vous ne pouvez pas y arriver sans faire de dettes'  
      2 = 'Vous y arrivez difficilement'  
      3 = 'C''''est juste, il faut faire attention'  
      4 = 'Ça va'  
      5 = 'Vous êtes plutôt à l''''aise'  
      6 = 'Vous êtes vraiment à l''''aise'  
      99 = 'N''a pas répondu' ;
   value EAYY_E5A
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABS
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABT
      1 = 'Au moins une fois par semaine'  
      2 = 'Une à trois fois par mois'  
      3 = 'Plusieurs fois dans l''année (mais moins d''une fois par mois)'  
      4 = 'Seulement pour des occasions exceptionnelles'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_F3F
      1 = 'Il n''y en a pas'  
      2 = '1 ou 2 personnes'  
      3 = 'Entre 3 et 5 personnes'  
      4 = '6 personnes ou plus'  
      8 = 'Ne sait pas' ;
   value EAYY_F4F
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_F5F
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n''est jamais assez prudent quand on a affaire aux autres'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value LABU
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_G1F
      1 = 'Moins de 2 heures par jour'  
      2 = 'De 2 à 4 heures par jour'  
      3 = 'Plus de 4 heures par jour'  
      4 = 'Je ne regarde par la télévision'  
      8 = 'Ne sait pas' ;
   value EAYY_G2F
      1 = 'Aucun'  
      2 = 'Moins de 6'  
      3 = 'De 6 à moins de 12'  
      4 = 'De 12 à 24 (c''est-à-dire entre 1 et 2 livres par mois)'  
      5 = 'De 25 à 50 (c''est-à-dire plus de 2 livres par mois)'  
      6 = 'Plus de 50 (c''est-à-dire plus de 4 livres par mois)'  
      8 = 'Ne sait pas' ;
   value LABV
      1 = 'Jamais'  
      2 = '1 à 3 fois'  
      3 = '4 à 6 fois'  
      4 = '7 à 12 fois'  
      5 = 'Plus de 12 fois'  
      9 = 'N''a pas répondu' ;
   value EAYY_G4F
      1 = 'Régulièrement tout au long de l''année'  
      2 = 'De temps en temps tout au long de l''année'  
      3 = 'Seulement pendant certaines périodes ou pendant les vacances'  
      4 = 'Occasionnellement ou rarement'  
      5 = 'Jamais'  
      8 = 'Ne sait pas' ;
   value EAYY_G5F
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu' ;
   value EAYY_H1A
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_H2F
      1 = 'Pas du tout d''importance'  
      2 = 'Un peu d''importance'  
      3 = 'Assez d''importance'  
      4 = 'Beaucoup d''importance'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_I1F
      1 = 'Beaucoup'  
      2 = 'Assez'  
      3 = 'Peu'  
      4 = 'Pas du tout'  
      8 = 'Ne sait pas' ;
   value EAYY_I8F
      0 = 'Gauche'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = 'Droite'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_J1F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_K3F
      1 = 'Tous les jours ou presque'  
      2 = 'Plusieurs fois par semaine'  
      3 = 'Une fois par semaine'  
      4 = 'Une à trois fois par mois'  
      5 = 'Moins souvent'  
      9 = 'N''a pas répondu' ;
   value EAYY_PCS
      10 = 'Agriculteurs exploitants'  
      20 = '(Artisans, commerçants et chefs d''entreprise)'  
      31 = 'Professions libérales et assimilés'  
      32 = 'Cadres de la fonction publique, professions intellectuelles'  
      36 = 'Cadres d''entreprise'  
      41 = 'Professions intermédiaires de l''enseignement, de la santé, d'  
      46 = 'Professions intermédiaires administratives et commerciales d'  
      47 = 'Techniciens'  
      48 = 'Contremaîtres, agents de maîtrise'  
      51 = 'Employés de la fonction publique'  
      54 = 'Employés administratifs d''entreprise'  
      55 = 'Employés de commerce'  
      56 = 'Personnels des services directs aux particuliers'  
      61 = 'Ouvriers qualifiés'  
      66 = '(Ouvriers non qualifiés et ouvriers agricoles)'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value LABW
      1 = 'Agriculteurs exploitants'  
      2 = 'Artisans, commerçants et chefs d''entreprise'  
      3 = 'Cadres et professions intellectuelles supérieures'  
      4 = 'Professions intermédiaires'  
      5 = 'Employés'  
      6 = 'Ouvriers'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value EAYY_TYP
      1 = 'Ménages d''une seule personne'  
      2 = 'Familles monoparentales'  
      3 = 'Couples sans enfant'  
      4 = 'Couples avec enfant(s)'  
      5 = 'Ménages complexes de plus d''une personne' ;
   value INSEE_NU
      1 = 'FR1 : Région parisienne'  
      2 = 'FR2 : Bassin parisien'  
      3 = 'FR3 : Nord'  
      4 = 'FR4 : Est'  
      5 = 'FR5 : Ouest'  
      6 = 'FR6 : Sud-ouest'  
      7 = 'FR7 : Centre-est'  
      8 = 'FR8 : Méditerranée'  
      9 = 'FRA : Départements d''Outre-Mer' ;
   value INSEE_CA
      111 = 'Commune appartenant à un grand pôle (10 000 emplois ou plus)'  
      112 = 'Commune appartenant à la couronne d''un grand pôle'  
      120 = 'Commune multipolarisée des grandes aires urbaines'  
      211 = 'Commune appartenant à un moyen pôle (5 000 à moins de 10 000'  
      212 = 'Commune appartenant à la couronne d''un moyen pôle'  
      221 = 'Commune appartenant à un petit pôle (de 1 500 à moins de 5 0'  
      222 = 'Commune appartenant à la couronne d''un petit pôle'  
      300 = 'Autre commune multipolarisée'  
      400 = 'Commune isolée hors influence des pôles' ;
   value INSEE_TA
      0 = 'Commune hors aire urbaine'  
      1 = 'Commune appartenant à une aire urbaine de moins de 15 000 ha'  
      2 = 'Commune appartenant à une aire urbaine de 15 000 à 19 999 ha'  
      3 = 'Commune appartenant à une aire urbaine de 20 000 à 24 999 ha'  
      4 = 'Commune appartenant à une aire urbaine de 25 000 à 34 999 ha'  
      5 = 'Commune appartenant à une aire urbaine de 35 000 à 49 999 ha'  
      6 = 'Commune appartenant à une aire urbaine de 50 000 à 99 999 ha'  
      7 = 'Commune appartenant à une aire urbaine de 100 000 à 199 999'  
      8 = 'Commune appartenant à une aire urbaine de 200 000 à 499 999'  
      9 = 'Commune appartenant à une aire urbaine de 500 000 à 9 999 99'  
      10 = 'Commune appartenant à l''aire urbaine de Paris' ;
   value INSEE_TU
      0 = 'Commune rurale'  
      1 = 'Commune appartenant à une unité urbaine de 2 000 à 4 999 hab'  
      2 = 'Commune appartenant à une unité urbaine de 5 000 à 9 999 hab'  
      3 = 'Commune appartenant à une unité urbaine de 10 000 à 19 999 h'  
      4 = 'Commune appartenant à une unité urbaine de 20 000 à 49 999 h'  
      5 = 'Commune appartenant à une unité urbaine de 50 000 à 99 999 h'  
      6 = 'Commune appartenant à une unité urbaine de 100 000 à 199 999'  
      7 = 'Commune appartenant à une unité urbaine de 200 000 à 1 999 9'  
      8 = 'Commune appartenant à l''unité urbaine de Paris' ;
   value COCO4_CL
      1 = 'Français(e)'  
      2 = 'A acquis la nationalité française'  
      3 = 'Nationalité étrangère' ;

DATA library.&dataset ;
INFILE datafile LRECL=716;
INPUT
   UID_ANONYM_COVID  1-4    coco4_cal_AGE1  5        coco4_cal_AGE2  6     
   coco4_cal_DIPL  7        coco4_cal_SEXE  8        coco4_cal_ZEAT  9     
   coco4_q04  10            coco4_q05_c  11-14       coco4_q06_1  15-18    
   coco4_q06_2  19-22       coco4_q06_3  23-26       coco4_q06_4  27-30    
   coco4_q06_5  31-34       coco4_q06_6  35-38       coco4_q06_7  39-42    
   coco4_q06_8  43-46       coco4_q06_9  47-50       coco4_q06_10  51-54   
   coco4_q07_1  55          coco4_q07_2  56          coco4_q07_3  57       
   coco4_q09  58-61         coco4_q10  62-65         coco4_q16  66         
   coco4_q17  67-70         coco4_q18  71-74         coco4_q19  75-78      
   coco4_q20  79-82         coco4_q21  83-86         coco4_q25_a  87-90    
   coco4_q38_modifie  91-94   coco4_q62_modifie  95-98
   coco4_q63_modifie  99-102   coco4_q64_modifie  103-106
   coco4_q68  107-110       coco4_q79  111-114    
   coco4_q125_modifie_1  115-118   coco4_q125_modifie_2  119-122
   coco4_q125_modifie_3  123-126   coco4_q125_modifie_4  127-130
   coco4_q125_modifie_5  131-134   coco4_q141  135-138   
   coco4_q142_1  139        coco4_q142_2  140        coco4_q142_3  141     
   coco4_q142_4  142        coco4_q143_1  143-146    coco4_q143_2  147-150 
   coco4_q143_3  151-154    coco4_q143_4  155-158    coco4_q143_5  159-162 
   coco4_q143_6  163-166    coco4_q143_7  167-170    coco4_q143_8  171-174 
   coco4_q143_9  175-178    coco4_q144  179-182      coco4_q145  183-186   
   coco4_experience_1_DO  187   coco4_q146  188-191      coco4_q147  192-195   
   coco4_q148  196-199      coco4_q149  200-203      coco4_q150_1  204-207 
   coco4_q150_2  208-211    coco4_q150_3  212-215    coco4_q150_4  216-219 
   coco4_q150_5  220-223    coco4_q150_6  224-227    coco4_q150_7  228-231 
   coco4_q151_1_c  232-236   coco4_q151_2_c  237-241   coco4_q151_3_c  242-246
   coco4_q151_4_c  247-250   coco4_q151_5_c  251-255   coco4_q151_6_c  256-259
   coco4_q152  260-263      coco4_q153_1  264-267    coco4_q153_2  268-271 
   coco4_q153_3  272-275    coco4_q153_4  276-279    coco4_q153_5  280-283 
   coco4_q153_6  284-287    coco4_q154_1  288-291    coco4_q154_2  292-295 
   coco4_q154_3  296-299    coco4_q154_4  300-303    coco4_q154_5  304-307 
   coco4_q155_1  308-311    coco4_q155_2  312-315    coco4_q155_3  316-319 
   coco4_q155_4  320-323    coco4_q155_5  324-327    coco4_q155_6  328-331 
   coco4_q155_7  332-335    coco4_q155_8  336-339    coco4_q155_9  340-343 
   coco4_q155_10  344-347   coco4_SWB  348-364       ea17_SWB  365-382     
   ea18_SWB  383-400        ea19_SWB  401-417        eayy_A1  418          
   eayy_A2A_rec  419-420    eayy_A3_rec  421         eayy_A3B_rec  422     
   eayy_A3C_rec  423        eayy_A3D  424            eayy_A3E_rec  425     
   eayy_A4  426-427         eayy_A5  428             eayy_A5A  429-432     
   eayy_A5C  433-436        eayy_A5C_rec  437-440    eayy_B1  441-442      
   eayy_B10A  443           eayy_B10AA  444-447      eayy_B10ACJT  448     
   eayy_B11  449            eayy_B11CJT  450         eayy_B18_rec  451-452 
   eayy_B18C  453           eayy_B18CCJT  454        eayy_B18CJT_rec  455-456
   eayy_B1A  457-460        eayy_B1ACJT  461-464     eayy_B1B  465         
   eayy_B1BCJT  466         eayy_B1CJT  467-468      eayy_B2_rec  469-470  
   eayy_B25  471            eayy_B2CJT_rec  472-473   eayy_B4_rec  474      
   eayy_B4CJT_rec  475      eayy_B5_rec  476         eayy_B5A  477         
   eayy_B5B_rec  478        eayy_B5C  479-480        eayy_B6A_rec  481-482 
   eayy_B6B_rec  483-484    eayy_B7B_rec  485-486    eayy_B8_rec  487      
   eayy_B9_rec  488         eayy_C1_rec  489         eayy_C1JEU  490       
   eayy_C8  491-494         eayy_C8A_rec  495-498    eayy_C8B_rec  499-502 
   eayy_D1_rec  503         eayy_D1A  504-507        eayy_D2  508-509      
   eayy_D3  510             eayy_D4_rec  511         eayy_D5_rec  512      
   eayy_D6  513             eayy_D7_1  514           eayy_D7_10  515       
   eayy_D7_2  516           eayy_D7_3  517           eayy_D7_4  518        
   eayy_D7_5  519           eayy_D7_6  520           eayy_D7_7  521        
   eayy_D7_8  522           eayy_D7_9  523           eayy_E1A  524         
   eayy_E1B  525            eayy_E1C  526            eayy_E1D  527         
   eayy_E1E  528            eayy_E1F  529            eayy_E1G  530         
   eayy_E1H  531            eayy_E1I  532            eayy_E1J  533         
   eayy_E2A_rec  534-535    eayy_E2AUC  536-537      eayy_E2AUC_SOURCE  538
   eayy_E3A  539-542        eayy_E3B  543-546        eayy_E3C  547-550     
   eayy_E3D  551-554        eayy_E3E  555-558        eayy_E4  559-562      
   eayy_E5  563-564         eayy_E5A  565-568        eayy_E5B_1  569-572   
   eayy_E5B_2  573-576      eayy_E5B_3  577-580      eayy_E5B_4  581-584   
   eayy_E5B_5  585-588      eayy_E5B_6  589-592      eayy_E5B_7  593-596   
   eayy_E5B_8  597-600      eayy_E5B_9  601-604      eayy_F1_rec  605      
   eayy_F3  606             eayy_F4  607-610         eayy_F5  611-614      
   eayy_F6_rec  615         eayy_F7  616             eayy_F8  617          
   eayy_G1  618             eayy_G2  619             eayy_G3A  620         
   eayy_G3B  621            eayy_G3C  622            eayy_G4  623          
   eayy_G5  624             eayy_G6_1  625           eayy_G6_2  626        
   eayy_G6_3  627           eayy_G6_4  628           eayy_H1A  629         
   eayy_H2  630             eayy_H4  631             eayy_I1  632          
   eayy_I8  633-634         eayy_J1  635             eayy_K3  636          
   eayy_PCS18  637-639      eayy_PCS6  640-642       eayy_PCS6CJT  643-645 
   eayy_TYPMEN5  646        VAGUE  647-650           insee_NUTS1  651      
   insee_CATAEU2010  652-654   insee_TAU2014  655-656   insee_TUU2014  657    
   POIDS_coco4  658-675     PDSPLT_coco4 $ 676-693   coco4_cal_NAT  694    
   POIDS_INIT_coco4  695-705   PDSPLT_INIT_coco4 $ 706-716
 ;                       

LABEL
   UID_ANONYM_COVID = "Identifiant interviewé"
   coco4_cal_AGE1 = "Age décennal (calage panel pilote)"
   coco4_cal_AGE2 = "Age décennal (calage)"
   coco4_cal_DIPL = "Diplôme (calage)"
   coco4_cal_SEXE = "Sexe"
   coco4_cal_ZEAT = "Zone d'études et d'aménagement du territoire"
   coco4_q04 = "Auto-évaluation de la santé"
   coco4_q05_c = "Poids en kg (recodage)"
   coco4_q06_1 = "Symptômes pendant les deux dernières semaines : Toux"
   coco4_q06_2 = "Symptômes pendant les deux dernières semaines : Maux de tête"
   coco4_q06_3 = "Symptômes pendant les deux dernières semaines : Fatigue"
   coco4_q06_4 = "Symptômes pendant les deux dernières semaines : Rhume"
   coco4_q06_5 = "Symptômes pendant les deux dernières semaines : Maux de gorge"
   coco4_q06_6 = "Symptômes pendant les deux dernières semaines : Gêne respiratoire"
   coco4_q06_7 = "Symptômes pendant les deux dernières semaines : Courbatures"
   coco4_q06_8 = "Symptômes pendant les deux dernières semaines : Fièvre"
   coco4_q06_9 = "Symptômes pendant les deux dernières semaines : Troubles digestifs"
   coco4_q06_10 = "Symptômes pendant les deux dernières semaines : Aucun de ces symptômes"
   coco4_q07_1 = "Consultation médicale : Aucune"
   coco4_q07_2 = "Consultation médicale : Pour un ou plusieurs symptômes"
   coco4_q07_3 = "Consultation médicale : Autres raisons"
   coco4_q09 = "Infection par le virus covid-19"
   coco4_q10 = "État de santé actuel après une probable infection par le virus covid-19"
   coco4_q16 = "Les 2 dernières semaines, s'est senti : nerveux"
   coco4_q17 = "Les 2 dernières semaines, s'est senti : découragé"
   coco4_q18 = "Les 2 dernières semaines, s'est senti : calme"
   coco4_q19 = "Les 2 dernières semaines, s'est senti : triste et abattu"
   coco4_q20 = "Les 2 dernières semaines, s'est senti : heureux"
   coco4_q21 = "Sentiment de solitude"
   coco4_q25_a = "Tensions au sein du ménage au cours des deux dernières semaines"
   coco4_q38_modifie = "Situation actuelle vis-à-vis du télétravail"
   coco4_q62_modifie = "Description de l'expérience de deux mois de confinement"
   coco4_q63_modifie = "Conditions de vie lors du confinement, par rapport à la plupart des Français"
   coco4_q64_modifie = "Stress lié au confinement"
   coco4_q68 = "Satisfaction quant à la manière dont le Gouvernement français gère l'épidémie du virus Covid-19"
   coco4_q79 = "Préoccupation par les conséquences sanitaires ou les conséquences économiques de l’épidémie du virus Covid-19"
   coco4_q125_modifie_1 = "Fréquence des contacts directs prévus : Des personnes beaucoup plus jeunes que l'interviewé"
   coco4_q125_modifie_2 = "Fréquence des contacts directs prévus : Des personnes un peu plus jeunes que l'interviewé"
   coco4_q125_modifie_3 = "Fréquence des contacts directs prévus : Des personnes d’environ l'âge de l'interviewé"
   coco4_q125_modifie_4 = "Fréquence des contacts directs prévus : Des personnes un peu plus âgées que l'interviewé"
   coco4_q125_modifie_5 = "Fréquence des contacts directs prévus : Des personnes beaucoup plus âgées que l'interviewé"
   coco4_q141 = "Volonté de mettre les enfants à l'école dès la réouverture des classes"
   coco4_q142_1 = "Personnes revues ou prévues de revoir durant première semaine de déconfinement : Membres de la famille"
   coco4_q142_2 = "Personnes revues ou prévues de revoir durant première semaine de déconfinement : Amis"
   coco4_q142_3 = "Personnes revues ou prévues de revoir durant première semaine de déconfinement : Collègues"
   coco4_q142_4 = "Personnes revues ou prévues de revoir durant première semaine de déconfinement : Personne"
   coco4_q143_1 = "Ralentir croissance pour préserver l'environnement"
   coco4_q143_2 = "Mondialisation négative pour la France"
   coco4_q143_3 = "Prendre aux riches pour donner aux pauves"
   coco4_q143_4 = "Mettre en place un revenu universel"
   coco4_q143_5 = "Les chômeurs pourraient trouver du travail s'ils le voulaient vraiment"
   coco4_q143_6 = "Trop d'immigrés en France"
   coco4_q143_7 = "Réduire le nombre de fonctionnaires"
   coco4_q143_8 = "Renforcer les pouvoirs de l'Europe"
   coco4_q143_9 = "Faire des compromis en politique, c'est trahir ses valeurs"
   coco4_q144 = "Contrôle de l'État sur entreprises"
   coco4_q145 = "Rôle de l'école"
   coco4_experience_1_DO = "Appartenance au groupe expérimental"
   coco4_q146 = "Experience : Mesures pour réduire la pollution vs liberté de déplacement"
   coco4_q147 = "Experience : Mesures pour réduire la pollution vs liberté d'entreprendre"
   coco4_q148 = "Experience : Mesures pour réduire la pollution vs liberté dans ses choix de consommation"
   coco4_q149 = "Fonctionnement de la démocratie"
   coco4_q150_1 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour soutenir les entreprises"
   coco4_q150_2 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour les hôpitaux publics"
   coco4_q150_3 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour le secteur de l'éducation"
   coco4_q150_4 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour la police et le maintien de l'ordre public"
   coco4_q150_5 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour l'assurance chômage"
   coco4_q150_6 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour les aides sociales"
   coco4_q150_7 = "Dépenser autant ou moins, par rapport à avant le confinement : Pour les territoires ruraux"
   coco4_q151_1_c = "Estimation du salaire mensuel net d'un : Caissier de grands surfaces (recodage)"
   coco4_q151_2_c = "Estimation du salaire mensuel net d'une : Aide à domicile pour les personnes âgées (recodage)"
   coco4_q151_3_c = "Estimation du salaire mensuel net d'un : Livreur (recodage)"
   coco4_q151_4_c = "Estimation du salaire mensuel net d'un : Éboueur (recodage)"
   coco4_q151_5_c = "Estimation du salaire mensuel net d'un : Infirmier à l’hôpital (recodage)"
   coco4_q151_6_c = "Estimation du salaire mensuel net d'un : Ouvrier non-qualifié (recodage)"
   coco4_q152 = "Pronostic concernant un deuxième pic de l’épidémie du Covid-19"
   coco4_q153_1 = "Adéquation du salaire : Caissier de grands surfaces"
   coco4_q153_2 = "Adéquation du salaire : Aide à domicile pour les personnes âgées"
   coco4_q153_3 = "Adéquation du salaire : Livreur"
   coco4_q153_4 = "Adéquation du salaire : Éboueur"
   coco4_q153_5 = "Adéquation du salaire : Infirmier à l’hôpital"
   coco4_q153_6 = "Adéquation du salaire : Ouvrier non-qualifié"
   coco4_q154_1 = "État d'esprit actuel : Le fait de penser au passé donne du plaisir"
   coco4_q154_2 = "État d'esprit actuel : Pense que le passé a été plein d’erreurs"
   coco4_q154_3 = "État d'esprit actuel : Ce qui devait arriver est arrivé"
   coco4_q154_4 = "État d'esprit actuel : Il faut voir tous les aspects positifs qui émergeront de cette épreuve"
   coco4_q154_5 = "État d'esprit actuel : Tirer des leçons de cette expérience pour améliorer sa vie"
   coco4_q155_1 = "Représentation de soi : Extraverti, enthousiaste"
   coco4_q155_2 = "Représentation de soi : Critique, agressif"
   coco4_q155_3 = "Représentation de soi : Fiable, discipliné"
   coco4_q155_4 = "Représentation de soi : Anxieux, facilement déprimé"
   coco4_q155_5 = "Représentation de soi : Ouvert à de nouvelles expériences, créatif"
   coco4_q155_6 = "Représentation de soi : Réservé, tranquille"
   coco4_q155_7 = "Représentation de soi : Sympathique, chaleureux"
   coco4_q155_8 = "Représentation de soi : Désorganisé, insouciant"
   coco4_q155_9 = "Représentation de soi : Calme, relaxé"
   coco4_q155_10 = "Représentation de soi : Conventionnel, peu imaginatif"
   coco4_SWB = "Niveau de bien-être subjectif"
   ea17_SWB = "Niveau de bien-être subjectif"
   ea18_SWB = "Niveau de bien-être subjectif"
   ea19_SWB = "Niveau de bien-être subjectif"
   eayy_A1 = "Sexe (enquête annuelle)"
   eayy_A2A_rec = "Age quinquennal (recodage)"
   eayy_A3_rec = "A la nationalité francaise (recodage)"
   eayy_A3B_rec = "Pays de naissance (recodage)"
   eayy_A3C_rec = "Nationalité (recodage)"
   eayy_A3D = "A une seconde nationalité"
   eayy_A3E_rec = "Seconde nationalité (recodage)"
   eayy_A4 = "Statut matrimonial légal"
   eayy_A5 = "Vit en couple"
   eayy_A5A = "Situation familiale"
   eayy_A5C = "Ancienneté du couple"
   eayy_A5C_rec = "Ancienneté du couple (recodage)"
   eayy_B1 = "Situation principale vis-à-vis du travail"
   eayy_B10A = "Recherche d'emploi"
   eayy_B10AA = "Rercherche un autre emploi"
   eayy_B10ACJT = "Recherche d'emploi (conjoint)"
   eayy_B11 = "Ne travaille pas mais a déjà travaillé"
   eayy_B11CJT = "Ne travaille pas mais a déjà travaillé (conjoint)"
   eayy_B18_rec = "Diplôme le plus élevé (recodage)"
   eayy_B18C = "Niveau de formation (recodage)"
   eayy_B18CCJT = "Niveau de formation (conjoint) (calcul)"
   eayy_B18CJT_rec = "Diplôme le plus élevé (conjoint) (recodage)"
   eayy_B1A = "Emploi (étudiant, chômeur, retraité, autre inactif)"
   eayy_B1ACJT = "Emploi (étudiant, chômeur, retraité, autre inactif) (conjoint)"
   eayy_B1B = "Exercice d'une activité professionnelle (recodage)"
   eayy_B1BCJT = "Exercice d'une activité professionnelle (conjoint) (calcul)"
   eayy_B1CJT = "Situation principale vis-à-vis du travail (conjoint)"
   eayy_B2_rec = "Statut de l'activité actuelle ou antérieure (recodage)"
   eayy_B25 = "Supervision d'autres salariés"
   eayy_B2CJT_rec = "Statut de l'activité actuelle ou antérieure (conjoint) (calcul)"
   eayy_B4_rec = "Nombre de salariés employés actuellement ou par le passé (recodage)"
   eayy_B4CJT_rec = "Nombre de salariés employés actuellement ou par le passé (conjoint) (calcul)"
   eayy_B5_rec = "Type de contrat de travail (recodage)"
   eayy_B5A = "Temps de travail"
   eayy_B5B_rec = "Type de temps partiel (recodage)"
   eayy_B5C = "Raison principale du travail à temps partiel"
   eayy_B6A_rec = "Catégorie de l'emploi actuel ou antérieur secteur privé (recodage)"
   eayy_B6B_rec = "Catégorie de l'emploi actuel ou antérieur secteur public (recodage)"
   eayy_B7B_rec = "Fonction principale de l'emploi actuel ou antérieur (recodage)"
   eayy_B8_rec = "Nombre de salariés dans l'entreprise de l'emploi actuel ou antérieur (recodage)"
   eayy_B9_rec = "Superficie de l'exploitation actuelle ou antérieure (recodage)"
   eayy_C1_rec = "Nombre de personnes dans le foyer (recodage)"
   eayy_C1JEU = "Nombre de jeunes (calcul)"
   eayy_C8 = "A des enfants"
   eayy_C8A_rec = "Nombre d'enfants (recodage)"
   eayy_C8B_rec = "Nombre d'enfants cohabitants (recodage)"
   eayy_D1_rec = "Statut d'occupation du logement (recodage)"
   eayy_D1A = "Appartenance du logement à un organisme HLM"
   eayy_D2 = "Propriétaire du logement"
   eayy_D3 = "Type d'habitation"
   eayy_D4_rec = "Nombre pièces d'habitation du logement (recodage)"
   eayy_D5_rec = "Année d'emménagement dans le logement (calcul)"
   eayy_D6 = "Type d'habitat au voisinage du logement"
   eayy_D7_1 = "Problèmes concernant le quartier : terrains-vagues, locaux désaffectés, friches industrielles, logements insalubres"
   eayy_D7_10 = "Problèmes concernant le quartier : aucun de ces problèmes"
   eayy_D7_2 = "Problèmes concernant le quartier : bruits ou pollution"
   eayy_D7_3 = "Problèmes concernant le quartier : voirie insuffisante"
   eayy_D7_4 = "Problèmes concernant le quartier : saleté"
   eayy_D7_5 = "Problèmes concernant le quartier : manque d'espaces verts"
   eayy_D7_6 = "Problèmes concernant le quartier : manque de commerces"
   eayy_D7_7 = "Problèmes concernant le quartier : manque de lieux de rencontre, d'équipements"
   eayy_D7_8 = "Problèmes concernant le quartier : isolement du quartier"
   eayy_D7_9 = "Problèmes concernant le quartier : manque de sécurité"
   eayy_E1A = "Personnes dans le ménage percevant : salaires, traitements et primes"
   eayy_E1B = "Personnes dans le ménage percevant : revenus d'une activité professionnelle non salariée"
   eayy_E1C = "Personnes dans le ménage percevant : allocations de chômage"
   eayy_E1D = "Personnes dans le ménage percevant : préretraites, retraites"
   eayy_E1E = "Personnes dans le ménage percevant : prestations liées à la maladie ou l'invalidité"
   eayy_E1F = "Personnes dans le ménage percevant : prestations familiales et bourses"
   eayy_E1G = "Personnes dans le ménage percevant : allocation logement, aide au logement"
   eayy_E1H = "Personnes dans le ménage percevant : RSA"
   eayy_E1I = "Personnes dans le ménage percevant : loyers et fermages"
   eayy_E1J = "Personnes dans le ménage percevant : pensions, aides"
   eayy_E2A_rec = "Tranche de montant des ressources (calcul)"
   eayy_E2AUC = "Tranche de revenu mensuel du ménage par unité de consommation (calcul)"
   eayy_E2AUC_SOURCE = "Source d'information du montant des ressources par unité de consommation"
   eayy_E3A = "Détention placements financiers : livrets d'épargne"
   eayy_E3B = "Détention placements financiers : épargne-logement"
   eayy_E3C = "Détention placements financiers : assurances-vies"
   eayy_E3D = "Détention placements financiers : épargne retraite"
   eayy_E3E = "Détention placements financiers : valeurs immobilières"
   eayy_E4 = "Résidence secondaire"
   eayy_E5 = "Situation financière actuelle du mènage"
   eayy_E5A = "Baisse de revenu importante les 12 derniers mois"
   eayy_E5B_1 = "Baisse de revenu importante les 12 derniers mois : licenciement/perte d'emploi"
   eayy_E5B_2 = "Baisse de revenu importante les 12 derniers mois : modification du salaire/heures"
   eayy_E5B_3 = "Baisse de revenu importante les 12 derniers mois : invalidité/incapacité"
   eayy_E5B_4 = "Baisse de revenu importante les 12 derniers mois : maternité/congé parental/garde des enfants"
   eayy_E5B_5 = "Baisse de revenu importante les 12 derniers mois : départ à la retraite"
   eayy_E5B_6 = "Baisse de revenu importante les 12 derniers mois : mariage/rupture"
   eayy_E5B_7 = "Baisse de revenu importante les 12 derniers mois : décès"
   eayy_E5B_8 = "Baisse de revenu importante les 12 derniers mois : autre changement dans le ménage"
   eayy_E5B_9 = "Baisse de revenu importante les 12 derniers mois: autre raison"
   eayy_F1_rec = "Fréquence de rencontre des amis (recodage)"
   eayy_F3 = "A quelqu'un pour discuter de questions intimes et personnelles"
   eayy_F4 = "Sentiment de solitude"
   eayy_F5 = "Opinion confiance ou prudence en général"
   eayy_F6_rec = "Fréquence de rencontre de la famille (recodage)"
   eayy_F7 = "Membre association humanitaire ou sociale"
   eayy_F8 = "Membre amicale ou association sportive ou culturelle"
   eayy_G1 = "Télévision les 12 derniers mois"
   eayy_G2 = "Nombre de livres lus les 12 derniers mois"
   eayy_G3A = "Sortie culturelle les 12 derniers mois : au cinéma"
   eayy_G3B = "Sortie culturelle les 12 derniers mois : au théâtre ou au concert"
   eayy_G3C = "Sortie culturelle les 12 derniers mois : au musée ou une exposition"
   eayy_G4 = "Bricolage les 12 derniers mois"
   eayy_G5 = "Maîtrise d'une langue étrangère"
   eayy_G6_1 = "Partir en vacances les 12 derniers mois : non"
   eayy_G6_2 = "Partir en vacances les 12 derniers mois : dans la région"
   eayy_G6_3 = "Partir en vacances les 12 derniers mois : dans une autre région"
   eayy_G6_4 = "Partir en vacances les 12 derniers mois : à l'étranger"
   eayy_H1A = "A une religion (recodage)"
   eayy_H2 = "Importance de la religion"
   eayy_H4 = "Éducation religieuse"
   eayy_I1 = "Intérêt pour la politique"
   eayy_I8 = "Auto-positionnement sur l'échelle gauche/droite"
   eayy_J1 = "État de santé"
   eayy_K3 = "Fréquence activité sportive 30 minutes d'affilée"
   eayy_PCS18 = "Catégorie socioprofessionnelle en 18 postes (profession actuelle ou dernière profession)"
   eayy_PCS6 = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession)"
   eayy_PCS6CJT = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession) (conjoint)"
   eayy_TYPMEN5 = "Type de ménage (calcul)"
   VAGUE = "VAGUE"
   insee_NUTS1 = "Nomenclature des unités territoriales statistiques niv. 1"
   insee_CATAEU2010 = "Catégorie de la commune dans le zonage en aires urbaines 2010"
   insee_TAU2014 = "Tranche d'aire urbaine 2014"
   insee_TUU2014 = "Tranche d'unité urbaine 2014"
   POIDS_coco4 = "Poids individu"
   PDSPLT_coco4 = "Poids individu (panel pilote)"
   coco4_cal_NAT = "Nationalité (calage)"
   POIDS_INIT_coco4 = "Poids initial"
   PDSPLT_INIT_coco4 = "Poids initial (panel pilote)" ;

 /* User Missing Value Specifications */
  IF coco4_q04 = 9999 THEN coco4_q04 =. ;
  IF coco4_q05_c = 7777 OR coco4_q05_c = 8888 OR coco4_q05_c = 9999 THEN coco4_q05_c =. ;
  IF coco4_q06_1 = 9999 THEN coco4_q06_1 =. ;
  IF coco4_q06_2 = 9999 THEN coco4_q06_2 =. ;
  IF coco4_q06_3 = 9999 THEN coco4_q06_3 =. ;
  IF coco4_q06_4 = 9999 THEN coco4_q06_4 =. ;
  IF coco4_q06_5 = 9999 THEN coco4_q06_5 =. ;
  IF coco4_q06_6 = 9999 THEN coco4_q06_6 =. ;
  IF coco4_q06_7 = 9999 THEN coco4_q06_7 =. ;
  IF coco4_q06_8 = 9999 THEN coco4_q06_8 =. ;
  IF coco4_q06_9 = 9999 THEN coco4_q06_9 =. ;
  IF coco4_q06_10 = 9999 THEN coco4_q06_10 =. ;
  IF coco4_q09 = 9999 THEN coco4_q09 =. ;
  IF coco4_q10 = 6666 THEN coco4_q10 =. ;
  IF coco4_q17 = 9999 THEN coco4_q17 =. ;
  IF coco4_q18 = 9999 THEN coco4_q18 =. ;
  IF coco4_q19 = 9999 THEN coco4_q19 =. ;
  IF coco4_q20 = 9999 THEN coco4_q20 =. ;
  IF coco4_q21 = 9999 THEN coco4_q21 =. ;
  IF coco4_q25_a = 9999 THEN coco4_q25_a =. ;
  IF coco4_q38_modifie = 9999 THEN coco4_q38_modifie =. ;
  IF coco4_q62_modifie = 9999 THEN coco4_q62_modifie =. ;
  IF coco4_q63_modifie = 9999 THEN coco4_q63_modifie =. ;
  IF coco4_q64_modifie = 9999 THEN coco4_q64_modifie =. ;
  IF coco4_q68 = 9999 THEN coco4_q68 =. ;
  IF coco4_q79 = 9999 THEN coco4_q79 =. ;
  IF coco4_q125_modifie_1 = 9999 THEN coco4_q125_modifie_1 =. ;
  IF coco4_q125_modifie_2 = 9999 THEN coco4_q125_modifie_2 =. ;
  IF coco4_q125_modifie_3 = 9999 THEN coco4_q125_modifie_3 =. ;
  IF coco4_q125_modifie_4 = 9999 THEN coco4_q125_modifie_4 =. ;
  IF coco4_q125_modifie_5 = 9999 THEN coco4_q125_modifie_5 =. ;
  IF coco4_q141 = 9999 THEN coco4_q141 =. ;
  IF coco4_q143_1 = 9999 THEN coco4_q143_1 =. ;
  IF coco4_q143_2 = 9999 THEN coco4_q143_2 =. ;
  IF coco4_q143_3 = 9999 THEN coco4_q143_3 =. ;
  IF coco4_q143_4 = 9999 THEN coco4_q143_4 =. ;
  IF coco4_q143_5 = 9999 THEN coco4_q143_5 =. ;
  IF coco4_q143_6 = 9999 THEN coco4_q143_6 =. ;
  IF coco4_q143_7 = 9999 THEN coco4_q143_7 =. ;
  IF coco4_q143_8 = 9999 THEN coco4_q143_8 =. ;
  IF coco4_q143_9 = 9999 THEN coco4_q143_9 =. ;
  IF coco4_q144 = 9999 THEN coco4_q144 =. ;
  IF coco4_q145 = 9999 THEN coco4_q145 =. ;
  IF coco4_q146 = 6666 OR coco4_q146 = 9999 THEN coco4_q146 =. ;
  IF coco4_q147 = 6666 OR coco4_q147 = 9999 THEN coco4_q147 =. ;
  IF coco4_q148 = 6666 OR coco4_q148 = 9999 THEN coco4_q148 =. ;
  IF coco4_q149 = 9999 THEN coco4_q149 =. ;
  IF coco4_q150_1 = 9999 THEN coco4_q150_1 =. ;
  IF coco4_q150_2 = 9999 THEN coco4_q150_2 =. ;
  IF coco4_q150_3 = 9999 THEN coco4_q150_3 =. ;
  IF coco4_q150_4 = 9999 THEN coco4_q150_4 =. ;
  IF coco4_q150_5 = 9999 THEN coco4_q150_5 =. ;
  IF coco4_q150_6 = 9999 THEN coco4_q150_6 =. ;
  IF coco4_q150_7 = 9999 THEN coco4_q150_7 =. ;
  IF coco4_q151_1_c = 9999 THEN coco4_q151_1_c =. ;
  IF coco4_q151_2_c = 9999 THEN coco4_q151_2_c =. ;
  IF coco4_q151_3_c = 9999 THEN coco4_q151_3_c =. ;
  IF coco4_q151_4_c = 9999 THEN coco4_q151_4_c =. ;
  IF coco4_q151_5_c = 9999 THEN coco4_q151_5_c =. ;
  IF coco4_q151_6_c = 9999 THEN coco4_q151_6_c =. ;
  IF coco4_q152 = 9999 THEN coco4_q152 =. ;
  IF coco4_q153_1 = 9999 THEN coco4_q153_1 =. ;
  IF coco4_q153_2 = 9999 THEN coco4_q153_2 =. ;
  IF coco4_q153_3 = 9999 THEN coco4_q153_3 =. ;
  IF coco4_q153_4 = 9999 THEN coco4_q153_4 =. ;
  IF coco4_q153_5 = 9999 THEN coco4_q153_5 =. ;
  IF coco4_q153_6 = 9999 THEN coco4_q153_6 =. ;
  IF coco4_q154_1 = 9999 THEN coco4_q154_1 =. ;
  IF coco4_q154_2 = 9999 THEN coco4_q154_2 =. ;
  IF coco4_q154_3 = 9999 THEN coco4_q154_3 =. ;
  IF coco4_q154_4 = 9999 THEN coco4_q154_4 =. ;
  IF coco4_q154_5 = 9999 THEN coco4_q154_5 =. ;
  IF coco4_q155_1 = 9999 THEN coco4_q155_1 =. ;
  IF coco4_q155_2 = 9999 THEN coco4_q155_2 =. ;
  IF coco4_q155_3 = 9999 THEN coco4_q155_3 =. ;
  IF coco4_q155_4 = 9999 THEN coco4_q155_4 =. ;
  IF coco4_q155_5 = 9999 THEN coco4_q155_5 =. ;
  IF coco4_q155_6 = 9999 THEN coco4_q155_6 =. ;
  IF coco4_q155_7 = 9999 THEN coco4_q155_7 =. ;
  IF coco4_q155_8 = 9999 THEN coco4_q155_8 =. ;
  IF coco4_q155_9 = 9999 THEN coco4_q155_9 =. ;
  IF coco4_q155_10 = 9999 THEN coco4_q155_10 =. ;
  IF coco4_SWB = 9999 THEN coco4_SWB =. ;
  IF ea17_SWB = 9999 THEN ea17_SWB =. ;
  IF ea18_SWB = 9999 THEN ea18_SWB =. ;
  IF ea19_SWB = 9999 THEN ea19_SWB =. ;
  IF eayy_A3_rec >= 7 THEN eayy_A3_rec =. ;
  IF eayy_A3B_rec >= 9 THEN eayy_A3B_rec =. ;
  IF eayy_A3C_rec >= 6 THEN eayy_A3C_rec =. ;
  IF eayy_A3D >= 6 THEN eayy_A3D =. ;
  IF eayy_A3E_rec >= 6 THEN eayy_A3E_rec =. ;
  IF eayy_A4 >= 77 THEN eayy_A4 =. ;
  IF eayy_A5 >= 7 THEN eayy_A5 =. ;
  IF eayy_A5A >= 6 OR eayy_A5A = 9996 THEN eayy_A5A =. ;
  IF eayy_A5C >= 6 OR eayy_A5C = 9996 THEN eayy_A5C =. ;
  IF eayy_A5C_rec >= 66 OR eayy_A5C_rec = 9996 THEN eayy_A5C_rec =. ;
  IF eayy_B1 >= 77 THEN eayy_B1 =. ;
  IF eayy_B10A >= 6 THEN eayy_B10A =. ;
  IF eayy_B10AA >= 6 OR eayy_B10AA = 9996 THEN eayy_B10AA =. ;
  IF eayy_B10ACJT >= 6 THEN eayy_B10ACJT =. ;
  IF eayy_B11 >= 6 THEN eayy_B11 =. ;
  IF eayy_B11CJT >= 6 THEN eayy_B11CJT =. ;
  IF eayy_B18_rec >= 77 THEN eayy_B18_rec =. ;
  IF eayy_B18C >= 7 THEN eayy_B18C =. ;
  IF eayy_B18CCJT >= 6 THEN eayy_B18CCJT =. ;
  IF eayy_B18CJT_rec >= 66 THEN eayy_B18CJT_rec =. ;
  IF eayy_B1A >= 6 OR eayy_B1A = 9996 THEN eayy_B1A =. ;
  IF eayy_B1ACJT >= 6 OR eayy_B1ACJT = 9996 THEN eayy_B1ACJT =. ;
  IF eayy_B1B >= 7 THEN eayy_B1B =. ;
  IF eayy_B1BCJT >= 6 THEN eayy_B1BCJT =. ;
  IF eayy_B1CJT >= 66 THEN eayy_B1CJT =. ;
  IF eayy_B2_rec >= 66 THEN eayy_B2_rec =. ;
  IF eayy_B25 >= 6 THEN eayy_B25 =. ;
  IF eayy_B2CJT_rec >= 66 THEN eayy_B2CJT_rec =. ;
  IF eayy_B4_rec >= 6 THEN eayy_B4_rec =. ;
  IF eayy_B4CJT_rec >= 6 THEN eayy_B4CJT_rec =. ;
  IF eayy_B5_rec >= 6 THEN eayy_B5_rec =. ;
  IF eayy_B5A >= 6 THEN eayy_B5A =. ;
  IF eayy_B5B_rec >= 6 THEN eayy_B5B_rec =. ;
  IF eayy_B5C >= 66 THEN eayy_B5C =. ;
  IF eayy_B6A_rec >= 66 THEN eayy_B6A_rec =. ;
  IF eayy_B6B_rec >= 66 THEN eayy_B6B_rec =. ;
  IF eayy_B7B_rec >= 66 THEN eayy_B7B_rec =. ;
  IF eayy_B8_rec >= 6 THEN eayy_B8_rec =. ;
  IF eayy_B9_rec >= 6 THEN eayy_B9_rec =. ;
  IF eayy_C1JEU >= 9 THEN eayy_C1JEU =. ;
  IF eayy_C8 >= 7 OR eayy_C8 = 9996 THEN eayy_C8 =. ;
  IF eayy_C8A_rec >= 6 OR eayy_C8A_rec = 9996 THEN eayy_C8A_rec =. ;
  IF eayy_C8B_rec >= 6 OR eayy_C8B_rec = 9996 THEN eayy_C8B_rec =. ;
  IF eayy_D1_rec >= 7 THEN eayy_D1_rec =. ;
  IF eayy_D1A >= 6 OR eayy_D1A = 9996 THEN eayy_D1A =. ;
  IF eayy_D2 >= 66 THEN eayy_D2 =. ;
  IF eayy_D4_rec >= 99 THEN eayy_D4_rec =. ;
  IF eayy_D5_rec >= 9 THEN eayy_D5_rec =. ;
  IF eayy_D6 >= 9 THEN eayy_D6 =. ;
  IF eayy_D7_1 >= 9 THEN eayy_D7_1 =. ;
  IF eayy_D7_10 >= 9 THEN eayy_D7_10 =. ;
  IF eayy_D7_2 >= 9 THEN eayy_D7_2 =. ;
  IF eayy_D7_3 >= 9 THEN eayy_D7_3 =. ;
  IF eayy_D7_4 >= 9 THEN eayy_D7_4 =. ;
  IF eayy_D7_5 >= 9 THEN eayy_D7_5 =. ;
  IF eayy_D7_6 >= 9 THEN eayy_D7_6 =. ;
  IF eayy_D7_7 >= 9 THEN eayy_D7_7 =. ;
  IF eayy_D7_8 >= 9 THEN eayy_D7_8 =. ;
  IF eayy_D7_9 >= 9 THEN eayy_D7_9 =. ;
  IF eayy_E2A_rec >= 77 THEN eayy_E2A_rec =. ;
  IF eayy_E2AUC >= 66 THEN eayy_E2AUC =. ;
  IF eayy_E3A = 9996 THEN eayy_E3A =. ;
  IF eayy_E3B = 9996 THEN eayy_E3B =. ;
  IF eayy_E3C = 9996 THEN eayy_E3C =. ;
  IF eayy_E3D = 9996 THEN eayy_E3D =. ;
  IF eayy_E3E = 9996 THEN eayy_E3E =. ;
  IF eayy_E4 >= 7 OR eayy_E4 = 9996 THEN eayy_E4 =. ;
  IF eayy_E5 >= 99 THEN eayy_E5 =. ;
  IF eayy_E5A >= 9 OR eayy_E5A = 9996 THEN eayy_E5A =. ;
  IF eayy_E5B_1 >= 6 THEN eayy_E5B_1 =. ;
  IF eayy_E5B_2 >= 6 THEN eayy_E5B_2 =. ;
  IF eayy_E5B_3 >= 6 THEN eayy_E5B_3 =. ;
  IF eayy_E5B_4 >= 6 THEN eayy_E5B_4 =. ;
  IF eayy_E5B_5 >= 6 THEN eayy_E5B_5 =. ;
  IF eayy_E5B_6 >= 6 THEN eayy_E5B_6 =. ;
  IF eayy_E5B_7 >= 6 THEN eayy_E5B_7 =. ;
  IF eayy_E5B_8 >= 6 THEN eayy_E5B_8 =. ;
  IF eayy_E5B_9 >= 6 OR eayy_E5B_9 = 9996 THEN eayy_E5B_9 =. ;
  IF eayy_F1_rec >= 7 THEN eayy_F1_rec =. ;
  IF eayy_F3 >= 8 THEN eayy_F3 =. ;
  IF eayy_F4 >= 7 OR eayy_F4 = 9996 THEN eayy_F4 =. ;
  IF eayy_F5 >= 7 OR eayy_F5 = 9996 THEN eayy_F5 =. ;
  IF eayy_F6_rec >= 7 THEN eayy_F6_rec =. ;
  IF eayy_F7 >= 7 THEN eayy_F7 =. ;
  IF eayy_F8 >= 7 THEN eayy_F8 =. ;
  IF eayy_G1 >= 8 THEN eayy_G1 =. ;
  IF eayy_G2 >= 8 THEN eayy_G2 =. ;
  IF eayy_G3A >= 9 THEN eayy_G3A =. ;
  IF eayy_G3B >= 9 THEN eayy_G3B =. ;
  IF eayy_G3C >= 9 THEN eayy_G3C =. ;
  IF eayy_G4 >= 8 THEN eayy_G4 =. ;
  IF eayy_G5 >= 9 THEN eayy_G5 =. ;
  IF eayy_G6_1 >= 9 THEN eayy_G6_1 =. ;
  IF eayy_G6_2 >= 9 THEN eayy_G6_2 =. ;
  IF eayy_G6_3 >= 9 THEN eayy_G6_3 =. ;
  IF eayy_G6_4 >= 9 THEN eayy_G6_4 =. ;
  IF eayy_H1A >= 7 THEN eayy_H1A =. ;
  IF eayy_H2 >= 7 THEN eayy_H2 =. ;
  IF eayy_H4 >= 7 THEN eayy_H4 =. ;
  IF eayy_I1 >= 8 THEN eayy_I1 =. ;
  IF eayy_I8 >= 77 THEN eayy_I8 =. ;
  IF eayy_J1 >= 7 THEN eayy_J1 =. ;
  IF eayy_K3 >= 9 THEN eayy_K3 =. ;
  IF eayy_PCS18 >= 666 THEN eayy_PCS18 =. ;
  IF eayy_PCS6 >= 66 THEN eayy_PCS6 =. ;
  IF eayy_PCS6CJT >= 66 THEN eayy_PCS6CJT =. ;
  IF eayy_TYPMEN5 >= 6 THEN eayy_TYPMEN5 =. ;
  IF insee_NUTS1 >= 99 THEN insee_NUTS1 =. ;
  IF insee_CATAEU2010 >= 999 THEN insee_CATAEU2010 =. ;
  IF insee_TAU2014 >= 99 THEN insee_TAU2014 =. ;
  IF insee_TUU2014 >= 9 THEN insee_TUU2014 =. ;

FORMAT
   coco4_cal_AGE1 COCO4_CA.   coco4_cal_AGE2 COCO4__A.   coco4_cal_DIPL COCO4__B.
   coco4_cal_SEXE COCO4__C.   coco4_cal_ZEAT COCO4__D.   coco4_q04 COCO4_Q0F.  
   coco4_q05_c COCO4__E.    coco4_q06_1 LABA.        coco4_q06_2 LABA.     
   coco4_q06_3 LABA.        coco4_q06_4 LABA.        coco4_q06_5 LABA.     
   coco4_q06_6 LABA.        coco4_q06_7 LABA.        coco4_q06_8 LABA.     
   coco4_q06_9 LABA.        coco4_q06_10 LABA.       coco4_q07_1 LABB.     
   coco4_q07_2 LABB.        coco4_q07_3 LABB.        coco4_q09 COCO4__S.   
   coco4_q10 COCO4_Q1F.     coco4_q16 COCO4__T.      coco4_q17 LABC.       
   coco4_q18 LABC.          coco4_q19 LABC.          coco4_q20 LABC.       
   coco4_q21 COCO4__X.      coco4_q25_a COCO4__Y.    coco4_q38_modifie COCO4_Q3F.
   coco4_q62_modifie COCO4_Q6F.   coco4_q63_modifie COCO4__Z.   coco4_q64_modifie COCO4_AA.
   coco4_q68 COCO4_AB.      coco4_q79 COCO4_Q7F.     coco4_q125_modifie_1 LABD.
   coco4_q125_modifie_2 LABD.   coco4_q125_modifie_3 LABD.   coco4_q125_modifie_4 LABD.
   coco4_q125_modifie_5 LABD.   coco4_q141 COCO4_AH.     coco4_q142_1 LABB.    
   coco4_q142_2 LABB.       coco4_q142_3 LABB.       coco4_q142_4 LABB.    
   coco4_q143_1 LABE.       coco4_q143_2 LABE.       coco4_q143_3 LABE.    
   coco4_q143_4 LABE.       coco4_q143_5 LABE.       coco4_q143_6 LABE.    
   coco4_q143_7 LABE.       coco4_q143_8 LABE.       coco4_q143_9 LABE.    
   coco4_q144 COCO4_AV.     coco4_q145 COCO4_AW.     coco4_experience_1_DO COCO4_EX.
   coco4_q146 COCO4_AX.     coco4_q147 COCO4_AY.     coco4_q148 COCO4_AZ.  
   coco4_q149 COCO4_BA.     coco4_q150_1 LABF.       coco4_q150_2 LABF.    
   coco4_q150_3 LABF.       coco4_q150_4 LABF.       coco4_q150_5 LABF.    
   coco4_q150_6 LABF.       coco4_q150_7 LABF.       coco4_q152 COCO4_BO.  
   coco4_q153_1 LABH.       coco4_q153_2 LABH.       coco4_q153_3 LABH.    
   coco4_q153_4 LABH.       coco4_q153_5 LABH.       coco4_q153_6 LABH.    
   coco4_q154_1 LABI.       coco4_q154_2 LABI.       coco4_q154_3 LABI.    
   coco4_q154_4 LABI.       coco4_q154_5 LABI.       coco4_q155_1 LABJ.    
   coco4_q155_2 LABJ.       coco4_q155_3 LABJ.       coco4_q155_4 LABJ.    
   coco4_q155_5 LABJ.       coco4_q155_6 LABJ.       coco4_q155_7 LABJ.    
   coco4_q155_8 LABJ.       coco4_q155_9 LABJ.       coco4_q155_10 LABJ.   
   coco4_SWB COCO4_SW.      ea17_SWB LABK.           ea18_SWB LABK.        
   ea19_SWB LABK.           eayy_A1 EAYY_A1F.        eayy_A2A_rec EAYY_A2A.
   eayy_A3_rec EAYY_A3F.    eayy_A3B_rec EAYY_A3B.   eayy_A3C_rec LABL.    
   eayy_A3D EAYY_A3D.       eayy_A3E_rec LABL.       eayy_A4 EAYY_A4F.     
   eayy_A5 EAYY_A5F.        eayy_A5A EAYY_A5A.       eayy_A5C EAYY_A5C.    
   eayy_A5C_rec EAYY_A_A.   eayy_B1 EAYY_B1F.        eayy_B10A EAYY_B10F.  
   eayy_B10AA EAYY_B_A.     eayy_B10ACJT EAYY_B_B.   eayy_B11 LABM.        
   eayy_B11CJT LABM.        eayy_B18_rec EAYY_B18F.   eayy_B18C EAYY_B_D.   
   eayy_B18CCJT EAYY_B_E.   eayy_B18CJT_rec EAYY_B_F.   eayy_B1A LABN.        
   eayy_B1ACJT LABN.        eayy_B1B EAYY_B1B.       eayy_B1BCJT EAYY_B_H. 
   eayy_B1CJT EAYY_B1C.     eayy_B2_rec EAYY_B2F.    eayy_B25 EAYY_B25F.   
   eayy_B2CJT_rec EAYY_B2C.   eayy_B4_rec LABO.        eayy_B4CJT_rec LABO.  
   eayy_B5_rec EAYY_B5F.    eayy_B5A EAYY_B5A.       eayy_B5B_rec EAYY_B5B.
   eayy_B5C EAYY_B5C.       eayy_B6A_rec EAYY_B6A.   eayy_B6B_rec EAYY_B6B.
   eayy_B7B_rec EAYY_B7B.   eayy_B8_rec EAYY_B8F.    eayy_B9_rec EAYY_B9F. 
   eayy_C1_rec EAYY_C1F.    eayy_C1JEU EAYY_C1J.     eayy_C8 EAYY_C8F.     
   eayy_C8A_rec EAYY_C8A.   eayy_C8B_rec EAYY_C8B.   eayy_D1_rec EAYY_D1F. 
   eayy_D1A EAYY_D1A.       eayy_D2 EAYY_D2F.        eayy_D3 EAYY_D3F.     
   eayy_D4_rec EAYY_D4F.    eayy_D5_rec EAYY_D5F.    eayy_D6 EAYY_D6F.     
   eayy_D7_1 LABP.          eayy_D7_10 LABP.         eayy_D7_2 LABP.       
   eayy_D7_3 LABP.          eayy_D7_4 LABP.          eayy_D7_5 LABP.       
   eayy_D7_6 LABP.          eayy_D7_7 LABP.          eayy_D7_8 LABP.       
   eayy_D7_9 LABP.          eayy_E1A LABQ.           eayy_E1B LABQ.        
   eayy_E1C LABQ.           eayy_E1D LABQ.           eayy_E1E LABQ.        
   eayy_E1F LABQ.           eayy_E1G LABQ.           eayy_E1H LABQ.        
   eayy_E1I LABQ.           eayy_E1J LABQ.           eayy_E2A_rec EAYY_E2A.
   eayy_E2AUC EAYY_E_A.     eayy_E2AUC_SOURCE EAYY_E_B.   eayy_E3A LABR.        
   eayy_E3B LABR.           eayy_E3C LABR.           eayy_E3D LABR.        
   eayy_E3E LABR.           eayy_E4 EAYY_E4F.        eayy_E5 EAYY_E5F.     
   eayy_E5A EAYY_E5A.       eayy_E5B_1 LABS.         eayy_E5B_2 LABS.      
   eayy_E5B_3 LABS.         eayy_E5B_4 LABS.         eayy_E5B_5 LABS.      
   eayy_E5B_6 LABS.         eayy_E5B_7 LABS.         eayy_E5B_8 LABS.      
   eayy_E5B_9 LABS.         eayy_F1_rec LABT.        eayy_F3 EAYY_F3F.     
   eayy_F4 EAYY_F4F.        eayy_F5 EAYY_F5F.        eayy_F6_rec LABT.     
   eayy_F7 LABU.            eayy_F8 LABU.            eayy_G1 EAYY_G1F.     
   eayy_G2 EAYY_G2F.        eayy_G3A LABV.           eayy_G3B LABV.        
   eayy_G3C LABV.           eayy_G4 EAYY_G4F.        eayy_G5 EAYY_G5F.     
   eayy_G6_1 LABP.          eayy_G6_2 LABP.          eayy_G6_3 LABP.       
   eayy_G6_4 LABP.          eayy_H1A EAYY_H1A.       eayy_H2 EAYY_H2F.     
   eayy_H4 LABU.            eayy_I1 EAYY_I1F.        eayy_I8 EAYY_I8F.     
   eayy_J1 EAYY_J1F.        eayy_K3 EAYY_K3F.        eayy_PCS18 EAYY_PCS.  
   eayy_PCS6 LABW.          eayy_PCS6CJT LABW.       eayy_TYPMEN5 EAYY_TYP.
   insee_NUTS1 INSEE_NU.    insee_CATAEU2010 INSEE_CA.   insee_TAU2014 INSEE_TA.
   insee_TUU2014 INSEE_TU.   coco4_cal_NAT COCO4_CL. ;
                      

LENGTH
   UID_ANONYM_COVID 4       coco4_cal_AGE1 3         coco4_cal_AGE2 3      
   coco4_cal_DIPL 3         coco4_cal_SEXE 3         coco4_cal_ZEAT 3      
   coco4_q04 3              coco4_q05_c 4            coco4_q06_1 4         
   coco4_q06_2 4            coco4_q06_3 4            coco4_q06_4 4         
   coco4_q06_5 4            coco4_q06_6 4            coco4_q06_7 4         
   coco4_q06_8 4            coco4_q06_9 4            coco4_q06_10 4        
   coco4_q07_1 3            coco4_q07_2 3            coco4_q07_3 3         
   coco4_q09 4              coco4_q10 4              coco4_q16 3           
   coco4_q17 4              coco4_q18 4              coco4_q19 4           
   coco4_q20 4              coco4_q21 4              coco4_q25_a 4         
   coco4_q38_modifie 4      coco4_q62_modifie 4      coco4_q63_modifie 4   
   coco4_q64_modifie 4      coco4_q68 4              coco4_q79 4           
   coco4_q125_modifie_1 4   coco4_q125_modifie_2 4   coco4_q125_modifie_3 4
   coco4_q125_modifie_4 4   coco4_q125_modifie_5 4   coco4_q141 4          
   coco4_q142_1 3           coco4_q142_2 3           coco4_q142_3 3        
   coco4_q142_4 3           coco4_q143_1 4           coco4_q143_2 4        
   coco4_q143_3 4           coco4_q143_4 4           coco4_q143_5 4        
   coco4_q143_6 4           coco4_q143_7 4           coco4_q143_8 4        
   coco4_q143_9 4           coco4_q144 4             coco4_q145 4          
   coco4_experience_1_DO 3   coco4_q146 4             coco4_q147 4          
   coco4_q148 4             coco4_q149 4             coco4_q150_1 4        
   coco4_q150_2 4           coco4_q150_3 4           coco4_q150_4 4        
   coco4_q150_5 4           coco4_q150_6 4           coco4_q150_7 4        
   coco4_q151_1_c 4         coco4_q151_2_c 4         coco4_q151_3_c 4      
   coco4_q151_4_c 4         coco4_q151_5_c 4         coco4_q151_6_c 4      
   coco4_q152 4             coco4_q153_1 4           coco4_q153_2 4        
   coco4_q153_3 4           coco4_q153_4 4           coco4_q153_5 4        
   coco4_q153_6 4           coco4_q154_1 4           coco4_q154_2 4        
   coco4_q154_3 4           coco4_q154_4 4           coco4_q154_5 4        
   coco4_q155_1 4           coco4_q155_2 4           coco4_q155_3 4        
   coco4_q155_4 4           coco4_q155_5 4           coco4_q155_6 4        
   coco4_q155_7 4           coco4_q155_8 4           coco4_q155_9 4        
   coco4_q155_10 4          eayy_A1 3                eayy_A2A_rec 3        
   eayy_A3_rec 3            eayy_A3B_rec 3           eayy_A3C_rec 3        
   eayy_A3D 3               eayy_A3E_rec 3           eayy_A4 3             
   eayy_A5 3                eayy_A5A 4               eayy_A5C 4            
   eayy_A5C_rec 4           eayy_B1 3                eayy_B10A 3           
   eayy_B10AA 4             eayy_B10ACJT 3           eayy_B11 3            
   eayy_B11CJT 3            eayy_B18_rec 3           eayy_B18C 3           
   eayy_B18CCJT 3           eayy_B18CJT_rec 3        eayy_B1A 4            
   eayy_B1ACJT 4            eayy_B1B 3               eayy_B1BCJT 3         
   eayy_B1CJT 3             eayy_B2_rec 3            eayy_B25 3            
   eayy_B2CJT_rec 3         eayy_B4_rec 3            eayy_B4CJT_rec 3      
   eayy_B5_rec 3            eayy_B5A 3               eayy_B5B_rec 3        
   eayy_B5C 3               eayy_B6A_rec 3           eayy_B6B_rec 3        
   eayy_B7B_rec 3           eayy_B8_rec 3            eayy_B9_rec 3         
   eayy_C1_rec 3            eayy_C1JEU 3             eayy_C8 4             
   eayy_C8A_rec 4           eayy_C8B_rec 4           eayy_D1_rec 3         
   eayy_D1A 4               eayy_D2 3                eayy_D3 3             
   eayy_D4_rec 3            eayy_D5_rec 3            eayy_D6 3             
   eayy_D7_1 3              eayy_D7_10 3             eayy_D7_2 3           
   eayy_D7_3 3              eayy_D7_4 3              eayy_D7_5 3           
   eayy_D7_6 3              eayy_D7_7 3              eayy_D7_8 3           
   eayy_D7_9 3              eayy_E1A 3               eayy_E1B 3            
   eayy_E1C 3               eayy_E1D 3               eayy_E1E 3            
   eayy_E1F 3               eayy_E1G 3               eayy_E1H 3            
   eayy_E1I 3               eayy_E1J 3               eayy_E2A_rec 3        
   eayy_E2AUC 3             eayy_E2AUC_SOURCE 3      eayy_E3A 4            
   eayy_E3B 4               eayy_E3C 4               eayy_E3D 4            
   eayy_E3E 4               eayy_E4 4                eayy_E5 3             
   eayy_E5A 4               eayy_E5B_1 4             eayy_E5B_2 4          
   eayy_E5B_3 4             eayy_E5B_4 4             eayy_E5B_5 4          
   eayy_E5B_6 4             eayy_E5B_7 4             eayy_E5B_8 4          
   eayy_E5B_9 4             eayy_F1_rec 3            eayy_F3 3             
   eayy_F4 4                eayy_F5 4                eayy_F6_rec 3         
   eayy_F7 3                eayy_F8 3                eayy_G1 3             
   eayy_G2 3                eayy_G3A 3               eayy_G3B 3            
   eayy_G3C 3               eayy_G4 3                eayy_G5 3             
   eayy_G6_1 3              eayy_G6_2 3              eayy_G6_3 3           
   eayy_G6_4 3              eayy_H1A 3               eayy_H2 3             
   eayy_H4 3                eayy_I1 3                eayy_I8 3             
   eayy_J1 3                eayy_K3 3                eayy_PCS18 4          
   eayy_PCS6 4              eayy_PCS6CJT 4           eayy_TYPMEN5 3        
   VAGUE 4                  insee_NUTS1 3            insee_CATAEU2010 4    
   insee_TAU2014 3          insee_TUU2014 3          coco4_cal_NAT 3 ;

   

RUN ;
