/* This SAS program was automatically generated by Stat/Transfer ver.13.3.984.0312 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco1_2020/donnees_coco1/sas_coco1/fr.cdsp.ddi.elipss.202004coco1.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'C:/Users/21027/Desktop/MAD/ELIPSS/COCO/diffusion/cdsp_coco1_2020/donnees_coco1/sas_coco1/' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = fr_cdsp_ ;

proc format library = library ;
   value COCO1_Q0F
      1 = 'Oui, j''ai été surpris(e)'  
      2 = 'Non, je n''ai pas été surpris(e)' ;
   value COCO1__A
      1 = 'Trop tôt'  
      2 = 'Au bon moment'  
      3 = 'Trop tardivement'  
      4 = 'Le confinement n''était pas nécessaire'  
     .A = 'N''a pas répondu' ;
   value COCO1__B
      1 = '1 semaine'  
      2 = '2 semaines'  
      3 = '3 semaines'  
      4 = '4 semaines'  
      5 = '5 semaines'  
      6 = '6 semaines ou plus'  
     .A = 'N''a pas répondu' ;
   value COCO1__C
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
     .A = 'N''a pas répondu' ;
   value COCO1__D
      1 = 'Moins de 55 kg'  
      2 = 'Entre 55 et 59 kg'  
      3 = 'Entre 60 et 64 kg'  
      4 = 'Entre 65 et 69 kg'  
      5 = 'Entre 70 et 74 kg'  
      6 = 'Entre 75 et 79 kg'  
      7 = 'Entre 80 et 84 kg'  
      8 = 'Entre 85 et et 94 kg'  
      9 = '95 kg et plus'  
     .A = 'Refuse de répondre'  
     .B = 'Ne sait pas'  
     .C = 'Non réponse' ;
   value LABA
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu' ;
   value LABB
      1 = 'Choisi'  
      2 = 'Non Choisi' ;
   value LABC
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu'  
     .B = 'Non concernée' ;
   value COCO1__T
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'N''a pas répondu'  
     .B = 'Non concerné' ;
   value COCO1__U
      1 = 'J’ai été testé(e) positif(ve)'  
      2 = 'J’ai de fortes suspicions d’avoir été atteint(e)'  
      3 = 'Je ne pense pas avoir été atteint(e)'  
     .A = 'N''a pas répondu' ;
   value COCO1_Q1F
      1 = 'Je suis guéri(e)'  
      2 = 'Je suis encore malade mais je vais plutôt bien'  
      3 = 'Je suis malade'  
     .A = 'Non concernée' ;
   value LABD
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value LABE
      1 = 'Oui'  
      2 = 'Non'  
     .A = 'N''a pas répondu' ;
   value COCO1_AC
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais' ;
   value LABF
      1 = 'En permanence'  
      2 = 'Souvent'  
      3 = 'Quelques fois'  
      4 = 'Rarement'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value COCO1_AG
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)' ;
   value COCO1_AH
      1 = 'Dans ma résidence principale'  
      2 = 'Dans ma résidence secondaire'  
      3 = 'Chez d’autres membres de ma famille'  
      4 = 'Chez des amis'  
      5 = 'Ailleurs' ;
   value COCO1_AI
     .A = 'N''a pas répondu' ;
   value LABG
      1 = 'Choisi'  
      2 = 'Non Choisi'  
     .A = 'Non concernée' ;
   value COCO1_AQ
      1 = 'Jamais'  
      2 = 'Rarement'  
      3 = 'Parfois'  
      4 = 'Souvent'  
      5 = 'Très souvent'  
     .A = 'Non concernée' ;
   value COCO1_AR
      1 = 'Moins de 20 m²'  
      2 = 'De 20 à 39 m²'  
      3 = 'De 40 à 59 m²'  
      4 = 'De 60 à 79 m²'  
      5 = 'De 80 à 100 m²'  
      6 = 'Plus de 100 m²'  
     .A = 'N''a pas répondu' ;
   value COCO1_AS
      0 = 'Non'  
      1 = 'Oui'  
     .A = 'N''a pas répondu' ;
   value LABH
      1 = '0'  
      2 = '1'  
      3 = '2'  
      4 = '3'  
      5 = '4'  
      6 = '5+'  
     .A = 'N''a pas répondu' ;
   value COCO1_BA
      1 = 'Oui'  
      2 = 'Non'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BB
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
     .A = 'N''a pas répondu' ;
   value COCO1_BC
      1 = 'Contrat à durée indéterminée'  
      2 = 'Contrat à durée déterminée (autre que saisonnier)'  
      3 = 'Contrat saisonnier'  
      4 = 'Contrat d''intérim ou de travail temporaire'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BD
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
     .A = 'Non concernée' ;
   value COCO1_BE
      1 = 'Agriculteur'  
      2 = 'Artisan, commerçant ou chef d’entreprise'  
      3 = 'Cadre ou profession intellectuelle supérieure'  
      4 = 'Profession intermédiaire (technicien, contremaître, etc.)'  
      5 = 'Employé'  
      6 = 'Ouvrier'  
      7 = 'N’a jamais eu d’activité professionnelle'  
     .A = 'N''a pas répondu' ;
   value COCO1_BF
      1 = 'Toujours'  
      2 = 'Régulièrement'  
      3 = 'Occasionnellement'  
      4 = 'Rarement'  
      5 = 'Jamais'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BG
      1 = 'En congés'  
      2 = 'En congé maladie'  
      3 = 'En congé parental en raison de la garde de mes enfants (auto'  
      4 = 'Au chômage partiel ou chômage technique'  
      5 = 'Au chômage'  
      6 = 'Au travail, que ce soit à la maison ou sur mon lieu habituel'  
      7 = 'Dans une autre situation (précisez) [inputbox]'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BH
      1 = 'Principalement travaillé sur votre lieu de travail habituel'  
      2 = 'Alterné télétravail et travail sur votre lieu de travail hab'  
      3 = 'Principalement été en télétravail'  
     .A = 'Non concernée' ;
   value COCO1_BI
      1 = 'Moins que d’habitude'  
      2 = 'Autant que d’habitude'  
      3 = 'Plus que d’habitude'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_Q4F
      1 = 'Mon activité n’est pas compatible avec le télétravail'  
      2 = 'Mon employeur ne m’a pas permis de faire du télétravail'  
      3 = 'Pour d’autres raisons'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BP
      1 = 'Moins de 400 €'  
      2 = 'De 400 à 599 €'  
      3 = 'De 600 à 799 €'  
      4 = 'De 800 à 999 €'  
      5 = 'De 1000 à 1199 €'  
      6 = 'De 1200 à 1499 €'  
      7 = 'De 1500 à 1799 €'  
      8 = 'De 1800 à 1999 €'  
      9 = 'De 2000 à 2499 €'  
      10 = 'De 2500 à 2999 €'  
      11 = 'De 3000 à 3999 €'  
      12 = 'De 4000 à 5999 €'  
      13 = 'De 6000 à 9999 €'  
      14 = '10000 € et plus'  
     .A = 'N''a pas répondu' ;
   value COCO1_BQ
      1 = 'Oui, ils ont augmenté'  
      2 = 'Oui, ils ont baissé'  
      3 = 'Non, ils n’ont pas changé'  
     .A = 'N''a pas répondu' ;
   value COCO1_BV
      1 = 'Jamais'  
      2 = 'Une fois par semaine ou moins'  
      3 = 'Une fois tous les deux ou trois jours'  
      4 = 'Tous les jours ou presque'  
     .A = 'N''a pas répondu' ;
   value COCO1_BW
      1 = 'Jamais'  
      2 = 'Une seule fois'  
      3 = 'Plusieurs fois'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_BX
      1 = 'Positive'  
      2 = 'Négative'  
     .A = 'Non concernée'  
     .B = 'N''a pas répondu' ;
   value COCO1_Q5F
      1 = 'Positive'  
     .A = 'Non concernée' ;
   value COCO1_BY
      1 = 'Tous les jours d’école ou presque'  
      2 = 'Au moins deux fois par semaine'  
      3 = 'Au moins une fois par semaine'  
      4 = 'Jamais'  
      5 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABI
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABJ
      1 = '8 fois ou plus'  
      2 = 'Entre 5 et 7 fois'  
      3 = '3 ou 4 fois'  
      4 = '1 ou 2 fois'  
      5 = 'Jamais'  
      6 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value LABK
      1 = 'Oui'  
      2 = 'Non' ;
   value LABL
      1 = 'Je n’ai pas fait cette activité'  
      2 = 'Entre 0 et 1 heure'  
      3 = 'Entre 1 et 2 heures'  
      4 = 'Entre 2 et 3 heures'  
      5 = 'Entre 3 et 4 heures'  
      6 = 'Entre 4 et 6 heures'  
      7 = 'Entre 6 et 8 heures'  
      8 = 'Entre 8 et 10 heures'  
      9 = 'Plus de 10 heures'  
     .A = 'N''a pas répondu' ;
   value LABM
      1 = 'Très souvent'  
      2 = 'Souvent'  
      3 = 'Parfois'  
      4 = 'Jamais'  
     .A = 'N''a pas répondu' ;
   value LABN
      1 = 'Beaucoup moins que d’habitude'  
      2 = 'Un peu moins que d’habitude'  
      3 = 'Autant que d’habitude'  
      4 = 'Un peu plus que d’habitude'  
      5 = 'Beaucoup plus que d’habitude'  
      6 = 'Non concerné(e)'  
     .A = 'N''a pas répondu' ;
   value COCO1_EE
      1 = 'C''est une expérience qui nous fait perdre beaucoup de temps'  
      2 = 'C''est une expérience qui permet de prendre du recul et réflé'  
      3 = 'C''est une expérience qui permet de consacrer du temps à des'  
      4 = 'C’est une expérience qui fatigue les nerfs'  
     .A = 'N''a pas répondu' ;
   value COCO1_EF
      1 = 'Plus difficiles que celles de la plupart des Français'  
      2 = 'Proches de celles de la plupart des Français'  
      3 = 'Meilleures que celles de la plupart des Français'  
     .A = 'N''a pas répondu' ;
   value COCO1_EG
      0 = '0 - Pas du tout'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Énormément'  
     .A = 'N''a pas répondu' ;
   value COCO1_EH
      1 = 'Une manière de mieux comprendre et de mieux agir en conséque'  
      2 = 'Une source supplémentaire d’angoisse'  
      3 = 'Une source de confusion'  
     .A = 'N''a pas répondu' ;
   value COCO1_EI
      0 = '0 - Très difficile'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '5 - Ni facile, ni difficile'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Très facile'  
     .A = 'N''a pas répondu' ;
   value COCO1_EJ
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n’est jamais assez prudent quand on a affaire aux autres'  
     .A = 'N''a pas répondu' ;
   value COCO1_EK
      1 = 'Tout à fait satisfait(e)'  
      2 = 'Plutôt satisfait(e)'  
      3 = 'Plutôt pas satisfait(e)'  
      4 = 'Pas du tout satisfait(e)'  
     .A = 'N''a pas répondu' ;
   value LABO
      1 = 'Tout à fait d’accord'  
      2 = 'Plutôt d’accord'  
      3 = 'Plutôt pas d’accord'  
      4 = 'Pas d’accord du tout'  
     .A = 'N''a pas répondu' ;
   value COCO1_ET
      0 = '0 - Conséquences sanitaires'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Conséquences économiques'  
     .A = 'N''a pas répondu' ;
   value COCO1_Q8F
      1 = 'L’impact économique sera transitoire'  
      2 = 'L’impact économique sera durable'  
     .A = 'N''a pas répondu' ;
   value LABP
      0 = '0 - Très pessimiste'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '5 - Ni optimiste, ni pessimiste'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = '10 - Très optimiste'  
     .A = 'N''a pas répondu' ;
   value LABQ
      1 = 'Pas du tout'  
      2 = 'Un peu'  
      3 = 'Assez'  
      4 = 'Beaucoup'  
     .A = 'N''a pas répondu' ;
   value COCO1_FJ
      1 = 'Oui, j’accepte de participer à ce dispositif exceptionnel et'  
      2 = 'Non, je ne souhaite pas participer à ce dispositif exception' ;
   value EAYY_A1F
      1 = 'Un homme'  
      2 = 'Une femme' ;
   value EAYY_A2A
      4 = 'Moins de 24 ans'  
      5 = 'De 25 à 29 ans'  
      6 = 'De 30 à 34 ans'  
      7 = 'De 35 à 39 ans'  
      8 = 'De 40 à 44 ans'  
      9 = 'De 45 à 49 ans'  
      10 = 'De 50 à 54 ans'  
      11 = 'De 55 à 59 ans'  
      12 = 'De 60 à 64 ans'  
      13 = 'De 65 à 69 ans'  
      14 = '70 ans et plus' ;
   value EAYY_A3F
      1 = 'Oui, de naissance'  
      2 = '(Oui par réintégration, naturalisation, par mariage, par déc'  
      3 = 'Non'  
      4 = 'Apatride' ;
   value EAYY_A3B
      1 = 'France'  
      2 = 'Union européenne'  
      3 = 'Hors Union européenne'  
      9 = 'N''a pas répondu' ;
   value LABR
      1 = 'Union européenne'  
      2 = 'Hors Union européenne'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_A4F
      1 = 'Célibataire (jamais légalement marié(e))'  
      2 = 'Pacsé(e)'  
      3 = 'Union libre ou concubinage'  
      4 = 'Marié(e) (ou séparé(e) mais non divorcé(e))'  
      5 = 'Divorcé(e)'  
      6 = 'Pacs dissout'  
      7 = 'Veuf(ve)'  
      77 = 'Refuse de répondre' ;
   value EAYY_A5F
      1 = 'Oui, avec quelqu''un qui vit dans votre logement'  
      2 = 'Oui, avec quelqu''un qui ne vit pas dans votre logement'  
      3 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_A5A
      1 = 'Marié(e)'  
      2 = 'Pacsé(e)'  
      3 = 'En union libre, en concubinage'  
      4 = 'Autre (précisez)'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A5C
      1 = 'Depuis moins d’un an'  
      2 = 'Depuis un an ou plus'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_A_A
      1 = 'Moins de 2 ans'  
      2 = 'De 2 à 4 ans'  
      3 = 'De 5 à 9 ans'  
      4 = 'De 10 à 14 ans'  
      5 = 'De 15 à 19 ans'  
      6 = 'De 20 à 24 ans'  
      7 = '25 ans et plus'  
      66 = 'Non concerné'  
      99 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1F
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      77 = 'Refuse de répondre' ;
   value EAYY_B10F
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B_A
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B_B
      1 = 'Oui, depuis moins d''un an'  
      2 = 'Oui, depuis un an ou plus'  
      3 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de réponse'  
      8 = 'Ne sait pas' ;
   value LABS
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné' ;
   value EAYY_B18F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,' ;
   value EAYY_B_D
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire (' ;
   value EAYY_B_E
      1 = 'Niveau VI : sans diplôme ou Brevet des collèges'  
      2 = 'Niveau V : CAP ou BEP'  
      3 = 'Niveau IV : Baccalauréat général, technologique ou professio'  
      4 = 'Niveau III : diplômes de niveau Bac+2 (DUT, BTS, DEUG, école'  
      5 = 'Niveau II et I : diplômes de 2nd et 3e cycle universitaire ('  
      6 = 'Non concerné' ;
   value EAYY_B_F
      1 = '(Aucun diplôme)'  
      4 = 'CEP (certificat d''études primaires)'  
      5 = 'BEPC, brevet élementaire, brevet des collèges'  
      6 = 'CAP, brevet de compagnon'  
      7 = 'BEP'  
      8 = 'Baccalauréat général, brevet supérieur'  
      9 = 'Baccalauréat technologique ou professionnel, brevet professi'  
      10 = 'Diplôme de 1er cycle universitaire, BTS, DUT, diplôme des pr'  
      11 = 'Diplôme de 2e ou 3e cycle universitaire (y compris médecine,'  
      66 = 'Non concerné' ;
   value LABT
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_B1B
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      7 = 'Refuse de répondre' ;
   value EAYY_B_H
      1 = 'Est en activité'  
      2 = 'N''est pas en activité'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre' ;
   value EAYY_B1C
      1 = 'En emploi'  
      2 = 'En apprentissage sous contrat ou en stage rémunéré'  
      3 = 'Chômeur (ayant déjà travaillé)'  
      4 = 'Chômeur (à la recherche d''un premier emploi)'  
      5 = 'En études (étudiant(e), élève, en formation ou en stage non'  
      6 = 'Retraité(e) ou retiré(e) des affaires ou en préretraite'  
      7 = 'Femme ou homme au foyer'  
      8 = 'Dans une autre situation d''inactivité (personne handicapée,'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre' ;
   value EAYY_B2F
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salarié(e) d''un particulier'  
      7 = 'Vous aidez un membre de votre famille dans son travail sans'  
      8 = 'Vous êtes chef d''entreprise salarié, PDG, gérant(e) minorita'  
      9 = 'Vous êtes indépendant(e) ou à votre compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B25F
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_B2C
      1 = 'Salarié(e) de l''État'  
      2 = 'Salarié(e) d''une collectivité territoriale, des HLM'  
      3 = 'Salarié(e) de la fonction publique hospitalière'  
      4 = 'Salarié(e) d''une entreprise publique'  
      5 = 'Salarié(e) d''une entreprise, d''un artisan, d''une association'  
      6 = 'Salairé(e) d''un particulier'  
      7 = 'Il(elle) aide un membre de sa famille dans son travail sans'  
      8 = 'Il(elle) est chef d''entreprise salarié, PDG, gérant(e) minor'  
      9 = 'Il(elle) est indépendant(e) ou à son compte'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value LABU
      1 = 'Aucun salarié'  
      2 = 'Au moins 1 salarié'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B5F
      1 = 'Contrat à durée indéterminée'  
      2 = '(Contrat à durée déterminée (dont contrat saisonnier))'  
      4 = 'Contrat d''interim ou de travail temporaire'  
      5 = 'Contrat d''apprentissage'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5A
      1 = 'À temps complet'  
      2 = 'À temps partiel'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu' ;
   value EAYY_B5B
      1 = '(80% et plus)'  
      3 = 'Entre 50 et 80%'  
      4 = 'Mi-temps (50%)'  
      5 = 'Moins d''un mi-temps (moins de 50%)'  
      6 = 'Non concerné' ;
   value EAYY_B5C
      1 = 'Pour exercer une autre activité professionnelle, ou suivre d'  
      2 = 'Pour raisons de santé'  
      3 = 'Vous n''avez pas trouvé d''emploi à temps plein'  
      4 = 'Cela vous a été imposé par votre employeur'  
      5 = 'Pour vous occuper de vos enfants, ou d''un autre membre de vo'  
      6 = 'Pour disposer de temps libre ou faire des travaux domestique'  
      7 = 'Pour une autre raison (précisez)'  
      66 = 'Non concerné' ;
   value EAYY_B6A
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvier(e) qualifié(e) ou hautement qualifié(e), technicien(n'  
      3 = 'Technicien(ne)'  
      4 = 'Agent de maîtrise, maîtrise administrative ou commerciale, V'  
      5 = 'Ingénieur, cadre (à l''exception des directeurs généraux ou d'  
      6 = 'Employé(e) de bureau, employé(e) de commerce, personnel de s'  
      7 = 'Directeur général, adjoint direct'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B6B
      1 = 'Manœuvre ou ouvrier(e) spécialisé(e)'  
      2 = 'Ouvrier(e) qualifié(e) ou hautement qualifié(e), technicien('  
      3 = 'Technicien(ne)'  
      4 = 'Personnel de catégorie C ou assimilé'  
      5 = 'Personnel de catégorie B ou assimilé'  
      6 = 'Personnel de catégorie A ou assimilé'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B7B
      1 = 'Production, chantier, exploitation'  
      2 = 'Installation, réparation, maintenance'  
      3 = 'Gardiennage, nettoyage, entretien ménager'  
      4 = 'Manutention, magasinage, logistique'  
      5 = 'Secrétariat, saisie, accueil'  
      6 = 'Gestion, comptabilité'  
      7 = 'Commercial, technico-commercial'  
      8 = 'Études, recherche et développement, méthodes'  
      9 = 'Enseignement'  
      10 = 'Soin des personnes'  
      11 = 'Autre fonction (précisez)'  
      66 = 'Non concerné'  
      88 = 'Ne sait pas' ;
   value EAYY_B8F
      1 = 'Moins de 10'  
      2 = '10 à 49'  
      3 = '50 à 499'  
      4 = '500 et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_B9F
      1 = 'Moins de 20 hectares'  
      2 = 'De 20 à moins de 50 hectares'  
      3 = 'De 50 à moins de 100 hectares'  
      4 = 'De 100 à moins de 200 hectares'  
      5 = '200 hectares et plus'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas' ;
   value EAYY_C1F
      1 = '1 habitant'  
      2 = '2 habitants'  
      3 = '3 habitants'  
      4 = '4 habitants'  
      5 = '5 habitants'  
      6 = '6 habitants et plus' ;
   value EAYY_C1J
      1 = '0 jeune'  
      2 = '1 jeune'  
      3 = '2 jeunes'  
      4 = '3 jeunes ou plus' ;
   value EAYY_C8F
      1 = 'Oui'  
      2 = 'Non'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8A
      1 = '1 enfant'  
      2 = '2 enfants'  
      3 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_C8B
      1 = '0 enfant'  
      2 = '1 enfant'  
      3 = '2 enfants'  
      4 = '3 enfants ou plus'  
      6 = 'Non concerné'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D1F
      1 = 'Propriétaire (ou copropriétaire) : vous ne payez pas de créd'  
      2 = 'Accédant à la propriété : vous payez toujours un crédit immo'  
      3 = '(Locataire, sous-locataire)'  
      5 = 'Occupant à titre gratuit'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_D1A
      1 = 'Oui'  
      2 = 'Non'  
      6 = 'Non concerné'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_D2F
      1 = 'Votre conjoint(e)'  
      2 = 'Un autre membre du foyer'  
      3 = 'Une autre personne de votre famille'  
      4 = 'Un autre particulier'  
      5 = 'Un organisme HLM (ou assimilé, OPAC, offices, sociétés, fond'  
      6 = 'Une administration, organisme de Sécurité Sociale ou associa'  
      7 = 'Une banque, assurance ou autre société du secteur public ou'  
      8 = 'L''employeur d''un membre du ménage dans le cadre d''un logemen'  
      9 = 'Autre cas'  
      66 = 'Non concerné'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_D3F
      1 = 'Une maison individuelle'  
      2 = 'Un appartement'  
      3 = 'Autre (précisez)' ;
   value EAYY_D4F
      1 = '1 pièce'  
      2 = '2 pièces'  
      3 = '3 pièces'  
      4 = '4 pièces'  
      5 = '5 pièces'  
      6 = '6 pièces'  
      7 = '7 pièces'  
      8 = '8 pièces'  
      9 = '9 pièces et plus' ;
   value EAYY_D5F
      1 = 'Moins de 2 ans'  
      2 = 'Entre 2 à 5 ans'  
      3 = 'Entre 5 et 10 ans'  
      4 = 'Entre 10 et 15 ans'  
      5 = 'Il y a plus de 15 ans'  
      9 = 'N''a pas répondu' ;
   value EAYY_D6F
      1 = 'Maisons dispersées, hors agglomération'  
      2 = 'Maisons en lotissement, en quartier pavillonnaire ou en vill'  
      3 = 'Immeubles en ville (autre que cité ou grand ensemble)'  
      4 = 'Immeubles en cité ou grand ensemble'  
      5 = 'Habitat mixte : à la fois immeubles et maisons'  
      9 = 'N''a pas répondu' ;
   value LABV
      1 = 'Choisi'  
      2 = 'Non choisi'  
      9 = 'N''a pas répondu' ;
   value LABW
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas' ;
   value EAYY_E2A
      3 = '(Moins de 800 €)'  
      4 = 'De 800 à moins de 1000 €'  
      5 = 'De 1000 à moins de 1200 €'  
      6 = 'De 1200 à moins de 1500 €'  
      7 = 'De 1500 à moins de 1800 €'  
      8 = 'De 1800 à moins de 2000 €'  
      9 = 'De 2000 à moins de 2500 €'  
      10 = 'De 2500 à moins de 3000 €'  
      11 = 'De 3000 à moins de 4000 €'  
      12 = 'De 4000 à moins de 6000 €'  
      13 = '(6000 € et plus)'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_E_A
      1 = 'Moins de 650 €'  
      2 = 'De 650 à moins de 950 €'  
      3 = 'De 950 à moins de 1200 €'  
      4 = 'De 1200 à moins de 1400 €'  
      5 = 'De 1400 à moins de 1650 €'  
      6 = 'De 1650 à moins de 1900 €'  
      7 = 'De 1900 à moins de 2200 €'  
      8 = 'De 2200 à moins de 2500 €'  
      9 = 'De 2500 à moins de 3200 €'  
      10 = '3200 € et plus'  
      99 = 'N''a pas répondu' ;
   value EAYY_E_B
      1 = 'À partir du montant déclaré des ressources'  
      2 = 'À partir de la tranche déclarée des ressources'  
      3 = 'Non calculé' ;
   value LABX
      1 = 'Oui'  
      2 = 'Non'  
      3 = 'Je ne sais pas'  
     .A = 'Non enquêté(e)' ;
   value EAYY_E4F
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
     .B = 'Non enquêté(e)' ;
   value EAYY_E5F
      1 = 'Vous ne pouvez pas y arriver sans faire de dettes'  
      2 = 'Vous y arrivez difficilement'  
      3 = 'C''''est juste, il faut faire attention'  
      4 = 'Ça va'  
      5 = 'Vous êtes plutôt à l''''aise'  
      6 = 'Vous êtes vraiment à l''''aise'  
      99 = 'N''a pas répondu' ;
   value EAYY_E5A
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABY
      1 = 'Choisi'  
      2 = 'Non choisi'  
      6 = 'Non concerné'  
      9 = 'N''a pas répondu'  
     .B = 'Non enquêté(e)' ;
   value LABZ
      1 = 'Au moins une fois par semaine'  
      2 = 'Une à trois fois par mois'  
      3 = 'Plusieurs fois dans l''année (mais moins d''une fois par mois)'  
      4 = 'Seulement pour des occasions exceptionnelles'  
      5 = 'Jamais'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_F3F
      1 = 'Il n''y en a pas'  
      2 = '1 ou 2 personnes'  
      3 = 'Entre 3 et 5 personnes'  
      4 = '6 personnes ou plus'  
      8 = 'Ne sait pas' ;
   value EAYY_F4F
      1 = 'Très seul(e)'  
      2 = 'Plutôt seul(e)'  
      3 = 'Plutôt entouré(e)'  
      4 = 'Très entouré(e)'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value EAYY_F5F
      1 = 'On peut faire confiance à la plupart des gens'  
      2 = 'On n''est jamais assez prudent quand on a affaire aux autres'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas'  
     .B = 'Non enquêté(e)' ;
   value LABAA
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_G1F
      1 = 'Moins de 2 heures par jour'  
      2 = 'De 2 à 4 heures par jour'  
      3 = 'Plus de 4 heures par jour'  
      4 = 'Je ne regarde par la télévision'  
      8 = 'Ne sait pas' ;
   value EAYY_G2F
      1 = 'Aucun'  
      2 = 'Moins de 6'  
      3 = 'De 6 à moins de 12'  
      4 = 'De 12 à 24 (c''est-à-dire entre 1 et 2 livres par mois)'  
      5 = 'De 25 à 50 (c''est-à-dire plus de 2 livres par mois)'  
      6 = 'Plus de 50 (c''est-à-dire plus de 4 livres par mois)'  
      8 = 'Ne sait pas' ;
   value LABAB
      1 = 'Jamais'  
      2 = '1 à 3 fois'  
      3 = '4 à 6 fois'  
      4 = '7 à 12 fois'  
      5 = 'Plus de 12 fois'  
      9 = 'N''a pas répondu' ;
   value EAYY_G4F
      1 = 'Régulièrement tout au long de l''année'  
      2 = 'De temps en temps tout au long de l''année'  
      3 = 'Seulement pendant certaines périodes ou pendant les vacances'  
      4 = 'Occasionnellement ou rarement'  
      5 = 'Jamais'  
      8 = 'Ne sait pas' ;
   value EAYY_G5F
      1 = 'Oui'  
      2 = 'Non'  
      9 = 'N''a pas répondu' ;
   value EAYY_H1A
      1 = 'Oui'  
      2 = 'Non'  
      7 = 'Refuse de répondre' ;
   value EAYY_H2F
      1 = 'Pas du tout d''importance'  
      2 = 'Un peu d''importance'  
      3 = 'Assez d''importance'  
      4 = 'Beaucoup d''importance'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_I1F
      1 = 'Beaucoup'  
      2 = 'Assez'  
      3 = 'Peu'  
      4 = 'Pas du tout'  
      8 = 'Ne sait pas' ;
   value EAYY_I8F
      0 = 'Gauche'  
      1 = '--1--'  
      2 = '--2--'  
      3 = '--3--'  
      4 = '--4--'  
      5 = '--5--'  
      6 = '--6--'  
      7 = '--7--'  
      8 = '--8--'  
      9 = '--9--'  
      10 = 'Droite'  
      77 = 'Refuse de répondre'  
      88 = 'Ne sait pas' ;
   value EAYY_J1F
      1 = 'Très bonne'  
      2 = 'Bonne'  
      3 = 'Assez bonne'  
      4 = 'Mauvaise'  
      5 = 'Très mauvaise'  
      7 = 'Refuse de répondre'  
      8 = 'Ne sait pas' ;
   value EAYY_K3F
      1 = 'Tous les jours ou presque'  
      2 = 'Plusieurs fois par semaine'  
      3 = 'Une fois par semaine'  
      4 = 'Une à trois fois par mois'  
      5 = 'Moins souvent'  
      9 = 'N''a pas répondu' ;
   value EAYY_PCS
      10 = 'Agriculteurs exploitants'  
      20 = '(Artisans, commerçants et chefs d''entreprise)'  
      31 = 'Professions libérales et assimilés'  
      32 = 'Cadres de la fonction publique, professions intellectuelles'  
      36 = 'Cadres d''entreprise'  
      41 = 'Professions intermédiaires de l''enseignement, de la santé, d'  
      46 = 'Professions intermédiaires administratives et commerciales d'  
      47 = 'Techniciens'  
      48 = 'Contremaîtres, agents de maîtrise'  
      51 = 'Employés de la fonction publique'  
      54 = 'Employés administratifs d''entreprise'  
      55 = 'Employés de commerce'  
      56 = 'Personnels des services directs aux particuliers'  
      61 = 'Ouvriers qualifiés'  
      66 = '(Ouvriers non qualifiés et ouvriers agricoles)'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value LABAC
      1 = 'Agriculteurs exploitants'  
      2 = 'Artisans, commerçants et chefs d''entreprise'  
      3 = 'Cadres et professions intellectuelles supérieures'  
      4 = 'Professions intermédiaires'  
      5 = 'Employés'  
      6 = 'Ouvriers'  
      666 = 'Non concerné'  
      999 = 'N''a pas répondu' ;
   value EAYY_TYP
      1 = 'Ménages d''une seule personne'  
      2 = 'Familles monoparentales'  
      3 = 'Couples sans enfant'  
      4 = 'Couples avec enfant(s)'  
      5 = 'Ménages complexes de plus d''une personne' ;
   value COCO1_CA
      1 = '18-24 ans'  
      2 = '25-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-79 ans' ;
   value COCO1_FK
      1 = '18-22 ans'  
      2 = '23-34 ans'  
      3 = '35-44 ans'  
      4 = '45-54 ans'  
      5 = '55-64 ans'  
      6 = '65-75 ans'  
      7 = '76-79 ans' ;
   value COCO1_FL
      1 = 'Aucun/CEP/BEPC'  
      2 = 'CAP/BEP'  
      3 = 'Bac/Bac+2'  
      4 = 'Bac+3 et plus' ;
   value COCO1_FM
      1 = 'Homme'  
      2 = 'Femme' ;
   value COCO1_FN
      1 = 'Région parisienne'  
      2 = 'Bassin parisien'  
      3 = 'Nord'  
      4 = 'Est'  
      5 = 'Ouest'  
      6 = 'Sud-ouest'  
      7 = 'Centre-est'  
      8 = 'Méditerranée' ;
   value COCO1_FO
      1 = 'Français(e)'  
      2 = 'A acquis la nationalité française'  
      3 = 'Nationalité étrangère' ;
   value INSEE_NU
      1 = 'FR1 : Région parisienne'  
      2 = 'FR2 : Bassin parisien'  
      3 = 'FR3 : Nord'  
      4 = 'FR4 : Est'  
      5 = 'FR5 : Ouest'  
      6 = 'FR6 : Sud-ouest'  
      7 = 'FR7 : Centre-est'  
      8 = 'FR8 : Méditerranée'  
      9 = 'FRA : Départements d''Outre-Mer' ;
   value INSEE_TA
      0 = 'Commune hors aire urbaine'  
      1 = 'Commune appartenant à une aire urbaine de moins de 15 000 ha'  
      2 = 'Commune appartenant à une aire urbaine de 15 000 à 19 999 ha'  
      3 = 'Commune appartenant à une aire urbaine de 20 000 à 24 999 ha'  
      4 = 'Commune appartenant à une aire urbaine de 25 000 à 34 999 ha'  
      5 = 'Commune appartenant à une aire urbaine de 35 000 à 49 999 ha'  
      6 = 'Commune appartenant à une aire urbaine de 50 000 à 99 999 ha'  
      7 = 'Commune appartenant à une aire urbaine de 100 000 à 199 999'  
      8 = 'Commune appartenant à une aire urbaine de 200 000 à 499 999'  
      9 = 'Commune appartenant à une aire urbaine de 500 000 à 9 999 99'  
      10 = 'Commune appartenant à l''aire urbaine de Paris' ;
   value INSEE_TU
      0 = 'Commune rurale'  
      1 = 'Commune appartenant à une unité urbaine de 2 000 à 4 999 hab'  
      2 = 'Commune appartenant à une unité urbaine de 5 000 à 9 999 hab'  
      3 = 'Commune appartenant à une unité urbaine de 10 000 à 19 999 h'  
      4 = 'Commune appartenant à une unité urbaine de 20 000 à 49 999 h'  
      5 = 'Commune appartenant à une unité urbaine de 50 000 à 99 999 h'  
      6 = 'Commune appartenant à une unité urbaine de 100 000 à 199 999'  
      7 = 'Commune appartenant à une unité urbaine de 200 000 à 1 999 9'  
      8 = 'Commune appartenant à l''unité urbaine de Paris' ;
   value INSEE_CA
      111 = 'Commune appartenant à un grand pôle (10 000 emplois ou plus)'  
      112 = 'Commune appartenant à la couronne d''un grand pôle'  
      120 = 'Commune multipolarisée des grandes aires urbaines'  
      211 = 'Commune appartenant à un moyen pôle (5 000 à moins de 10 000'  
      212 = 'Commune appartenant à la couronne d''un moyen pôle'  
      221 = 'Commune appartenant à un petit pôle (de 1 500 à moins de 5 0'  
      222 = 'Commune appartenant à la couronne d''un petit pôle'  
      300 = 'Autre commune multipolarisée'  
      400 = 'Commune isolée hors influence des pôles' ;

DATA library.&dataset ;
INFILE datafile LRECL=984;
INPUT
   UID_ANONYM_COVID  1-4    coco1_q01  5             coco1_q02  6-9        
   coco1_q03  10-13         coco1_q04  14-17         coco1_q05_c  18-21    
   coco1_q06_1  22-25       coco1_q06_2  26-29       coco1_q06_3  30-33    
   coco1_q06_4  34-37       coco1_q06_5  38-41       coco1_q06_6  42-45    
   coco1_q06_7  46-49       coco1_q06_8  50-53       coco1_q06_9  54-57    
   coco1_q06_10  58-61      coco1_q07_1  62          coco1_q07_2  63       
   coco1_q07_3  64          coco1_q08_1  65-68       coco1_q08_2  69-72    
   coco1_q08_3  73-76       coco1_q09  77-80         coco1_q10  81-84      
   coco1_q11_1  85-88       coco1_q11_2  89-92       coco1_q11_3  93-96    
   coco1_q12  97-100        coco1_q13  101-104       coco1_q14  105-108    
   coco1_q15  109-112       coco1_q16  113           coco1_q17  114-117    
   coco1_q18  118-121       coco1_q19  122-125       coco1_q20  126-129    
   coco1_q21  130           coco1_q22  131           coco1_q23  132-135    
   coco1_q24_1  136-139     coco1_q24_2  140-143     coco1_q24_3  144-147  
   coco1_q24_4  148-151     coco1_q24_5  152-155     coco1_q24_6  156      
   coco1_q24_7  157         coco1_q25  158-161       coco1_q26  162-165    
   coco1_q26_rec  166       coco1_q27_1  167-170     coco1_q27_2  171-174  
   coco1_q27_3  175-178     coco1_q27_4  179-182     coco1_q27_5  183-186  
   coco1_q28  187-190       coco1_q29  191-194       coco1_q30  195-198    
   coco1_q31  199-202       coco1_q32  203-206       coco1_q33  207-210    
   coco1_q34  211-214       coco1_q35  215-218       coco1_q36  219-222    
   coco1_q37  223-226       coco1_q38  227-230       coco1_q39  231-234    
   coco1_q40  235-238       coco1_q41_1  239-242     coco1_q41_2  243-246  
   coco1_q41_3  247-250     coco1_q41_4  251-254     coco1_q41_5  255-258  
   coco1_q41_6  259-262     coco1_q44  263-266       coco1_q45  267-270    
   coco1_q46_1  271-274     coco1_q46_2  275-278     coco1_q46_3  279-282  
   coco1_q46_4  283-286     coco1_q47  287-290       coco1_q48  291-294    
   coco1_q49  295-298       coco1_q50  299-302       coco1_q51  303-306    
   coco1_q52_1  307-310     coco1_q52_2  311-314     coco1_q52_3  315-318  
   coco1_q52_4  319-322     coco1_q53_1  323-326     coco1_q53_2  327-330  
   coco1_q53_3  331-334     coco1_q54_1  335-338     coco1_q54_2  339-342  
   coco1_q54_3  343-346     coco1_q54_4  347-350     coco1_q54_5  351-354  
   coco1_q54_6  355-358     coco1_q54_7  359-362     coco1_q54_8  363-366  
   coco1_q54_bis_1  367-370   coco1_q54_bis_2  371-374
   coco1_q54_bis_3  375-378   coco1_q54_bis_4  379-382
   coco1_q54_bis_5  383-386   coco1_q54_bis_6  387-390
   coco1_q54_bis_7  391-394   coco1_q55  395           coco1_q56  396-399    
   coco1_q57  400-403       coco1_q58_1  404-407     coco1_q58_2  408-411  
   coco1_q58_3  412-415     coco1_q58_4  416-419     coco1_q58_5  420-423  
   coco1_q58_6  424-427     coco1_q58_7  428-431     coco1_q59_1  432-435  
   coco1_q59_2  436-439     coco1_q59_3  440-443     coco1_q59_4  444-447  
   coco1_q59_5  448-451     coco1_q59_6  452-455     coco1_q59_7  456-459  
   coco1_q59_8  460-463     coco1_q59_9  464-467     coco1_q60_1  468-471  
   coco1_q60_2  472-475     coco1_q60_3  476-479     coco1_q60_4  480-483  
   coco1_q60_5  484-487     coco1_q60_6  488-491     coco1_q61_1  492-495  
   coco1_q61_2  496-499     coco1_q61_3  500-503     coco1_q61_4  504-507  
   coco1_q61_5  508-511     coco1_q61_6  512-515     coco1_q61_7  516-519  
   coco1_q61_8  520-523     coco1_q61_9  524-527     coco1_q61_10  528-531 
   coco1_q62  532-535       coco1_q63  536-539       coco1_q64  540-543    
   coco1_q65  544-547       coco1_q66  548-551       coco1_q67  552-555    
   coco1_q68  556-559       coco1_q69  560-563       coco1_q70  564-567    
   coco1_q71  568-571       coco1_q72  572-575       coco1_q73  576-579    
   coco1_q74  580-583       coco1_q75  584-587       coco1_q76  588-591    
   coco1_q77  592-595       coco1_q79  596-599       coco1_q80  600-603    
   coco1_q81  604-607       coco1_q82  608-611       coco1_q83  612-615    
   coco1_q83_1  616-619     coco1_q83_2  620-623     coco1_q83_3  624-627  
   coco1_q83_4  628-631     coco1_q83_5  632-635     coco1_q83_6  636-639  
   coco1_q83_7  640-643     coco1_q83_8  644-647     coco1_q83_9  648-651  
   coco1_q83_10  652-655    coco1_q84  656-659       coco1_q85  660-663    
   coco1_q86  664           eayy_A1  665             eayy_A2A_rec  666-667 
   eayy_A3_rec  668         eayy_A3B_rec  669        eayy_A3C_rec  670     
   eayy_A3D  671            eayy_A3E_rec  672        eayy_A4  673-674      
   eayy_A5  675             eayy_A5A  676-679        eayy_A5C  680-683     
   eayy_A5C_rec  684-687    eayy_B1  688-689         eayy_B10A  690        
   eayy_B10AA  691-694      eayy_B10ACJT  695        eayy_B11  696         
   eayy_B11CJT  697         eayy_B18_rec  698-699    eayy_B18C  700        
   eayy_B18CCJT  701        eayy_B18CJT_rec  702-703   eayy_B1A  704-707     
   eayy_B1ACJT  708-711     eayy_B1B  712            eayy_B1BCJT  713      
   eayy_B1CJT  714-715      eayy_B2_rec  716-717     eayy_B25  718         
   eayy_B2CJT_rec  719-720   eayy_B4_rec  721         eayy_B4CJT_rec  722   
   eayy_B5_rec  723         eayy_B5A  724            eayy_B5B_rec  725     
   eayy_B5C  726-727        eayy_B6A_rec  728-729    eayy_B6B_rec  730-731 
   eayy_B7B_rec  732-733    eayy_B8_rec  734         eayy_B9_rec  735      
   eayy_C1_rec  736         eayy_C1JEU  737          eayy_C8  738-741      
   eayy_C8A_rec  742-745    eayy_C8B_rec  746-749    eayy_D1_rec  750      
   eayy_D1A  751-754        eayy_D2  755-756         eayy_D3  757          
   eayy_D4_rec  758         eayy_D5_rec  759         eayy_D6  760          
   eayy_D7_1  761           eayy_D7_10  762          eayy_D7_2  763        
   eayy_D7_3  764           eayy_D7_4  765           eayy_D7_5  766        
   eayy_D7_6  767           eayy_D7_7  768           eayy_D7_8  769        
   eayy_D7_9  770           eayy_E1A  771            eayy_E1B  772         
   eayy_E1C  773            eayy_E1D  774            eayy_E1E  775         
   eayy_E1F  776            eayy_E1G  777            eayy_E1H  778         
   eayy_E1I  779            eayy_E1J  780            eayy_E2A_rec  781-782 
   eayy_E2AUC  783-784      eayy_E2AUC_SOURCE  785   eayy_E3A  786-789     
   eayy_E3B  790-793        eayy_E3C  794-797        eayy_E3D  798-801     
   eayy_E3E  802-805        eayy_E4  806-809         eayy_E5  810-811      
   eayy_E5A  812-815        eayy_E5B_1  816-819      eayy_E5B_2  820-823   
   eayy_E5B_3  824-827      eayy_E5B_4  828-831      eayy_E5B_5  832-835   
   eayy_E5B_6  836-839      eayy_E5B_7  840-843      eayy_E5B_8  844-847   
   eayy_E5B_9  848-851      eayy_F1_rec  852         eayy_F3  853          
   eayy_F4  854-857         eayy_F5  858-861         eayy_F6_rec  862      
   eayy_F7  863             eayy_F8  864             eayy_G1  865          
   eayy_G2  866             eayy_G3A  867            eayy_G3B  868         
   eayy_G3C  869            eayy_G4  870             eayy_G5  871          
   eayy_G6_1  872           eayy_G6_2  873           eayy_G6_3  874        
   eayy_G6_4  875           eayy_H1A  876            eayy_H2  877          
   eayy_H4  878             eayy_I1  879             eayy_I8  880-881      
   eayy_J1  882             eayy_K3  883             eayy_PCS18  884-886   
   eayy_PCS6  887-889       eayy_PCS6CJT  890-892    eayy_TYPMEN5  893     
   VAGUE  894-897           coco1_SWB $ 898-914      coco1_cal_AGE1  915   
   coco1_cal_AGE2  916      coco1_cal_DIPL  917      coco1_cal_SEXE  918   
   coco1_cal_ZEAT  919      coco1_cal_NAT  920       insee_NUTS1  921      
   insee_TAU2014  922-923   insee_TUU2014  924       insee_CATAEU2010  925-927
   coco1_POIDS  928-945     coco1_PDSPLT $ 946-962   coco1_POIDS_INIT  963-973
   coco1_PDSPLT_INIT $ 974-984 ;                       

LABEL
   UID_ANONYM_COVID = "Identifiant interviewé"
   coco1_q01 = "Surprise sur l’annonce du confinement en France"
   coco1_q02 = "Avis sur le calendrier de mise en place du confinement"
   coco1_q03 = "Estimation de la durée du confinement en France"
   coco1_q04 = "Auto-évaluation de la santé"
   coco1_q05_c = "Poids en kg (recodage)"
   coco1_q06_1 = "Symptômes pendant les deux dernières semaines : Toux"
   coco1_q06_2 = "Symptômes pendant les deux dernières semaines : Maux de tête"
   coco1_q06_3 = "Symptômes pendant les deux dernières semaines : Fatigue"
   coco1_q06_4 = "Symptômes pendant les deux dernières semaines : Rhume"
   coco1_q06_5 = "Symptômes pendant les deux dernières semaines : Maux de gorge"
   coco1_q06_6 = "Symptômes pendant les deux dernières semaines : Gêne respiratoire"
   coco1_q06_7 = "Symptômes pendant les deux dernières semaines : Courbatures"
   coco1_q06_8 = "Symptômes pendant les deux dernières semaines : Fièvre"
   coco1_q06_9 = "Symptômes pendant les deux dernières semaines : Troubles digestifs"
   coco1_q06_10 = "Symptômes pendant les deux dernières semaines : Aucun de ces symptômes"
   coco1_q07_1 = "Consultation médicale : Aucune"
   coco1_q07_2 = "Consultation médicale : Pour un ou plusieurs symptômes"
   coco1_q07_3 = "Consultation médicale : Autres raisons"
   coco1_q08_1 = "Moyen consultation médicale : Chez le médecin"
   coco1_q08_2 = "Moyen consultation médicale : A distance par téléphone"
   coco1_q08_3 = "Moyen consultation médicale : A distance par visio-conférence"
   coco1_q09 = "Infection par le virus covid-19"
   coco1_q10 = "État de santé actuel après une probable infection par le virus covid-19"
   coco1_q11_1 = "Personnes atteintes par le virus Covid-19 : Famille"
   coco1_q11_2 = "Personnes atteintes par le virus Covid-19 : Connaissance(s)"
   coco1_q11_3 = "Personnes atteintes par le virus Covid-19 : Personne"
   coco1_q12 = "Nombre de proches testés positif ou suspicions Covid-19"
   coco1_q13 = "Nombre de proches guéris après être testés positif ou suspicions Covid-19"
   coco1_q14 = "Nombre de proches décédés après être testés positif ou suspicions Covid-19"
   coco1_q15 = "Connaissance de personnes testées positif ou suspicions Covid-19 dans le quartier"
   coco1_q16 = "Les 2 dernières semaines, s'est senti : nerveux"
   coco1_q17 = "Les 2 dernières semaines, s'est senti : découragé"
   coco1_q18 = "Les 2 dernières semaines, s'est senti : calme"
   coco1_q19 = "Les 2 dernières semaines, s'est senti : triste et abattu"
   coco1_q20 = "Les 2 dernières semaines, s'est senti : heureux"
   coco1_q21 = "Sentiment de solitude"
   coco1_q22 = "Résidence actuelle"
   coco1_q23 = "Nombre de personnes vivant dans le ménage"
   coco1_q24_1 = "Vit avec : conjoint(e)"
   coco1_q24_2 = "Vit avec : des enfants ou petit-enfants"
   coco1_q24_3 = "Vit avec : des parents ou grand-parents"
   coco1_q24_4 = "Vit avec : d'autres membres de la famille"
   coco1_q24_5 = "Vit avec : des amis ou d'autres personnes"
   coco1_q24_6 = "Vit avec : un ou plusieurs chiens"
   coco1_q24_7 = "Vit avec : un ou plusieurs autres animaux (autres que des chiens)"
   coco1_q25 = "Tensions au sein du ménage"
   coco1_q26 = "Taille du logement (en m²)"
   coco1_q26_rec = "Appartement de moins de 25 m² par personne (calcul)"
   coco1_q27_1 = "Dans le logement : Balcon(s) ou terrasse(s)"
   coco1_q27_2 = "Dans le logement : Jardin ou terrain"
   coco1_q27_3 = "Dans le logement : Cour accessible"
   coco1_q27_4 = "Dans le logement : Autre accès extérieur"
   coco1_q27_5 = "Dans le logement : Aucun accès extérieur"
   coco1_q28 = "Nombre d’ordinateur(s) (fixe(s) ou portable(s)) dans le logement"
   coco1_q29 = "Nombre de smartphone(s) et tablette(s) dans le logement"
   coco1_q30 = "Nombre de personne(s) utilisant Internet pour le travail dans le logement"
   coco1_q31 = "Bonne connexion Internet pendant la période de confinement"
   coco1_q32 = "Situation principale vis-à-vis du travail avant le confinement"
   coco1_q33 = "Contrat de travail avant le confinement"
   coco1_q34 = "Type d'emploi"
   coco1_q35 = "Activité professionnelle"
   coco1_q36 = "Fréquence du télétravail avant le 15 mars"
   coco1_q37 = "Situation professionnelle actuelle pendant le confinement"
   coco1_q38 = "Situation actuelle vis-à-vis du télétravail"
   coco1_q39 = "Difficultés pour se rendre sur le lieu de travail"
   coco1_q40 = "Raison principale pour se rendre sur le lieu de travail"
   coco1_q41_1 = "Conditions de travail : des risques pour la santé"
   coco1_q41_2 = "Conditions de travail : des conflits avec employeur"
   coco1_q41_3 = "Conditions de travail : des conflits avec collègues"
   coco1_q41_4 = "Conditions de travail : un risque de chômage"
   coco1_q41_5 = "Conditions de travail : une perte de salaire"
   coco1_q41_6 = "Conditions de travail : aucune de ces situations"
   coco1_q44 = "Revenu net du ménage"
   coco1_q45 = "Changement des revenus du foyer en mars 2020 par rapport au mois précédent"
   coco1_q46_1 = "Dépense 400€ : avec économies"
   coco1_q46_2 = "Dépense 400€ : avec emprunt auprès des proches"
   coco1_q46_3 = "Dépense 400€ : avec emprunt auprès d'une banque"
   coco1_q46_4 = "Dépense 400€ : impossible"
   coco1_q47 = "Fréquence des sorties au cours des deux dernières semaines"
   coco1_q48 = "Contrôle de police lors des sorties"
   coco1_q49 = "Expérience dans le contact avec la police"
   coco1_q50 = "Expérience dans le dernier contact avec la police"
   coco1_q51 = "Fréquence de la surveillance des travaux scolaires des enfants"
   coco1_q52_1 = "Fréquence des rencontres avec des amis dans la vie réelle"
   coco1_q52_2 = "Fréquence des rencontres avec des amis dans la vie virtuelle"
   coco1_q52_3 = "Fréquence des rencontres avec la famille dans la vie réelle"
   coco1_q52_4 = "Fréquence des rencontres avec  la famille par rencontre virtuelle"
   coco1_q53_1 = "Fréquence des contacts avec la famille à l'étranger"
   coco1_q53_2 = "Fréquence des contacts avec des amis à l'étranger"
   coco1_q53_3 = "Fréquence des contacts avec des collègues à l'étranger"
   coco1_q54_1 = "Reçu un coup de main ou l’aide : de la famille"
   coco1_q54_2 = "Reçu un coup de main ou l’aide : d'amis proches"
   coco1_q54_3 = "Reçu un coup de main ou l'aide : de collègues"
   coco1_q54_4 = "Reçu un coup de main ou l'aide : de voisins"
   coco1_q54_5 = "Reçu un coup de main ou l'aide : d'agents des services publics"
   coco1_q54_6 = "Reçu un coup de main ou l'aide : de bénévoles d’une association"
   coco1_q54_7 = "Reçu un coup de main ou l'aide : de personnes que vous ne connaissiez pas auparavant"
   coco1_q54_8 = "Reçu un coup de main ou l'aide : de personne"
   coco1_q54_bis_1 = "Donné un coup de main ou de l’aide à : la famille"
   coco1_q54_bis_2 = "Donné un coup de main ou de l’aide à : des amis proches"
   coco1_q54_bis_3 = "Donné un coup de main ou l'aide à : des collègues"
   coco1_q54_bis_4 = "Donné un coup de main ou l'aide à : des voisins"
   coco1_q54_bis_5 = "Donné un coup de main ou l'aide à : une association"
   coco1_q54_bis_6 = "Donné un coup de main ou l'aide à : des personnes que vous ne connaissiez pas auparavant"
   coco1_q54_bis_7 = "Donné un coup de main ou l'aide à : personne"
   coco1_q55 = "Faire des stocks"
   coco1_q56 = "Achat des produits de moins bonne qualité que d’habitude"
   coco1_q57 = "Achat des produits plus chers que d’habitude"
   coco1_q58_1 = "Fréquentation : des petits commerces"
   coco1_q58_2 = "Fréquentation : des grandes surfaces"
   coco1_q58_3 = "Fréquentation : des espaces verts, de la campagne"
   coco1_q58_4 = "Fréquentation : des services médicaux"
   coco1_q58_5 = "Fréquentation : des pharmacies"
   coco1_q58_6 = "Fréquentation : des services publics"
   coco1_q58_7 = "Fréquentation : d'aucun de ces lieux"
   coco1_q59_1 = "Temps consacré à : faire du ménage"
   coco1_q59_2 = "Temps consacré à : s’occuper de ses enfants"
   coco1_q59_3 = "Temps consacré à : prendre soin de personnes fragiles ou vulnérables"
   coco1_q59_4 = "Temps consacré à : exercer son activité professionnelle"
   coco1_q59_5 = "Temps consacré à : faire des exercices physiques / du sport"
   coco1_q59_6 = "Temps consacré à : dormir"
   coco1_q59_7 = "Temps consacré à : parler au téléphone"
   coco1_q59_8 = "Temps consacré à : utiliser des réseaux sociaux"
   coco1_q59_9 = "Temps consacré à : regarder la télévision"
   coco1_q60_1 = "Fréquence de : faire les courses"
   coco1_q60_2 = "Fréquence de : faire la cuisine"
   coco1_q60_3 = "Fréquence de : lire"
   coco1_q60_4 = "Fréquence de : faire du bricolage, du jardinage, des travaux de décoration"
   coco1_q60_5 = "Fréquence de : prier"
   coco1_q60_6 = "Fréquence de : méditer"
   coco1_q61_1 = "Temps consacré par rapport à d’habitude : à faire du ménage"
   coco1_q61_2 = "Temps consacré par rapport à d’habitude : à s’occuper de ses enfants"
   coco1_q61_3 = "Temps consacré par rapport à d’habitude : à prendre soin de personnes fragiles ou vulnérables"
   coco1_q61_4 = "Temps consacré par rapport à d’habitude : à exercer son activité professionnelle"
   coco1_q61_5 = "Temps consacré par rapport à d’habitude : à faire des exercices physiques / du sport"
   coco1_q61_6 = "Temps consacré par rapport à d’habitude : à dormir"
   coco1_q61_7 = "Temps consacré par rapport à d’habitude : à parler au téléphone"
   coco1_q61_8 = "Temps consacré par rapport à d’habitude : à utiliser des réseaux sociaux"
   coco1_q61_9 = "Temps consacré par rapport à d’habitude : à regarder la télévision"
   coco1_q61_10 = "Temps consacré par rapport à d’habitude : à avoir des relations intimes avec une autre personne"
   coco1_q62 = "Description de l'expérience du confinement"
   coco1_q63 = "Conditions de vie lors du confinement, par rapport à la plupart des Français"
   coco1_q64 = "Stress lié au confinement"
   coco1_q65 = "Avis sur s'informer plus sur le covid-19"
   coco1_q66 = "Volonté de prendre des risques"
   coco1_q67 = "Confiance aux autres"
   coco1_q68 = "Satisfaction quant à la manière dont le Gouvernement français gère l'épidémie du virus Covid-19"
   coco1_q69 = "Avis Covid-19 : il faudra beaucoup plus fermer les frontières entre l’UE et l’espace hors UE"
   coco1_q70 = "Avis Covid-19 : fermer beaucoup plus les frontières de la France à tous"
   coco1_q71 = "Avis Covid-19 : libéraliser le marché du travail pour soutenir certains secteurs"
   coco1_q72 = "Avis Covid-19 : limiter la liberté de circulation des individus pour le bien collectif"
   coco1_q73 = "Avis Covid-19 : réquisitionner des biens privés pour le bien collectif"
   coco1_q74 = "Avis Covid-19 : assurer le bien collectif sans se soucier de l’équilibre des finances publiques"
   coco1_q75 = "Avis Covid-19 : les Français traités à égalité par le gouvernement vis-à-vis du Covid-19"
   coco1_q76 = "Avis Covid-19 : les risques du virus Covid-19 ont été plutôt exagérés"
   coco1_q77 = "Avis Covid-19 : les Français savent prendre leurs responsabilités dans les périodes de crise"
   coco1_q79 = "Préoccupation par les conséquences sanitaires ou les conséquences économiques de l’épidémie du virus Covid-19"
   coco1_q80 = "Avis sur l’impact du confinement sur la situation économique en France"
   coco1_q81 = "Optimisme quant à : l'avenir personnel"
   coco1_q82 = "Optimisme quant à : l'avenir de sa commune"
   coco1_q83 = "Optimisme quant à : l'avenir de la France"
   coco1_q83_1 = "Attente que l'épidémie affecte : la sécurité de son emploi"
   coco1_q83_2 = "Attente que l'épidémie affecte : les revenus de son foyer"
   coco1_q83_3 = "Attente que l'épidémie affecte : sa santé et celle de ses proches"
   coco1_q83_4 = "Attente que l'épidémie affecte : son alimentation"
   coco1_q83_5 = "Attente que l'épidémie affecte : sa vie amoureuse ou conjugale"
   coco1_q83_6 = "Attente que l'épidémie affecte : ses relations sociales"
   coco1_q83_7 = "Attente que l'épidémie affecte : ses habitudes de voyage"
   coco1_q83_8 = "Attente que l'épidémie affecte : ses loisirs"
   coco1_q83_9 = "Attente que l'épidémie affecte : ses opinions politiques"
   coco1_q83_10 = "Attente que l'épidémie affecte : ses croyances et sa spiritualité"
   coco1_q84 = "Optimisme quant à : l'avenir de l’Union européenne"
   coco1_q85 = "Optimisme quant à : l'avenir du monde"
   coco1_q86 = "Volonté de participer à un court questionnaire de maximum 5 questions à partir du 10 avril"
   eayy_A1 = "Sexe (enquête annuelle)"
   eayy_A2A_rec = "Age quinquennal (recodage)"
   eayy_A3_rec = "A la nationalité francaise (recodage)"
   eayy_A3B_rec = "Pays de naissance (recodage)"
   eayy_A3C_rec = "Nationalité (recodage)"
   eayy_A3D = "A une seconde nationalité"
   eayy_A3E_rec = "Seconde nationalité (recodage)"
   eayy_A4 = "Statut matrimonial légal"
   eayy_A5 = "Vit en couple"
   eayy_A5A = "Situation familiale"
   eayy_A5C = "Ancienneté du couple"
   eayy_A5C_rec = "Ancienneté du couple (recodage)"
   eayy_B1 = "Situation principale vis-à-vis du travail"
   eayy_B10A = "Recherche d'emploi"
   eayy_B10AA = "Rercherche un autre emploi"
   eayy_B10ACJT = "Recherche d'emploi (conjoint)"
   eayy_B11 = "Ne travaille pas mais a déjà travaillé"
   eayy_B11CJT = "Ne travaille pas mais a déjà travaillé (conjoint)"
   eayy_B18_rec = "Diplôme le plus élevé (recodage)"
   eayy_B18C = "Niveau de formation (recodage)"
   eayy_B18CCJT = "Niveau de formation (conjoint) (calcul)"
   eayy_B18CJT_rec = "Diplôme le plus élevé (conjoint) (recodage)"
   eayy_B1A = "Emploi (étudiant, chômeur, retraité, autre inactif)"
   eayy_B1ACJT = "Emploi (étudiant, chômeur, retraité, autre inactif) (conjoint)"
   eayy_B1B = "Exercice d'une activité professionnelle (recodage)"
   eayy_B1BCJT = "Exercice d'une activité professionnelle (conjoint) (calcul)"
   eayy_B1CJT = "Situation principale vis-à-vis du travail (conjoint)"
   eayy_B2_rec = "Statut de l'activité actuelle ou antérieure (recodage)"
   eayy_B25 = "Supervision d'autres salariés"
   eayy_B2CJT_rec = "Statut de l'activité actuelle ou antérieure (conjoint) (calcul)"
   eayy_B4_rec = "Nombre de salariés employés actuellement ou par le passé (recodage)"
   eayy_B4CJT_rec = "Nombre de salariés employés actuellement ou par le passé (conjoint) (calcul)"
   eayy_B5_rec = "Type de contrat de travail (recodage)"
   eayy_B5A = "Temps de travail"
   eayy_B5B_rec = "Type de temps partiel (recodage)"
   eayy_B5C = "Raison principale du travail à temps partiel"
   eayy_B6A_rec = "Catégorie de l'emploi actuel ou antérieur secteur privé (recodage)"
   eayy_B6B_rec = "Catégorie de l'emploi actuel ou antérieur secteur public (recodage)"
   eayy_B7B_rec = "Fonction principale de l'emploi actuel ou antérieur (recodage)"
   eayy_B8_rec = "Nombre de salariés dans l'entreprise de l'emploi actuel ou antérieur (recodage)"
   eayy_B9_rec = "Superficie de l'exploitation actuelle ou antérieure (recodage)"
   eayy_C1_rec = "Nombre de personnes dans le foyer (recodage)"
   eayy_C1JEU = "Nombre de jeunes (calcul)"
   eayy_C8 = "A des enfants"
   eayy_C8A_rec = "Nombre d'enfants (recodage)"
   eayy_C8B_rec = "Nombre d'enfants cohabitants (recodage)"
   eayy_D1_rec = "Statut d'occupation du logement (recodage)"
   eayy_D1A = "Appartenance du logement à un organisme HLM"
   eayy_D2 = "Propriétaire du logement"
   eayy_D3 = "Type d'habitation"
   eayy_D4_rec = "Nombre pièces d'habitation du logement (recodage)"
   eayy_D5_rec = "Année d'emménagement dans le logement (calcul)"
   eayy_D6 = "Type d'habitat au voisinage du logement"
   eayy_D7_1 = "Problèmes concernant le quartier : terrains-vagues, locaux désaffectés, friches industrielles, logements insalubres"
   eayy_D7_10 = "Problèmes concernant le quartier : aucun de ces problèmes"
   eayy_D7_2 = "Problèmes concernant le quartier : bruits ou pollution"
   eayy_D7_3 = "Problèmes concernant le quartier : voirie insuffisante"
   eayy_D7_4 = "Problèmes concernant le quartier : saleté"
   eayy_D7_5 = "Problèmes concernant le quartier : manque d'espaces verts"
   eayy_D7_6 = "Problèmes concernant le quartier : manque de commerces"
   eayy_D7_7 = "Problèmes concernant le quartier : manque de lieux de rencontre, d'équipements"
   eayy_D7_8 = "Problèmes concernant le quartier : isolement du quartier"
   eayy_D7_9 = "Problèmes concernant le quartier : manque de sécurité"
   eayy_E1A = "Personnes dans le ménage percevant : salaires, traitements et primes"
   eayy_E1B = "Personnes dans le ménage percevant : revenus d'une activité professionnelle non salariée"
   eayy_E1C = "Personnes dans le ménage percevant : allocations de chômage"
   eayy_E1D = "Personnes dans le ménage percevant : préretraites, retraites"
   eayy_E1E = "Personnes dans le ménage percevant : prestations liées à la maladie ou l'invalidité"
   eayy_E1F = "Personnes dans le ménage percevant : prestations familiales et bourses"
   eayy_E1G = "Personnes dans le ménage percevant : allocation logement, aide au logement"
   eayy_E1H = "Personnes dans le ménage percevant : RSA"
   eayy_E1I = "Personnes dans le ménage percevant : loyers et fermages"
   eayy_E1J = "Personnes dans le ménage percevant : pensions, aides"
   eayy_E2A_rec = "Tranche de montant des ressources (calcul)"
   eayy_E2AUC = "Tranche de revenu mensuel du ménage par unité de consommation (calcul)"
   eayy_E2AUC_SOURCE = "Source d'information du montant des ressources par unité de consommation"
   eayy_E3A = "Détention placements financiers : livrets d'épargne"
   eayy_E3B = "Détention placements financiers : épargne-logement"
   eayy_E3C = "Détention placements financiers : assurances-vies"
   eayy_E3D = "Détention placements financiers : épargne retraite"
   eayy_E3E = "Détention placements financiers : valeurs immobilières"
   eayy_E4 = "Résidence secondaire"
   eayy_E5 = "Situation financière actuelle du mènage"
   eayy_E5A = "Baisse de revenu importante les 12 derniers mois"
   eayy_E5B_1 = "Baisse de revenu importante les 12 derniers mois : licenciement/perte d'emploi"
   eayy_E5B_2 = "Baisse de revenu importante les 12 derniers mois : modification du salaire/heures"
   eayy_E5B_3 = "Baisse de revenu importante les 12 derniers mois : invalidité/incapacité"
   eayy_E5B_4 = "Baisse de revenu importante les 12 derniers mois : maternité/congé parental/garde des enfants"
   eayy_E5B_5 = "Baisse de revenu importante les 12 derniers mois : départ à la retraite"
   eayy_E5B_6 = "Baisse de revenu importante les 12 derniers mois : mariage/rupture"
   eayy_E5B_7 = "Baisse de revenu importante les 12 derniers mois : décès"
   eayy_E5B_8 = "Baisse de revenu importante les 12 derniers mois : autre changement dans le ménage"
   eayy_E5B_9 = "Baisse de revenu importante les 12 derniers mois: autre raison"
   eayy_F1_rec = "Fréquence de rencontre des amis (recodage)"
   eayy_F3 = "A quelqu'un pour discuter de questions intimes et personnelles"
   eayy_F4 = "Sentiment de solitude"
   eayy_F5 = "Opinion confiance ou prudence en général"
   eayy_F6_rec = "Fréquence de rencontre de la famille (recodage)"
   eayy_F7 = "Membre association humanitaire ou sociale"
   eayy_F8 = "Membre amicale ou association sportive ou culturelle"
   eayy_G1 = "Télévision les 12 derniers mois"
   eayy_G2 = "Nombre de livres lus les 12 derniers mois"
   eayy_G3A = "Sortie culturelle les 12 derniers mois : au cinéma"
   eayy_G3B = "Sortie culturelle les 12 derniers mois : au théâtre ou au concert"
   eayy_G3C = "Sortie culturelle les 12 derniers mois : au musée ou une exposition"
   eayy_G4 = "Bricolage les 12 derniers mois"
   eayy_G5 = "Maîtrise d'une langue étrangère"
   eayy_G6_1 = "Partir en vacances les 12 derniers mois : non"
   eayy_G6_2 = "Partir en vacances les 12 derniers mois : dans la région"
   eayy_G6_3 = "Partir en vacances les 12 derniers mois : dans une autre région"
   eayy_G6_4 = "Partir en vacances les 12 derniers mois : à l'étranger"
   eayy_H1A = "A une religion (recodage)"
   eayy_H2 = "Importance de la religion"
   eayy_H4 = "Éducation religieuse"
   eayy_I1 = "Intérêt pour la politique"
   eayy_I8 = "Auto-positionnement sur l'échelle gauche/droite"
   eayy_J1 = "État de santé"
   eayy_K3 = "Fréquence activité sportive 30 minutes d'affilée"
   eayy_PCS18 = "Catégorie socioprofessionnelle en 18 postes (profession actuelle ou dernière profession)"
   eayy_PCS6 = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession)"
   eayy_PCS6CJT = "Groupe socioprofessionnel en 6 postes (profession actuelle ou dernière profession) (conjoint)"
   eayy_TYPMEN5 = "Type de ménage (calcul)"
   VAGUE = "VAGUE"
   coco1_SWB = "Niveau de bien-être subjectif"
   coco1_cal_AGE1 = "Age décennal (calage panel pilote)"
   coco1_cal_AGE2 = "Age décennal (calage)"
   coco1_cal_DIPL = "Diplôme (calage)"
   coco1_cal_SEXE = "Sexe (calage)"
   coco1_cal_ZEAT = "Zone d'études et d'aménagement du territoire (calage)"
   coco1_cal_NAT = "Nationalité (calage)"
   insee_NUTS1 = "Nomenclature des unités territoriales statistiques niv. 1"
   insee_TAU2014 = "Tranche d'aire urbaine 2014"
   insee_TUU2014 = "Tranche d'unité urbaine 2014"
   insee_CATAEU2010 = "Catégorie de la commune dans le zonage en aires urbaines 2010"
   coco1_POIDS = "Poids individu"
   coco1_PDSPLT = "Poids individu (panel pilote)"
   coco1_POIDS_INIT = "Poids initial"
   coco1_PDSPLT_INIT = "Poids initial (panel pilote)" ;

 /* User Missing Value Specifications */
  IF coco1_q02 = 9999 THEN coco1_q02 =. ;
  IF coco1_q03 = 9999 THEN coco1_q03 =. ;
  IF coco1_q04 = 9999 THEN coco1_q04 =. ;
  IF coco1_q05_c = 7777 OR coco1_q05_c = 8888 OR coco1_q05_c = 9999 THEN coco1_q05_c =. ;
  IF coco1_q06_1 = 9999 THEN coco1_q06_1 =. ;
  IF coco1_q06_2 = 9999 THEN coco1_q06_2 =. ;
  IF coco1_q06_3 = 9999 THEN coco1_q06_3 =. ;
  IF coco1_q06_4 = 9999 THEN coco1_q06_4 =. ;
  IF coco1_q06_5 = 9999 THEN coco1_q06_5 =. ;
  IF coco1_q06_6 = 9999 THEN coco1_q06_6 =. ;
  IF coco1_q06_7 = 9999 THEN coco1_q06_7 =. ;
  IF coco1_q06_8 = 9999 THEN coco1_q06_8 =. ;
  IF coco1_q06_9 = 9999 THEN coco1_q06_9 =. ;
  IF coco1_q06_10 = 9999 THEN coco1_q06_10 =. ;
  IF coco1_q08_1 = 9999 OR coco1_q08_1 = 6666 THEN coco1_q08_1 =. ;
  IF coco1_q08_2 = 9999 OR coco1_q08_2 = 6666 THEN coco1_q08_2 =. ;
  IF coco1_q08_3 = 9999 OR coco1_q08_3 = 6666 THEN coco1_q08_3 =. ;
  IF coco1_q09 = 9999 THEN coco1_q09 =. ;
  IF coco1_q10 = 6666 THEN coco1_q10 =. ;
  IF coco1_q11_1 = 9999 THEN coco1_q11_1 =. ;
  IF coco1_q11_2 = 9999 THEN coco1_q11_2 =. ;
  IF coco1_q11_3 = 9999 THEN coco1_q11_3 =. ;
  IF coco1_q13 = 6666 OR coco1_q13 = 9999 THEN coco1_q13 =. ;
  IF coco1_q14 = 6666 OR coco1_q14 = 9999 THEN coco1_q14 =. ;
  IF coco1_q15 = 9999 THEN coco1_q15 =. ;
  IF coco1_q17 = 9999 THEN coco1_q17 =. ;
  IF coco1_q18 = 9999 THEN coco1_q18 =. ;
  IF coco1_q19 = 9999 THEN coco1_q19 =. ;
  IF coco1_q20 = 9999 THEN coco1_q20 =. ;
  IF coco1_q23 = 9999 THEN coco1_q23 =. ;
  IF coco1_q24_1 = 6666 THEN coco1_q24_1 =. ;
  IF coco1_q24_2 = 6666 THEN coco1_q24_2 =. ;
  IF coco1_q24_3 = 6666 THEN coco1_q24_3 =. ;
  IF coco1_q24_4 = 6666 THEN coco1_q24_4 =. ;
  IF coco1_q24_5 = 6666 THEN coco1_q24_5 =. ;
  IF coco1_q25 = 6666 THEN coco1_q25 =. ;
  IF coco1_q26 = 9999 THEN coco1_q26 =. ;
  IF coco1_q26_rec = 9 THEN coco1_q26_rec =. ;
  IF coco1_q27_1 = 9999 THEN coco1_q27_1 =. ;
  IF coco1_q27_2 = 9999 THEN coco1_q27_2 =. ;
  IF coco1_q27_3 = 9999 THEN coco1_q27_3 =. ;
  IF coco1_q27_4 = 9999 THEN coco1_q27_4 =. ;
  IF coco1_q27_5 = 9999 THEN coco1_q27_5 =. ;
  IF coco1_q28 = 9999 THEN coco1_q28 =. ;
  IF coco1_q29 = 9999 THEN coco1_q29 =. ;
  IF coco1_q30 = 9999 THEN coco1_q30 =. ;
  IF coco1_q31 = 6666 OR coco1_q31 = 9999 THEN coco1_q31 =. ;
  IF coco1_q32 = 9999 THEN coco1_q32 =. ;
  IF coco1_q33 = 6666 OR coco1_q33 = 9999 THEN coco1_q33 =. ;
  IF coco1_q34 = 6666 THEN coco1_q34 =. ;
  IF coco1_q35 = 9999 THEN coco1_q35 =. ;
  IF coco1_q36 = 6666 OR coco1_q36 = 9999 THEN coco1_q36 =. ;
  IF coco1_q37 = 6666 OR coco1_q37 = 9999 THEN coco1_q37 =. ;
  IF coco1_q38 = 6666 THEN coco1_q38 =. ;
  IF coco1_q39 = 6666 OR coco1_q39 = 9999 THEN coco1_q39 =. ;
  IF coco1_q40 = 6666 OR coco1_q40 = 9999 THEN coco1_q40 =. ;
  IF coco1_q41_1 = 6666 THEN coco1_q41_1 =. ;
  IF coco1_q41_2 = 6666 THEN coco1_q41_2 =. ;
  IF coco1_q41_3 = 6666 THEN coco1_q41_3 =. ;
  IF coco1_q41_4 = 6666 THEN coco1_q41_4 =. ;
  IF coco1_q41_5 = 6666 THEN coco1_q41_5 =. ;
  IF coco1_q41_6 = 6666 THEN coco1_q41_6 =. ;
  IF coco1_q44 = 9999 THEN coco1_q44 =. ;
  IF coco1_q45 = 9999 THEN coco1_q45 =. ;
  IF coco1_q46_1 = 9999 THEN coco1_q46_1 =. ;
  IF coco1_q46_2 = 9999 THEN coco1_q46_2 =. ;
  IF coco1_q46_3 = 9999 THEN coco1_q46_3 =. ;
  IF coco1_q46_4 = 9999 THEN coco1_q46_4 =. ;
  IF coco1_q47 = 9999 THEN coco1_q47 =. ;
  IF coco1_q48 = 6666 OR coco1_q48 = 9999 THEN coco1_q48 =. ;
  IF coco1_q49 = 6666 OR coco1_q49 = 9999 THEN coco1_q49 =. ;
  IF coco1_q50 = 6666 THEN coco1_q50 =. ;
  IF coco1_q51 = 9999 THEN coco1_q51 =. ;
  IF coco1_q52_1 = 9999 THEN coco1_q52_1 =. ;
  IF coco1_q52_2 = 9999 THEN coco1_q52_2 =. ;
  IF coco1_q52_3 = 9999 THEN coco1_q52_3 =. ;
  IF coco1_q52_4 = 9999 THEN coco1_q52_4 =. ;
  IF coco1_q53_1 = 9999 THEN coco1_q53_1 =. ;
  IF coco1_q53_2 = 9999 THEN coco1_q53_2 =. ;
  IF coco1_q53_3 = 9999 THEN coco1_q53_3 =. ;
  IF coco1_q54_1 = 9999 THEN coco1_q54_1 =. ;
  IF coco1_q54_2 = 9999 THEN coco1_q54_2 =. ;
  IF coco1_q54_3 = 9999 THEN coco1_q54_3 =. ;
  IF coco1_q54_4 = 9999 THEN coco1_q54_4 =. ;
  IF coco1_q54_5 = 9999 THEN coco1_q54_5 =. ;
  IF coco1_q54_6 = 9999 THEN coco1_q54_6 =. ;
  IF coco1_q54_7 = 9999 THEN coco1_q54_7 =. ;
  IF coco1_q54_8 = 9999 THEN coco1_q54_8 =. ;
  IF coco1_q54_bis_1 = 9999 THEN coco1_q54_bis_1 =. ;
  IF coco1_q54_bis_2 = 9999 THEN coco1_q54_bis_2 =. ;
  IF coco1_q54_bis_3 = 9999 THEN coco1_q54_bis_3 =. ;
  IF coco1_q54_bis_4 = 9999 THEN coco1_q54_bis_4 =. ;
  IF coco1_q54_bis_5 = 9999 THEN coco1_q54_bis_5 =. ;
  IF coco1_q54_bis_6 = 9999 THEN coco1_q54_bis_6 =. ;
  IF coco1_q54_bis_7 = 9999 THEN coco1_q54_bis_7 =. ;
  IF coco1_q56 = 9999 THEN coco1_q56 =. ;
  IF coco1_q57 = 9999 THEN coco1_q57 =. ;
  IF coco1_q58_1 = 9999 THEN coco1_q58_1 =. ;
  IF coco1_q58_2 = 9999 THEN coco1_q58_2 =. ;
  IF coco1_q58_3 = 9999 THEN coco1_q58_3 =. ;
  IF coco1_q58_4 = 9999 THEN coco1_q58_4 =. ;
  IF coco1_q58_5 = 9999 THEN coco1_q58_5 =. ;
  IF coco1_q58_6 = 9999 THEN coco1_q58_6 =. ;
  IF coco1_q58_7 = 9999 THEN coco1_q58_7 =. ;
  IF coco1_q59_1 = 9999 THEN coco1_q59_1 =. ;
  IF coco1_q59_2 = 9999 THEN coco1_q59_2 =. ;
  IF coco1_q59_3 = 9999 THEN coco1_q59_3 =. ;
  IF coco1_q59_4 = 9999 THEN coco1_q59_4 =. ;
  IF coco1_q59_5 = 9999 THEN coco1_q59_5 =. ;
  IF coco1_q59_6 = 9999 THEN coco1_q59_6 =. ;
  IF coco1_q59_7 = 9999 THEN coco1_q59_7 =. ;
  IF coco1_q59_8 = 9999 THEN coco1_q59_8 =. ;
  IF coco1_q59_9 = 9999 THEN coco1_q59_9 =. ;
  IF coco1_q60_1 = 9999 THEN coco1_q60_1 =. ;
  IF coco1_q60_2 = 9999 THEN coco1_q60_2 =. ;
  IF coco1_q60_3 = 9999 THEN coco1_q60_3 =. ;
  IF coco1_q60_4 = 9999 THEN coco1_q60_4 =. ;
  IF coco1_q60_5 = 9999 THEN coco1_q60_5 =. ;
  IF coco1_q60_6 = 9999 THEN coco1_q60_6 =. ;
  IF coco1_q61_1 = 9999 THEN coco1_q61_1 =. ;
  IF coco1_q61_2 = 9999 THEN coco1_q61_2 =. ;
  IF coco1_q61_3 = 9999 THEN coco1_q61_3 =. ;
  IF coco1_q61_4 = 9999 THEN coco1_q61_4 =. ;
  IF coco1_q61_5 = 9999 THEN coco1_q61_5 =. ;
  IF coco1_q61_6 = 9999 THEN coco1_q61_6 =. ;
  IF coco1_q61_7 = 9999 THEN coco1_q61_7 =. ;
  IF coco1_q61_8 = 9999 THEN coco1_q61_8 =. ;
  IF coco1_q61_9 = 9999 THEN coco1_q61_9 =. ;
  IF coco1_q61_10 = 9999 THEN coco1_q61_10 =. ;
  IF coco1_q62 = 9999 THEN coco1_q62 =. ;
  IF coco1_q63 = 9999 THEN coco1_q63 =. ;
  IF coco1_q64 = 9999 THEN coco1_q64 =. ;
  IF coco1_q65 = 9999 THEN coco1_q65 =. ;
  IF coco1_q66 = 9999 THEN coco1_q66 =. ;
  IF coco1_q67 = 9999 THEN coco1_q67 =. ;
  IF coco1_q68 = 9999 THEN coco1_q68 =. ;
  IF coco1_q69 = 9999 THEN coco1_q69 =. ;
  IF coco1_q70 = 9999 THEN coco1_q70 =. ;
  IF coco1_q71 = 9999 THEN coco1_q71 =. ;
  IF coco1_q72 = 9999 THEN coco1_q72 =. ;
  IF coco1_q73 = 9999 THEN coco1_q73 =. ;
  IF coco1_q74 = 9999 THEN coco1_q74 =. ;
  IF coco1_q75 = 9999 THEN coco1_q75 =. ;
  IF coco1_q76 = 9999 THEN coco1_q76 =. ;
  IF coco1_q77 = 9999 THEN coco1_q77 =. ;
  IF coco1_q79 = 9999 THEN coco1_q79 =. ;
  IF coco1_q80 = 9999 THEN coco1_q80 =. ;
  IF coco1_q81 = 9999 THEN coco1_q81 =. ;
  IF coco1_q82 = 9999 THEN coco1_q82 =. ;
  IF coco1_q83 = 9999 THEN coco1_q83 =. ;
  IF coco1_q83_1 = 9999 THEN coco1_q83_1 =. ;
  IF coco1_q83_2 = 9999 THEN coco1_q83_2 =. ;
  IF coco1_q83_3 = 9999 THEN coco1_q83_3 =. ;
  IF coco1_q83_4 = 9999 THEN coco1_q83_4 =. ;
  IF coco1_q83_5 = 9999 THEN coco1_q83_5 =. ;
  IF coco1_q83_6 = 9999 THEN coco1_q83_6 =. ;
  IF coco1_q83_7 = 9999 THEN coco1_q83_7 =. ;
  IF coco1_q83_8 = 9999 THEN coco1_q83_8 =. ;
  IF coco1_q83_9 = 9999 THEN coco1_q83_9 =. ;
  IF coco1_q83_10 = 9999 THEN coco1_q83_10 =. ;
  IF coco1_q84 = 9999 THEN coco1_q84 =. ;
  IF coco1_q85 = 9999 THEN coco1_q85 =. ;
  IF eayy_A3_rec >= 7 THEN eayy_A3_rec =. ;
  IF eayy_A3B_rec >= 9 THEN eayy_A3B_rec =. ;
  IF eayy_A3C_rec >= 6 THEN eayy_A3C_rec =. ;
  IF eayy_A3D >= 6 THEN eayy_A3D =. ;
  IF eayy_A3E_rec >= 6 THEN eayy_A3E_rec =. ;
  IF eayy_A4 >= 77 THEN eayy_A4 =. ;
  IF eayy_A5 >= 7 THEN eayy_A5 =. ;
  IF eayy_A5A >= 6 OR eayy_A5A = 9996 THEN eayy_A5A =. ;
  IF eayy_A5C >= 6 OR eayy_A5C = 9996 THEN eayy_A5C =. ;
  IF eayy_A5C_rec >= 66 OR eayy_A5C_rec = 9996 THEN eayy_A5C_rec =. ;
  IF eayy_B1 >= 77 THEN eayy_B1 =. ;
  IF eayy_B10A >= 6 THEN eayy_B10A =. ;
  IF eayy_B10AA >= 6 OR eayy_B10AA = 9996 THEN eayy_B10AA =. ;
  IF eayy_B10ACJT >= 6 THEN eayy_B10ACJT =. ;
  IF eayy_B11 >= 6 THEN eayy_B11 =. ;
  IF eayy_B11CJT >= 6 THEN eayy_B11CJT =. ;
  IF eayy_B18_rec >= 77 THEN eayy_B18_rec =. ;
  IF eayy_B18C >= 7 THEN eayy_B18C =. ;
  IF eayy_B18CCJT >= 6 THEN eayy_B18CCJT =. ;
  IF eayy_B18CJT_rec >= 66 THEN eayy_B18CJT_rec =. ;
  IF eayy_B1A >= 6 OR eayy_B1A = 9996 THEN eayy_B1A =. ;
  IF eayy_B1ACJT >= 6 OR eayy_B1ACJT = 9996 THEN eayy_B1ACJT =. ;
  IF eayy_B1B >= 7 THEN eayy_B1B =. ;
  IF eayy_B1BCJT >= 6 THEN eayy_B1BCJT =. ;
  IF eayy_B1CJT >= 66 THEN eayy_B1CJT =. ;
  IF eayy_B2_rec >= 66 THEN eayy_B2_rec =. ;
  IF eayy_B25 >= 6 THEN eayy_B25 =. ;
  IF eayy_B2CJT_rec >= 66 THEN eayy_B2CJT_rec =. ;
  IF eayy_B4_rec >= 6 THEN eayy_B4_rec =. ;
  IF eayy_B4CJT_rec >= 6 THEN eayy_B4CJT_rec =. ;
  IF eayy_B5_rec >= 6 THEN eayy_B5_rec =. ;
  IF eayy_B5A >= 6 THEN eayy_B5A =. ;
  IF eayy_B5B_rec >= 6 THEN eayy_B5B_rec =. ;
  IF eayy_B5C >= 66 THEN eayy_B5C =. ;
  IF eayy_B6A_rec >= 66 THEN eayy_B6A_rec =. ;
  IF eayy_B6B_rec >= 66 THEN eayy_B6B_rec =. ;
  IF eayy_B7B_rec >= 66 THEN eayy_B7B_rec =. ;
  IF eayy_B8_rec >= 6 THEN eayy_B8_rec =. ;
  IF eayy_B9_rec >= 6 THEN eayy_B9_rec =. ;
  IF eayy_C1JEU >= 9 THEN eayy_C1JEU =. ;
  IF eayy_C8 >= 7 OR eayy_C8 = 9996 THEN eayy_C8 =. ;
  IF eayy_C8A_rec >= 6 OR eayy_C8A_rec = 9996 THEN eayy_C8A_rec =. ;
  IF eayy_C8B_rec >= 6 OR eayy_C8B_rec = 9996 THEN eayy_C8B_rec =. ;
  IF eayy_D1_rec >= 7 THEN eayy_D1_rec =. ;
  IF eayy_D1A >= 6 OR eayy_D1A = 9996 THEN eayy_D1A =. ;
  IF eayy_D2 >= 66 THEN eayy_D2 =. ;
  IF eayy_D4_rec >= 99 THEN eayy_D4_rec =. ;
  IF eayy_D5_rec >= 9 THEN eayy_D5_rec =. ;
  IF eayy_D6 >= 9 THEN eayy_D6 =. ;
  IF eayy_D7_1 >= 9 THEN eayy_D7_1 =. ;
  IF eayy_D7_10 >= 9 THEN eayy_D7_10 =. ;
  IF eayy_D7_2 >= 9 THEN eayy_D7_2 =. ;
  IF eayy_D7_3 >= 9 THEN eayy_D7_3 =. ;
  IF eayy_D7_4 >= 9 THEN eayy_D7_4 =. ;
  IF eayy_D7_5 >= 9 THEN eayy_D7_5 =. ;
  IF eayy_D7_6 >= 9 THEN eayy_D7_6 =. ;
  IF eayy_D7_7 >= 9 THEN eayy_D7_7 =. ;
  IF eayy_D7_8 >= 9 THEN eayy_D7_8 =. ;
  IF eayy_D7_9 >= 9 THEN eayy_D7_9 =. ;
  IF eayy_E2A_rec >= 77 THEN eayy_E2A_rec =. ;
  IF eayy_E2AUC >= 66 THEN eayy_E2AUC =. ;
  IF eayy_E3A = 9996 THEN eayy_E3A =. ;
  IF eayy_E3B = 9996 THEN eayy_E3B =. ;
  IF eayy_E3C = 9996 THEN eayy_E3C =. ;
  IF eayy_E3D = 9996 THEN eayy_E3D =. ;
  IF eayy_E3E = 9996 THEN eayy_E3E =. ;
  IF eayy_E4 >= 7 OR eayy_E4 = 9996 THEN eayy_E4 =. ;
  IF eayy_E5 >= 99 THEN eayy_E5 =. ;
  IF eayy_E5A >= 9 OR eayy_E5A = 9996 THEN eayy_E5A =. ;
  IF eayy_E5B_1 >= 6 THEN eayy_E5B_1 =. ;
  IF eayy_E5B_2 >= 6 THEN eayy_E5B_2 =. ;
  IF eayy_E5B_3 >= 6 THEN eayy_E5B_3 =. ;
  IF eayy_E5B_4 >= 6 THEN eayy_E5B_4 =. ;
  IF eayy_E5B_5 >= 6 THEN eayy_E5B_5 =. ;
  IF eayy_E5B_6 >= 6 THEN eayy_E5B_6 =. ;
  IF eayy_E5B_7 >= 6 THEN eayy_E5B_7 =. ;
  IF eayy_E5B_8 >= 6 THEN eayy_E5B_8 =. ;
  IF eayy_E5B_9 >= 6 OR eayy_E5B_9 = 9996 THEN eayy_E5B_9 =. ;
  IF eayy_F1_rec >= 7 THEN eayy_F1_rec =. ;
  IF eayy_F3 >= 8 THEN eayy_F3 =. ;
  IF eayy_F4 >= 7 OR eayy_F4 = 9996 THEN eayy_F4 =. ;
  IF eayy_F5 >= 7 OR eayy_F5 = 9996 THEN eayy_F5 =. ;
  IF eayy_F6_rec >= 7 THEN eayy_F6_rec =. ;
  IF eayy_F7 >= 7 THEN eayy_F7 =. ;
  IF eayy_F8 >= 7 THEN eayy_F8 =. ;
  IF eayy_G1 >= 8 THEN eayy_G1 =. ;
  IF eayy_G2 >= 8 THEN eayy_G2 =. ;
  IF eayy_G3A >= 9 THEN eayy_G3A =. ;
  IF eayy_G3B >= 9 THEN eayy_G3B =. ;
  IF eayy_G3C >= 9 THEN eayy_G3C =. ;
  IF eayy_G4 >= 8 THEN eayy_G4 =. ;
  IF eayy_G5 >= 9 THEN eayy_G5 =. ;
  IF eayy_G6_1 >= 9 THEN eayy_G6_1 =. ;
  IF eayy_G6_2 >= 9 THEN eayy_G6_2 =. ;
  IF eayy_G6_3 >= 9 THEN eayy_G6_3 =. ;
  IF eayy_G6_4 >= 9 THEN eayy_G6_4 =. ;
  IF eayy_H1A >= 7 THEN eayy_H1A =. ;
  IF eayy_H2 >= 7 THEN eayy_H2 =. ;
  IF eayy_H4 >= 7 THEN eayy_H4 =. ;
  IF eayy_I1 >= 8 THEN eayy_I1 =. ;
  IF eayy_I8 >= 77 THEN eayy_I8 =. ;
  IF eayy_J1 >= 7 THEN eayy_J1 =. ;
  IF eayy_K3 >= 9 THEN eayy_K3 =. ;
  IF eayy_PCS18 >= 666 THEN eayy_PCS18 =. ;
  IF eayy_PCS6 >= 66 THEN eayy_PCS6 =. ;
  IF eayy_PCS6CJT >= 66 THEN eayy_PCS6CJT =. ;
  IF eayy_TYPMEN5 >= 6 THEN eayy_TYPMEN5 =. ;
  IF insee_NUTS1 >= 99 THEN insee_NUTS1 =. ;
  IF insee_TAU2014 >= 99 THEN insee_TAU2014 =. ;
  IF insee_TUU2014 >= 9 THEN insee_TUU2014 =. ;
  IF insee_CATAEU2010 >= 999 THEN insee_CATAEU2010 =. ;

FORMAT
   coco1_q01 COCO1_Q0F.     coco1_q02 COCO1__A.      coco1_q03 COCO1__B.   
   coco1_q04 COCO1__C.      coco1_q05_c COCO1__D.    coco1_q06_1 LABA.     
   coco1_q06_2 LABA.        coco1_q06_3 LABA.        coco1_q06_4 LABA.     
   coco1_q06_5 LABA.        coco1_q06_6 LABA.        coco1_q06_7 LABA.     
   coco1_q06_8 LABA.        coco1_q06_9 LABA.        coco1_q06_10 LABA.    
   coco1_q07_1 LABB.        coco1_q07_2 LABB.        coco1_q07_3 LABB.     
   coco1_q08_1 LABC.        coco1_q08_2 LABC.        coco1_q08_3 COCO1__T. 
   coco1_q09 COCO1__U.      coco1_q10 COCO1_Q1F.     coco1_q11_1 LABA.     
   coco1_q11_2 LABA.        coco1_q11_3 LABA.        coco1_q12 LABD.       
   coco1_q15 LABE.          coco1_q16 COCO1_AC.      coco1_q17 LABF.       
   coco1_q18 LABF.          coco1_q19 LABF.          coco1_q20 LABF.       
   coco1_q21 COCO1_AG.      coco1_q22 COCO1_AH.      coco1_q24_1 LABG.     
   coco1_q24_2 LABG.        coco1_q24_3 LABG.        coco1_q24_4 LABG.     
   coco1_q24_5 LABG.        coco1_q24_6 LABB.        coco1_q24_7 LABB.     
   coco1_q25 COCO1_AQ.      coco1_q26 COCO1_AR.      coco1_q26_rec COCO1_AS.
   coco1_q27_1 LABA.        coco1_q27_2 LABA.        coco1_q27_3 LABA.     
   coco1_q27_4 LABA.        coco1_q27_5 LABA.        coco1_q28 LABH.       
   coco1_q29 LABH.          coco1_q30 LABH.          coco1_q31 COCO1_BA.   
   coco1_q32 COCO1_BB.      coco1_q33 COCO1_BC.      coco1_q34 COCO1_BD.   
   coco1_q35 COCO1_BE.      coco1_q36 COCO1_BF.      coco1_q37 COCO1_BG.   
   coco1_q38 COCO1_BH.      coco1_q39 COCO1_BI.      coco1_q40 COCO1_Q4F.  
   coco1_q41_1 LABG.        coco1_q41_2 LABG.        coco1_q41_3 LABG.     
   coco1_q41_4 LABG.        coco1_q41_5 LABG.        coco1_q41_6 LABG.     
   coco1_q44 COCO1_BP.      coco1_q45 COCO1_BQ.      coco1_q46_1 LABA.     
   coco1_q46_2 LABA.        coco1_q46_3 LABA.        coco1_q46_4 LABA.     
   coco1_q47 COCO1_BV.      coco1_q48 COCO1_BW.      coco1_q49 COCO1_BX.   
   coco1_q50 COCO1_Q5F.     coco1_q51 COCO1_BY.      coco1_q52_1 LABI.     
   coco1_q52_2 LABI.        coco1_q52_3 LABI.        coco1_q52_4 LABI.     
   coco1_q53_1 LABJ.        coco1_q53_2 LABJ.        coco1_q53_3 LABJ.     
   coco1_q54_1 LABA.        coco1_q54_2 LABA.        coco1_q54_3 LABA.     
   coco1_q54_4 LABA.        coco1_q54_5 LABA.        coco1_q54_6 LABA.     
   coco1_q54_7 LABA.        coco1_q54_8 LABA.        coco1_q54_bis_1 LABA. 
   coco1_q54_bis_2 LABA.    coco1_q54_bis_3 LABA.    coco1_q54_bis_4 LABA. 
   coco1_q54_bis_5 LABA.    coco1_q54_bis_6 LABA.    coco1_q54_bis_7 LABA. 
   coco1_q55 LABK.          coco1_q56 LABE.          coco1_q57 LABE.       
   coco1_q58_1 LABA.        coco1_q58_2 LABA.        coco1_q58_3 LABA.     
   coco1_q58_4 LABA.        coco1_q58_5 LABA.        coco1_q58_6 LABA.     
   coco1_q58_7 LABA.        coco1_q59_1 LABL.        coco1_q59_2 LABL.     
   coco1_q59_3 LABL.        coco1_q59_4 LABL.        coco1_q59_5 LABL.     
   coco1_q59_6 LABL.        coco1_q59_7 LABL.        coco1_q59_8 LABL.     
   coco1_q59_9 LABL.        coco1_q60_1 LABM.        coco1_q60_2 LABM.     
   coco1_q60_3 LABM.        coco1_q60_4 LABM.        coco1_q60_5 LABM.     
   coco1_q60_6 LABM.        coco1_q61_1 LABN.        coco1_q61_2 LABN.     
   coco1_q61_3 LABN.        coco1_q61_4 LABN.        coco1_q61_5 LABN.     
   coco1_q61_6 LABN.        coco1_q61_7 LABN.        coco1_q61_8 LABN.     
   coco1_q61_9 LABN.        coco1_q61_10 LABN.       coco1_q62 COCO1_EE.   
   coco1_q63 COCO1_EF.      coco1_q64 COCO1_EG.      coco1_q65 COCO1_EH.   
   coco1_q66 COCO1_EI.      coco1_q67 COCO1_EJ.      coco1_q68 COCO1_EK.   
   coco1_q69 LABO.          coco1_q70 LABO.          coco1_q71 LABO.       
   coco1_q72 LABO.          coco1_q73 LABO.          coco1_q74 LABO.       
   coco1_q75 LABO.          coco1_q76 LABO.          coco1_q77 LABO.       
   coco1_q79 COCO1_ET.      coco1_q80 COCO1_Q8F.     coco1_q81 LABP.       
   coco1_q82 LABP.          coco1_q83 LABP.          coco1_q83_1 LABQ.     
   coco1_q83_2 LABQ.        coco1_q83_3 LABQ.        coco1_q83_4 LABQ.     
   coco1_q83_5 LABQ.        coco1_q83_6 LABQ.        coco1_q83_7 LABQ.     
   coco1_q83_8 LABQ.        coco1_q83_9 LABQ.        coco1_q83_10 LABQ.    
   coco1_q84 LABP.          coco1_q85 LABP.          coco1_q86 COCO1_FJ.   
   eayy_A1 EAYY_A1F.        eayy_A2A_rec EAYY_A2A.   eayy_A3_rec EAYY_A3F. 
   eayy_A3B_rec EAYY_A3B.   eayy_A3C_rec LABR.       eayy_A3D LABK.        
   eayy_A3E_rec LABR.       eayy_A4 EAYY_A4F.        eayy_A5 EAYY_A5F.     
   eayy_A5A EAYY_A5A.       eayy_A5C EAYY_A5C.       eayy_A5C_rec EAYY_A_A.
   eayy_B1 EAYY_B1F.        eayy_B10A EAYY_B10F.     eayy_B10AA EAYY_B_A.  
   eayy_B10ACJT EAYY_B_B.   eayy_B11 LABS.           eayy_B11CJT LABS.     
   eayy_B18_rec EAYY_B18F.   eayy_B18C EAYY_B_D.      eayy_B18CCJT EAYY_B_E.
   eayy_B18CJT_rec EAYY_B_F.   eayy_B1A LABT.           eayy_B1ACJT LABT.     
   eayy_B1B EAYY_B1B.       eayy_B1BCJT EAYY_B_H.    eayy_B1CJT EAYY_B1C.  
   eayy_B2_rec EAYY_B2F.    eayy_B25 EAYY_B25F.      eayy_B2CJT_rec EAYY_B2C.
   eayy_B4_rec LABU.        eayy_B4CJT_rec LABU.     eayy_B5_rec EAYY_B5F. 
   eayy_B5A EAYY_B5A.       eayy_B5B_rec EAYY_B5B.   eayy_B5C EAYY_B5C.    
   eayy_B6A_rec EAYY_B6A.   eayy_B6B_rec EAYY_B6B.   eayy_B7B_rec EAYY_B7B.
   eayy_B8_rec EAYY_B8F.    eayy_B9_rec EAYY_B9F.    eayy_C1_rec EAYY_C1F. 
   eayy_C1JEU EAYY_C1J.     eayy_C8 EAYY_C8F.        eayy_C8A_rec EAYY_C8A.
   eayy_C8B_rec EAYY_C8B.   eayy_D1_rec EAYY_D1F.    eayy_D1A EAYY_D1A.    
   eayy_D2 EAYY_D2F.        eayy_D3 EAYY_D3F.        eayy_D4_rec EAYY_D4F. 
   eayy_D5_rec EAYY_D5F.    eayy_D6 EAYY_D6F.        eayy_D7_1 LABV.       
   eayy_D7_10 LABV.         eayy_D7_2 LABV.          eayy_D7_3 LABV.       
   eayy_D7_4 LABV.          eayy_D7_5 LABV.          eayy_D7_6 LABV.       
   eayy_D7_7 LABV.          eayy_D7_8 LABV.          eayy_D7_9 LABV.       
   eayy_E1A LABW.           eayy_E1B LABW.           eayy_E1C LABW.        
   eayy_E1D LABW.           eayy_E1E LABW.           eayy_E1F LABW.        
   eayy_E1G LABW.           eayy_E1H LABW.           eayy_E1I LABW.        
   eayy_E1J LABW.           eayy_E2A_rec EAYY_E2A.   eayy_E2AUC EAYY_E_A.  
   eayy_E2AUC_SOURCE EAYY_E_B.   eayy_E3A LABX.           eayy_E3B LABX.        
   eayy_E3C LABX.           eayy_E3D LABX.           eayy_E3E LABX.        
   eayy_E4 EAYY_E4F.        eayy_E5 EAYY_E5F.        eayy_E5A EAYY_E5A.    
   eayy_E5B_1 LABY.         eayy_E5B_2 LABY.         eayy_E5B_3 LABY.      
   eayy_E5B_4 LABY.         eayy_E5B_5 LABY.         eayy_E5B_6 LABY.      
   eayy_E5B_7 LABY.         eayy_E5B_8 LABY.         eayy_E5B_9 LABY.      
   eayy_F1_rec LABZ.        eayy_F3 EAYY_F3F.        eayy_F4 EAYY_F4F.     
   eayy_F5 EAYY_F5F.        eayy_F6_rec LABZ.        eayy_F7 LABAA.        
   eayy_F8 LABAA.           eayy_G1 EAYY_G1F.        eayy_G2 EAYY_G2F.     
   eayy_G3A LABAB.          eayy_G3B LABAB.          eayy_G3C LABAB.       
   eayy_G4 EAYY_G4F.        eayy_G5 EAYY_G5F.        eayy_G6_1 LABV.       
   eayy_G6_2 LABV.          eayy_G6_3 LABV.          eayy_G6_4 LABV.       
   eayy_H1A EAYY_H1A.       eayy_H2 EAYY_H2F.        eayy_H4 LABAA.        
   eayy_I1 EAYY_I1F.        eayy_I8 EAYY_I8F.        eayy_J1 EAYY_J1F.     
   eayy_K3 EAYY_K3F.        eayy_PCS18 EAYY_PCS.     eayy_PCS6 LABAC.      
   eayy_PCS6CJT LABAC.      eayy_TYPMEN5 EAYY_TYP.   coco1_cal_AGE1 COCO1_CA.
   coco1_cal_AGE2 COCO1_FK.   coco1_cal_DIPL COCO1_FL.   coco1_cal_SEXE COCO1_FM.
   coco1_cal_ZEAT COCO1_FN.   coco1_cal_NAT COCO1_FO.   insee_NUTS1 INSEE_NU. 
   insee_TAU2014 INSEE_TA.   insee_TUU2014 INSEE_TU.   insee_CATAEU2010 INSEE_CA.
 ;
                      

LENGTH
   UID_ANONYM_COVID 4       coco1_q01 3              coco1_q02 4           
   coco1_q03 4              coco1_q04 4              coco1_q05_c 4         
   coco1_q06_1 4            coco1_q06_2 4            coco1_q06_3 4         
   coco1_q06_4 4            coco1_q06_5 4            coco1_q06_6 4         
   coco1_q06_7 4            coco1_q06_8 4            coco1_q06_9 4         
   coco1_q06_10 4           coco1_q07_1 3            coco1_q07_2 3         
   coco1_q07_3 3            coco1_q08_1 4            coco1_q08_2 4         
   coco1_q08_3 4            coco1_q09 4              coco1_q10 4           
   coco1_q11_1 4            coco1_q11_2 4            coco1_q11_3 4         
   coco1_q12 4              coco1_q13 4              coco1_q14 4           
   coco1_q15 4              coco1_q16 3              coco1_q17 4           
   coco1_q18 4              coco1_q19 4              coco1_q20 4           
   coco1_q21 3              coco1_q22 3              coco1_q24_1 4         
   coco1_q24_2 4            coco1_q24_3 4            coco1_q24_4 4         
   coco1_q24_5 4            coco1_q24_6 3            coco1_q24_7 3         
   coco1_q25 4              coco1_q26 4              coco1_q26_rec 3       
   coco1_q27_1 4            coco1_q27_2 4            coco1_q27_3 4         
   coco1_q27_4 4            coco1_q27_5 4            coco1_q28 4           
   coco1_q29 4              coco1_q30 4              coco1_q31 4           
   coco1_q32 4              coco1_q33 4              coco1_q34 4           
   coco1_q35 4              coco1_q36 4              coco1_q37 4           
   coco1_q38 4              coco1_q39 4              coco1_q40 4           
   coco1_q41_1 4            coco1_q41_2 4            coco1_q41_3 4         
   coco1_q41_4 4            coco1_q41_5 4            coco1_q41_6 4         
   coco1_q44 4              coco1_q45 4              coco1_q46_1 4         
   coco1_q46_2 4            coco1_q46_3 4            coco1_q46_4 4         
   coco1_q47 4              coco1_q48 4              coco1_q49 4           
   coco1_q50 4              coco1_q51 4              coco1_q52_1 4         
   coco1_q52_2 4            coco1_q52_3 4            coco1_q52_4 4         
   coco1_q53_1 4            coco1_q53_2 4            coco1_q53_3 4         
   coco1_q54_1 4            coco1_q54_2 4            coco1_q54_3 4         
   coco1_q54_4 4            coco1_q54_5 4            coco1_q54_6 4         
   coco1_q54_7 4            coco1_q54_8 4            coco1_q54_bis_1 4     
   coco1_q54_bis_2 4        coco1_q54_bis_3 4        coco1_q54_bis_4 4     
   coco1_q54_bis_5 4        coco1_q54_bis_6 4        coco1_q54_bis_7 4     
   coco1_q55 3              coco1_q56 4              coco1_q57 4           
   coco1_q58_1 4            coco1_q58_2 4            coco1_q58_3 4         
   coco1_q58_4 4            coco1_q58_5 4            coco1_q58_6 4         
   coco1_q58_7 4            coco1_q59_1 4            coco1_q59_2 4         
   coco1_q59_3 4            coco1_q59_4 4            coco1_q59_5 4         
   coco1_q59_6 4            coco1_q59_7 4            coco1_q59_8 4         
   coco1_q59_9 4            coco1_q60_1 4            coco1_q60_2 4         
   coco1_q60_3 4            coco1_q60_4 4            coco1_q60_5 4         
   coco1_q60_6 4            coco1_q61_1 4            coco1_q61_2 4         
   coco1_q61_3 4            coco1_q61_4 4            coco1_q61_5 4         
   coco1_q61_6 4            coco1_q61_7 4            coco1_q61_8 4         
   coco1_q61_9 4            coco1_q61_10 4           coco1_q62 4           
   coco1_q63 4              coco1_q64 4              coco1_q65 4           
   coco1_q66 4              coco1_q67 4              coco1_q68 4           
   coco1_q69 4              coco1_q70 4              coco1_q71 4           
   coco1_q72 4              coco1_q73 4              coco1_q74 4           
   coco1_q75 4              coco1_q76 4              coco1_q77 4           
   coco1_q79 4              coco1_q80 4              coco1_q81 4           
   coco1_q82 4              coco1_q83 4              coco1_q83_1 4         
   coco1_q83_2 4            coco1_q83_3 4            coco1_q83_4 4         
   coco1_q83_5 4            coco1_q83_6 4            coco1_q83_7 4         
   coco1_q83_8 4            coco1_q83_9 4            coco1_q83_10 4        
   coco1_q84 4              coco1_q85 4              coco1_q86 3           
   eayy_A1 3                eayy_A2A_rec 3           eayy_A3_rec 3         
   eayy_A3B_rec 3           eayy_A3C_rec 3           eayy_A3D 3            
   eayy_A3E_rec 3           eayy_A4 3                eayy_A5 3             
   eayy_A5A 4               eayy_A5C 4               eayy_A5C_rec 4        
   eayy_B1 3                eayy_B10A 3              eayy_B10AA 4          
   eayy_B10ACJT 3           eayy_B11 3               eayy_B11CJT 3         
   eayy_B18_rec 3           eayy_B18C 3              eayy_B18CCJT 3        
   eayy_B18CJT_rec 3        eayy_B1A 4               eayy_B1ACJT 4         
   eayy_B1B 3               eayy_B1BCJT 3            eayy_B1CJT 3          
   eayy_B2_rec 3            eayy_B25 3               eayy_B2CJT_rec 3      
   eayy_B4_rec 3            eayy_B4CJT_rec 3         eayy_B5_rec 3         
   eayy_B5A 3               eayy_B5B_rec 3           eayy_B5C 3            
   eayy_B6A_rec 3           eayy_B6B_rec 3           eayy_B7B_rec 3        
   eayy_B8_rec 3            eayy_B9_rec 3            eayy_C1_rec 3         
   eayy_C1JEU 3             eayy_C8 4                eayy_C8A_rec 4        
   eayy_C8B_rec 4           eayy_D1_rec 3            eayy_D1A 4            
   eayy_D2 3                eayy_D3 3                eayy_D4_rec 3         
   eayy_D5_rec 3            eayy_D6 3                eayy_D7_1 3           
   eayy_D7_10 3             eayy_D7_2 3              eayy_D7_3 3           
   eayy_D7_4 3              eayy_D7_5 3              eayy_D7_6 3           
   eayy_D7_7 3              eayy_D7_8 3              eayy_D7_9 3           
   eayy_E1A 3               eayy_E1B 3               eayy_E1C 3            
   eayy_E1D 3               eayy_E1E 3               eayy_E1F 3            
   eayy_E1G 3               eayy_E1H 3               eayy_E1I 3            
   eayy_E1J 3               eayy_E2A_rec 3           eayy_E2AUC 3          
   eayy_E2AUC_SOURCE 3      eayy_E3A 4               eayy_E3B 4            
   eayy_E3C 4               eayy_E3D 4               eayy_E3E 4            
   eayy_E4 4                eayy_E5 3                eayy_E5A 4            
   eayy_E5B_1 4             eayy_E5B_2 4             eayy_E5B_3 4          
   eayy_E5B_4 4             eayy_E5B_5 4             eayy_E5B_6 4          
   eayy_E5B_7 4             eayy_E5B_8 4             eayy_E5B_9 4          
   eayy_F1_rec 3            eayy_F3 3                eayy_F4 4             
   eayy_F5 4                eayy_F6_rec 3            eayy_F7 3             
   eayy_F8 3                eayy_G1 3                eayy_G2 3             
   eayy_G3A 3               eayy_G3B 3               eayy_G3C 3            
   eayy_G4 3                eayy_G5 3                eayy_G6_1 3           
   eayy_G6_2 3              eayy_G6_3 3              eayy_G6_4 3           
   eayy_H1A 3               eayy_H2 3                eayy_H4 3             
   eayy_I1 3                eayy_I8 3                eayy_J1 3             
   eayy_K3 3                eayy_PCS18 4             eayy_PCS6 4           
   eayy_PCS6CJT 4           eayy_TYPMEN5 3           VAGUE 4               
   coco1_cal_AGE1 3         coco1_cal_AGE2 3         coco1_cal_DIPL 3      
   coco1_cal_SEXE 3         coco1_cal_ZEAT 3         coco1_cal_NAT 3       
   insee_NUTS1 3            insee_TAU2014 3          insee_TUU2014 3       
   insee_CATAEU2010 4 ;



RUN ;
